### PR TITLE
Add clover to "Database" section

### PR DESCRIPTION
**Pull request by ostafen**
> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc): https://github.com/ostafen/clover
- pkg.go.dev: https://pkg.go.dev/github.com/ostafen/clover
- goreportcard.com: https://goreportcard.com/report/github.com/ostafen/clover
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.):  https://app.codecov.io/gh/ostafen/clover

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below before you submit PR:**
_not every repository (project) will fit into every option, but most projects should_

- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
review:
- golint https://goreportcard.com/report/github.com/ostafen/clover#golint
- coverage >=80%, just a little bit left
- alphabetical order

**Comment by ostafen** [comment]
> review:
> 
> * golint https://goreportcard.com/report/github.com/ostafen/clover#golint
> * coverage >=80%, just a little bit left
> * alphabetical order

All the points should now be fixed :)

**Comment by phanirithvij** [comment]
I think this isn't stable for production yet.

**Comment by ostafen** [comment]
What should I do in your opinion for make it production stable?

**Comment by phanirithvij** [comment]
@ostafen, Sorry for the confusion, I meant to say a stable version, not a production-ready one.
- I meant it in the context of [quality standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards), the requirement of having a stable version or being very close to one.
- But in the readme, it says it's still under development, and there are no tagged releases.
- Also missing a roadmap.
- I'm not sure if writing to disk for every insert is a good idea. (I'm not much familiar with NoSQL internals, so please ignore this question if it makes no sense)
- Mention any pitfalls.
  - Is it thread-safe?
  - How lightweight is it?
  - ...

**Comment by ostafen** [comment]
Hi, regarding the stability I am about to tag the current version. The phrase on the Readme sounds confusing. It doesn't mean that the project isn't in a usable state, it refers to the fact the it is in continuous development (in the sens3 of maintenence). I will change the sentence.
Regarding the performance issue, the library is meant for being very simple, both from an the point of view of api and implementation, and this is why, it rewrite the entire file on every update (this is also the strategy used by tinyDB, from which has inspired my project).
A more performante alternative, is to append changes to collection in a log structured way, but this involves several issues (handling crash recovery, or compacting the files).
I will evaluate the possibility of adopting this strategy in a future version, but currently the focus was on simplicity.
Thank you for your feedback, I will integrate the information you suggested

**Comment by phanirithvij** [comment]
@ostafen thanks for the quick reply, after tagging a release and making the applicable changes. Please ping Avelino for a review.

**Pull request merged**
