### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ctolib**

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@felipeweb [bug] [help wanted] [pending-review] [question] [removal] [suggestion]

_(just kidding)_

**Comment by avelino** [comment]
@ctolib Write description in English

**Comment by btnwtn** [comment]
@avelino Why write descriptions for Chinese books in English?

**Comment by shurcooL** [comment]
@btnwtn The books might be Chinese, but this document is in English. It makes sense to use English descriptions for consistency. But titles (e.g., book title) can be in the original language.

**Comment by ctolib** [comment]
cancle

**Pull request closed without merging**
