### PR TITLE
Add Gitfile

### PR DESCRIPTION
**Pull request by bradurani**
Add Gitfile, a lightweight package manager for Git repos

### CODE REVIEW

**Comment by bradurani** [comment]
Do you need something from me?

**Comment by shurcooL** [comment]
The section you're adding to is called *Libraries for package and dependency management.*, but your project is a command, not a library.

https://godoc.org/github.com/bradurani/Gitfile/gitfile

**Comment by bradurani** [comment]
Where should it go? It seems the command line section is also for libraries. This is a command line package manager

**Comment by shurcooL** [comment]
There's a section for software and tools written in Go here:

https://github.com/avelino/awesome-go#tools

But you're right, this Package Management section contains package management tools, not necessarily libraries.

So your change is fine. We should update the description, because "Libraries for package and dependency management" is not accurate.

**Comment by avelino** [comment]
new rules 8 days with label `pending-submitter-response`: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers

**Pull request closed without merging**
