### PR TITLE
Added link to rickb777/date

### PR DESCRIPTION
**Pull request by rickb777**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/rickb777/date
- godoc.org: https://godoc.org/github.com/rickb777/date
- goreportcard.com: https://goreportcard.com/report/github.com/rickb777/date
- coverage service link: https://coveralls.io/github/rickb777/date?branch=master

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [*] I have added my package in alphabetical order.
- [*] I have an appropriate description with correct grammar.
- [*] I know that this package was not listed before.
- [*] I have added godoc link to the repo and to my pull request.
- [*] I have added coverage service link to the repo and to my pull request.
- [*] I have added goreportcard link to the repo and to my pull request.
- [*] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by cassiobotaro** [comment]
@rickb777

**Comment by avelino** [comment]
pls read: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers

**Comment by rickb777** [comment]
OK I've submitted this PR twice and it has been rejected twice.

I don't understand why, please explain.

**Comment by cassiobotaro** [comment]
The maintainers will review your PR and notify you and tag it in case any information is still missing. **They will wait 8 days for your interaction, after that the PR will be closed**.

**Comment by rickb777** [comment]
You haven't explained why this was closed because you didn't make clear what response you needed. What criterion did I fail to meet?

**Comment by cassiobotaro** [comment]
image
Sorry if it isn't clear for you but you should ask for information before. 
Fix golint, send again and will approve.
image

**Pull request closed without merging**
