### PR TITLE
Add rest-go

### PR DESCRIPTION
**Pull request by edermanoel94**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/edermanoel94/rest-go
- godoc.org: https://godoc.org/github.com/edermanoel94/rest-go
- goreportcard.com: https://goreportcard.com/report/github.com/edermanoel94/rest-go
- coverage service link ([gocover](https://gocover.io/github.com/edermanoel94/rest-go), [coveralls](https://coveralls.io/) etc.) https://gocover.io/github.com/edermanoel94/rest-go

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by edermanoel94** [comment]
Fixed!

**Comment by kirillDanshin** [comment]
@edermanoel94 

https://github.com/edermanoel94/rest-go/blob/bc9fbacdef3ebb9eaf770a5260a4f7a3949ccf50/format.go#L7
please use
```go
return []byte(fmt.Sprintf(`{"message":"%s"}`, err.Error()))
```
instead. also, if err.Error() will contain a `"`, you'll get an invalid JSON output.

**Comment by edermanoel94** [comment]
Thanks dude

**Comment by kirillDanshin** [comment]
@edermanoel94 note: you fixed the code formatting there, but this will not escape quotes so JSON will not break. you might want to use strings.Replace there.

**Comment by edermanoel94** [comment]
I make a test for that, thanks @kirillDanshin

**Pull request merged**
