### PR TITLE
Updated LabStack packages

### PR DESCRIPTION
**Pull request by vishr**
Signed-off-by: Vishal Rana <vr@labstack.com>

### CODE REVIEW

**Comment by matrixik** [comment]
Thank you for contribution.
Unfortunately package lack documentation https://goreportcard.com/report/github.com/labstack/gommon/log and proper README

**Comment by matrixik** [comment]
Ugh, I did not want to discourage you from adding this package to the list. I was simply pointing that documentation should be improved before it can be merged.

**Comment by vishr** [comment]
@matrixik No problem, once I add doc, I will create a new PR.

**Comment by matrixik** [comment]
Great, thank you.

**Pull request closed without merging**
