### PR TITLE
Add gop - Build and manage your Go applications out of GOPATH

### PR DESCRIPTION
**Pull request by lunny**
Please provide package links to:

github.com repo: https://github.com/lunny/gop
godoc.org: https://godoc.org/github.com/lunny/gop
goreportcard.com: https://goreportcard.com/report/github.com/lunny/gop
coverage service link (codecov): https://codecov.io/gh/lunny/gop

 - [x] I have added my package in alphabetical order.
 - [x] I have an appropriate description with correct grammar.
 - [x] I know that this package was not listed before.
 - [x] I have added godoc link to the repo and to my pull request.
 - [x] I have added coverage service link to the repo and to my pull request.
 - [x] I have added goreportcard link to the repo and to my pull request.
 - [x] I have read Contribution guidelines, maintainers note and Quality standard.

### CODE REVIEW

**Comment by appleboy** [comment]
Missing the Pull Request template?

https://github.com/avelino/awesome-go/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by lunny** [comment]
@appleboy @cassiobotaro done.

**Comment by appleboy** [comment]
@cassiobotaro  go report card report the misspell error since this package import https://github.com/Unknwon library.

**Comment by cassiobotaro** [comment]
@appleboy ok, agree, but we still with gocyclo warnings.

**Pull request merged**
