### PR TITLE
add bqwriter to the list of Third-Party APIs

### PR DESCRIPTION
**Pull request by GlenDC**
The library is currently on `v0.6.2` and is already used in production for several
products by OTA-Insight. We aim to have to be on a stable version in the near future.
In order to do so we are waiting on:

- the stabilisation of the Storage API used for one of three possible clients under the hood;
- opt-in data write error handling with managed retry: decide whether we want it or not, and if so, lock this into the API;

> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc): <https://github.com/ota-insight/bqwriter>
- pkg.go.dev: <https://pkg.go.dev/github.com/OTA-Insight/bqwriter>
- goreportcard.com: <https://goreportcard.com/report/github.com/OTA-Insight/bqwriter>
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): <https://gocover.io/github.com/OTA-Insight/bqwriter>

All links above can be found in the Repository as well, except for the coverage. I do not find coverage as a metric meaningful. I do find coverage as a concept useful but only where it applies. So I made sure to test all code of the logic I defined, but code which creates or interacts with google cloud production API's aren't tested as that would not longer make them unit tests IMHO. That's the reason why I didn't publish this myself as part of the README. I do however check coverage while developing.

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below before you submit PR:**
_not every repository (project) will fit into every option, but most projects should_

- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: False
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by GlenDC** [comment]
> * goreportcard

This card is included in the README as a badge, and and can also be seen at https://goreportcard.com/report/github.com/OTA-Insight/bqwriter.

**Review by avelino — CHANGES_REQUESTED** [review]
need links, pls read pull request template, we ask for some information (links)

**Comment by GlenDC** [comment]
> need links, pls read pull request template, we ask for some information (links)

My sincere appologies. I've added the links now. I did read that request and I was looking initially everywhere in the repo but couldn't find it. Now I know why, it needs to be part of the PR description. For some reason I didn't notice that earlier. It has been rectified now, @avelino.

Recently I've by the way discovered one can add templates to GitHub for Pull Requests as well as issues. You already make use of it. Sadly they do not provide the nice form-look for Pull Requests as they do for issues. As I find that form-layout a lot clearer to make sure one doesn't forget to provide information. It wouldn't stop "bad" parties of course, but for people like myself who might otherwise look over something by accident it would be helpful. Either way, nothing you can do about it of course. I should read more carefully next time, once again, my apologies.

**Review by avelino — CHANGES_REQUESTED** [review]
Required minimal `80%` coverage, today is `69.8%`

**Comment by GlenDC** [comment]
> Required minimal `80%` coverage, today is `69.8%`

The coverage is now at 82%.

**Pull request merged**
