### PR TITLE
Add Gogland & deprecate the idea plug-in

### PR DESCRIPTION
**Pull request by justinclift**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request - N/A in this case :wink:
- [x] I have added coverage service link to the repo and to my pull request - N/A in this case
- [X] I have added goreportcard link to the repo and to my pull request - N/A in this case
- [X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by kamilsk** [comment]
Why is it deprecated? Anybody can still use it in IDEA, PhpStorm and other IDE from JetBrains. Do you have any proof that authors don't support it anymore?

**Comment by kamilsk** [comment]
IDE will be paid in future. But plugin will not.

**Comment by justinclift** [comment]
@ignatov Hmmm, did I get that wrong?

**Comment by justinclift** [comment]
@kamilsk Hmmm, it's definitely possible I've misunderstood the deprecation.  Maybe the deprecation was for that plugin only, with it now being replaced by this? (unsure) https://plugins.jetbrains.com/plugin/9568-go

@ignatov should be able to sort this out. :smile:

**Comment by ignatov** [comment]
JetBrains doesn't have any plans to support the old plugin. I haven't seen any external contributor for the past several years to that plugin, so I'm quite skeptical about the future of the open source plugin.

**Comment by justinclift** [comment]
@ignatov Thanks. :smile:

**Comment by justinclift** [comment]
Just updated things more clearly, and removed the doubled up link as it's no longer needed.

**Pull request merged**
