### PR TITLE
Add https://github.com/nlpodyssey/spago

### PR DESCRIPTION
**Pull request by matteo-grella**
github.com repo: https://github.com/nlpodyssey/spago
pkg.go.dev: https://pkg.go.dev/github.com/nlpodyssey/spago?tab=overview
goreportcard.com: https://goreportcard.com/report/github.com/nlpodyssey/spago
coverage service link: https://codecov.io/gh/nlpodyssey/spago

- [X] I have added my package in alphabetical order.
- [X] I have an appropriate description with correct grammar.
- [X] I know that this package was not listed before.
- [X] I have added pkg.go.dev link to the repo and to my pull request.
- [X] I have added coverage service link to the repo and to my pull request.
- [X] I have added goreportcard link to the repo and to my pull request.
- [X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Additional info:

- [X] checked Valid go.mod file 
- [X] checked Permissive license 
- [X] checked Tagged version

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by phanirithvij** [comment]
@avelino coverage doesn't meet quality standards but it's an ML project I assume it's hard to test it practically, so is it acceptable?

Tag v.0.1.0 was released 13 days ago.
Also, it's not yet stable, quoting from the readme

> We're not at a v1.0.0 yet, so spaGO is currently an experimental work-in-progress. It's pretty easy to get your hands on through, so you might want to use it in your real applications. Early adopters may make use of it for production use today as long as they understand and accept that spaGO is not fully tested and that APIs will change (maybe extensively).
>
> ~If you're wondering, I haven't used spaGO in production yet, but I plan to do the first integration tests soon.~
>
> spaGO has been running smoothly for a couple of months now in a system that analyzes thousands of news items a day!

But it has ~800 stars and a lot of active development so it is progressing towards `stable`.

**Comment by matteo-grella** [comment]
@avelino Is there anything I can do to prevent this issue from being closed?

**Comment by marco-nicola** [comment]
@avelino may thanks! This is so... awesome! :smile: :heart:

**Pull request merged**
