### PR TITLE
add GoHooks

### PR DESCRIPTION
**Pull request by averageflow**
Requested links:

- github.com repo: [gohooks](https://github.com/averageflow/gohooks)
- pkg.go.dev: [pkg.go.dev documentation](https://pkg.go.dev/github.com/averageflow/gohooks/gohooks)
- goreportcard.com: [goreportcard.com](https://goreportcard.com/report/github.com/averageflow/gohooks)
- coverage service link [codecov](https://codecov.io/gh/averageflow/gohooks)

Accepted conditions:

- [ x ] I have added my package in alphabetical order.
- [ x ] I have an appropriate description with correct grammar.
- [ x ] I know that this package was not listed before.
- [ x ] I have added pkg.go.dev link to the repo and to my pull request.
- [ x ] I have added coverage service link to the repo and to my pull request.
- [ x ] I have added goreportcard link to the repo and to my pull request.
- [ x ] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: False

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by averageflow** [comment]
EDIT: I had to change to Github CI instead of Travis and also using now codecov.io for coverage instead of Code Climate.

**Review by avelino — CHANGES_REQUESTED** [review]
Fixed:
- coverage > 80% today is 78.26%
- golint

**Comment by averageflow** [comment]
I have linted, fixed any possible problems, and test coverage is now 84%. I think is really worth adding to this list.

**Comment by averageflow** [comment]
@avelino I hope you approve this PR

**Pull request merged**
