### PR TITLE
Added Mule (https://github.com/wlbr/mule)

### PR DESCRIPTION
**Pull request by wlbr**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/wlbr/mule
- godoc.org: https://godoc.org/github.com/wlbr/mule
- goreportcard.com: https://goreportcard.com/report/github.com/wlbr/mule
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://coveralls.io/github/wlbr/mule?branch=master

Actually there is a full table of links in the end of the repos readme.

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: False
- goreportcard.com: False
- coverage: True

**Comment by wlbr** [comment]
Sorrry, what link is missing? 
The link to the package is within the change. And in the title of the merge request.

**Comment by wlbr** [comment]
* Documentation: https://godoc.org/github.com/wlbr/mule
* Lint: http://go-lint.appspot.com/github.com/wlbr/mule
* Continous Integration: [Travis Status](https://travis-ci.com/wlbr/mule)
* Test Coverage: [Coverage Status](https://coveralls.io/github/wlbr/mule?branch=master)
* Metrics: [GoReportCard](https://goreportcard.com/report/github.com/wlbr/mule)

**Comment by appleboy** [comment]
Please fix the errors in https://goreportcard.com/report/github.com/wlbr/mule#misspell

**Comment by wlbr** [comment]
done

**Comment by wlbr** [comment]
Ping.

**Comment by wlbr** [comment]
Guys, sorry, but what is going on here?

**Comment by wlbr** [comment]
Hi, the test coverage is now at 55% [Coverage Status](https://coveralls.io/github/wlbr/mule?branch=master)

The remaining parts are trivial things in the main function and not sensibly testable. Take a look at https://coveralls.io/builds/29219950/source?filename=mule.go

**Comment by panjf2000** [comment]
Please resolve https://goreportcard.com/report/github.com/wlbr/mule#gofmt

**Comment by wlbr** [comment]
done.

**Comment by wlbr** [comment]
ping.

**Pull request merged**
