### PR TITLE
Adding go-nmea to Utilities

### PR DESCRIPTION
**Pull request by adrianmo**

### CODE REVIEW

**Comment by shurcooL** [comment]
The library looks good, but not sure if Utilities is the best section for it. Did you not find anything more appropriate?

It feels like it should go together with other file format parsers somewhere. Perhaps Text Processing?

**Comment by adrianmo** [comment]
Yes, you are right, probably "Test Processing" more appropriate. Let me move it there.

**Comment by adrianmo** [comment]
Done

**Comment by shurcooL** [comment]
LGTM.

**Pull request merged**
