### PR TITLE
Added Janus API Gateway

### PR DESCRIPTION
**Pull request by italolelis**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo: https://github.com/hellofresh/janus
- godoc.org: https://godoc.org/github.com/hellofresh/janus
- goreportcard.com: https://goreportcard.com/report/github.com/hellofresh/janus
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/hellofresh/janus

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by cassiobotaro** [comment]
@italolelis Pls check the coverage link

**Comment by appleboy** [comment]
wrong coverage link

**Comment by italolelis** [comment]
@cassiobotaro @appleboy Sorry guys, I've changed the coverage link to use coveralls, should be working now.

Thanks 👍

**Comment by cassiobotaro** [comment]
@italolelis link is ok now, thanks, but your coverage is only 52%. Please write more tests to increase your coverage. 
"Tests, where practical. If the library/program is testable, then coverage should be >= 80% for non-data-related packages and >=90% for data related packages. Notice: the tests will be reviewed too. We will check your coverage manually if your package's coverage is just a benchmark results." - extracted from our  [contribution-guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines)

**Comment by italolelis** [comment]
@cassiobotaro No worries, I'll try to find some time to write them. 
Thanks again 👍

**Comment by cassiobotaro** [comment]
More than 8 days without fixes. Feel free to send again following the quality standards.

**Pull request closed without merging**
