### PR TITLE
Add bokchoy library

### PR DESCRIPTION
**Pull request by thoas**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/thoas/bokchoy
- godoc.org: https://godoc.org/github.com/thoas/bokchoy
- goreportcard.com: https://goreportcard.com/report/github.com/thoas/bokchoy
- travis.org : https://travis-ci.org/thoas/bokchoy

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by thoas** [comment]
@avelino coverage has been added to travis CI

```
coverage: 76.2% of statements
ok  	github.com/thoas/bokchoy	8.518s
real	0m42.921s
user	0m16.032s
sys	0m3.191s
The command "make test" exited with 0.

**Comment by avelino** [comment]
@thoas 

> Tests, where practical. If the library/program is testable, then coverage should be >= 80% for non-data-related packages and >=90% for data related packages. Notice: the tests will be reviewed too. We will check your coverage manually if your package's coverage is just a benchmark results.

read: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards

**Comment by thoas** [comment]
@avelino sorry for that, coverage is now `>= 85%`.

```console
PASS
coverage: 85.9% of statements
ok  	github.com/thoas/bokchoy	8.015s
real	0m25.147s
user	0m17.744s
sys	0m3.254s
```

**Comment by kirillDanshin** [comment]
@thoas please fix your readme. your screen.gif link is broken in chrome.

https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fd2aztkdj0ezvrk.cloudfront.net%2Fitems%2F0f3I270J0v0C09032l0B%2Fscreen.gif&hl=en

also, as this is a queue library, we require >= 90% coverage (see https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards).

otherwise, it's a quite interesting project. Feel free to open a new PR as soon as you fix this issues.

(note: I'm closing a majority of old issues in order to clean PRs)

**Pull request closed without merging**
