### PR TITLE
Add stop-and-go

### PR DESCRIPTION
**Pull request by elgohr**
- github.com repo: https://github.com/elgohr/stop-and-go
- pkg.go.dev: https://pkg.go.dev/github.com/elgohr/stop-and-go?tab=overview
- goreportcard.com: https://goreportcard.com/report/github.com/elgohr/stop-and-go
- coverage service link: https://codecov.io/gh/elgohr/stop-and-go

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
Review:
- godocs
- [rearme example](https://github.com/elgohr/stop-and-go#usage) don’t use package (import)

**Comment by elgohr** [comment]
Adapted the example.

Nevertheless I stick with current packages (which were taken by intend), instead of making godocs beautiful.
I prefer having a meaningful API.

**Comment by avelino** [comment]
I sent a pull request with example working, see here:
https://github.com/elgohr/stop-and-go/pull/2

**Comment by elgohr** [comment]
What's next? :)

**Comment by elgohr** [comment]
Thank you 🙂

**Pull request merged**
