### PR TITLE
Add goipp (https://github.com/OpenPrinting/goipp)

### PR DESCRIPTION
**Pull request by alexpevzner**
Note, the project was moved to OpenPrinting, https://github.com/OpenPrinting/goipp

Please check if what you want to add to awesome-go list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

* github.com repo: https://github.com/OpenPrinting/goipp
* godoc.org: https://godoc.org/github.com/OpenPrinting/goipp
* goreportcard.com: https://goreportcard.com/report/github.com/OpenPrinting/goipp
* coverage service link: https://gocover.io/github.com/OpenPrinting/goipp

Coverage: 55.3%

Please note, project contains a lot of code, that converts integer constants into strings. This code is counted, but cannot be tested, so overall coverage is not very high.

**Make sure that you've checked the boxes below before you submit PR:((

- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note]( https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: False
- goreportcard.com: False
- coverage: False

**Comment by alexpevzner** [comment]
Hi @panjf2000 , I've updated PR according to your rules. Please, look again

**Comment by alexpevzner** [comment]
Hi @panjf2000 

I'd be glad to implement your code quality suggestions, but I need an advise, how to better do it. Let me explain my problem.

This library implements IPP protocol. IPP has a lot of named integer constants with provided conversion to string.

Constant declaration typically looks like this:

    const (
        // Delimiter tags
        TagZero                   Tag = 0x00 // Zero tag - used for separators
        TagOperationGroup         Tag = 0x01 // Operation group
        TagJobGroup               Tag = 0x02 // Job group
        TagEnd                    Tag = 0x03 // End-of-attributes
        TagPrinterGroup           Tag = 0x04 // Printer group
        // a lot of constants skipped
    )

it causes golint co complain "warning: comment on exported const TagZero should be of the form "TagZero ..." (golint)". If I will put comment on a line before each constant declaration, golint will be happy, but documentation will be much less readable, because it will be full of very long constant declarations sequences.

Conversion to string looks like this:

    func (tag Tag) String() string {
            switch tag {
            case TagZero:
                    return "zero"
            case TagOperationGroup:
                    return "operation-attributes-tag"
            case TagJobGroup:
                    return "job-attributes-tag"
            case TagEnd:
                    return "end-of-attributes-tag"
            case TagPrinterGroup:
                    return "printer-attributes-tag"
            // skipped
    }

gocyclo complains that this code has a high cyclomatic complexity, but it is hard to understand how to reduce this complexity.

Also, it is not clear, how to test function like this. Well, I can write a "test" that will simply roll a loop, calling this function with various tag values. Formally, it will increase test coverage, but actually this test will test nothing.

As there are a lot of named constants, and a lot of value->string conversion code, so overall test coverage is low. But most of the "normal" code, which does something less trivial that constant-to-string conversion, is well-covered.

**Comment by alexpevzner** [comment]
ping?

**Comment by panjf2000** [comment]
Since `cyclomatic complexity` is not an absolute standard of code quality and I'm not a big fan of it, so `gocyclo` is not a mandatory standard in awesome-go. 

However, we demand other quality standards on goreportcard.com, therefore you should resolve the `golint` issue by any means.

As for code coverage of 80%, it is also our contributing guideline, see https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards, unless you have some special reasons which make it hard/impossible to be >=80%, you have to increase it to >=80%.

**Comment by panjf2000** [comment]
It's been more than 15 days without a reply from the PR owner, I'm closing this PR according to our [contributing guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers).

Feel free to reopen it once you resolve those code issues.

**Comment by alexpevzner** [comment]
Seems you have rejected my application without even reading my arguments :-(

#2939, that you've mentioned here, you have merged with a similar problems and similar reasons just because its author was more noisy that me.

**Comment by panjf2000** [comment]
Not again...

Every guy who violates our standards thinks he should be an exception to merge his PR, that guy insisted that too but I've taught him a lesson about following rules and he also resolved all code issues I requested except for `gocyclo` which is not a mandatory item.

I did read your comments but the reasons you used to justify breaking our standards just didn't convince me to give you an exception.

**Comment by alexpevzner** [comment]
Your standard requires "tests, where practical". Testing code that simply converts integer values to strings is not practical. So here your standard is not violated.

golint dictates unreadable for humans form of commenting public constants. Programs are written for humans, not for golint. It is obviously golint bug.

Instead of "taughting me a lesson", you'd better find a minute or two to read my polite and correct questions before answering them. May be you should find a couple minutes to look to the code itself rather that to golint logs.

I believe the quality of this library is very high, because 1) it is professionally written 2) it is well documented 3) it works in a real project and tested against a variety of real hardware.

**Pull request closed without merging**
