### PR TITLE
add Gleam

### PR DESCRIPTION
**Pull request by chrislusf**
adding gleam

### CODE REVIEW

**Comment by chrislusf** [comment]
Added wiki docs, godocs, travis tests.

The report card is here and I will be continuously improving the results.
http://goreportcard.com/report/chrislusf/gleam

**Comment by kirillDanshin** [comment]
please fill our pull request template in your pull request message, fix all goreportcard issues and setup coverage services.

**Comment by chrislusf** [comment]
Please provide package links to:

github.com repo: https://github.com/chrislusf/gleam
godoc.org: https://godoc.org/github.com/chrislusf/gleam/flow
goreportcard.com: https://goreportcard.com/report/github.com/chrislusf/gleam
coverage service link (gocover, coveralls etc.): https://codecov.io/gh/chrislusf/gleam
Note: that new categories can be added only when there are 3 packages or more.

Make sure that you've checked the boxes below before you submit PR:

 I have added my package in alphabetical order
 I know that this package was not listed before
 I have added godoc link to the repo and to my pull request
 I have added coverage service link to the repo and to my pull request
 I have added goreportcard link to the repo and to my pull request
 I have read Contribution guidelines and Quality standard.

**Comment by kirillDanshin** [comment]
@chrislusf coverage should be >= 80%, now you have only 29%.

**Comment by chrislusf** [comment]
@kirillDanshin I agree. The project is big and new, but already 300+ stars. I am actively working on it to improve the metrics. 

There are simply way too many tests to add. And many code are generated, I need to exclude them.

**Comment by kirillDanshin** [comment]
@chrislusf also you may want to check out efaceconv package, I see you use empty interfaces that adds big overhead. eface is `struct {_type *_type; data unsafe.Pointer; }`, so to read from interface{} you should copy value to a new variable that adds one allocation per assertion. To write into interface{} you should allocate a new eface instance, that is one more allocation. with efaceconv and efaceconv/ecutils you can avoid this, but use it only under the hood and don't give result of GetDataPtr to user.

**Comment by chrislusf** [comment]
@kirillDanshin This is an amazing tip! Thanks! Great to learn this!

**Comment by chrislusf** [comment]
@avelino @kirillDanshin I have managed to increase the coverage from %40 to %60, by skipping many proto buffer generated code.

However, adding the coverage tests for this distributed system is difficult. The system is run in distributed mode and needs at least one master server and one agent server to begin testing the distributed execution. I have tried but failed to run the tests in distributed mode due to the system design. It is quite a big project just to rewrite the system for the testing purpose.

I have tests with code coverage for standalone mode already.
For distributed mode, there are a bunch of examples to test the distributed execution already. Please see https://github.com/chrislusf/gleam/tree/master/examples

This is a project getting some attraction. I would request you adjust the criteria a little bit. The test is very important. However, the testing method is different for this truly distributed computing system.

**Comment by kirillDanshin** [comment]
@chrislusf you can run it in go.test.sh in background mode.
ok, I merge this. but please improve your coverage without disabling tests.

**Pull request merged**
