### PR TITLE
Add qiniu/qmgo

### PR DESCRIPTION
**Pull request by jiangz222**
Qmgo - The MongoDB dirver for Go . It‘s based on MongoDB official driver but easier to use like Mgo

**Please provide package links to:**

- github.com repo: https://github.com/qiniu/qmgo
- pkg.go.dev: https://pkg.go.dev/github.com/qiniu/qmgo?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/qiniu/qmgo
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](https://codecov.io/gh/qiniu/qmgo) etc.): https://codecov.io/gh/qiniu/qmgo

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by panjf2000** [comment]
Why is there no documentation tab for this repo on pkg.go.dev while other open-source repositories do?

**Comment by jiangz222** [comment]
> Why is there no documentation tab for this repo on pkg.go.dev while other open-source repositories do?

DONE!

**Comment by panjf2000** [comment]
All links look good to me but there is no file changed in this PR, you need to add your repo into the README.

**Comment by jiangz222** [comment]
> All links look good to me but there is no file changed in this PR, you need to add your repo into the README.

Done 👌

**Pull request merged**
