### PR TITLE
Added Azul3D in section gamedev.

### PR DESCRIPTION
**Pull request by dtelyukh**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo: https://github.com/azul3d/engine
- godoc.org: https://godoc.org/github.com/azul3d/engine
- goreportcard.com: https://goreportcard.com/report/github.com/azul3d/engine
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/azul3d/engine (gocover.io fails on this repo for some reason)

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [ ] I have added godoc link to the repo and to my pull request
- [ ] I have added coverage service link to the repo and to my pull request
- [ ] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by shurcooL** [comment]
As far as I know, azul3d engine is not being actively developed anymore. Is that so @slimsag? Do you think it's worth adding to the list in its current state and future outlook?

**Comment by slimsag** [comment]
That is true. However, it is still one of (the?) Most complete 3d engine in
Go to date so I'd say it would be very valuable to anyone interested in
gamedev.

**Comment by shurcooL** [comment]
> it would be very valuable to anyone interested in gamedev.

I see. In that case, it's worth adding.

**Comment by shurcooL** [comment]
I've added links to the original post.

I'm being more lenient with the review because this is a 3D game engine, which has huge scope. I don't expect near 100% test coverage for 3D code the way I would for a small format decoding library, for example.

LGTM since this is valuable in the field of game dev in Go and is as good/better than many other entries in this category, of which there aren't that many to begin with.

**Pull request merged**
