### PR TITLE
Add rabbus eventbus

### PR DESCRIPTION
**Pull request by rafaeljesus**
- github.com repo: https://github.com/rafaeljesus/rabbus
- godoc.org: https://godoc.org/github.com/rafaeljesus/rabbus
- goreportcard.com: https://goreportcard.com/report/github.com/rafaeljesus/rabbus
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/)) http://gocover.io/github.com/rafaeljesus/rabbus

- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

PS: GoCover seems to be broken, the actual is coverage is`coverage: 81.5% of statements` you can see build logs, pls [check it out](https://circleci.com/gh/rafaeljesus/rabbus/11)

### CODE REVIEW

**Comment by rafaeljesus** [comment]
@avelino 

> PS: GoCover seems to be broken, the actual is coverage iscoverage: 81.5% of statements you can see build logs, pls check it out

**Comment by rafaeljesus** [comment]
https://circleci.com/gh/rafaeljesus/rabbus all green

**Comment by avelino** [comment]
screenshot 2017-05-07 17 40 48

**Comment by rafaeljesus** [comment]
I see, but don't understand why it is failing only the coverage tools. I had this error before when I was unable to connect to the rabbitmq-server, I am going to close since I don't know how to fix this on GOCover and cover.run. Thank you

**Comment by avelino** [comment]
@rafaeljesus mock

**Pull request closed without merging**
