### PR TITLE
add Beep audio library

### PR DESCRIPTION
**Pull request by faiface**
Hi! Beep wasn't ready for Awesome Go for a long time, because it had a terrible README, no tutorials, and no examples. But that has changed now, so I'm adding it :)

GitHub: https://github.com/faiface/beep
GoDoc: https://godoc.org/github.com/faiface/beep
Go Report Card: https://goreportcard.com/report/github.com/faiface/beep

### CODE REVIEW

**Comment by faiface** [comment]
The test coverage is about 60% right now. I will make my best to increase it as high as I can, and I'll get back to you.

**Comment by ceriath** [comment]
@faiface any progress? could you provide a working coverage link?

**Comment by faiface** [comment]
Sorry for not responding sooner, I'm working on the tests, although I've had other things recently, so there wasn't too much work. Hopefully I'll finish them soon, then get back to you.

If it's necessary, we can close this issue and then I'll open another one, but I don't think that's needed.

**Comment by avelino** [comment]
> The maintainers will review your PR and notify you and tag it in case any information is still missing. They will wait 30 days for your interaction, after that the PR will be closed.
https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers

**Pull request closed without merging**
