### PR TITLE
Add dudeldu

### PR DESCRIPTION
**Pull request by krotik**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/krotik/dudeldu
- godoc.org: https://godoc.org/devt.de/krotik/dudeldu
- goreportcard.com: https://goreportcard.com/report/devt.de/krotik/dudeldu
- coverage service link [gocover](https://gocover.io/github.com/krotik/dudeldu) / <a href="https://void.devt.de/pub/dudeldu/coverage.txt">Code coverage</a>

Note: The linked github repo in the README.md is a mirror of (devt.de/krotik/dudeldu) - I would like to use it to cope with traffic and receive stars.

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x ] I have added my package in alphabetical order.
- [ x] I have an appropriate description with correct grammar.
- [ x] I know that this package was not listed before.
- [ x] I have added godoc link to the repo and to my pull request.
- [ x] I have added coverage service link to the repo and to my pull request.
- [ x] I have added goreportcard link to the repo and to my pull request.
- [ x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@krotik can you please review the gocyclo warnings?

**Comment by krotik** [comment]
Thanks @kirillDanshin  for the review. Two warnings come from test files which can get quite long. The other warning is about request handler functions which take care of a myriad of different cases. All the logicis fully tested (i.e. every branch, loop and condition has been tested).

**Comment by kirillDanshin** [comment]
@krotik 

I'm ok with long tests in this particular case, but I think you really need to refactor your handlers and also consider replacing `if DebugOutput { Print` with just a `debug` function (inside this func you can check for DebugOutput etc.), you'll save a lot of space in this way.
Did you consider instance wide debugging? you'll need to move `DebugOutput` to the server structure in this case, and probably support a customizable log output for each instance. that's may be an idea for a new feature :)

Also, `/* */` comments doesn't look well in godoc, I'd suggest you to switch over to `//`.

In some cases I see that you use redundant parenthesis, which keep the same operator precedence, like here: https://github.com/krotik/dudeldu/blob/master/requesthandler.go#L139 (proof: https://play.golang.org/p/cmB7Ko7Bzhf)

**Comment by krotik** [comment]
Thanks @kirillDanshin for the code review. I've now refactored the handlers into smaller functions. I agree with your suggestion for `if DebugOutput { Print` and also refactored this into a function.

Your suggestion of moving `DebugOutput` (and maybe `Print`) makes sense. I'll have to think about it. A server supports already multiple streams and multiple clients so I wouldn't expect normally more than one server running at a given time but it could be easily done and wouldn't hurt ...

I am not sure why `/* */` don't look well in godoc - does something look off in godoc for Dudeldu? I must say that I find `//` quite jarring for multi-line comments when reading source code so would prefer to keep `/* */` but I can see that `//` is considered more idiomatic ...

The redundant parenthesis are there mostly to ease code comprehension. I don't mind either way and removed them.

**Comment by kirillDanshin** [comment]
@krotik speaking of godoc, you can see the difference in text alignment here https://godoc.org/devt.de/krotik/dudeldu#Playlist and here https://godoc.org/github.com/audioid/audioid/metadata#Track

There's also some differences in IDE, but it depends on particular editor and plugins

**Comment by krotik** [comment]
@kirillDanshin thank you - I understand. Seeing the two options side-by-side I must say that I do prefer the current format and alignment. Please do let me know if `//` line comments are a hard requirement for the `awesome-go` list.

**Comment by kirillDanshin** [comment]
@krotik we're do not require any particular comment style, although I'd pass this one to @ceriath

**Comment by ceriath** [comment]
Are you sure you want to have this file checked into github? https://github.com/krotik/dudeldu/blob/master/rufs.secret

Also, i am not a big fan of the ``-auth`` parameter, since auth infos will end up in your commandline history this way. However, that does not prevent this from merging into the list, i'll wait on your response on the first matter before merging though.

**Comment by krotik** [comment]
Thanks @ceriath well spotted - this was some leftover from some experiment :+1: I've removed the files.

Regarding the auth parameter - you are right. Having an authentication parameter in the commandline history is not a good thing and I'll add support for environment variables. 

Dudeldu as a standalone server is not expected to deliver very sensitive data (it is a music stream in the end). The current auth happens via unsecured basic auth and can only have a single username/password combination. The whole reason for the auth feature is not to be secure but to make the stream non-public. This is important to not get into trouble with for example the GEMA in Germany for running a public streaming service :smiley_cat:.

Having said that, it is of course possible to include DudelDu as a library, run it behind a secured HTTPS service and add a custom request handling layer for more fine grained access control.

Thanks again @kirillDanshin and @ceriath for the code review. It is much appreciated.

**Comment by krotik** [comment]
I've also added now instance specific debug logging as suggested by @kirillDanshin and the option to pass in authentication information via an environment variable.

**Comment by krotik** [comment]
Hi, could someone please merge this PR? @kirillDanshin @ceriath

**Pull request merged**
