### PR TITLE
Include new resource under the tutorials category

### PR DESCRIPTION
**Pull request by IgorRocha**
Hi!
I'm a computer engineering student from Brazil, and I have taught programming for engineer undergrads for more than two years. Today I'm working at Classpert - an online course aggregation engine with over 130000 courses already. I'm submitting this PR to include a link to our page regarding Go courses: https://classpert.com/go-programming
I hope this kind of link doesn't break any Wiki guidelines. We would also love to hear feedback from the wik maintainers on how we could provide more insights that could be useful for Go learners.

Thanks!
#######################

Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo:
- godoc.org:
- goreportcard.com:
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `[cover.run](https://cover.run/go?tag=golang-1.10&repo=github.com%2Fuser%2Frepository)`

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [ ] I have added godoc link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request.
- [ ] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
I think it necessary to **open thread discussion** (issue), the courses on the website sent in the PR are paid courses.

My opinion is that you must **not** enter the list. Entering it seems that the community  **"awesome-go"** approves the users do the courses, I do not know the quality of the course to recommend the courses

**Comment by IgorRocha** [comment]
Hi @avelino! Thanks for looking into the PR. 
We display both paid and free courses at classpert.com. Would it be better if the link I want to include on the awesome-go list had a parameter that filtered the results to show only free courses?

**Comment by avelino** [comment]
free: https://pt-br.classpert.com/go-programming?filter%5Bprice%5D%5B%5D=0&filter%5Bprice%5D%5B%5D=0&p=1&q=

`0 index` It doesn't make sense to keep it, you agree with me?

**Comment by IgorRocha** [comment]
You're absolutely correct, @avelino! Thanks for pointing that out. I can see that we do have a couple of indexed free golang courses, but for some reason they are not appearing on that page. Anyway, we have too few free courses to be included in the awesome-go list. We will work on fetching more free courses that can be valuable for the Go community, and then I will open a new PR. Thanks for the feedback and congrats on maintaining a useful resource list for the community!

**Pull request closed without merging**
