### PR TITLE
add olivia-ai/olivia to the bot building section

### PR DESCRIPTION
**Pull request by hugolgst**
Add [Olivia](https://github.com/olivia-ai/olivia) chatbot to the list.

**Please provide package links to:**

- github.com repo: https://github.com/olivia-ai/olivia
- pkg.go.dev: https://pkg.go.dev/github.com/olivia-ai/olivia?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/olivia-ai/olivia
- coverage service link: https://codecov.io/gh/olivia-ai/olivia

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: False
- goreportcard.com: False
- coverage: False

**Comment by hugolgst** [comment]
It is in alphabetical order, the links are here too.

**Comment by panjf2000** [comment]
You didn't fill in the info according to the PR template.

**Comment by hugolgst** [comment]
I've fixed it.

**Comment by panjf2000** [comment]
Also, please resolve the golint issues: https://goreportcard.com/report/github.com/olivia-ai/olivia#golint

**Comment by hugolgst** [comment]
All done, sorry for messing this PR.

**Pull request merged**
