### PR TITLE
Adding YANFF library

### PR DESCRIPTION
**Pull request by aregm**
Hi again,
Adding a link to the YANFF - Yet Another Network Function Framework to the awesome-go. Framework for creating cloud native network scalable network functions.

- github.com repo: https://github.com/intel-go/yanff
- godoc.org: https://godoc.org/github.com/intel-go/yanff
- goreportcard.com: [Go Report Card](https://goreportcard.com/report/github.com/intel-go/yanff)
- coverage service link - This is a framework, it has external dependencies for the successful build, which cannot be done online. 

- [X] I have added my package in alphabetical order.
- [X] I have an appropriate description with correct grammar.
- [X] I know that this package was not listed before.
- [X] I have added godoc link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request. - cannot be done by coverage tool online
- [X] I have added goreportcard link to the repo and to my pull request.
- [X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by aregm** [comment]
Ping.

**Comment by aregm** [comment]
@appleboy Is this a "must-have" requirement? You have a bunch of packages not conforming to this requirement, but still included., e.g. SNAP telemetry framework which comes also from Intel.

**Comment by appleboy** [comment]
@aregm Yes. you can only ignore `gocyclo` warnings.

**Comment by avelino** [comment]
read pls: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers

**Comment by aregm** [comment]
@appleboy @avelino Done.

**Comment by appleboy** [comment]
Not yet. https://goreportcard.com/report/github.com/intel-go/yanff

**Comment by aregm** [comment]
This PR is closed, let's discuss in PR 1579 - What not yet?

**Pull request closed without merging**
