### PR TITLE
Add immudb

### PR DESCRIPTION
**Pull request by vchaindz**
Add immudb to README

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: False
- coverage: False

**Comment by vchaindz** [comment]
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/codenotary/immudb
- pkg.go.dev:
- goreportcard.com: https://goreportcard.com/report/github.com/codenotary/immudb
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.)


Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [ ] I have added pkg.go.dev link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

**Comment by vchaindz** [comment]
what is missing exactly?
we don't have these two, but everything else is mentioned:
- I have added pkg.go.dev link to the repo and to my pull request.
- I have added coverage service link to the repo and to my pull request.

**Comment by panjf2000** [comment]
It's been more than 15 days without a reply from the PR owner, I'm closing this PR according to our [contributing guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers).

Feel free to reopen it once you resolve those issues.

**Comment by vchaindz** [comment]
goreportcard errors have been fixed

**Comment by Giako** [comment]
Is it possible to reopen this PR?

Here follows the up-to-date version of the comment by @vchaindz with the coveralls coverage service link:

---

Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/codenotary/immudb
- pkg.go.dev: https://pkg.go.dev/github.com/codenotary/immudb?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/codenotary/immudb
- coverage service link: https://coveralls.io/github/codenotary/immudb?branch=master

Very good coverage: [Go Report Card](https://goreportcard.com/report/github.com/codenotary/immudb)

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

**Review by avelino — COMMENTED** [review]
review:
- godocs
- golint https://goreportcard.com/report/github.com/codenotary/immudb#golint

When it's OK, open a new pull request - this way we avoid conflict

**Pull request closed without merging**
