### PR TITLE
Adding the golang-set package which offers thread-safe and non-thread-sa...

### PR DESCRIPTION
**Pull request by deckarep**
Hello,

This library offers unit-tested, benchmarked high-performance set datastructures for Go.  It comes in both thread-safe and non-threadsafe versions and implements a common interface between both of them.

https://github.com/deckarep/golang-set

Note: I added this under a new category of data-structres since I didn't think it really belonged anywhere else.

Please consider adding it!

-Thanks!

### CODE REVIEW

**Comment by mholt** [comment]
I agree the new category is merited. The Database category has a pseudo-section for data structures. Would you mind moving all those into the new Data Structures category? That'd help us make this a lot better, I think.

**Comment by deckarep** [comment]
Will do!

**Comment by deckarep** [comment]
@mholt - this should be good to go now!  Thanks for looking at this.

**Comment by mholt** [comment]
Sweet, we just gotta take care of that merge conflict - could you do that? Then I'll merge it in.

**Comment by deckarep** [comment]
@mholt - ok, should be good to go.

**Comment by mholt** [comment]
Thank you!

**Pull request merged**
