### PR TITLE
Add go-pg

### PR DESCRIPTION
**Pull request by vmihailenco**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo: https://github.com/go-pg/pg
- godoc.org: http://godoc.org/gopkg.in/pg.v5
- goreportcard.com: https://goreportcard.com/report/gopkg.in/pg.v5
- coverage service link (gocover, coveralls etc.): https://travis-ci.org/go-pg/pg

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [ ] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by felipeweb** [comment]
@vmihailenco  add coverage link

**Comment by funny-falcon** [comment]
What is "coverage link" ?

**Comment by kamilsk** [comment]
@funny-falcon, https://gocover.io/github.com/go-pg/pg (in this case) or https://coveralls.io/github/kamilsk/semaphore as examples

**Comment by funny-falcon** [comment]
It has testing link https://travis-ci.org/go-pg/pg

And it doesn't looks like github.com/lib/pq has any coverage, but it is listed.

**Comment by kirillDanshin** [comment]
LATM.

thanks.

**Pull request merged**
