### PR TITLE
add link to VarHandler

### PR DESCRIPTION
**Pull request by azr**
- godoc.org: https://godoc.org/github.com/azr/generators/varhandler
- goreportcard.com:  https://goreportcard.com/report/github.com/azr/generators
- gocover.io: Can't really, its a generator.

I'll be the maintainer.

I'd rather put it into web framework stuff, but it can put be in generation too, so I put it in both.

Is it fine ?

Cheers !

### CODE REVIEW

**Comment by kirillDanshin** [comment]
Hello.

Thank you for your contributions.

I'm sorry, but you'll need to remove duplicates and all new categories.
Please, read our [contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md). Unfortunately, we can't approve your pull request until you fix this issues.

**Comment by azr** [comment]
Et voilà ! 

Is it better ?

**Comment by kirillDanshin** [comment]
@azr Voilà ce dont nous avons besoin. Merci!
@matrixik can we merge it? looks pretty good to me now.

@azr if you want, I can write some tests for your generator later.

**Comment by azr** [comment]
@kirillDanshin oh nice, I'd gladly accept some tests !! :)

**Comment by matrixik** [comment]
Hello, sorry it took me so long (life).

`golint` is low, mostly duo to examples but fix warnings in main package files (generator.go and var_func_def.go), please (just some docs), and you have some misspelled words in docs.

Nonetheless nice package.

**Comment by azr** [comment]
hello @matrixik all right, I'm going to fix those next week !

thanks :)

**Pull request merged**
