### PR TITLE
add repo evaluator which evaluates an expression dynamicly

### PR DESCRIPTION
**Pull request by nullne**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/nullne/evaluator
- godoc.org: https://godoc.org/github.com/nullne/evaluator
- goreportcard.com: https://goreportcard.com/report/github.com/nullne/evaluator
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.) : [Coverage Status](https://coveralls.io/github/nullne/evaluator?branch=master)

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by nullne** [comment]
@cassiobotaro I complemented with some necessary docs. Is it good enough with 62%？ Most of the uncomments exported variables are self-explanatory.   
thank you for your time

**Comment by cassiobotaro** [comment]
@nullne I think you can do better, and there are other warnings like `warning: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary) (golint)`.
Look this too.
image

**Comment by nullne** [comment]
@cassiobotaro I fix most of the "if else block" format but there are still some left. In most cases, it's very clear to drop else statement. In some cases it's better to use the format 'if ... else ...". 
for example in my code 
```
 if l, isList := exp.i.(list); isList {
     ...
 } else{
     ...
 }
```

you will get it on the first glance at this code block. if the element is a list, blablabla,  else treat it the other way

**Comment by nullne** [comment]
@appleboy added license.  
thank you for your time

**Comment by nullne** [comment]
@cassiobotaro   It's better now, right?
btw. time lag is so boring, hah
screen shot 2017-11-10 at 10 59 53 am

**Comment by appleboy** [comment]
@nullne You can remove the `else` block to improve code quality.

https://github.com/nullne/evaluator/blob/master/s-expression.go#L65-L74

**Comment by nullne** [comment]
@appleboy  all right, look at this, all 100%

screen shot 2017-11-10 at 12 11 18 pm

**Comment by cassiobotaro** [comment]
thanks @nullne !

**Pull request merged**
