### PR TITLE
add minimp3

### PR DESCRIPTION
**Pull request by lieff**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

 *  github.com repo: https://github.com/tosone/minimp3
 *  godoc.org: https://godoc.org/github.com/tosone/minimp3
 *  goreportcard.com: https://goreportcard.com/report/github.com/tosone/minimp3
 *  coverage service link: [Coverage Status](https://coveralls.io/github/tosone/minimp3)

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by lieff** [comment]
My bad, fixed and squashed commits.

**Comment by appleboy** [comment]
Please follow the issue template.

**Comment by lieff** [comment]
I can provide C part links:
https://codecov.io/gh/lieff/minimp3
https://scan.coverity.com/projects/lieff-minimp3

Go bindings part pending here https://github.com/tosone/minimp3/issues/1

**Comment by tosone** [comment]
Thank you @lieff. I have never notice this : ) 

- github.com repo: https://github.com/tosone/minimp3
- godoc.org: https://godoc.org/github.com/tosone/minimp3
- goreportcard.com: https://goreportcard.com/report/github.com/tosone/minimp3
- coverage service link: [Coverage Status](https://coveralls.io/github/tosone/minimp3)

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

**Pull request merged**
