### PR TITLE
Add rain

### PR DESCRIPTION
**Pull request by cenkalti**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/cenkalti/rain
- godoc.org: https://godoc.org/github.com/cenkalti/rain/torrent
- goreportcard.com: https://goreportcard.com/report/github.com/cenkalti/rain
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://gocover.io/github.com/cenkalti/rain/torrent

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by panjf2000** [comment]
Please fix issues in goreport: 
https://goreportcard.com/report/github.com/cenkalti/rain#golint
https://goreportcard.com/report/github.com/cenkalti/rain#gocyclo

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: True
- goreportcard.com: True
- coverage: True

**Comment by cenkalti** [comment]
Hello @panjf2000 

All golint warnings belong to internal packages. These packages are quite small and not importable by user and I don't think they need to be commented.

Gocyclo issues are another story. There are some inevitable events that I must write a switch with many cases. For example, the client must take different actions when a message received from a peer by inspecting the message ID. Please take look at: https://github.com/cenkalti/rain/blob/7ab91a6052aa3c18c86fcb0244b7cd85f80cea72/torrent/torrent_messagehandler.go#L116

**Comment by panjf2000** [comment]
@cenkalti 
I admired your work here but I'm not convinced by your explanations about the golint, I will just leave the decision to @avelino

**Comment by cenkalti** [comment]
@panjf2000 I have fixed all golint issues. Can you check it again please?
https://goreportcard.com/report/github.com/cenkalti/rain

**Comment by panjf2000** [comment]
Well, since`gocyclo` is a controversial standard and I am not a big favorer of it, I will just approve your PR and pass it to @avelino

**Comment by panjf2000** [comment]
@cenkalti 
Besides, please squash your commits to just one before your PR get merged.

**Comment by cenkalti** [comment]
Squashed my commits.

**Pull request merged**
