### PR TITLE
Added github.com/tdewolff/minify

### PR DESCRIPTION
**Pull request by tdewolff**
https://godoc.org/github.com/tdewolff/minify
https://goreportcard.com/report/github.com/tdewolff/minify
https://travis-ci.org/tdewolff/minify
http://gocover.io/github.com/tdewolff/minify all subpackages and dependencies have coverage of ~100% too

### CODE REVIEW

**Comment by felipeweb** [comment]
@tdewolff Please add on readme

**Comment by tdewolff** [comment]
Where? And which links need to be added?

**Comment by felipeweb** [comment]
https://godoc.org/github.com/tdewolff/minify
https://goreportcard.com/report/github.com/tdewolff/minify
https://travis-ci.org/tdewolff/minify
http://gocover.io/github.com/tdewolff/minify

**Comment by tdewolff** [comment]
[Build Status](https://travis-ci.org/tdewolff/minify)
[Go Report Card](https://goreportcard.com/report/github.com/tdewolff/minify)
[GoDoc](https://godoc.org/github.com/tdewolff/minify)
[Coverage Status](https://coveralls.io/github/tdewolff/minify?branch=master)

**Pull request merged**
