### PR TITLE
Full Review [WIP]

### PR DESCRIPTION
**Pull request by ceriath**
See #1446 and #2036 

Right now, we seem to have a huge variety of code quality in this awesome list. We should do a full review of the list and remove packages that (no longer) meet our [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards). 

(I also don't know why nobody bothered yet to take care of the packages mentioned in #1446)

This PR is Work in Progress.

- [x] Audio and Music
- [x] Authentication and OAuth
- [ ] Bot Building
- [ ] Command Line
- [ ] Configuration
- [ ] Continuous Integration
- [ ] CSS Preprocessors
- [ ] Data Structures
- [ ] Database
- [ ] Database Drivers
- [ ] Date and Time
- [ ] Distributed Systems
- [ ] Email
- [ ] Embeddable Scripting Languages
- [ ] Error Handling
- [ ] Files
- [ ] Financial
- [ ] Forms
- [ ] Functional
- [ ] Game Development
- [ ] Generation and Generics
- [ ] Geographic
- [ ] Go Compilers
- [ ] Goroutines
- [ ] GUI
- [ ] Hardware
- [ ] Images
- [ ] IoT
- [ ] Job Scheduler
- [ ] JSON
- [ ] Logging
- [ ] Machine Learning
- [ ] Messaging
- [ ] Microsoft Office
- [ ] Microsoft Excel
- [ ] Miscellaneous
- [ ] Dependency Injection
- [ ] Strings
- [ ] Natural Language Processing
- [ ] Networking
- [ ] HTTP Clients
- [ ] OpenGL
- [ ] ORM
- [ ] Package Management
- [ ] Query Language
- [ ] Resource Embedding
- [ ] Science and Data Analysis
- [ ] Security
- [ ] Serialization
- [ ] Template Engines
- [ ] Testing
- [ ] Text Processing
- [ ] Third-party APIs
- [ ] Utilities
- [ ] UUID
- [ ] Validation
- [ ] Version Control
- [ ] Video
- [ ] Web Frameworks
- [ ] Middlewares
- [ ] Actual middlewares
- [ ] Libraries for creating HTTP middlewares
- [ ] Routers
- [ ] Windows
- [ ] XML
- [ ] Tools

- [ ] Code Analysis
- [ ] Editor Plugins
- [ ] Go Generate Tools
- [ ] Go Tools
- [ ] Software Packages
- [ ] DevOps Tools
- [ ] Other Software
- [ ] Server Applications

- [ ] Resources

- [ ] Benchmarks
- [ ] Conferences
- [ ] E-Books
- [ ] Gophers
- [ ] Meetups
- [ ] Twitter
- [ ] Websites
- [ ] Tutorials

### CODE REVIEW

**Comment by ceriath** [comment]
Note that i personally rather keep a package that has some minor issues (a few missing comments on self-explaining variables or functions, ...) than removing it, when the package generally is useful

**Comment by kilgaloon** [comment]
Do you think maybe there should be a bot that is scanning for packages and their quality and then creates PR automatically for package to be removed?

**Comment by ceriath** [comment]
I honestly don't think this could be done by a bot. Some packages just have to be looked into deeper to understand what they do. Also, writing a bot to do that might be more effort than just doing it by hand

**Comment by Dynom** [comment]
> May I ask why https://github.com/dgrijalva/jwt-go was removed? It's a very solid library for dealing with JSON Web Tokens

I don't know. My guess would be that it's superseded with "better" implementations, according to: https://jwt.io/ -- There are several implementations that have a better coverage of algorithms and functionality. In total there are 11 implementations and some seem a bit more actively maintained.


Slightly more on-topic of this thread:
Should there be a status/indicator regarding audits performed by recognised authorities for security related libraries?
I'm a little surprised that there isn't any mention about security on https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards.

/cc @FiloSottile

**Comment by avelino** [comment]
sorry delay @ceriath 
Divide into any pull request, please

**Pull request closed without merging**
