### PR TITLE
Added Gowut.

### PR DESCRIPTION
**Pull request by icza**
**Please provide package links to:**
- github.com repo: https://github.com/icza/gowut
- godoc.org: https://godoc.org/github.com/icza/gowut/gwu
- goreportcard.com: https://goreportcard.com/report/github.com/icza/gowut
- coverage service link (gocover, coveralls etc.): Not practical

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by icza** [comment]
What kind of tests should I add? Gowut is a web UI framework, it generates code that is run at client side, in the browser. What links do I need to add?

**Comment by kirillDanshin** [comment]
@icza you can do testing with Selenium Grid, for example.

**Comment by corburn** [comment]
Hello @icza,

Here is an example where adding `Render()` and a `// Output:` comment could turn your ExampleButton function into a unit test:

```go
func ExampleButton() {
    b := gwu.NewButton("Click me")
    b.AddEHandlerFunc(func(e gwu.Event) {
        if e.MouseBtn() == gwu.MouseBtnMiddle {
            // Middle click
        }
    }, gwu.ETypeClick)

    button.Render(os.Stdout)

    // Output:
    // <button ....>Click Me</button>
}
```

You could implement a functional test by taking your example `simple_demo.go` and turn it into a [whole file example](https://blog.golang.org/examples). In such a test you could use the [httptest package](https://golang.org/pkg/net/http/httptest/#ResponseRecorder) to simulate a client connecting to your server (Refer to the [ResponseRecoder](https://golang.org/pkg/net/http/httptest/#ResponseRecorder) example). The simulated client could then write the http.Response.Body to os.Stdout so the HTML could be validated with a `// Output:` comment.

Instead of or in addition to `Example` functions with `// Output:` comments, you could write `Test` functions for each renderable component. With [TableDrivenTests](https://github.com/golang/go/wiki/TableDrivenTests) your tests could, in a concise format, exercise the various component options.

**Comment by kirillDanshin** [comment]
@corburn hi.
it's bad to test what it output because any PR with output code optimizations will fail tests.
so Selenium is one of the best to test frontend behavior.

**Comment by icza** [comment]
Thanks for the feedback. Gonna close this PR and submit a new one when tests are added.

**Comment by kirillDanshin** [comment]
@icza feel free to ask me something :)

**Comment by shurcooL** [comment]
I just wanted to say I've looked at Gowut and it looks really cool. Nice work. Looking forward to it being added!

**Pull request closed without merging**
