### PR TITLE
add rainbond project

### PR DESCRIPTION
**Pull request by barnettZQG**
- github.com repo:  [https://github.com/goodrain/rainbond](https://github.com/goodrain/rainbond)
- godoc.org:  [https://godoc.org/github.com/goodrain/rainbond](https://godoc.org/github.com/goodrain/rainbond)
- goreportcard.com:  [https://goreportcard.com/report/github.com/goodrain/rainbond](https://goreportcard.com/report/github.com/goodrain/rainbond)

- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by barnettZQG** [comment]
@cassiobotaro Okay, we'll fix that later

**Comment by barnettZQG** [comment]
@cassiobotaro 
I've optimized the code, and result is A+  [Go Report Card](https://goreportcard.com/report/github.com/goodrain/rainbond)

Do I must have to resolve all issues?

**Comment by ceriath** [comment]
@barnettZQG yes, please resolve all issues. Some with gocyclo are okay, because those can be sometimes even more complex when trying to resolve the issues

**Comment by ceriath** [comment]
Closing this due to inactivity.
@barnettZQG Please reopen the PR after fixing the issues!

**Pull request closed without merging**
