### PR TITLE
Add httpware

### PR DESCRIPTION
**Pull request by nstogner**
httpware is a library for composing/creating http middleware. It also contains a collection of middleware packages. I was not sure whether to put it under "Actual Middlewares" or "Libraries for creating HTTP middlewares", so I went with the latter.

### CODE REVIEW

**Comment by nstogner** [comment]
any objection?

**Comment by nstogner** [comment]
bump

**Comment by kirillDanshin** [comment]
@nstogner please add links to godoc, goreportcard and gocover.io (with sub-packages). Thanks!

**Comment by nstogner** [comment]
Godoc:
https://godoc.org/github.com/nstogner/httpware

Go Report Card:
https://goreportcard.com/report/github.com/nstogner/httpware

Go Cover:
https://gocover.io/github.com/nstogner/httpware
https://gocover.io/github.com/nstogner/httpware/contentware
https://gocover.io/github.com/nstogner/httpware/corsware
https://gocover.io/github.com/nstogner/httpware/errorware
https://gocover.io/github.com/nstogner/httpware/httpctx
https://gocover.io/github.com/nstogner/httpware/limitware
https://gocover.io/github.com/nstogner/httpware/routeradapt
https://gocover.io/github.com/nstogner/httpware/tokenware

**Comment by kirillDanshin** [comment]
@nstogner thanks! please fix misspell and golint errors. also, please add more tests, for example `httpware/httpctx` and `httpware/logware` isn't covered at all. then rebase your fork with current master branch state or create new PR to avoid git conflicts. thank you again!

**Comment by nstogner** [comment]
The misspellings have been fixed. Tests have been added for the logware package:
https://gocover.io/github.com/nstogner/httpware/logware

The httpctx package does not have any testable code.

I will create a new PR.

**Comment by nstogner** [comment]
The new PR is here: https://github.com/avelino/awesome-go/pull/906

**Pull request closed without merging**
