### PR TITLE
Added grimd

### PR DESCRIPTION
**Pull request by looterz**
godoc.org: https://godoc.org/github.com/looterz/grimd
goreportcard.com: https://goreportcard.com/report/github.com/looterz/grimd
gocover.io: https://gocover.io/github.com/looterz/grimd

### CODE REVIEW

**Comment by kirillDanshin** [comment]
Hi.

Please, add more tests, fix documentation (so we can see it on godoc), fix issues from goreportcard, check out our quality standard and, finally, check out our pull request todo list from `pull request template`.

**Comment by looterz** [comment]
Thanks for the feedback, I setup the comments for functions according to go-vet but I see now that it isn't compatible with godoc's so I will be working on that. The only issue from the goreportcard is a gocyclo warning due to lots of error checking in a critical part of the codebase, so I'm not sure how I can fix that without ditching my error checking or logging. 

As for testing, a lot of it is marked as not covered because most of it is a program, not a library, with very few moving parts to test other than the cache so I'm unsure how I can go about setting up test units for those areas yet (first golang project).

**Comment by kirillDanshin** [comment]
@looterz please, ping me here when you done with docs

**Comment by looterz** [comment]
@kirillDanshin Everything is kept within package main and there are no exports, so I believe there won't be any docs generated by godoc.

**Comment by avelino** [comment]
new rules 8 days with label `pending-submitter-response`: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers

**Pull request closed without merging**
