### PR TITLE
update 

### PR DESCRIPTION
**Pull request by zdtdtel**
**update README.md** 
add a web framework - iris

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: False
- coverage: False

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by michaellee8** [comment]
I hate to do this but I think you would be better if you can do a quick search in PR before you actually submit code https://github.com/avelino/awesome-go/pulls?q=iris

Chinese translation for those who didn't understand the situation around iris-go:

Iris-go 的作者已經因為不尊重第三方許可權以及其他原因被這個 repo 封鎖了，他的問題可以在這裡看到：https://github.com/avelino/awesome-go/pull/1137，看不明白我可以幫忙翻譯。請不要再嘗試加 iris-go 進去這個repo了。

**Comment by phanirithvij** [comment]
Iris is banned from being added here

**Comment by zdtdtel** [comment]
@michaellee8  @phanirithvij 
I'm very sorry. I won't do that in the future. I will do a quick search in PR before submit code.

**Comment by phanirithvij** [comment]
@zdtdtel no worries, even I didn't know it was banned till I saw michaellee8's comment.

**Pull request closed without merging**
