### PR TITLE
add hashing section

### PR DESCRIPTION
**Pull request by blainsmith**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo: https://github.com/blainsmith/seahash
- godoc.org: https://godoc.org/github.com/blainsmith/seahash
- goreportcard.com: https://goreportcard.com/report/github.com/blainsmith/seahash
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/blainsmith/seahash

**Note**: that new categories can be added only when there are 3 packages or more.
I added a new section and moved a repo and added another one. There is a few more I've seen I can start collecting too.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by blainsmith** [comment]
I added coveralls to the repo. What isn't alphabetical?

**Comment by kirillDanshin** [comment]
@blainsmith add it to the links list in your message too.
@avelino it may be alphabetical but it based on old travis config.
@blainsmith please rebase your PR.

**Comment by blainsmith** [comment]
Still failing tests.

**Comment by avelino** [comment]
review error pls
```
    	repo_test.go:86: expected 'cryptography & hashing' but actual is 'css preprocessors'
    	repo_test.go:86: expected 'css preprocessors' but actual is 'cryptography & hashing'
    	repo_test.go:90: expected order is:
```
read more https://travis-ci.org/avelino/awesome-go/builds/187583899

**Comment by blainsmith** [comment]
You can close this and not merge if you want. I am out of ideas and I've spent too long actually messing with the tests for the sort order than adding the link in the first place.

**Comment by kirillDanshin** [comment]
@blainsmith just recreate your fork, it will be simple and quick.
thanks.

**Pull request closed without merging**
