### PR TITLE
Add Cameradar library

### PR DESCRIPTION
**Pull request by Ullaakut**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/Ullaakut/cameradar
- godoc.org: https://godoc.org/github.com/Ullaakut/cameradar
- goreportcard.com: https://goreportcard.com/report/github.com/Ullaakut/cameradar
- coverage service link [Coverage Status](https://coveralls.io/github/Ullaakut/cameradar?branch=master) https://coveralls.io/github/Ullaakut/cameradar?branch=master

**The low coverage of 79% is due to the fact that the library is mostly using `os.exec` and an external dependency which are not yet mocked. If that's an issue, I can prioritize this, but all of the relevant code that needs testing is currently already covered.**

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by jtemporal** [comment]
> all of the relevant code that needs testing is currently already covered.

Hi @Ullaakut this is great. But we need to follow our contributing guide that states the following:
> Tests, where practical. If the library/program is testable, then coverage should be >= 80% for non-data-related packages and >=90% for data related packages.

So please take a look into tackling those mocks :wink:

**Comment by Ullaakut** [comment]
Alright 👍 Will do this week and ping you on this PR, sounds good?

**Comment by avelino** [comment]
more 1% on cover pls 😄

**Comment by Ullaakut** [comment]
Yep, I started mocking the libcurl this morning, it might take me some time though I'm on many things at the same time :-)

**Comment by Ullaakut** [comment]
@avelino @jtemporal Fixed. I mocked my external library and the repo is now at 98% coverage! 🎉 Sounds good to you?

**Comment by Ullaakut** [comment]
Actually, wait I'll need to update this PR. I'm about to take ownership of the Cameradar repo from my organization, so the link will also change. I will ping you again once all of this is done.

Sorry for the bad timing!

**Comment by jtemporal** [comment]
@Ullaakut I changed the label so we know what's going on 😉

**Comment by Ullaakut** [comment]
@jtemporal @avelino Alright, I made all the necessary changes, updated this PR and squashed my commits not to break your timeline! 👌

**Pull request merged**
