### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by plandem**
added another library for XLSX

Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/plandem/xlsx
- godoc.org: https://godoc.org/github.com/plandem/xlsx
- goreportcard.com: https://goreportcard.com/report/github.com/plandem/xlsx
- coverage service link: https://codecov.io/gh/plandem/xlsx

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by plandem** [comment]
Of course its possible, but if you will closer, then 90% of this warnings about:
**MarshalXMLAttr** and **UnmarshalXMLAttr** methods. It's just weird to comment all that stuff that already well-known from official xml library

**Comment by plandem** [comment]
Hi! I updated long time ago, what's next?

**Comment by appleboy** [comment]
Please improve https://goreportcard.com/report/github.com/plandem/xlsx many warning from the report card.

**Comment by plandem** [comment]
Have ever look to these warning? That's weird to require comments for:
```
MarshalXMLAttr
UnmarshalXMLAttr
```

It's just faking/cheating system and has nothing with quality of code/documentation. 

What type of comments do you expect for this STANDARD interface implementation?

**Comment by plandem** [comment]
ok, I added comments for standard implementation of xml marshal/unmarshal. What's next?

**Pull request merged**
