### PR TITLE
Add Gio to list of Gui libaries

### PR DESCRIPTION
**Pull request by tehsphinx**
- github.com repo: https://github.com/gioui/gio
- pkg.go.dev: https://pkg.go.dev/gioui.org
- goreportcard.com: https://goreportcard.com/report/github.com/gioui/gio
- home page: https://gioui.org/

- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request. -- none found. https://gocover.io/ fails go getting it.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
Review:
- golint https://goreportcard.com/report/github.com/gioui/gio#golint
- Cover system link and >= 80%

**Comment by tehsphinx** [comment]
I'm not sure what that tells me. That the library does not meet the requirements?

**Comment by reindert-vetter** [comment]
@tehsphinx It is unclear in the readme how the application was tested. Where can I find the test coverage? _(I am not a maintainer of awesome)_

**Comment by tehsphinx** [comment]
To get a `coverage` link is very hard if not impossible as the GUI framework has target specific dependencies that do not work on coverage sites.

About `golint`: we could work on that.

**Comment by whereswaldon** [comment]
The test coverage isn't available through a service like gocover.io because Gio has CGO dependencies on Linux. On a Linux system, one can install those CGO deps and then `go test -cover ./...` like normal. Is there an alternative or exception process on that requirement?

**Comment by avelino** [comment]
about the cgo dependency I understand, but it doesn't make room to have low volume in golint, we are waiting for package updates

**Comment by x1unix** [comment]
@ tehsphinx I can suggest to generate coverage report manually (using GitHub Actions) and report it to Coveralls

Here is how I did it in my project - https://github.com/x1unix/go-playground/blob/master/.github/workflows/coverage.yml

**Pull request closed without merging**
