### PR TITLE
Add nsq-event-bus

### PR DESCRIPTION
**Pull request by rafaeljesus**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo: https://github.com/rafaeljesus/nsq-event-bus
- godoc.org: https://godoc.org/github.com/rafaeljesus/nsq-event-bus
- goreportcard.com: https://goreportcard.com/report/github.com/rafaeljesus/nsq-event-bus
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/rafaeljesus/nsq-event-bus

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by kirillDanshin** [comment]
hmm, as I can see, we have a bug in our tests

**Comment by rafaeljesus** [comment]
Is there anything I can help?

**Comment by shurcooL** [comment]
We can't merge this as is, because it would break CI and we couldn't use it on all future PRs.

One thing you can do for now, is to remove the link to https://github.com/nsqio/go-nsq in your description, to get rid of the false positive. Then we can review the rest of your PR and get it merged.

Alternatively, if you're interested, try to fix the CI so that such a false positive is not recognized. However, I suspect it'll be tricky, given the current algorithm for checking for duplicate links looks everywhere in the generated HTML.

**Comment by rafaeljesus** [comment]
@shurcooL thanks for you reply and clarification. I did remove the link, can you rebuild travis please?  I'll try to fix [it](https://github.com/avelino/awesome-go/issues/1336) once I find some free time

**Comment by shurcooL** [comment]
> I did remove the link

Still seeing it [there](https://github.com/avelino/awesome-go/pull/1333/files). Did you forget to push?

**Comment by kirillDanshin** [comment]
@rafaeljesus seeing that [here](https://github.com/rafaeljesus/awesome-go/commit/fcbf94fd14e6ea1e156dba396e7fcc42e7d5fa00) too. Please check out that you pushed updates in the right branch

**Comment by rafaeljesus** [comment]
Fixed guys!

**Pull request merged**
