### PR TITLE
add Colly to Miscellaneous

### PR DESCRIPTION
**Pull request by guylyons**
Just adding in Colly 😁 Thanks!

### CODE REVIEW

**Comment by cassiobotaro** [comment]
Pls follow [contributing](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md) guide.

**Comment by guylyons** [comment]
cassio, what in the contributing guide did i not follow? thought everything checked out fine, reading from the docs.

**Comment by cassiobotaro** [comment]
@guylyons https://github.com/avelino/awesome-go/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by guylyons** [comment]
you didn't answer my question. i've read the docs and am not seeing what it is that isn't passing your contribution guidelines.

**Comment by cassiobotaro** [comment]
@guylyons pls follow this [template](https://github.com/avelino/awesome-go/blob/master/.github/PULL_REQUEST_TEMPLATE.md) and solve conflicts.

**Pull request closed without merging**
