### PR TITLE
Add Zax logger

### PR DESCRIPTION
**Pull request by yuseferi**
Zax is a  simple wrapper around the Zap which helps zap to work context and you do not need to pass logger to any function, global parameters like `trace_id` etc could be log easier without repeating them in every downstream method.

> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**
[github.com/yuseferi/zax](github.com/yuseferi/zax)

more details what it's doing : https://medium.com/@yuseferi/zax-a-golang-package-to-add-context-on-top-of-zap-logger-e33ac3bdcddc

- repo link (github.com, gitlab.com, etc): [github.com/yuseferi/zax](github.com/yuseferi/zax)
- pkg.go.dev:  [https://pkg.go.dev/github.com/yuseferi/zax](https://pkg.go.dev/github.com/yuseferi/zax)
- goreportcard.com:[https://goreportcard.com/report/github.com/yuseferi/zax]( https://goreportcard.com/report/github.com/yuseferi/zax)
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): [https://app.codecov.io/github/yuseferi/zax](https://app.codecov.io/github/yuseferi/zax)

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below that apply before you submit PR.**
_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines for details._

- [x] The package has been added to the list in alphabetical order.
- [x] The package has an appropriate description with correct grammar.
- [x] As far as I know, the package has not been listed here before.
- [x] The repo documentation has a pkg.go.dev link.
- [x] The repo documentation has a coverage service link.
- [x] The repo documentation has a goreportcard link.
- [x] The repo has a version-numbered release and a go.mod file.
- [x] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines), [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers) and [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).
- [x] The repo has a continuous integration process that automatically runs tests that must pass before new pull requests are merged.
- [x] The authors of the project do not commit directly to the repo, but rather use pull requests that run the continuous-integration process.

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by yuseferi** [comment]
Hey @avelino could you please take care of this?

**Review by avelino — CHANGES_REQUESTED** [review]
Need links, pls read pull request template body

To learn more read the contribution guide
https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md

**Comment by yuseferi** [comment]
> Need links, pls read pull request template body
> 
> To learn more read the contribution guide https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md

Hey @avelino ,
Thank you for checking and sorry I missed that part. 
I updated it  and all the requested links has been provided. 

Cheers,

**Review by avelino — APPROVED** [review]
LGTM

**Pull request merged**
