### PR TITLE
Add link to hare under Databases.

### PR DESCRIPTION
**Pull request by jameycribbs**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/jameycribbs/hare
- pkg.go.dev: https://pkg.go.dev/github.com/jameycribbs/hare
- goreportcard.com: https://goreportcard.com/report/github.com/jameycribbs/hare
- coverage service link: https://gocover.io/github.com/jameycribbs/hare

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
check gocyclo https://goreportcard.com/report/github.com/jameycribbs/hare#gocyclo

**Comment by jameycribbs** [comment]
> check gocyclo https://goreportcard.com/report/github.com/jameycribbs/hare#gocyclo

gocyclo is complaining, because I make extensive use of table-driven tests in my test files, which means I have lots of anonymous functions in an array in the main test function for each test file.  I don't see this as a problem.  I added a "gocyclo:ignore" directive to each of the main test functions and I verified that this makes gocyclo ignore those test functions when I run gocyclo locally.  But, apparently, when goreportcard runs gocyclo, it does not seem to see those directives I added, because it still is reporting those test functions.

Is this going to be a problem for Hare getting listed on this website?  I really like the way I have structured my tests and really don't want to have to change my testing architecture.

Thanks.

**Comment by jameycribbs** [comment]
Ok, I have made the necessary changes to get this passing 100% at GoReportCard.

**Pull request merged**
