### PR TITLE
Add Coding Mystery to Websites

### PR DESCRIPTION
**Pull request by Tulstrup**

### CODE REVIEW

**Review by phanirithvij — CHANGES_REQUESTED** [review]
Alphabetical order, codingame should come later (according to the failed tests)

**Comment by Tulstrup** [comment]
> Alphabetical order, codingame should come later (according to the failed tests)

Done :)

**Comment by mockuser404** [comment]
My [implementation](https://github.com/mockuser404/codingmystery_in_go) in Go.

**Comment by phanirithvij** [comment]
@mockuser404 there is a community on Reddit (check the site footer). I think it is more productive to post/discuss there.
But it's great that you've spent time and implemented it in Go 🙂.

**Pull request merged**
