### PR TITLE
Add liftbridge to the Distributed Systems section

### PR DESCRIPTION
**Pull request by PunKeel**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/liftbridge-io/liftbridge
- godoc.org: https://godoc.org/github.com/liftbridge-io/liftbridge
- goreportcard.com: https://goreportcard.com/report/github.com/liftbridge-io/liftbridge
- coverage service link: https://coveralls.io/github/liftbridge-io/liftbridge

Very good coverage

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: False
- goreportcard.com: False
- coverage: True

**Comment by panjf2000** [comment]
There are still many issues in https://goreportcard.com/report/github.com/liftbridge-io/liftbridge, please fix those first.

**Comment by PunKeel** [comment]
This is not my repository - so cc @tylertreat

**Comment by tylertreat** [comment]
Thanks, I will address the Report Card issues and post back here.

**Comment by tylertreat** [comment]
@panjf2000 @PunKeel I have addressed the issues: https://goreportcard.com/report/github.com/liftbridge-io/liftbridge

**Comment by panjf2000** [comment]
@tylertreat 
I'm unable to see any code coverage on https://circleci.com/gh/liftbridge-io/liftbridge, it seems to be a CI platform which doesn't provide a feature of code coverage, either that or I'm browsing it in a wrong way, so could you please explain a little bit?

**Comment by tylertreat** [comment]
@panjf2000 Wrong code coverage link was provided. Here is the correct one: https://codecov.io/gh/liftbridge-io/liftbridge

**Comment by panjf2000** [comment]
@tylertreat 
Please increase the code coverage to >=80%

**Comment by tylertreat** [comment]
@panjf2000 Coverage is now 82%. Also switched to Coveralls: https://coveralls.io/github/liftbridge-io/liftbridge

**Pull request merged**
