### PR TITLE
Add go-project-layout

### PR DESCRIPTION
**Pull request by wangyoucao577**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/wangyoucao577/go-project-layout
- pkg.go.dev: https://pkg.go.dev/github.com/wangyoucao577/go-project-layout
- goreportcard.com: https://goreportcard.com/report/github.com/wangyoucao577/go-project-layout
- coverage service link: https://app.codecov.io/gh/wangyoucao577/go-project-layout

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by wangyoucao577** [comment]
@avelino  is there any concern to merge this PR?

**Comment by avelino** [comment]
Projects of this kind are controversial, I recommend reading this issue thread to give you context.
https://github.com/golang-standards/project-layout/issues/117

personally (avelino not awesome-go) recommend changing the name of your repository

**Comment by wangyoucao577** [comment]
@avelino  Actually I'm one of the people who stronglly disagree with the [golang-standards/project-layout](github.com/golang-standards/project-layout) project. But the problem is the `golang-standards` part since it's NOT a real standard. It brings a lot of confusion for newers. On the other hand, I think it's totally ok to use `go-project-layout` as a project name, it's just a personal workspace.

**Pull request merged**
