### PR TITLE
Adding ghostmates to Third Party APIs

### PR DESCRIPTION
**Pull request by jasonmoo**

### CODE REVIEW

**Comment by jasonmoo** [comment]
Please be more descript about your documentation requirements.  I have looked at other Third-party libs on this list that have similar documentation and seem to have passed.

**Comment by jasonmoo** [comment]
@mholt  you have rejected every single one of my pull requests.

**Comment by drewwells** [comment]
There is no documentation on any of the methods which is far more important than documenting the structs. https://github.com/jasonmoo/ghostmates/blob/master/webhook.go#L90

**Comment by mholt** [comment]
@jasonmoo Come again? Your pull requests are still here. I haven't closed/rejected them. Just tagged as needing some work before being added to the list.

Perhaps we could make the wording of the guidelines clearer. Tests are *preferred* where possible because sometimes tests are very painful/difficult to do properly depending on the code being tested. We've rejected/delayed PRs before (example, #412) because of lack of tests.

**Comment by shurcooL** [comment]
In case it's helpful to make your Go package better, here is output of [`golint`](https://github.com/golang/lint), which outputs style suggestions, on this package:

```
client.go:11:2: exported type Client should have comment or be unexported
client.go:16:2: exported type DeliverySpot should have comment or be unexported
client.go:24:2: exported type DeliveryQuote should have comment or be unexported
client.go:35:2: exported type Location should have comment or be unexported
client.go:40:2: exported type Courier should have comment or be unexported
client.go:48:2: exported type Address should have comment or be unexported
client.go:57:2: exported type Spot should have comment or be unexported
client.go:66:2: exported type Manifest should have comment or be unexported
client.go:71:2: exported type RelatedDelivery should have comment or be unexported
client.go:76:2: exported type Delivery should have comment or be unexported
client.go:101:2: exported type Deliveries should have comment or be unexported
client.go:111:2: exported const APIVersion should have comment (or a comment on this block) or be unexported
client.go:141:1: exported function NewManifest should have comment or be unexported
client.go:148:1: comment on exported function NewDeliverySpot should be of the form "NewDeliverySpot ..."
client.go:157:1: exported function NewClient should have comment or be unexported
client.go:176:1: exported method Client.GetQuote should have comment or be unexported
client.go:210:1: exported method Client.CreateDelivery should have comment or be unexported
client.go:259:1: exported method Client.GetOngoingDeliveries should have comment or be unexported
client.go:263:1: exported method Client.GetDeliveries should have comment or be unexported
client.go:313:1: exported method Client.GetDelivery should have comment or be unexported
client.go:337:1: exported method Client.CancelDelivery should have comment or be unexported
client.go:361:1: exported method Client.ReturnDelivery should have comment or be unexported
client.go:12:3: don't use underscores in Go names; struct field customer_id should be customerID
client.go:157:16: don't use underscores in Go names; func parameter customer_id should be customerID
client.go:157:29: don't use underscores in Go names; func parameter api_key should be apiKey
client.go:176:27: don't use underscores in Go names; method parameter pickup_address should be pickupAddress
client.go:176:43: don't use underscores in Go names; method parameter dropoff_address should be dropoffAddress
client.go:313:30: don't use underscores in Go names; method parameter delivery_id should be deliveryID
client.go:337:33: don't use underscores in Go names; method parameter delivery_id should be deliveryID
client.go:361:33: don't use underscores in Go names; method parameter delivery_id should be deliveryID
client_test.go:45:2: var TestCustomerId should be TestCustomerID
errors.go:11:2: exported type Error should have comment or be unexported
errors.go:23:2: exported const ErrorCodeInvalidParams should have comment (or a comment on this block) or be unexported
errors.go:35:1: exported function NewError should have comment or be unexported
example/main.go:19:7: exported const PostmatesClientTimeout should have comment or be unexported
example/main.go:26:2: exported var PostmatesAPIKey should have comment or be unexported
example/main.go:96:6: exported type GoogleNearby should have comment or be unexported
example/main.go:56:4: don't use underscores in Go names; var customer_id should be customerID
example/main.go:57:4: don't use underscores in Go names; var pickup_address should be pickupAddress
example/main.go:103:30: don't use underscores in Go names; func parameter pickup_address should be pickupAddress
example/main.go:120:26: error strings should not be capitalized
example/main.go:130:26: error strings should not be capitalized
webhook.go:14:2: exported type Webhook should have comment or be unexported
webhook.go:19:2: exported type Events should have comment or be unexported
webhook.go:26:2: comment on exported type DeliveryStatusEvent should be of the form "DeliveryStatusEvent ..." (with optional leading article)
webhook.go:38:2: comment on exported type DeliveryDeadlineEvent should be of the form "DeliveryDeadlineEvent ..." (with optional leading article)
webhook.go:50:2: comment on exported type CourierUpdateEvent should be of the form "CourierUpdateEvent ..." (with optional leading article)
webhook.go:62:2: comment on exported type DeliveryReturnEvent should be of the form "DeliveryReturnEvent ..." (with optional leading article)
webhook.go:76:2: exported const DeliveryStatusEventKind should have comment (or a comment on this block) or be unexported
webhook.go:85:2: exported var DefaultBufferLength should have comment or be unexported
webhook.go:90:1: exported function NewWebhook should have comment or be unexported
```

**Comment by matrixik** [comment]
Hello, thank you for contribution.
Package still have low `golint` score and some `go vet` errors:
https://goreportcard.com/report/github.com/jasonmoo/ghostmates

**Comment by cassiobotaro** [comment]
@jasonmoo  For  quality standards please follow:  https://github.com/avelino/awesome-go/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Pull request closed without merging**
