### PR TITLE
Add PipeCD

### PR DESCRIPTION
**Pull request by khanhtc1202**
**Please provide package links to:**

- repo link (github.com, gitlab.com, etc): https://github.com/pipe-cd/pipecd
- pkg.go.dev: https://pkg.go.dev/github.com/pipe-cd/pipecd
- goreportcard.com: https://goreportcard.com/report/github.com/pipe-cd/pipecd
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/pipe-cd/pipecd

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below that apply before you submit PR.**
_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines for details._

- [x] The package has been added to the list in alphabetical order.
- [x] The package has an appropriate description with correct grammar.
- [x] As far as I know, the package has not been listed here before.
- [x] The repo documentation has a pkg.go.dev link.
- [x] The repo documentation has a coverage service link.
- [x] The repo documentation has a goreportcard link.
- [x] The repo has a version-numbered release and a go.mod file.
- [x] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines), [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers) and [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).
- [x] The repo has a continuous integration process that automatically runs tests that must pass before new pull requests are merged.
- [x] The authors of the project do not commit directly to the repo, but rather use pull requests that run the continuous-integration process.

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by khanhtc1202** [comment]
Hi @phanirithvij , any consideration or WIP review on this? We want to clear any concerning points so it would be great if you guys could share 🙏

**Review by phanirithvij — CHANGES_REQUESTED** [review]
- awesome-go guidelines, require 80% code coverage unless the tool is very widely used and/or it is impossible to test the tool. Your project is at ~30%. Is it possible to improve it further?

- Fix all issues shown by https://goreportcard.com/report/github.com/pipe-cd/pipecd as much as possible.

**Comment by khanhtc1202** [comment]
@phanirithvij Thanks for your response.
> awesome-go guidelines, require 80% code coverage unless the tool is very widely used and/or it is impossible to test the tool. Your project is at ~30%. Is it possible to improve it further?

The tool uses a lot of cloud provider API, which makes it really difficult to test up to 80%, we're working on test improvement, but due to its natural above, it's hard to make that number. Besides, I think test coverage 80% should only be for libraries, not for tools or applications, WDYT?

> Fix all issues shown by https://goreportcard.com/report/github.com/pipe-cd/pipecd as much as possible.

For sure, we will work on that. But the report overall A+ already, so is that really required to pass the review?

**Comment by phanirithvij** [comment]
Sorry I missed this email

**Pull request merged**
