### PR TITLE
added gots

### PR DESCRIPTION
**Pull request by guygrigsby**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- godoc.org: https://godoc.org/github.com/Comcast/gots
- goreportcard.com: https://goreportcard.com/report/github.com/Comcast/gots
- gocover.io or coveralls: http://gocover.io/_badge/github.com/comcast/gots

Note, that new categories can be added only when there are 3 packages or more.

Make sure that you've checked the boxes below before you submit PR:
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added gocover.io or coveralls link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Not exist gocover.io

**Comment by kirillDanshin** [comment]
@avelino as I can see gocover.io is now down.
@guygrigsby can you add link to coveralls?

**Comment by guygrigsby** [comment]
@kirillDanshin Gocover is back up. I am including multiple links for all packages because I can't figure out how to make gocover.io work for all packages.
- http://gocover.io/github.com/comcast/gots/packet
- http://gocover.io/github.com/comcast/gots/ebp
- http://gocover.io/github.com/comcast/gots/adaptationfield
- http://gocover.io/github.com/comcast/gots/pes
- http://gocover.io/github.com/comcast/gots/psi
- http://gocover.io/github.com/comcast/gots/scte35

**Comment by kirillDanshin** [comment]
@guygrigsby
the packages has some issues:
`gots/packet` - only 40% coverage
`gots/adaptationfield` - isn't go-get-able at all
`gots/scte35` - only 61% coverage
I can't merge it yet.

**Comment by guygrigsby** [comment]
What are the exact requirements for coverage?

**Comment by avelino** [comment]
new rules 8 day with label `pending-submitter-response`: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers

**Pull request closed without merging**
