### PR TITLE
add Go supplementary cryptography libraries

### PR DESCRIPTION
**Pull request by xigang**
- [crypto](https://github.com/xigang/crypto) -Go supplementary cryptography libraries
- [godoc.org](https://godoc.org/github.com/xigang/crypto) 
- [goreportcard.com](https://goreportcard.com/report/github.com/xigang/crypto) 
- [gocover.io](https://gocover.io/github.com/xigang/crypto) 

Make sure that you've checked the boxes below before you submit PR:
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link
- [x] I have added gocover.io link
- [x] I have added goreportcard link
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard)

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@xigang please add more tests. thanks.

**Comment by xigang** [comment]
@kirillDanshin  hi, has been added to the test file in each folder :)

**Comment by kirillDanshin** [comment]
@xigang hi. `utils.go` still have low coverage. some of subpackages needs more tests too. please, fix. thanks!

**Comment by xigang** [comment]
@kirillDanshin hi,some of subpackages add some tests.

**Comment by cassiobotaro** [comment]
More than 8 days without answers. Feel free to submit this again

**Pull request closed without merging**
