### PR TITLE
add box-cli-maker

### PR DESCRIPTION
**Pull request by Delta456**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/Delta456/box-cli-maker
- pkg.go.dev: https://pkg.go.dev/github.com/Delta456/box-cli-maker/v2
- goreportcard.com: https://goreportcard.com/report/github.com/Delta456/box-cli-maker
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://golangci.com/r/github.com/Delta456/box-cli-maker

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
review:
- https://goreportcard.com/report/github.com/Delta456/box-cli-maker#golint
- I have not located the percentage of coverage

**Comment by Delta456** [comment]
> review:
> 
>     * https://goreportcard.com/report/github.com/Delta456/box-cli-maker#golint

It was done last time, will do it again.

>     * I have not located the percentage of coverage

Seems like `golangci` is discontinued 😦

**Comment by Delta456** [comment]
> `* I have not located the percentage of coverage`

https://gocover.io/github.com/Delta456/box-cli-maker

I do not know why it is 58.7% as it uses separate code for windows and unix systems.

**Comment by Delta456** [comment]
I am working on this PR.

**Comment by Delta456** [comment]
[Go Report Card](https://goreportcard.com/report/github.com/Delta456/box-cli-maker) has Go Lint 100% and [Go Cover.io](https://gocover.io/github.com/Delta456/box-cli-maker) has over 80% coverage.

**Pull request merged**
