### PR TITLE
Added goent

### PR DESCRIPTION
**Pull request by kzahedi**
GO Implementation of Entropy Measures

Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/kzahedi/goent
- godoc.org: https://godoc.org/github.com/kzahedi/goent
- goreportcard.com: https://goreportcard.com/report/github.com/kzahedi/goent
- coverage service link [coveralls](https://coveralls.io/repos/github/kzahedi/goent/badge.svg?branch=master)

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x ] I have added my package in alphabetical order.
- [ x] I have an appropriate description with correct grammar.
- [x ] I know that this package was not listed before.
- [x ] I have added godoc link to the repo and to my pull request.
- [x ] I have added coverage service link to the repo and to my pull request.
- [x ] I have added goreportcard link to the repo and to my pull request.
- [x ] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by kzahedi** [comment]
GO Implementation of Entropy Measures

Please check if what you want to add to awesome-go list meets quality standards before sending pull request. Thanks!

Please provide package links to:

github.com repo: https://github.com/kzahedi/goent
godoc.org: https://godoc.org/github.com/kzahedi/goent
goreportcard.com: https://goreportcard.com/report/github.com/kzahedi/goent
coverage service link coveralls
Very good coverage

Note: that new categories can be added only when there are 3 packages or more.

Make sure that you've checked the boxes below before you submit PR:

[x ] I have added my package in alphabetical order.
[ x] I have an appropriate description with correct grammar.
[x ] I know that this package was not listed before.
[x ] I have added godoc link to the repo and to my pull request.
[x ] I have added coverage service link to the repo and to my pull request.
[x ] I have added goreportcard link to the repo and to my pull request.
[x ] I have read Contribution guidelines, maintainers note and Quality standard.
Thanks for your PR, you're awesome! 👍

**Comment by kzahedi** [comment]
GO Implementation of Entropy Measures

Please check if what you want to add to awesome-go list meets quality standards before sending pull request. Thanks!

Please provide package links to:

github.com repo: https://github.com/kzahedi/goent
godoc.org: https://godoc.org/github.com/kzahedi/goent
goreportcard.com: https://goreportcard.com/report/github.com/kzahedi/goent
coverage service link https://coveralls.io/github/kzahedi/goent?branch=master
Very good coverage

Note: that new categories can be added only when there are 3 packages or more.

Make sure that you've checked the boxes below before you submit PR:

[x ] I have added my package in alphabetical order.
[ x] I have an appropriate description with correct grammar.
[x ] I know that this package was not listed before.
[x ] I have added godoc link to the repo and to my pull request.
[x ] I have added coverage service link to the repo and to my pull request.
[x ] I have added goreportcard link to the repo and to my pull request.
[x ] I have read Contribution guidelines, maintainers note and Quality standard.
Thanks for your PR, you're awesome! 👍

**Comment by kzahedi** [comment]
I don't see which link is missing. And I have read the Contribution guidelines. Could you be a bit more specific?

**Comment by kzahedi** [comment]
fixed (hopefully)

**Comment by appleboy** [comment]
@kzahedi Need one or more collaborator to review that.

**Pull request merged**
