### PR TITLE
Add rakyll/statik

### PR DESCRIPTION
**Pull request by ahmetalpbalkan**
- github.com repo:  http://github.com/rakyll/statik
- godoc.org: https://godoc.org/github.com/rakyll/statik
- goreportcard.com: https://goreportcard.com/report/github.com/rakyll/statik A+

**Note**: that new categories can be added only when there are 3 packages or more.

- [x] I have added my package in alphabetical order
- [ ] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [ ] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Recheck you go lint pls: https://goreportcard.com/report/github.com/rakyll/statik#golint

**Comment by ahmetalpbalkan** [comment]
I am not the owner, I will send a PR. This goreportcard is a bit weird it gives A+ to everybody: https://github.com/gojp/goreportcard/issues/173 I opened an issue.

**Comment by ahmetalpbalkan** [comment]
The golint warnings are about godoc comment formats, I just sent a PR to the repo, but I think it's harmless to merge this PR as is too.

**Comment by avelino** [comment]
thank you @ahmetalpbalkan

**Pull request merged**
