### PR TITLE
Update package description, add my Go learning resource.

### PR DESCRIPTION
**Pull request by gyuho**
Thanks!

1. I just updated my package description after refactoring.
2. And would like to add my Go learning material.

Thanks!

### CODE REVIEW

**Comment by dukex** [comment]
I suggest you create a new pull request adding your resource link.

The description update is fine, but the tests need pass

**Comment by gyuho** [comment]
Ok, I will. Thanks @dukex

**Comment by dukex** [comment]
Thank you, I'm reading your learn repo and it's amazing.

**Comment by gyuho** [comment]
Thanks @dukex.

Just fixed my PR here https://github.com/avelino/awesome-go/pull/574

:)

**Pull request closed without merging**
