### PR TITLE
adding MSpec

### PR DESCRIPTION
**Pull request by eduncan911**
Please provide package links to:
- godoc.org: https://godoc.org/github.com/eduncan911/mspec
- goreportcard.com: https://goreportcard.com/report/github.com/eduncan911/mspec
- gocover.io: https://gocover.io/github.com/eduncan911/mspec

Note, that new categories can be added only when there are 3 packages or more.

Make sure that you've checked the boxes below before you submit PR:
- [X] I have added my package in alphabetical order
- [X] I know that this package was not listed before
- [X] I have added godoc link
- [X] I have added gocover.io link
- [X] I have added goreportcard link
- [X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by eduncan911** [comment]
Will do!

**Comment by eduncan911** [comment]
Wait, Go Report card gives an A+?

All of the Linter warnings are expected: the BDD naming methodology in this package requires them so.

There is ONE `gofmt` error that is valid.  I'll fix that up, yes.

And I'll update the year-end branch.  Yep!

But isn't an GoReport A+ valid enough to be added to the list?

**Comment by cassiobotaro** [comment]
More than 8 days without fixes. Feel free to send again following the quality standards.

**Comment by eduncan911** [comment]
Well, it was a year since I submitted - and it passed the standards back then.

Travelling a lot so haven't had the time.

**Pull request closed without merging**
