### PR TITLE
add a code analyse tool: Golds

### PR DESCRIPTION
**Pull request by go101**
.

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: False
- coverage: False

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
> read our contribution guide where we talk about project code quality https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards

**Comment by go101** [comment]
> > read our contribution guide where we talk about project code quality https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards

@avelino Do you mean the `code` package should be documented? I did this in the last commit. Other packages are either internal or main packages.

**Comment by avelino** [comment]
when you opened the PR the body had template asking you to fill in some information, you deleted put a ".", I need you to fill in this information

```
**Please provide package links to:**

- github.com repo:
- pkg.go.dev:
- goreportcard.com:
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.)


Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [ ] I have added my package in alphabetical order.
- [ ] I have an appropriate description with correct grammar.
- [ ] I know that this package was not listed before.
- [ ] I have added pkg.go.dev link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request.
- [ ] I have added goreportcard link to the repo and to my pull request.
- [ ] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards).

Thanks for your PR, you're awesome! :+1:
```

**Comment by go101** [comment]
Ah, sorry not carefully reading.

Is it required to put the goreportcard.com link in the readme of the repository?

**Comment by avelino** [comment]
> Is it required to put the goreportcard.com link in the readme of the repository?

You can put in your repository (we don't ask for this in the contribution guide), I need you to write here in the pull request the information that you ask for in the pull request template.

**Comment by go101** [comment]
OK, I add the links below. It looks some scores are not high enough. So I will continue improving this project to get the needed scores.

One question: Are internal packages required to satisfy linters and minimum coverage? 

----

- github.com repo:  https://github.com/go101/golds
- pkg.go.dev: https://pkg.go.dev/go101.org/golds
- goreportcard.com: https://goreportcard.com/report/github.com/go101/golds
- coverage service link: https://gocover.io/go101.org/golds


Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards).

**Review by avelino — CHANGES_REQUESTED** [review]
review:
- golint https://goreportcard.com/report/github.com/go101/golds#golint
- coverage >= `80%`, today is `68.3%`

read all quality guide here -> https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards

**Pull request closed without merging**
