### PR TITLE
Add benchmark framework: fperf

### PR DESCRIPTION
**Pull request by shafreeck**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

Please provide package links to:
- godoc.org: https://godoc.org/github.com/shafreeck/fperf
- goreportcard.com: https://goreportcard.com/report/github.com/shafreeck/fperf
- gocover.io: https://gocover.io/github.com/shafreeck/fperf/client

Note, that new categories can be added only when there are 3 packages or more.

Make shure that you've checked the boxes below before you submit PR:
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link
- [x] I have added gocover.io link
- [x] I have added goreportcard link
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome :+1:

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@shafreeck hi. please, fix goreportcard issues, add `go test`able test files and documentation with examples. thanks.

**Comment by shafreeck** [comment]
@kirillDanshin I fixed goreportcard issues but there maybe something wrong with goreportcard.com that I can not refresh my repo. The necessary unit tests have been added too. Thanks very much for your suggestions.

**Comment by kirillDanshin** [comment]
@shafreeck are you sure that your package is `go get`able?

**Comment by shafreeck** [comment]
@kirillDanshin The problem is that `github.com/influxdb/influxdb` has been changed to `github.com/influxdata/influxdb`.  Now it is fixed. Goreportcard works well and all issues have been fixed.
Thanks !

**Comment by kirillDanshin** [comment]
@shafreeck but there are some `go vet` errors. please, fix. thanks.

**Comment by shafreeck** [comment]
@kirillDanshin One of the go vet errors has been fixed. The other one is not really a bug. `Print` is really a method that accepts an io.Writer

**Comment by kirillDanshin** [comment]
@shafreeck hm. pretty strange. ok.
but `fperf/clien` needs more tests. coverage about 26% is really low.

**Comment by shafreeck** [comment]
@kirillDanshin More tests have been added, none used code has been removed.

**Comment by kirillDanshin** [comment]
@shafreeck ok, fix your typo (two dots), add tests to `fperf` itself, `fperf/stats` and other subpackages. people will use all packages so they should be tested as well as `fperf/client`.

**Comment by cassiobotaro** [comment]
More than 8 days without answers

**Pull request closed without merging**
