### PR TITLE
Add gofight package in testing section.

### PR DESCRIPTION
**Pull request by appleboy**
Add `gofight` API handler testing tool

- Github: https://github.com/appleboy/gofight
- godoc.org: https://godoc.org/github.com/appleboy/gofight
- goreportcard.com: https://goreportcard.com/report/github.com/appleboy/gofight
- gocover.io: https://gocover.io/github.com/appleboy/gofight

Check list

- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link
- [x] I have added gocover.io link
- [x] I have added goreportcard link
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@appleboy thanks for your contribution. please, fix low golint score and add package description and link to examples to godoc (just add a comment right above `package` line). thanks!

**Comment by appleboy** [comment]
@kirillDanshin I already add package description and fix low golint score.

**Comment by appleboy** [comment]
ping @kirillDanshin

**Comment by kirillDanshin** [comment]
@appleboy pong :smile: 
merged, thanks for your contribution!

**Pull request merged**
