### PR TITLE
Add Documents category

### PR DESCRIPTION
**Pull request by matrixik**
Will fix #471 

But low golint/goreport scores for:
http://goreportcard.com/report/sajari/docconv @sajari
http://goreportcard.com/report/mikeshimura/goreport @mikeshimura
http://goreportcard.com/report/signintech/gopdf @signintech

### CODE REVIEW

**Comment by matrixik** [comment]
Ups, wrong names:
@dhowden
@oneplus1000 @miiton

**Comment by cassiobotaro** [comment]
@matrixik these libs have low golint/goreport, but maybe the category documents can be created. What you think about?

**Comment by matrixik** [comment]
@cassiobotaro I think category documents would be good addition but we should probably find at last 3 good quality libs for it...

**Comment by matrixik** [comment]
Closing, thx.

**Pull request closed without merging**
