### PR TITLE
Add Concourse

### PR DESCRIPTION
**Pull request by kedare**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/concourse/concourse
- pkg.go.dev: https://pkg.go.dev/mod/github.com/concourse/concourse
- goreportcard.com: https://goreportcard.com/report/github.com/concourse/concourse
- coverage service link: Not sure how to do this one as I don't own the project 

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: False

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by appleboy — CHANGES_REQUESTED** [review]
https://goreportcard.com/report/github.com/concourse/concourse

**Comment by kedare** [comment]
Is there any quality issue you see on the code ? A+ grade looks good to me :)

**Comment by appleboy** [comment]
Maybe send the PR to fix the following issue:

https://goreportcard.com/report/github.com/concourse/concourse#gofmt
https://goreportcard.com/report/github.com/concourse/concourse#ineffassign

**Comment by kedare** [comment]
Is the quality restriction that high to add a package to this project ?
The code quality in Concourse is excellent and it has the best grade possible on goreportcard
There are others projects in this list that have much lower % (For example https://goreportcard.com/report/github.com/pressly/sup)

**Comment by avelino** [comment]
> Is the quality restriction that high to add a package to this project ?
> The code quality in Concourse is excellent and it has the best grade possible on goreportcard
> There are others projects in this list that have much lower % (For example https://goreportcard.com/report/github.com/pressly/sup)

we charge a minimum quality to enter the list, you can read more here https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards

We would be grateful if you could review the projects listed that do not meet the need, unfortunately we had no minimum quality specification in the past (so many projects came in).

**Pull request closed without merging**
