### PR TITLE
Add wI2L/jettison

### PR DESCRIPTION
**Pull request by wI2L**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/wI2L/jettison
- godoc.org: https://godoc.org/github.com/wI2L/jettison
- goreportcard.com: https://goreportcard.com/report/wI2L/jettison
- coverage service link: https://codecov.io/gh/wI2L/jettison

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

**Disclaimer**: I am the author and maintainer of this package. Please also note that the coverage percentage reported by codecov isn't the same as the Go cover tool, which report a higher one.
```sh
PASS
coverage: 91.9% of statements
ok  	github.com/wI2L/jettison	1.152s
```

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

**Comment by panjf2000** [comment]
@wI2L 
Please fix the [golint issues](https://goreportcard.com/report/github.com/wI2L/jettison#golint) first.

**Comment by wI2L** [comment]
@panjf2000 If that's a blocker per your guidelines I am willing to fix it in *master* but I won't push a new release for just that. It is good for you ?

**Comment by panjf2000** [comment]
@wI2L 
You don't have to make a new release for that, just fix it in your master branch.
BTY, I think you'd better run the command: `golint ./...` under your package root path every time before you push a commit to the remote repo, not just for the quality-standard of awesome-go but your good code-style.😀

**Comment by wI2L** [comment]
@panjf2000 This is the case, I left this comment empty willingly until I could find a clear and concise comment about its usage regarding the new `errors.Unwrap` method introduced in 1.13 and then pushed my new version before I fixed it. One comment isn't a big deal ;)

**Comment by panjf2000** [comment]
Sorry, we have rules here and even if you want to make an exception, you have to convince @avelino first.

**Comment by wI2L** [comment]
@panjf2000 I think you misunderstood me, I wasn't asking for an exception about the missing comment, I was merely explaining to you why the comment wasn't there in the first place ;), after your suggestion of running `golint ./...`.

**Comment by panjf2000** [comment]
@wI2L 
My bad😅, then you could just ignore my previous comment and notify me whenever you fix the golint issues.

**Comment by wI2L** [comment]
@panjf2000 Fixed in https://github.com/wI2L/jettison/commit/5fef12c59c168f2d8523cd77d0db56a985bc30fb

**Comment by wI2L** [comment]
@avelino I understand the strong code quality requirements you enforce for the packages being listed in awesome-go, but in this case, I have the feeling that it isn't justified, and that you may not have read the code, but instead, just made a comment purely out of what the goreportcard shows?

I think that the `gocyclo` linter isn't always fair or justified, and in the case of the functions concerned here, it is true. 5 out of the 7 funcs have a score above the recommended limit of 15 by a margin of 2 to 5, which I consider pretty reasonnable.

`isValidNumber`, `writeEscapedBytes`, `isEmpty`, for example, would not gain anything if they were split in smaller funcs.

`newSliceInstr` and `newArrayInstr` both return a closure. Again, splitting those would create another func with a huge prototype (for all the variables required in the closure), wich isn't something I am enclined to do. I personally don't think it would be more readable, or "cleaner".

Jettison passes alot of linters from `golanci-lint` and `revive`, and I think the current codebase is pretty healthy as it stands.

**Pull request merged**
