### PR TITLE
Add sidecar - a service discovery tool

### PR DESCRIPTION
**Pull request by mihaitodor**
- github.com repo: https://github.com/Nitro/sidecar
- godoc.org: https://godoc.org/github.com/Nitro/sidecar
- goreportcard.com: https://goreportcard.com/report/github.com/Nitro/sidecar
- coverage service link (gocover, coveralls etc.): http://gocover.io/github.com/Nitro/sidecar

- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
@mihaitodor fork? @newrelic keeps the main project

**Comment by mihaitodor** [comment]
@avelino The original author decided to continue development under the Nitro fork, since he is working here now (cc @relistan)

**Comment by relistan** [comment]
The main development is on the Nitro fork. The README on newrelic/sidecar will be updated shortly.

**Comment by mihaitodor** [comment]
@avelino Do you need more information from our side?

**Pull request closed without merging**
