### PR TITLE
Add "yakvs"

### PR DESCRIPTION
**Pull request by sci4me**

### CODE REVIEW

**Comment by shurcooL** [comment]
Given that it's a key value store library, I think it'd helpful if it had docs. Right now it appears to have none. https://godoc.org/github.com/sci4me/yakvs/yakvs

**Comment by shurcooL** [comment]
Oh, is this meant to be a command rather than a library? If so, my comment above may be less applicable.

**Comment by sci4me** [comment]
Yes it is not meant to be a library at all, it is just a server. The protocol describes the TCP "api".

**Comment by sci4me** [comment]
I have added docs, but please, if you think they need improvement, let me know... I am not a skilled documentation writer.

**Comment by shurcooL** [comment]
Looks great, thanks for doing that!

LGTM.

**Pull request merged**
