### PR TITLE
Add gomuti/gomega to Testing category; correct the capitalization of RSpec.

### PR DESCRIPTION
**Pull request by xeger**
github.com repo:
https://github.com/xeger/gomuti
https://github.com/xeger/mongoose

godoc.org:
https://godoc.org/github.com/xeger/gomuti
https://godoc.org/github.com/xeger/mongoose

goreportcard.com:
https://goreportcard.com/report/github.com/xeger/gomuti
https://goreportcard.com/report/github.com/xeger/mongoose

coverage service link (gocover, coveralls etc.):
n/a (in progress)
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [ ] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read Contribution guidelines and Quality standard.

### CODE REVIEW

**Comment by avelino** [comment]
Sorry, we need every link to accept

**Comment by xeger** [comment]
The two items that I added, both contain a link that is formatted according to the [contributor guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md) ... unless I'm missing some detail?

**Comment by kirillDanshin** [comment]
@xeger yep, you've missed our PR template.

**Comment by xeger** [comment]
Ah; thank you. I see that I'm missing links to a public coverage report; will add this to both of my repos and then comment again on this PR. (Added the rest of the PR template, with links, etc.)

P.S. I couldn't find the PR template anywhere, not in `CONTRIBUTING.md` nor elsewhere. I copied the contents from someone else's PR; for future reference, where is the pristine copy?

**Comment by kirillDanshin** [comment]
@xeger PR template in github is always under .github directory in PULL_REQUEST_TEMPLATE.md file. Check out our template: [.github/PULL_REQUEST_TEMPLATE.md](https://github.com/avelino/awesome-go/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

**Comment by kirillDanshin** [comment]
Also I've just added the link to CONTRIBUTING.md

**Comment by avelino** [comment]
new rules 8 days with label `pending-submitter-response`: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers

**Pull request closed without merging**
