### PR TITLE
Add trandoshan-io/crawler project

### PR DESCRIPTION
**Pull request by creekorful**
**Please provide package links to:**

- github.com repo: https://github.com/trandoshan-io/crawler
- godoc.org: no documentation is available
- goreportcard.com: https://goreportcard.com/report/github.com/trandoshan-io/crawler
- coverage service link: I don't think it would be relevant, but I can add if needed.

**Make sure that you've checked the boxes below before you submit PR:**
- [X] I have added my package in alphabetical order.
- [X] I have an appropriate description with correct grammar.
- [X] I know that this package was not listed before.
- [ ] I have added godoc link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request.
- [X] I have added goreportcard link to the repo and to my pull request.
- [X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: False
- goreportcard.com: True
- coverage: False

**Comment by panjf2000** [comment]
> godoc.org: no documentation is available

Why is that?

**Comment by creekorful** [comment]
> > godoc.org: no documentation is available
> 
> Why is that?

Because the project is not a library

**Comment by panjf2000** [comment]
At least you should add a section in README to guide users how to use your program.

**Comment by avelino** [comment]
_sorry for closing the PR, we were waiting for your PRs_

**Pull request closed without merging**
