### PR TITLE
Add CosmosSDK

### PR DESCRIPTION
**Pull request by jaekwon**
- github.com repo: github.com/cosmos/cosmos-sdk
- godoc.org: https://godoc.org/github.com/cosmos/cosmos-sdk 
- goreportcard.com: https://goreportcard.com/report/github.com/cosmos/cosmos-sdk
- coverage service link ([codecov](https://codecov.io/gh/cosmos/cosmos-sdk))

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by ceriath** [comment]
restarted travis build, a go get went wrong with a 502

**Comment by jaekwon** [comment]
We will work toward test coverage > 70%, but the reportcard says A+.

**Comment by ceriath** [comment]
yes, reportcard says A+ but still has a lot of issues that could be easily fixed, so please do it

**Comment by avelino** [comment]
> The maintainers will review your PR and notify you and tag it in case any information is still missing. They will wait 30 days for your interaction, after that the PR will be closed.
https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers

**Pull request closed without merging**
