### PR TITLE
HnH/di - DI container library

### PR DESCRIPTION
**Pull request by HnH**
**Package links:**

- repo link: https://github.com/HnH/di
- pkg.go.dev: https://pkg.go.dev/github.com/HnH/di
- goreportcard.com: https://goreportcard.com/report/github.com/HnH/di (A+)
- coverage: https://app.codecov.io/gh/HnH/di (100%)

**Checklist:**

- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards).

### CODE REVIEW

**Review by avelino — CHANGES_REQUESTED** [review]
check `golint` https://goreportcard.com/report/github.com/HnH/di#golint

**Comment by HnH** [comment]
Yea, I saw this. Is a non go-way receiver naming a library quality issue?

**Comment by avelino** [comment]
we use this item to measure the minimum quality for awesome-go (you can read more [here](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards)).

**Comment by HnH** [comment]
@avelino I have renamed receivers and fixed remaining golint notes in https://github.com/HnH/di/commit/60dfc3e83a2a4bfa3001f975dfe7171d22c8f007 without drawing a new release.

**Pull request merged**
