### PR TITLE
Added Træfɪk

### PR DESCRIPTION
**Pull request by emilevauge**
Added a link to Træfɪk, a reverse-proxy made for docker, mesos, consul, etcd...

### CODE REVIEW

**Comment by anonx** [comment]
@EmileVauge List items must be in alphabetical order.

**Comment by klauspost** [comment]
Link redirects to a non-resolving domain.

**Comment by EmileVauge** [comment]
Sorry for that, should be fixed.

**Comment by emilevauge** [comment]
Closing it, as it doesn't seem interesting ;)

**Pull request closed without merging**
