### PR TITLE
Add https://github.com/xeptore/flaw package

### PR DESCRIPTION
**Pull request by xeptore**
> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc): https://github.com/xeptore/flaw
- pkg.go.dev: https://pkg.go.dev/github.com/xeptore/flaw
- goreportcard.com: https://goreportcard.com/report/github.com/xeptore/flaw
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.):

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below that apply before you submit PR.**
_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines for details._

- [x] The package has been added to the list in alphabetical order.
- [x] The package has an appropriate description with correct grammar.
- [x] As far as I know, the package has not been listed here before.
- [x] The repo documentation has a pkg.go.dev link.
- [ ] The repo documentation has a coverage service link.
- [ ] The repo documentation has a goreportcard link.
- [x] The repo has a version-numbered release and a go.mod file.
- [x] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines), [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers) and [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).
- [ ] The repo has a continuous integration process that automatically runs tests that must pass before new pull requests are merged.
- [ ] Continuous integration is used to attempt to catch issues prior to releasing this package to end-users.

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by cassiobotaro** [comment]
@xeptore Why is this PR still on draft? Do you need some help?

**Comment by xeptore** [comment]
Looking for spare time to update the repo, and mark remaining check boxes, @cassiobotaro.

**Comment by phanirithvij** [comment]
Forgive me for being blunt but how come you're already at v8 when no one is using your library.

**Comment by xeptore** [comment]
> Forgive me for being blunt but how come you're already at v8 when no one is using your library.

_* no one publicly maybe?_

Also, where can I find out users of a specific package beside the "imported by" section in pkg.go.dev, @phanirithvij?

**Comment by phanirithvij** [comment]
If no one publicly is using it then I suggest submitting the project again later when there are some. If it is *only* privately used does it belong in a public awesome-go list?

I looked at the imported by field like you said. I don't know of any other places.
And I looked the near-zero content in the readme.
And the low amount of interest in the project since its initial commit 7 months ago. (In the form of open issues, prs and stars/bookmarks to your project)

If you are trying to be in the spirit of awesome I suggest again resubmitting later on when it is actually awesome and you follow the full pr template.
I see this is a draft pr but please reopen a PR only after you're done with the changes you said you'd make when you have time.

Please note that I have no intention of personally targeting you or your project but I am simply stating what I see. I apologise if I have offended you.

I will leave this open and let @cassiobotaro handle this pr merging but I am against it in this state.

As I said multiple times I strongly suggest resubmitting after polishing it a lot further.

**Comment by xeptore** [comment]
> If you are trying to be in the spirit of awesome I suggest again resubmitting later on when it is actually awesome and you follow the full pr template.

OK, I got the point. Closing.

**Pull request closed without merging**
