### PR TITLE
add cmp - Provides comparison for different Go types and a Comparer i…

### PR DESCRIPTION
**Pull request by mickep76**
add cmp - Provides comparison for different Go types and a Comparer interface.

[GoDoc](https://godoc.org/github.com/mickep76/cmp)
[codecov](https://codecov.io/gh/mickep76/cmp)
[Build Status](https://travis-ci.org/mickep76/cmp)
[Go Report Card](https://goreportcard.com/report/github.com/mickep76/cmp)
[License](https://github.com/mickep76/mlfmt/blob/master/LICENSE)

### CODE REVIEW

**Comment by mickep76** [comment]
Go lint is fixable but they are from the example not the actual code, go cyclo not fixable since the function needs to be somewhat larger then what is normal.

**Comment by mickep76** [comment]
Fixed the lint errors in the example.

**Comment by mickep76** [comment]
Thought a little about, I could reduce the switch statement to using a Map with individual funcs for each comparison like:

```
func EqInt8(a, b interface{}) bool {
        return a.(int8) == b.(int8)
}

var EqMap map[reflect.Type]func(a, b interface{}) bool {
        reflect.Int8: EqInt8,
}

func Eq(a, b interface{}) (bool, error) {
        f, ok := EqMap[t] ...
}
```

Not sure that's an improvement but it would be one way of doing it.

**Comment by avelino** [comment]
`gocyclo 50%`

**Pull request closed without merging**
