### PR TITLE
Add Dasel.

### PR DESCRIPTION
**Pull request by TomWright**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/tomwright/dasel
- pkg.go.dev: https://pkg.go.dev/github.com/tomwright/dasel
- goreportcard.com: https://goreportcard.com/report/github.com/TomWright/dasel
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/TomWright/dasel

All important querying/update functionality is covered. Cobra commands have not got tests yet but have been tested manually by myself. I will be adding tests for these in the future.

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: False

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
coverage should be >= 80% for non-data-related packages and >=90% for data related packages
read more: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards

**Comment by TomWright** [comment]
Hi @avelino , sorry about that.
Test coverage is now >90%.

**Comment by avelino** [comment]
is `75.5%` review pls
Screen Shot 2020-10-09 at 9 25 44 AM

**Comment by TomWright** [comment]
It's at 92%:
- https://snipboard.io/XLy5FB.jpg
- https://snipboard.io/M17qJz.jpg

If you looked at the badge in the readme you may have to do a hard refresh if it was cached

**Comment by TomWright** [comment]
Oh I see you were looking at line coverage

**Comment by TomWright** [comment]
Codecov had some issues when running the pipelines on their end yesterday... I just added 1 more test and the line coverage shot up almost 20%.

image

**Comment by avelino** [comment]
@TomWright thank you for your contribution to organizing the project

**Pull request merged**
