### PR TITLE
Adding tt to Science and Data Analysis

### PR DESCRIPTION
**Pull request by jasonmoo**

### CODE REVIEW

**Comment by mholt** [comment]
Is this a library or a CLI tool? Usually we put programs into a different category; most of the categories are for libraries.

**Comment by jasonmoo** [comment]
CLI tool. Wasn't clear on that.

**Comment by matrixik** [comment]
Hi @jasonmoo 
Looks like your `tt` repo is not building because of changes in dependencies:
```
go/src/github.com/jasonmoo/tt/tt.go:402: cannot use scalable.New(uint(size)) (type "github.com/zhenjl/bloom".Bloom) as type "g
ithub.com/dataence/bloom".Bloom in return argument:
        "github.com/zhenjl/bloom".Bloom does not implement "github.com/dataence/bloom".Bloom (wrong type for Add method)
                have Add([]byte) "github.com/zhenjl/bloom".Bloom
                want Add([]byte) "github.com/dataence/bloom".Bloom
```

**Comment by jasonmoo** [comment]
Thanks @matrixik.  Updated in https://github.com/jasonmoo/tt/commit/7b6d5a2730e12c42dbbf9346d819191bfdfd538f

**Comment by matrixik** [comment]
Thank you for fix (and sorry for late reply).
Unfortunately your code have too low `golint` score https://goreportcard.com/report/github.com/jasonmoo/tt and no tests.

**Comment by cassiobotaro** [comment]
@llgcode For  quality standards please follow:  https://github.com/avelino/awesome-go/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Pull request closed without merging**
