### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by fanus**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/autovelop/playthos
- godoc.org: https://godoc.org/github.com/autovelop/playthos
- goreportcard.com: https://goreportcard.com/report/github.com/autovelop/playthos
- coverage service link: https://coveralls.io/github/autovelop/playthos?branch=master

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by fanus** [comment]
Updated the repo. All errors are gone, only linting warnings remain but will systematically be corrected.

**Comment by appleboy** [comment]
https://goreportcard.com/report/github.com/autovelop/playthos#golint

**Comment by fanus** [comment]
All the report card fixes are done now. Thanks.

**Comment by fanus** [comment]
I would like to close this until a later date due to a few bugs that were reported. I want these to be resolved before making this list.

**Pull request closed without merging**
