### PR TITLE
Add rerate(redis-based ratecounter & ratelimiter) to utilities

### PR DESCRIPTION
**Pull request by abo**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

Please provide package links to:
- godoc.org: https://godoc.org/github.com/abo/rerate
- goreportcard.com: https://goreportcard.com/report/github.com/abo/rerate
- gocover.io: https://gocover.io/github.com/abo/rerate

Note, that new categories can be added only when there are 3 packages or more.

Make sure that you've checked the boxes below before you submit PR:
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link
- [x] I have added gocover.io link
- [x] I have added goreportcard link
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by abo** [comment]
Hi @kirillDanshin , is this PR have any problem need to fix?

**Comment by kirillDanshin** [comment]
@abo hi :)
yep, you forgot the links. please, add those to your PR and I'll review it. thanks :)

**Comment by abo** [comment]
@kirillDanshin links to godoc/goreportcard/gocover ? its already added, gocover's badge not work, so i replace it with coveralls.io

**Comment by kirillDanshin** [comment]
@abo I think we need to update the template. we want links right in PR message. not only in the repo.

**Comment by abo** [comment]
@kirillDanshin Added. Tks :)

**Comment by kirillDanshin** [comment]
@abo add more `go run`-able examples please. it will be pretty useful. thanks for your contribution!

**Pull request merged**
