### PR TITLE
add two/tcp library

### PR DESCRIPTION
**Pull request by two**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: [https://github.com/two/tcp](https://github.com/two/tcp)
- godoc.org: [https://godoc.org/github.com/two/tcp](https://godoc.org/github.com/two/tcp)
- goreportcard.com: [https://goreportcard.com/report/github.com/two/tcp](https://goreportcard.com/report/github.com/two/tcp)
- coverage service link : [Code Coverage](https://codecov.io/gh/two/tcp)

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by two** [comment]
tks, I have already done it.

**Comment by two** [comment]
I have already done it, please merge my PR, tks~

**Comment by avelino** [comment]
> I have already done it, please merge my PR, tks~

Read contribute guide pls:
> Tests, where practical. If the library/program is testable, then coverage should be >= 80% for non-data-related packages and >=90% for data related packages. Notice: the tests will be reviewed too. We will check your coverage manually if your package's coverage is just a benchmark results.

**Comment by two** [comment]
hi, my coverage now is 87%, tks~

**Comment by appleboy** [comment]
wait @cassiobotaro approval

**Pull request closed without merging**
