### PR TITLE
add go-module to project layout section

### PR DESCRIPTION
**Pull request by kamilsk**
> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc): https://github.com/octomation/go-module
- pkg.go.dev: https://pkg.go.dev/go.octolab.org/template/module, useless
- goreportcard.com: https://goreportcard.com/report/go.octolab.org/template/module, useless
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://codecov.io/gh/octomation/go-module (useless)

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below that apply before you submit PR.**
_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines for details._

- [x] The package has been added to the list in alphabetical order.
- [x] The package has an appropriate description with correct grammar.
- [x] As far as I know, the package has not been listed here before.
- [x] The repo documentation has a pkg.go.dev link.
- [x] The repo documentation has a coverage service link.
- [x] The repo documentation has a goreportcard link.
- [x] The repo has a version-numbered release and a go.mod file.
- [x] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines), [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers) and [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).
- [x] The repo has a continuous integration process that automatically runs tests that must pass before new pull requests are merged.
- [x] The authors of the project do not commit directly to the repo, but rather use pull requests that run the continuous-integration process.

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by kamilsk** [comment]
I could provide links to pkg.go.dev and goreportcard but they are useless because I suggest a project template to quickly start new go modules without any boring routine configuring ci/cd, etc. I hope it will be useful for community.

**Comment by kamilsk** [comment]
ci/cd: https://github.com/octomation/go-module/actions

**Comment by kamilsk** [comment]
Hi folks, @sashamelentyev @phanirithvij 👋
Could someone take a look at the pr and give me some feedback?

**Comment by sashamelentyev** [comment]
@kamilsk hi!
All ok!

**Comment by kamilsk** [comment]
Great! Thank you!

**Pull request merged**
