### PR TITLE
Add sc package to Audio and Music section

### PR DESCRIPTION
**Pull request by briansorahan**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

Please provide package links to:
- godoc.org: https://godoc.org/github.com/scgolang/sc
- goreportcard.com: https://goreportcard.com/report/github.com/scgolang/sc
- gocover.io: http://gocover.io/github.com/scgolang/sc

Note, that new categories can be added only when there are 3 packages or more.

Make shure that you've checked the boxes below before you submit PR:
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link
- [x] I have added gocover.io link
- [x] I have added goreportcard link
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome :+1:

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@briansorahan please add the gocover link. thanks.

**Comment by briansorahan** [comment]
@kirillDanshin I added a gocover link and made it so `go test` skips any tests that require a SuperCollider server to be running. The test coverage is pretty low, but part of the reason is I don't have a mock in place for the SuperCollider server yet.

**Comment by briansorahan** [comment]
@kirillDanshin I'd like to add github.com/scgolang/osc too. Here are the relevant links for that package:

* godoc.org: https://godoc.org/github.com/scgolang/osc
* goreportcard.com: https://goreportcard.com/report/github.com/scgolang/osc
* gocover.io: http://gocover.io/github.com/scgolang/osc

Make sure that you've checked the boxes below before you submit PR:
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link
- [x] I have added gocover.io link
- [x] I have added goreportcard link
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

**Comment by avelino** [comment]
new rules 8 days with label `pending-submitter-response`: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers

obs: added 2 line same URL

**Pull request closed without merging**
