### PR TITLE
add AuthN

### PR DESCRIPTION
**Pull request by cainlevy**
✅ Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/keratin/authn-server
- godoc.org: https://godoc.org/github.com/keratin/authn-server
- goreportcard.com: https://goreportcard.com/report/github.com/keratin/authn-server
- coverage service link: [Coverage Status](https://coveralls.io/github/keratin/authn-server?branch=master)

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [ ] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by cainlevy** [comment]
I don't currently have a godoc link on my repo because AuthN is integrated through ENV vars and HTTP, not through its golang API. Advice is welcome!

**Comment by cainlevy** [comment]
@appleboy Do all exported methods need comments even if they're only used internally? This is a server, not a library. Thanks in advance.

**Comment by avelino** [comment]
No interaction, please read: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers

**Comment by lucagez** [comment]
@avelino would it be possible to reopen this? `Authn` is quite mature now and it certainly is one of the most comprehensive alternatives for authentication written in Go. It took me ages to find that hidden gem

**Pull request closed without merging**
