### PR TITLE
Add libsecurity-go to Security section.

### PR DESCRIPTION
**Pull request by rsagy**
Add the libsecurity-go: add a security layer of permissions (User/Group/Resource), Account Management, One Time Password (OTP), Account Control List (ACL), OATH Challenge-Response Algorithm (OCRA), Password management and Secure Storage as well as RESTful API

### CODE REVIEW

**Comment by dukex** [comment]
LGTM

**Comment by avelino** [comment]
@rsagy update source pls

**Comment by cassiobotaro** [comment]
@rsagy   For  quality standards please follow:  https://github.com/avelino/awesome-go/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by avelino** [comment]
resend pls, you project last update in `Latest commit 5211220  on Feb 21, 2016`

**Pull request closed without merging**
