### PR TITLE
Add Ofelia

### PR DESCRIPTION
**Pull request by git001**
Add Ofelia

Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/mcuadros/ofelia
- godoc.org: https://godoc.org/github.com/mcuadros/ofelia
- goreportcard.com: https://goreportcard.com/report/github.com/mcuadros/ofelia
- coverage service link codecov.io

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by git001** [comment]
added links

**Comment by appleboy** [comment]
https://goreportcard.com/report/github.com/mcuadros/ofelia fix errors.

**Comment by git001** [comment]
I only see warnings, which error do you mean?

**Comment by appleboy** [comment]
@git001 need to fix warnings.

**Comment by git001** [comment]
> @git001 need to fix warnings.

Really?  
Do you want to tell me that every mentioned go project in this repo have no warning?!  
Well I was just a suggestion, accept it or just close it, it's up to you.

**Comment by appleboy** [comment]
@git001 Please fix `golint`, `ineffassign` and `misspell` warning from goreport card or you can close the PR by yourself

**Comment by git001** [comment]
> @git001 Please fix golint, ineffassign and misspell warning from goreport card or you can close the PR by yourself

Thanks @appleboy to take care for the quality of the submitted programs.  
Sadly I have not enough time to contribute to Ofelia to fix the issues.  
I close the PR for now, maybe someone with more time can fix the issues and create a new PR or reopen this one.

Never the less, I say thanks for the great list of the golang tools and programms.

**Pull request closed without merging**
