### PR TITLE
Add uTask in 'DevOps Tools' section

### PR DESCRIPTION
**Pull request by w3st3ry**
**Please provide package links to:**

- github.com repo: https://github.com/ovh/utask
- godoc.org: https://godoc.org/github.com/ovh/utask
- goreportcard.com: https://goreportcard.com/report/github.com/ovh/utask
- coverage service link: https://coveralls.io/github/ovh/utask?branch=master

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: True
- goreportcard.com: True
- coverage: True

**Comment by w3st3ry** [comment]
It's better now @panjf2000

**Comment by panjf2000** [comment]
Code coverage isn't up to 80%, please add more unit tests.

**Comment by w3st3ry** [comment]
Fixed @panjf2000

**Comment by w3st3ry** [comment]
@panjf2000 I fixed the ineffassigns issues due to tests.

**Pull request merged**
