### PR TITLE
Add AwGo (Alfred library)

### PR DESCRIPTION
**Pull request by nikitavoloboev**
Go library to create [Alfred](https://www.alfredapp.com) workflows.

**Please provide package links to:**
- github.com repo: https://github.com/deanishe/awgo
- godoc.org: https://godoc.org/github.com/deanishe/awgo
- goreportcard.com: https://goreportcard.com/report/github.com/deanishe/awgo
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `cover.run go`

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by nikitavoloboev** [comment]
I can't add coverage link as I am not the owner of the repo. I just used it before and found it be really awesome. 

All the coverage websites require to have access to the repo.

**Comment by jtemporal** [comment]
I'd close this per @deanishe request:

> I'm the author of the library and do not want it included in this list or otherwise publicised at this point in time.

**Comment by deanishe** [comment]
I would appreciate that, @jtemporal. I'm still pushing breaking changes, and I wouldn't want the library in the awesome-go list until I can provide a Go-like compatibility guarantee (to the extent possible given AwGo's dependence on [Alfred](https://www.alfredapp.com)).

That aside, is the library now compatible with awesome-go's requirements?

Eventual inclusion would be an honour, and I'd like to thank @nikitavoloboev for "nominating" my work.

I'd also be very grateful for feedback from experienced Gophers.

**Comment by jtemporal** [comment]
Hi @deanishe I'd fix the the warnings on the [Go Report Card](https://goreportcard.com/report/github.com/deanishe/awgo) and also improve [Coverage](https://coveralls.io/github/deanishe/awgo?branch=master)...

I haven't checkout the code yet... But those two would be things to look at first glance ;)

**Comment by deanishe** [comment]
Thanks, @jtemporal. I don't think I'll be changing much there.

The report card is complaining about the MIT License headers in the files, which is pointless nitpicking, imo.

I'm also pretty comfortable with the level of unit-test coverage at this point. Much of the uncovered code is `if err != nil` blocks, trivial API sugar or calls out to Alfred, which doesn't lend itself to automated testing (and would not work *at all* on a CI server).

All the vaguely hairy stuff has decent coverage.

**Pull request closed without merging**
