### PR TITLE
update orderbook

### PR DESCRIPTION
**Pull request by i25959341**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/i25959341/orderbook
- godoc.org: https://godoc.org/github.com/i25959341/orderbook
- goreportcard.com: https://goreportcard.com/report/github.com/i25959341/orderbook
- coverage service link [gocover.run](https://gocover.run?tag=1.10&repo=github.com%2Fi25959341%2Forderbook)

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [ ] I have added godoc link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request.
- [ ] I have added goreportcard link to the repo and to my pull request.
- [ ] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by i25959341** [comment]
@cassiobotaro it said 100% what s wrong

**Comment by cassiobotaro** [comment]
@i25959341 Sorry, I probably confused it with another project during the review.

**Comment by i25959341** [comment]
Can we merge this?

**Comment by cassiobotaro** [comment]
@i25959341 one more review and it will be merged.

**Pull request merged**
