### PR TITLE
Add dlog

### PR DESCRIPTION
**Pull request by kirillDanshin**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- godoc.org: https://godoc.org/github.com/kirillDanshin/dlog
- goreportcard.com: https://goreportcard.com/report/github.com/kirillDanshin/dlog
- ~~gocover.io or coveralls:~~ untestable yet

Note, that new categories can be added only when there are 3 packages or more.

Make sure that you've checked the boxes below before you submit PR:
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [ ] I have added gocover.io or coveralls link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@matrixik @shurcooL @avelino any objections?

**Comment by matrixik** [comment]
Hi, maybe you could squash all this commits?
And you don't have links to godoc and goreportcard in your README.
goreportcard also showing error `There was an error processing your request: Could not go get the repository.`

**Comment by kirillDanshin** [comment]
@matrixik hi!
goreportcard issue was just a typo in my nickname. fixed.
sorry, I forgot to add badges. added.
squashed all commits in one.

**Comment by matrixik** [comment]
Nice, thank you.

**Pull request merged**
