### PR TITLE
- added github.com/bnkamalesh/goapp

### PR DESCRIPTION
**Pull request by bnkamalesh**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/bnkamalesh/goapp
- pkg.go.dev: Not applicable since this is not a Go package
- goreportcard.com: https://goreportcard.com/badge/github.com/bnkamalesh/goapp
- coverage service link: https://codecov.io/gh/bnkamalesh/goapp

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [ ] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: False
- coverage: False

**Comment by bnkamalesh** [comment]
@panjf2000 

- [x] Find out the reason of CI failure; - fixed, it was missing period at the end
- [x] Add all links we request - I have added coverage link, though this is an instructional repository and not a Go package; is it still required?
- [x] Only put your repo in one category on README

**Comment by panjf2000** [comment]
I just took a glance through your README and didn't quite understand this repo, does this repo provide some actual functionalities or just some examples and tutorials?

**Comment by bnkamalesh** [comment]
hello @panjf2000, this repository is instructional/tutorial for creating web applications with Go. It's **not** a Go package. The Go code available is sample code to show how we to implement what's mentioned in the instructions

**Comment by panjf2000** [comment]
In that case, wouldn't it be suitable for this repo to be put into 『Tutorial』category?

**Comment by bnkamalesh** [comment]
@panjf2000  done.

**Pull request merged**
