### PR TITLE
Added gqlc "GraphQL Compiler"

### PR DESCRIPTION
**Pull request by Zaba505**
- github.com repo: [repo](https://github.com/Zaba505/gqlc)
- godoc.org: [godoc](https://godoc.org/github.com/Zaba505/gqlc)
- goreportcard.com: [report](https://goreportcard.com/report/github.com/Zaba505/gqlc)
- coverage service link: [codecov](https://codecov.io/gh/Zaba505/gqlc)

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by Zaba505** [comment]
1. I fixed all the warnings on goreprtcard except the Pos/End methods in graphql/ast/ast.go. Those methods don't really need to be documented given their simplicity. This goes is in line with how the go/ast package is documented as well.
2. I added tests for graphql/token/position.go. As mentioned above graphql/ast is a very simple implementation and I feel it does not need to be tested (eventually the SortImports function will be tested, but for now it's not implemented). Code generator tests/coverage will be added as they are implemented.

If its worth mentioning this project is currently a WIP (see README for more details) but fast approaching its first release.

**Comment by ceriath** [comment]
i relied on [this](https://github.com/Zaba505/gqlc#supported-languages) but i totally agree. It does parse gql, which is what i checked when looking into the coverage issues, but currently is unable to do anything with it.

**Comment by kirillDanshin** [comment]
Update:

it seems like this project currently miss only one stated feature: [the go generator](https://github.com/gqlc/gqlc/blame/master/README.md#L92)

**Comment by Zaba505** [comment]
@kirillDanshin @ceriath All documented generators are now implemented!

**Pull request merged**
