### PR TITLE
Add sleet

### PR DESCRIPTION
**Pull request by daisy1754**
- github.com repo: https://github.com/BoltApp/sleet
- pkg.go.dev: https://pkg.go.dev/github.com/BoltApp/sleet?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/BoltApp/sleet
- coverage service link: https://codecov.io/gh/BoltApp/sleet

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
review:
- coverage is 70.95%
> [...] then coverage should be >= 80% for non-data-related packages and >=90% for data related packages [...]
- golint https://goreportcard.com/report/github.com/BoltApp/sleet#golint

read more: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards

**Comment by daisy1754** [comment]
working on adding test. For golint, it seems guideline isn't super explicit about requirement. Is 100% golint requirement? I want to avoid having redundunt comment like below

```
// TransactionType transaction type
TransactionType
```

**Comment by daisy1754** [comment]
FWIW author of lint suggests ignoring lint when it's not relevant https://github.com/golang/lint/issues/186#issuecomment-171162679

**Comment by avelino** [comment]
We don't ask for 100% lint, we recommend that you have all lint items corrected to keep the quality of your package to a minimum.

> In my view if it is possible to correct, why not correct?

**Comment by daisy1754** [comment]
IMO in some cases (please refer to my example above), "fixing" lint would actually do more harm than benefit. When variable name is self explanatory I prefer not to have comment.

Anyways we're working on increasing coverage. I'll update here once it's ready

**Comment by daisy1754** [comment]
@avelino coverage is now 80%+ https://codecov.io/gh/BoltApp/sleet
I went thorough and fixed lint mostly, but didn't add some redundunt comments so score is not 100 (but I believe this is better than adding redundunt comment just for sake of lint score).

Please kindly review again.

**Pull request merged**
