### PR TITLE
add ingo config utility

### PR DESCRIPTION
**Pull request by schachmat**
required links:
- [godoc.org](https://godoc.org/github.com/schachmat/ingo)
- [goreportcard.com](https://goreportcard.com/report/github.com/schachmat/ingo)
- [gocover.io](https://gocover.io/github.com/schachmat/ingo)

It distinguishes itself from the other choices by its simplicity. It just has around 100 lines of code only using standard library imports and only one exported function `ingo.Parse(appName string)` which is supposed to be used as a drop-in replacement for flags.Parse().

### CODE REVIEW

**Comment by kirillDanshin** [comment]
cool, add some tests and I'll merge it :)

**Comment by schachmat** [comment]
I'm not so sure how to test the default commandline. I would have to add a FlagSet parameter so arbitrary command lines can be tested. Also is it common for tests to use the file-system?

**Comment by kirillDanshin** [comment]
@schachmat yes.

**Comment by schachmat** [comment]
done.

**Comment by kirillDanshin** [comment]
good. merged.

**Pull request merged**
