### PR TITLE
Add STL library

### PR DESCRIPTION
**Pull request by russoj88**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/russoj88/stl
- godoc.org: https://godoc.org/github.com/russoj88/stl/stl
- goreportcard.com: https://goreportcard.com/report/github.com/russoj88/stl
- coverage service link: Didn't find one that supports go 1.12

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by russoj88** [comment]
@appleboy updated to get 100% in all categories.

**Comment by appleboy** [comment]
@russoj88 Can you add the code coverage? You can try the codecov.io service.

**Comment by russoj88** [comment]
@appleboy The repo is 88% covered.

I'll wait until some of the other coverage tools support go 1.12.  Seems a little silly to give access to a third party to write hooks to the repo.

Some of the tools don't support `russoj88/stl`, but support `russoj88/stl/stl`.  This results is low coverage (~30%) because it skips tests in `stl/stl_test`.

**Comment by russoj88** [comment]
Thanks!

**Pull request merged**
