### PR TITLE
Add gnomock to testing frameworks list

### PR DESCRIPTION
**Pull request by orlangure**
**Please provide package links to:**

- github.com repo: https://github.com/orlangure/gnomock
- pkg.go.dev: https://pkg.go.dev/github.com/orlangure/gnomock
- goreportcard.com: https://goreportcard.com/report/github.com/orlangure/gnomock
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/orlangure/gnomock

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
I did not find the percentage of test coverage in GitHub action, I recommend using a coverage system

we usually use these:
- [codecov](https://codecov.io/)
- [coveralls](https://coveralls.io/)
- [gocover](http://gocover.io/)

**Comment by orlangure** [comment]
Hi @avelino,
Gnomock has a fairly heavy test suite due to its nature: it helps in running integration tests, so all its tests are integration tests that make heavy use of containers. Platforms like `gocover` fail to execute the tests correctly.

Let me show the latest coverage reports as reported by `go test -cover` in [this build](https://github.com/orlangure/gnomock/runs/1499541864?check_suite_focus=true):
- `TestGnomock` task (core library): 
```
PASS
coverage: 85.3% of statements
ok  	github.com/orlangure/gnomock	30.296s	coverage: 85.3% of statements
```
- mongodb preset:
```
PASS
coverage: 79.3% of statements
ok  	github.com/orlangure/gnomock/preset/mongo	19.153s	coverage: 79.3% of statements
```
- postgres preset:
```
PASS
coverage: 75.0% of statements
ok  	github.com/orlangure/gnomock/preset/postgres	17.805s	coverage: 75.0% of statements
```
- k3s preset:
```
PASS
coverage: 78.0% of statements
ok  	github.com/orlangure/gnomock/preset/k3s	40.829s	coverage: 78.0% of statements
```
Other presets (sub-packages) have similar coverage. The package with the lowest coverage is `gnomock/gnomockd`:
```
PASS
coverage: 43.3% of statements
ok  	github.com/orlangure/gnomock/internal/gnomockd	0.118s	coverage: 43.3% of statements
```
These values appear in every github action job, in the last tasks (test preset and test server). To confirm, pick some of them and scroll to the bottom.

**Comment by avelino** [comment]
for the librarian to enter awesome-go needs a coverage system with public link, read more at https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md

**Comment by orlangure** [comment]
Hi, @avelino,
Fair enough. I set up codecov integration and added its badge to the [readme](https://github.com/orlangure/gnomock):

Current total coverage is 71%: https://codecov.io/gh/orlangure/gnomock

**Comment by avelino** [comment]
> Current total coverage is 71%: https://codecov.io/gh/orlangure/gnomock

minimal coverage >= 80%, is described in the contribution guide

**Comment by orlangure** [comment]
Hi @avelino,
Coverage is now 80%. Is there anything else I missed?
Thanks.

**Pull request merged**
