### PR TITLE
Added Handwriting.io Go client

### PR DESCRIPTION
**Pull request by groveriffic**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

Please provide package links to:
- godoc.org: 
- goreportcard.com: 
- gocover.io: 

Note, that new categories can be added only when there are 3 packages or more.

Make sure that you've checked the boxes below before you submit PR:
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link
- [x] I have added gocover.io link
- [x] I have added goreportcard link
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome :+1:

### CODE REVIEW

**Comment by kamilsk** [comment]
@groveriffic please provide links.

**Comment by groveriffic** [comment]
Sorry I misread that to mean the project should have links.
Here they are: 
[GoDoc](http://godoc.org/github.com/handwritingio/go-client/handwritingio)
[Go Report Card](https://goreportcard.com/report/github.com/handwritingio/go-client)
[gocover.io](https://gocover.io/github.com/handwritingio/go-client/handwritingio)

**Comment by kirillDanshin** [comment]
@groveriffic please, add more docs and tests.  thanks.

**Comment by cassiobotaro** [comment]
More than 8 days without answers. Feel free to submit this again

**Pull request closed without merging**
