### PR TITLE
Remove: `golang/dep` && `vgo`

### PR DESCRIPTION
**Pull request by yassinebenaid**
Remove: https://github.com/golang/dep
Reason: Archived.

### CODE REVIEW

**Comment by phanirithvij** [comment]
vgo repo also has a notice 

> This repository is obsolete. All features have been incorporated into the main Go tools. The following is of historical interest only.

I guess remove that category wholly? You can force push

**Comment by yassinebenaid** [comment]
Sorry, I don't have access to my laptop, I'm making these changes from phone. So I couldn't force-push.

**Comment by phanirithvij** [comment]
That's fine. We have squash merge as default so only one commit ends up in the main branch.

**Review by Rambo1377 — COMMENTED** [review]
OK

**Pull request merged**
