### PR TITLE
wgrest addition proposal

### PR DESCRIPTION
**Pull request by suquant**
Hello,

I'd like to propose to add a young but very useful project [wgrest](https://github.com/suquant/wgrest) to the list. Thank you.

- repo link (github.com, gitlab.com, etc): github.com/suquant/wgrest
- pkg.go.dev: https://pkg.go.dev/github.com/suquant/wgrest
- goreportcard.com: https://goreportcard.com/report/github.com/suquant/wgrest

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: False

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — COMMENTED** [review]
need coverage link

**Comment by suquant** [comment]
@avelino 

Coverage link: [codecov](https://codecov.io/gh/suquant/wgrest)

Thanks.

**Comment by avelino** [comment]
> Coverage link: [codecov](https://codecov.io/gh/suquant/wgrest)

pls read https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards

> Tests, where practical. If the library/program is testable, then coverage should be >= 80% for non-data-related packages and >=90% for data related packages. Notice: the tests will be reviewed too. We will check your coverage manually if your package's coverage is just a benchmark results.

**Pull request closed without merging**
