### PR TITLE
Added AdGuardHome

### PR DESCRIPTION
**Pull request by crypt0rr**
> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc): https://github.com/AdguardTeam/AdGuardHome
- pkg.go.dev: https://pkg.go.dev/github.com/AdguardTeam/AdGuardHome
- goreportcard.com: https://goreportcard.com/report/github.com/AdguardTeam/AdGuardHome
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/github/AdguardTeam/AdGuardHome?branch=master

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below before you submit PR:**
_not every repository (project) will fit into every option, but most projects should_

- [X] I have added my package in alphabetical order.
- [X] I have an appropriate description with correct grammar.
- [X] I know that this package was not listed before.
- [X] I have added pkg.go.dev link to the repo and to my pull request.
- [X] I have added coverage service link to the repo and to my pull request.
- [X] I have added goreportcard link to the repo and to my pull request.
- [X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by crypt0rr** [comment]
@avelino

**Review by avelino — CHANGES_REQUESTED** [review]
why change the menu identation?

the test coverage is `42%`, it needs to reach `>= 80%`.

[read more here](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards)

**Comment by crypt0rr** [comment]
Weird issue within VSCode, just adding one line to the `README.md` results in weird updates of other markup.. Will open new PR if fixed.

**Pull request closed without merging**
