### PR TITLE
Add WebAssembly category

### LINKED ISSUE #2933: WebAssembly?
There are few links in the official dos:
https://github.com/golang/go/wiki/WebAssembly#interacting-with-the-dom

I think their number will grow. What do you think about adding a section for wasm and putting all these links for the beginning?

### PR DESCRIPTION
**Pull request by orsinium**
Close #2933

To be honest, I'm not sure if all projects here are awesome, even if they listed [in the official guide](https://github.com/golang/go/wiki/WebAssembly). My motivation is the same as (I guess) had authors of that guide: collect what is here right now and just works, since Go compilation into wasm is relatively new and has no ecosystem around. However, I'm a bit more selective and listed only projects that work right now and have some minimal support. Anyway, let's talk.

A few projects that I can be sure are awesome:

+ https://github.com/tinygo-org/tinygo is amazing. I was surprised that it's not here yet.
+ https://github.com/agnivade/wasmbrowsertest is a must-have tool without alternative solutions. I use it actively and it works.

About other tools:

+ https://github.com/norunners/vert looks nice but I haven't tried it yet. I haven't seen alternatives, though.
+ https://github.com/dennwc/dom and https://github.com/gowebapi/webapi are quite messy but we need DOM bindings and has not a lot of alternatives. There is also https://github.com/siongui/godom but I haven't included it since the last commit in 2018. Also, I'm developing https://github.com/life4/gweb but at this point, I can't claim that it is awesome, I'll include it a bit later :)

Have I missed something?

## Links

tinygo:

+ https://github.com/tinygo-org/tinygo
+ https://goreportcard.com/report/github.com/tinygo-org/tinygo (A+)
+ https://pkg.go.dev/github.com/tinygo-org/tinygo?tab=subdirectories
+ https://tinygo.org/
+ cannot find coverage report

wasmbrowsertest:

+ https://github.com/agnivade/wasmbrowsertest
+ https://goreportcard.com/report/github.com/agnivade/wasmbrowsertest (A+)
+ no godoc, isn't intended to be used as a library
+ cannot find coverage report

vert:

+ https://github.com/norunners/vert
+ https://godoc.org/github.com/norunners/vert
+ https://goreportcard.com/report/github.com/norunners/vert (A+)
+ cannot find coverage

dom:

+ https://github.com/dennwc/dom
+ https://godoc.org/github.com/dennwc/dom
+ https://goreportcard.com/report/github.com/dennwc/dom (A+)
+ cannot find coverage

webapi:

+ https://github.com/gowebapi/webapi
+ https://goreportcard.com/report/github.com/gowebapi/webapi (A+)
+ https://godoc.org/github.com/gowebapi/webapi
+ cannot find coverage

go-canvas:

+ https://github.com/markfarnan/go-canvas
+ https://godoc.org/github.com/markfarnan/go-canvas/canvas
+ https://goreportcard.com/report/github.com/markfarnan/go-canvas (B)
+ cannot find coverage

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: False
- coverage: False

**Comment by panjf2000** [comment]
We need some links to check out whether those repositories are qualified to add into the awesome-list, like this one: #3006, and I found that some repositories you provided missing that kind of links, so could you please add those links into this PR? Thanks!

**Comment by orsinium** [comment]
@panjf2000 fixed! I haven't found coverage reports for anything, though. However, goreportcard A+ for everything except go-canvas.

**Comment by panjf2000** [comment]
```
=== RUN   TestAlpha/Awesome_Go
    TestAlpha/Awesome_Go: repo_test.go:131: expected 'web frameworks' but actual is 'webassembly'
    TestAlpha/Awesome_Go: repo_test.go:131: expected 'webassembly' but actual is 'web frameworks'
    TestAlpha/Awesome_Go: repo_test.go:135: expected order is:
        audio and music
        authentication and oauth
        bot building
        command line
        configuration
        continuous integration
        css preprocessors
        data structures
        database
        database drivers
        date and time
        distributed systems
        dynamic dns
        email
        embeddable scripting languages
        error handling
        files
        financial
        forms
        functional
        game development
        generation and generics
        geographic
        go compilers
        goroutines
        gui
        hardware
        images
        iot
        job scheduler
        json
        logging
        machine learning
        messaging
        microsoft office
        miscellaneous
        natural language processing
        networking
        opengl
        orm
        package management
        performance
        query language
        resource embedding
        science and data analysis
        security
        serialization
        server applications
        stream processing
        template engines
        testing
        text processing
        third-party apis
        utilities
        uuid
        validation
        version control
        video
        web frameworks
        webassembly
        windows
        xml
```

It failed on CI because of the order of categories, please fix it.
@orsinium

**Comment by orsinium** [comment]
Ah, right. Thanks. Fixed :)

**Pull request merged**
