### PR TITLE
Add go-m3u8 under Video

### PR DESCRIPTION
**Pull request by quangngotan95**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/quangngotan95/go-m3u8
- godoc.org: https://godoc.org/github.com/quangngotan95/go-m3u8/m3u8
- goreportcard.com: https://goreportcard.com/report/github.com/quangngotan95/go-m3u8
- coverage service link: https://codecov.io/gh/quangngotan95/go-m3u8

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by quangngotan95** [comment]
@cassiobotaro I've updated comments for golint, could you help review again?

**Comment by cassiobotaro** [comment]
great @quangngotan95 , can you fix these little warnings too? 
image
image

**Comment by quangngotan95** [comment]
@cassiobotaro 
1. For `gofmt` issue, I've ran gofmt myself every time but there are no issues. I'm not sure which gofmt version `goreportcard` is using. Anyway it's only a test file, not critical
2. For `golint` issue, my file only contains string constants, there's no value added for adding those comments just to supress `golint`

**Comment by quangngotan95** [comment]
@cassiobotaro please help check my comments above, if you think they're not valid, I'll try to resolve them.

**Pull request merged**
