### PR TITLE
adding fullcontact-go

### PR DESCRIPTION
**Pull request by Abramovic**
Go Library for FullContact's API

github - https://github.com/Abramovic/fullcontact-go
godoc.org - https://godoc.org/github.com/Abramovic/fullcontact-go
goreportcard.com - https://goreportcard.com/report/github.com/Abramovic/fullcontact-go

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@Abramovic you forgot gocover.io links. As an exception, I'll do it for you:
https://gocover.io/github.com/Abramovic/fullcontact-go

**Comment by kirillDanshin** [comment]
@Abramovic please, add more tests. Thank you.

**Comment by cassiobotaro** [comment]
coverage  low too...

**Comment by Abramovic** [comment]
test coverage is now at 70%

**Comment by cassiobotaro** [comment]
More than 8 days without answers. Feel free to send again following the quality standards.

**Comment by cassiobotaro** [comment]
More than 8 days without answers. Feel free to send again following the quality standards.

**Pull request closed without merging**
