### PR TITLE
Add Golangflow.io

### PR DESCRIPTION
**Pull request by bscott**
Add to Websites section

Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo:
- godoc.org:
- goreportcard.com:
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `cover.run go`

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [ ] I have added my package in alphabetical order
- [ ] I know that this package was not listed before
- [ ] I have added godoc link to the repo and to my pull request
- [ ] I have added coverage service link to the repo and to my pull request
- [ ] I have added goreportcard link to the repo and to my pull request
- [ ] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by bscott** [comment]
Fixed the order

**Comment by avelino** [comment]
@bscott pls check https://travis-ci.org/avelino/awesome-go/builds/251844952#L315

**Comment by bscott** [comment]
@avelino I'e tried multiple formats, is there a style guide?, not sure why it keeps failing.

https://travis-ci.org/avelino/awesome-go/builds/254246976?utm_source=github_status&utm_medium=notification

**Comment by bscott** [comment]
@appleboy can you explain, I see that the link is there.

**Comment by kirillDanshin** [comment]
It's not a lib. It's a website @appleboy

Thanks

**Comment by appleboy** [comment]
@bscott Sorry for my mistake.

**Comment by bscott** [comment]
Thanks!

**Pull request merged**
