### PR TITLE
Add ent

### PR DESCRIPTION
**Pull request by sukso96100**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/facebookincubator/ent
- godoc.org: https://godoc.org/github.com/facebookincubator/ent
- goreportcard.com: https://goreportcard.com/report/github.com/facebookincubator/ent
- coverage service link: [CircleCI](https://circleci.com/gh/facebookincubator/ent)

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: True
- goreportcard.com: True
- coverage: False

**Comment by sukso96100** [comment]
What should i do if i'm not a contributor of the ent project? Do i need to tell them to fix those issues?

**Comment by ceriath** [comment]
You can always improve their project and open a pull request with the change, i am sure they'll be happy!

**Comment by ceriath** [comment]
Closing this due to inactivity. Please feel free to reopen.

**Pull request closed without merging**
