### PR TITLE
Add gramework

### PR DESCRIPTION
**Pull request by kirillDanshin**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo: [link](https://github.com/gramework/gramework)
- godoc.org: [link](https://godoc.org/github.com/gramework/gramework)
- goreportcard.com: [link](https://goreportcard.com/report/github.com/gramework/gramework)
- coverage service link (gocover, coveralls etc.): [link](https://codecov.io/gh/gramework/gramework)

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:
  :3

### CODE REVIEW

**Comment by joeybloggs** [comment]
Please increase test coverage and provide at least a basic usage example in the README or godocs

**Comment by kirillDanshin** [comment]
@joeybloggs working on the coverage. now I should test TLS code, and that's difficult now.
just pushed the docs in readme

**Comment by kirillDanshin** [comment]
@joeybloggs what's minimal acceptable coverage for this case, what do you think?

**Comment by joeybloggs** [comment]
@kirillDanshin I would say 80% at the least ideally 90+

**Comment by kirillDanshin** [comment]
@joeybloggs got it, so I need about 25-30% more (67% now), right?

also, we've got an update: https://github.com/smallnest/go-web-framework-benchmark#basic-test

benchmark is now updated and includes gramework. some of the results are pretty interesting:

default
default

**Comment by kirillDanshin** [comment]
@cassiobotaro @joeybloggs still working on tests. found pretty hard to test as much as I can.

**Comment by cassiobotaro** [comment]
Coverage still low.

**Comment by avelino** [comment]
Resend PR pls, UP cover

**Pull request closed without merging**
