### PR TITLE
Added Kallax on ORM

### PR DESCRIPTION
**Pull request by renatosuero**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: (https://github.com/src-d/go-kallax)
- godoc.org: (http://godoc.org/gopkg.in/src-d/go-kallax.v1)
- goreportcard.com:(https://goreportcard.com/report/github.com/src-d/go-kallax)
- coverage service link ([codecov](https://codecov.io/gh/src-d/go-kallax),[travis](https://travis-ci.org/src-d/go-kallax))

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [X] I have added my package in alphabetical order
- [X] I know that this package was not listed before
- [X] I have added godoc link to the repo and to my pull request
- [X] I have added coverage service link to the repo and to my pull request
- [X] I have added goreportcard link to the repo and to my pull request
- [X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by renatosuero** [comment]
@cassiobotaro the url is correct, sorry I don't understand the problem.Can you help me ?

**Comment by kamilsk** [comment]
@renatosuero, I think @cassiobotaro talks about https://goreportcard.com/report/github.com/src-d/go-kallax#golint

**Comment by cassiobotaro** [comment]
@renatosuero pls fix  https://goreportcard.com/report/github.com/src-d/go-kallax#golint

**Comment by renatosuero** [comment]
@cassiobotaro sorry, but I don't have time now =(. I'll fix it and I send  a new PR. sorry

**Comment by cassiobotaro** [comment]
@renatosuero ok, pls submit a new PR when it's all ok.

**Pull request closed without merging**
