### PR TITLE
Adding Iris

### PR DESCRIPTION
**Pull request by gpedro**
- github.com repo: https://github.com/karatas/iris
- godoc.org: https://godoc.org/github.com/kataras/iris http://docs.iris-go.com/
- goreportcard.com: https://goreportcard.com/report/kataras/iris
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): N/A

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [ ] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by kirillDanshin** [comment]
It was banned.

**Comment by gpedro** [comment]
why? o.O

**Comment by kirillDanshin** [comment]
We can add go-siris, if they add third-party licenses, but not iris itself.

**Comment by kirillDanshin** [comment]
Because of multiple license violation, stealing contributor's commits etc.

**Comment by gpedro** [comment]
#1135
#1137

**Comment by kirillDanshin** [comment]
Yes, thanks for references. I'm online on the phone, where I can't search issues on.

**Comment by kirillDanshin** [comment]
Kataras' account is removed again :/

**Comment by kirillDanshin** [comment]
screenshot_20170730-214319

**Comment by kirillDanshin** [comment]
Thanks for trying to contribute. Please send us a PR with another awesome lib.

**Comment by kirillDanshin** [comment]
Whoops. Noted the broken link

**Pull request closed without merging**
