### PR TITLE
🚀 Add Fiber to Web Frameworks

### PR DESCRIPTION
**Pull request by Fenny**
🔌 **[Fiber](https://github.com/gofiber/fiber)** is an [Express.js](https://expressjs.com/en/4x/api.html) styled HTTP web framework implementation running on 🚀 [Fasthttp](https://github.com/valyala/fasthttp), the **fastest** HTTP engine for Go. The package make use of **similar framework convention** as they are in Express.

People switching from [Node.js](https://nodejs.org/en/about/) to [Go](https://golang.org/doc/) often end up in a bad learning curve to start building their webapps, this project is meant to **ease** things up for **fast** development, but with **zero memory allocation** and **performance** in mind.

**Please provide package links to:**

- github.com repo: https://github.com/gofiber/fiber
- api documentation: https://fiber.wiki
- godoc.org: https://godoc.org/github.com/gofiber/fiber
- goreportcard.com: https://goreportcard.com/report/github.com/gofiber/fiber
- gocover.io: https://gocover.io/github.com/gofiber/fiber

_`gocover.io` seems to have a [time-out bug](https://github.com/vieux/gocover.io/issues/41). It complains about an error for `strconv.ParseFloat` which is not called anywhere in the source code.The test coverage is 0% when tested locally._

**Extra links:**
- API documentation: https://gofiber.github.io/fiber/
- Benchmarks: https://gofiber.github.io/fiber/#/benchmarks

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: True
- goreportcard.com: True
- coverage: True

**Comment by xhit** [comment]
For documentation: gocover.io returns that error when timeout, use this command for get the coverage and same html of gocover.io and attach them or upload to public hosting:

`go test -coverprofile=c.out && go tool cover -html=c.out`

I had to do this adding in PR https://github.com/avelino/awesome-go/pull/2738

**Comment by Fenny** [comment]
@xhit, thanks for your feedback. We will add tests this week :+1:

**Comment by Fenny** [comment]
@panjf2000, could you review?
https://gocover.io/github.com/gofiber/fiber

Thanks :+1:

**Comment by panjf2000** [comment]
I've seen it and unfortunately, this coverage doesn't meet our standard(>=80%), please add more unit tests to increase it.

**Comment by Fenny** [comment]
@panjf2000, could you review one more time?
`ok      github.com/gofiber/fiber        0.009s  coverage: 80.7% of statements`

**Comment by Fenny** [comment]
@panjf2000 fixed :+1:

**Pull request merged**
