### PR TITLE
Added Concert, Minio Client and s3verify.

### PR DESCRIPTION
**Pull request by koolhead17**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

S3verify
github.com repo: [https://github.com/minio/s3verify](https://github.com/minio/s3verify)
Godoc.org: [https://godoc.org/github.com/minio/s3verify](https://godoc.org/github.com/minio/s3verify)
Goreportcard.com: [https://goreportcard.com/report/github.com/minio/s3verify](https://goreportcard.com/report/github.com/minio/s3verify)
coverage service link (gocover, coveralls etc.): Not Available. 

Concert
github.com repo: [https://github.com/minio/concert](https://github.com/minio/concert)
Godoc.org: [https://godoc.org/github.com/minio/concert](https://godoc.org/github.com/minio/concert)
Goreportcard.com: [https://goreportcard.com/report/github.com/minio/concert](https://goreportcard.com/report/github.com/minio/concert)
coverage service link (gocover, coveralls etc.): Not Available. 

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [ ] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by shurcooL** [comment]
You have a duplicate link 'https://github.com/minio/mc'.

**Comment by koolhead17** [comment]
My bad, removed it.

**Comment by avelino** [comment]
We need every link to accept

**Comment by koolhead17** [comment]
@avelino Each project has Github link associated with each project, please let me know what links I missed.

**Comment by kirillDanshin** [comment]
@koolhead17 
you've missed
```


Please provide package links to:

    github.com repo:
    godoc.org:
    goreportcard.com:
    coverage service link (gocover, coveralls etc.):

```

for each project.

**Comment by koolhead17** [comment]
S3verify
github.com repo: [https://github.com/minio/s3verify](https://github.com/minio/s3verify)
Godoc.org: [https://godoc.org/github.com/minio/s3verify](https://godoc.org/github.com/minio/s3verify)
Goreportcard.com: [https://goreportcard.com/report/github.com/minio/s3verify](https://goreportcard.com/report/github.com/minio/s3verify)
coverage service link (gocover, coveralls etc.): Not Available. 

Concert
github.com repo: [https://github.com/minio/concert](https://github.com/minio/concert)
Godoc.org: [https://godoc.org/github.com/minio/concert](https://godoc.org/github.com/minio/concert)
Goreportcard.com: [https://goreportcard.com/report/github.com/minio/concert](https://goreportcard.com/report/github.com/minio/concert)
coverage service link (gocover, coveralls etc.): Not Available. 

I hope this helps.

**Comment by avelino** [comment]
new rules 8 days with label `pending-submitter-response`: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers

**Pull request closed without merging**
