### PR TITLE
Add govaluate

### PR DESCRIPTION
**Pull request by yeka**
I was looking for something to parse mathematical equation in a string.
Couldn't find one here, I tried to write one myself.
Knowing it would take a while before I could make one that work, I googled a bit and found [govaluate](github.com/Knetic/govaluate).
So I decided to make a PR so others who are looking for the same thing can find it here.

Not sure though if I put it in the right category :p

-- Updated: --
Here's the link: [github](https://github.com/Knetic/govaluate) [godoc](https://godoc.org/github.com/Knetic/govaluate) [Go Report Card](https://goreportcard.com/report/github.com/Knetic/govaluate) [gocover](https://gocover.io/github.com/Knetic/govaluate)

- [x] I have added the package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to my pull request and it's exists in the repo.
- [x] I have added coverage service link ~to the repo and~ to my pull request.
- [x] I have added goreportcard link ~to the repo and~ to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

* The strike through is because I don't own the repo, though I'll make a PR there.

### CODE REVIEW

**Comment by zet4** [comment]
Use https://github.com/avelino/awesome-go/blob/master/.github/PULL_REQUEST_TEMPLATE.md and follow https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md

**Comment by yeka** [comment]
Links updated

**Comment by yeka** [comment]
which warning do you find unsettling?
I mean I'm not gonna solve them all unnecessarily.

**Comment by cassiobotaro** [comment]
image
It's not java or javascript!
image

**Comment by cassiobotaro** [comment]
https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers

**Pull request closed without merging**
