### PR TITLE
www - static web server

### PR DESCRIPTION
**Pull request by nbari**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/nbari/www
- godoc.org: https://godoc.org/github.com/nbari/www
- goreportcard.com: https://goreportcard.com/report/github.com/nbari/www
- coverage service link: https://coveralls.io/github/nbari/www

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by nbari** [comment]
Hi @cassiobotaro I did my best but didn't know how to full fill some requirements, the thing is that the tiny server is less than 100 lines using mainly go standard libraries, therefore, I omitted tests of native packages. Could you please explain to me what I am missing or how full met the requirements for this cases.

thanks in advance.

**Comment by cassiobotaro** [comment]
I update your PR description. Still missing godoc and coverage...

**Comment by nbari** [comment]
Hi @cassiobotaro many thanks, I added the links but need to investigate how to do test (https://github.com/nbari/www/issues/2)

**Comment by cassiobotaro** [comment]
Feel free to submit again when in conformity with https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md

**Comment by nbari** [comment]
hi @cassiobotaro Just added the missing tests and updated the links, hope is ok now.

**Comment by cassiobotaro** [comment]
@nbari coverage still low

**Comment by nbari** [comment]
@cassiobotaro check the code (https://coveralls.io/builds/13726244/source?filename=www.go) full program is less than 100 lines and the 60% basically is only for the main function.

That's why I mention before is very tiny and using mainly standard libraries the ones are already tested.

**Comment by cassiobotaro** [comment]
@nbari start by removing main function content, and create new functions with specific responsibilities.

**Comment by nbari** [comment]
Hi @cassiobotaro, that will imply re-testing the flag package and could not make sense,  I do understand your point but I think this is an example of how awesome go can be in terms of the things that can be done by using only standard libraries, anyway this is a nice challenge now of how to try to cover 100% and keep code in less than 100 lines, I will do my best 👍

**Comment by avelino** [comment]
Closing this PR, I await around with the test coverage

**Pull request closed without merging**
