### PR TITLE
Add tempdb to database list

### PR DESCRIPTION
**Pull request by rafaeljesus**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo: https://github.com/rafaeljesus/tempdb
- godoc.org: https://godoc.org/github.com/rafaeljesus/tempdb
- goreportcard.com: https://goreportcard.com/report/github.com/rafaeljesus/tempdb
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/rafaeljesus/tempdb

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by appleboy** [comment]
Please fix errors from go report card.

**Comment by rafaeljesus** [comment]
@appleboy can you check again? I've also increased coverage to 100.0% locally

**Comment by kirillDanshin** [comment]
@rafaeljesus you can reduce memory allocations by creating and using a new const with your key prefix (see https://github.com/rafaeljesus/tempdb/blob/master/tempdb.go#L75, https://github.com/rafaeljesus/tempdb/blob/master/tempdb.go#L90).
anyway, LGTM, merged

**Comment by rafaeljesus** [comment]
@kirillDanshin thanks for the suggestion mate!

**Comment by rafaeljesus** [comment]
@kirillDanshin https://github.com/rafaeljesus/tempdb/commit/4e255a3008625c6946d140b7a4aecee54ee08a07

**Comment by kirillDanshin** [comment]
cool. also, check out if your debug lib provides compile-time disabling, if not - I'll suggest you to extract debug format string (see [here](https://github.com/rafaeljesus/tempdb/blob/4e255a3008625c6946d140b7a4aecee54ee08a07/tempdb.go#L82)).

 if you want to check out a simple debug logger with compile-time disabling, check out my [dlog](https://github.com/kirillDanshin/dlog).

**Comment by rafaeljesus** [comment]
Good to know, I will check that out

**Comment by rafaeljesus** [comment]
hey mate @kirillDanshin can you elaborate?
> extract debug format string

**Comment by kirillDanshin** [comment]
@rafaeljesus yep:
```go
const someDebugFmtLalala = "Saved %s/%s. Expiring in %d seconds"
```

**Comment by rafaeljesus** [comment]
@kirillDanshin gotcha! thx

**Pull request merged**
