### PR TITLE
Add ponzu to list of web frameworks

### PR DESCRIPTION
**Pull request by ashishmohite**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo: https://github.com/ponzu-cms/ponzu
- godoc.org: https://godoc.org/github.com/ponzu-cms/ponzu
- goreportcard.com: https://goreportcard.com/report/github.com/ponzu-cms/ponzu
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/ponzu-cms/ponzu/cmd/ponzu

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by joeybloggs** [comment]
@ashishmohite missing godoc, coverage and report card links

I also don't see many tests.

**Comment by ashishmohite** [comment]
@joeybloggs i tried to find links mentioned in the comment on the project's repo but couldn't find those. What can be done next ?

**Comment by joeybloggs** [comment]
@ashishmohite you can always contact the maintainer via email or create an issue within the repo; most maintainers are very receptive :)

**Comment by petermbenjamin** [comment]
@ashishmohite & @joeybloggs , are these what you're looking for:
godoc.org: https://godoc.org/github.com/ponzu-cms/ponzu

**Comment by ashishmohite** [comment]
@petermbenjamin Yes, I'd created issue on pozu repo and I got a message from it's maintainer that it's been created .
Apparently it seems that gocover link isn't working

**Comment by nilslice** [comment]
Hi @ashishmohite, @joeybloggs, @petermbenjamin - I'm the maintainer of the Ponzu repo. Thank you for considering the project for inclusion on this list!

The current test coverage is very low but progress is being made. The coverage link is actually here: https://gocover.io/github.com/ponzu-cms/ponzu/cmd/ponzu since we distribute the CLI + framework in the same repo and it is the only buildable code. More tests will be added soon, which should bring the project up to the standards required by awesome-go.

**Comment by ashishmohite** [comment]
@nilslice I can help with test coverage. I'm a newbie in golang tough

**Comment by nilslice** [comment]
@ashishmohite - all help is appreciated! I created Ponzu with a goal in mind to bring more programmers to the Go language -- just like Wordpress brought so many to PHP, and Rails to Ruby, so new Gophers are quite welcome :) 

If you have time to write any tests, please stick to the standard library as much as possible. If you need to use an external package, try to choose one with few (if any) external dependencies - since we are currently vendoring & flattening all dependencies, and ideally only to mock resources.

Thank you & please let me know if you have any issues. I'm typically available in the Gopher's Slack #ponzu channel: 
[#ponzu on Slack](https://gophers.slack.com/messages/C3TBV356D)

**Comment by avelino** [comment]
[cover.run go](https://cover.run/go/github.com/ponzu-cms/ponzu/cmd/ponzu)
https://cover.run/go/github.com/ponzu-cms/ponzu/cmd/ponzu

**Comment by avelino** [comment]
new rules 8 days with label `pending-submitter-response`: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers

**Pull request closed without merging**
