### PR TITLE
Add packages for FTP, SFTP protocols.

### LINKED ISSUE #266: No packages for ftp/sftp.
FTP and SFTP are well defined and widespread standards, yet this list does not contain any Go packages.

Here's a good package for SFTP that I'm aware of:

http://godoc.org/github.com/pkg/sftp

### PR DESCRIPTION
**Pull request by shurcooL**
Resolves #266.
/cc @jlaffaye @davecheney @koofr

### CODE REVIEW

**Comment by mholt** [comment]
Cool - thanks for doing this. To be consistent, the links should go to the project homepage rather than straight to the docs, I think.

**Comment by avelino** [comment]
+1

**Comment by shurcooL** [comment]
@mholt, I've addressed that in fd44cd5, PTAL.

**Comment by mholt** [comment]
Thanks! It'll be good to close that issue properly.

**Pull request merged**
