### PR TITLE
Remove non-free books per policy

### PR DESCRIPTION
**Pull request by bitfield**
See #3701 and #3908: only free books should be listed here.

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: False
- coverage: False

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by phanirithvij** [comment]
@avelino I think a paid books section makes sense but personally I'm of the same opinion as you.

Or maybe we could put up issue/discussion for a vote to see if the community wants it?

**Comment by avelino** [comment]
> @avelino I think a paid books section makes sense but personally I'm of the same opinion as you.
> 
> Or maybe we could put up issue/discussion for a vote to see if the community (including the maintainers) are interested in it?

I created an issue to discuss this subject, I will post my opinion there

**Comment by adebobo19** [comment]
True

**Pull request closed without merging**
