### PR TITLE
Add ToTo

### PR DESCRIPTION
**Pull request by blogcin**

### CODE REVIEW

**Comment by matrixik** [comment]
Great, but what happen to first line?

**Comment by blogcin** [comment]
I don't know :(...

**Comment by blogcin** [comment]
I didn't change that.

**Comment by matrixik** [comment]
Hmmm, `ToTo` isa cli tool and I'm thinking maybe it's better if it will be added to `Software Packages` => `Other Software`. `Networking` is for libraries that can be used by other programs.

**Comment by matrixik** [comment]
Thank you for contribution, I added it in `Software Packages` => `Other Software`

**Pull request closed without merging**
