### PR TITLE
Add github.com/jacobsa/fuse under files section

### PR DESCRIPTION
**Pull request by dotslash**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/jacobsa/fuse
- godoc.org: https://godoc.org/github.com/jacobsa/fuse, https://godoc.org/github.com/jacobsa/fuse/fuseops, https://godoc.org/github.com/jacobsa/fuse/fuseutil
- goreportcard.com: https://goreportcard.com/report/github.com/jacobsa/fuse
- coverage service link : https://gocover.io/github.com/jacobsa/fuse

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by dotslash** [comment]
@appleboy I dont understand what your comment means? Are you saying this repository is low quality?

**Comment by appleboy** [comment]
@dotslash Yes, you can see the result from goreport card: https://goreportcard.com/report/github.com/jacobsa/fuse

**Comment by dotslash** [comment]
As some one who worked on fuse filesystems, all I can say is that this is the best fuse library out there in golang. It will be a shame if the curated list of awesome go projects does not have a place for this because of go lint. This is a big library that does very low level things. 

While go lint is a great tool, looking at "only lint" to measure how good the codebase is not ideal IMO. I can add more critique about go lint, but thats not the point. Inspite of the 37 issues, the report card says A+. (this is a big library)  

The documentation of this fuse library, especially the fuseops package is so detailed that, I recommend the checking the documentation of jacabsa/fuse even if one is working on c-fuse. You can check for yourself.

cpp fuse: https://libfuse.github.io/doxygen/index.html
jacabsa/fuse: https://godoc.org/github.com/jacobsa/fuse

If we are looking for validation, this is used by google's https://github.com/GoogleCloudPlatform/gcsfuse. 

I neither own or contribute to this and am here only because i truly think this is a great piece of software.

**Comment by dotslash** [comment]
Looks like there is no room for disagreement here. It's an understatement to say that Im disappointed.

**Pull request closed without merging**
