### PR TITLE
Added github.com/shomali11/xredis

### PR DESCRIPTION
**Pull request by shomali11**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/shomali11/xredis
- godoc.org: https://godoc.org/github.com/shomali11/xredis
- goreportcard.com: https://goreportcard.com/report/github.com/shomali11/xredis
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: http://gocover.io/github.com/shomali11/xredis

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [X] I have added my package in alphabetical order
- [X] I know that this package was not listed before
- [X] I have added godoc link to the repo and to my pull request
- [X] I have added coverage service link to the repo and to my pull request
- [X] I have added goreportcard link to the repo and to my pull request
- [X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by shomali11** [comment]
@cassiobotaro Done. I improved it to 92.2%

**Comment by shomali11** [comment]
I added some mock tests. The code coverage looks better now.

**Comment by shomali11** [comment]
@cassiobotaro I was wondering if you had a chance to review. I have updated the tests and improved the code coverage to 95.3% according to http://gocover.io/github.com/shomali11/xredis

The following are my unit and mock tests if you are interested.
https://github.com/shomali11/xredis/blob/master/options_test.go
https://github.com/shomali11/xredis/blob/master/xredis_test.go

**Comment by shomali11** [comment]
Awesome!
Could you merge it?

**Comment by cassiobotaro** [comment]
Thanks @shomali11!

**Comment by shomali11** [comment]
You are most welcome :)

**Pull request merged**
