### PR TITLE
artifactory_exporter to Server Applications

### PR DESCRIPTION
**Pull request by peimanja**
**Please provide package links to:**

- github.com repo: https://github.com/peimanja/artifactory_exporter
- pkg.go.dev: https://pkg.go.dev/github.com/peimanja/artifactory_exporter?tab=overview
- goreportcard.com: https://goreportcard.com/report/github.com/peimanja/artifactory_exporter
- coverage service link 

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: False

**Comment by panjf2000** [comment]
missing code coverage.

**Comment by peimanja** [comment]
> missing code coverage.

Thanks, I will fix that and update here

**Comment by panjf2000** [comment]
It's been more than 15 days without a reply from the PR owner, I'm closing this PR according to our [contributing guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers).

Feel free to reopen it once you resolve all the code issues.

**Pull request closed without merging**
