### PR TITLE
Add echotron telegram bot library

### PR DESCRIPTION
**Pull request by DarkFighterLuke**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

- github.com repo: https://github.com/NicoNex/echotron
- pkg.go.dev: https://pkg.go.dev/github.com/NicoNex/echotron/v2
- goreportcard.com: https://goreportcard.com/report/github.com/NicoNex/echotron
- coverage service link:  [coveralls](https://coveralls.io/github/NicoNex/echotron?branch=master/),

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
review:
- cover >80%

**Comment by NicoNex** [comment]
@avelino the vast majority of the uncovered methods are empty methods that are useful only to implement some interfaces as you can see [here](https://coveralls.io/builds/38811691/source?filename=inlinetypes.go).

Apart from those methods the only ones that are not covered are 5 methods in `dispatcher.go` which hang since they contain infinite loops and thus are pretty untestable. 

In any case we have covered all the methods that are testable and can break.

**Comment by NicoNex** [comment]
@avelino can you review the repo again please? 
We have added a lot of tests and the coverage has increased to 81% as you can see from [here](https://coveralls.io/github/NicoNex/echotron?branch=master).

If the badge in the repo displays a lower number it's because of github caching those images for a certain time, so eventually click on it in order to check directly the coveralls page.

**Comment by DarkFighterLuke** [comment]
@avelino any news?

**Pull request merged**
