### PR TITLE
Add ChainJacking by Checkmarx

### PR DESCRIPTION
**Pull request by kaplanlior**
ChainJacking is a tool to find which of your Go lang direct GitHub dependencies is susceptible to ChainJacking attack.

- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: False
- coverage: False

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by kaplanlior** [comment]
Thanks @avelino , looking forward to see this merged :+1:

**Review by avelino — COMMENTED** [review]
need links, pls read contribute guide 
https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md

**Comment by kaplanlior** [comment]
repo link (github.com, gitlab.com, etc): https://github.com/Checkmarx/chainjacking
pkg.go.dev: [n/a], tool is in Python to help secure go code
goreportcard.com: [n/a], tool is in Python to help secure go code
coverage service link (codecov, coveralls, gocover etc.): We'll add our SAST report (I'll edit this reply)

**Comment by avelino** [comment]
> tool is in Python to help secure go code

Great tool, but why wasn't it written in Go, since it is a tool to deal with software written in Go?

**Comment by kaplanlior** [comment]
The important for us is to help the users to be secure.

Rewrite in GO would be a nice feature request once this is accepted to this list.
Do you want the honor to open it at https://github.com/Checkmarx/chainjacking ?

**Comment by avelino** [comment]
@phanirithvij what is your opinion?

**Review by phanirithvij — APPROVED** [review]
I think it's great to include it in awesome-go as it exclusively deals with go projects (as of now).
I think any tools whose primary focus is making go developers' lives easier, even if written in other languages, can belong in awesome-go. (be any category like code-gen, RPC, ffi, etc.)

I agree that Go could've been a great choice to pick at the beginning of writing chainjacking.
Maybe if chainjacking becomes mature enough to support multiple languages and frameworks, then it can belong in [awesome-devsecops](https://github.com/TaptuIT/awesome-devsecops) like [Checkmarx/kics](https://github.com/Checkmarx/kics).

**Comment by kaplanlior** [comment]
@avelino Thanks for the merge.

Can / should I also add it to the Security section in addition to code analysis ?

**Pull request merged**
