### PR TITLE
Add Trybe's style guide

### PR DESCRIPTION
**Pull request by eminetto**
Add Trybe's style guide

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: False
- coverage: False

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
all lines that contain a description must end with a period `.`

**Comment by avelino** [comment]
> @avelino this falls under having no readme in english, should it be merged?

@phanirithvij it is a company style guide, it was put in the description (here on awesome-go) that it is in Portuguese (Brazil)

My opinion is that we should accept it, what do you think?

**Comment by phanirithvij** [comment]
@eminetto any plans to have a README_EN ?

**Comment by eminetto** [comment]
@phanirithvij we can work in an english version, but it will take a time. We can close this Pull Request and i open again when we translate.

**Comment by phanirithvij** [comment]
Thanks for understanding.

**Comment by phanirithvij** [comment]
#4022

**Pull request closed without merging**
