### PR TITLE
Add Prudence

### PR DESCRIPTION
**Pull request by tliron**
Add Prudence

Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo:
- pkg.go.dev:
- goreportcard.com:
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.)

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: False
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
Place the links in the pull request description

**Comment by tliron** [comment]
Thanks, I edited both the PR name and commit message.

**Comment by avelino** [comment]
> Thanks, I edited both the PR name and commit message.

github.com repo:
pkg.go.dev:
goreportcard.com:
coverage service link (codecov, coveralls, gocover etc.)

???

**Comment by tliron** [comment]
I'm sorry, I really don't understand the last message.

**Comment by tliron** [comment]
Why is this closed? Sorry, you wrote me a message that I did not understand. If you explain what you want me to do I will do it.

**Comment by avelino** [comment]
> Why is this closed? Sorry, you wrote me a message that I did not understand. If you explain what you want me to do I will do it.

take your time to read the [pull request template](https://github.com/avelino/awesome-go/blob/master/.github/PULL_REQUEST_TEMPLATE.md) (you have not filled in the required links) and the [quality guide](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards)

**Comment by tliron** [comment]
I think there is a bug in your automated system because the page does have a goreportcard link and it is A+.

**Comment by avelino** [comment]
fill in the links below

github.com repo:
pkg.go.dev:
goreportcard.com:
coverage service link (codecov, coveralls, gocover etc.)

**Comment by tliron** [comment]
I'm confused about the requirement for coverage service -- I went through existing entries on awesome-go to try to see what is popular and I see many do not use a coverage service at all. Do I need to use a coverage service?

**Comment by tliron** [comment]
In any case, here are the rest of the links:

github.com repo: https://github.com/tliron/puccini
pkg.go.dev: https://pkg.go.dev/github.com/tliron/puccini
goreportcard.com: https://goreportcard.com/report/github.com/tliron/puccini

**Pull request closed without merging**
