### PR TITLE
add jfcg/yell: yet another minimalistic logging library

### PR DESCRIPTION
**Pull request by jfcg**
- github.com repo: https://github.com/jfcg/yell
- pkg.go.dev: https://pkg.go.dev/github.com/jfcg/yell
- goreportcard.com: https://goreportcard.com/report/github.com/jfcg/yell
- coverage service link: https://gocover.io/github.com/jfcg/yell

- [X] I have added my package in alphabetical order.
- [X] I have an appropriate description with correct grammar.
- [X] I know that this package was not listed before.
- [X] I have added pkg.go.dev link to the repo and to my pull request.
- [X] I have added coverage service link to the repo and to my pull request.
- [X] I have added goreportcard link to the repo and to my pull request.
- [X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
- cover >= 80%, today `58.9%`
- example on project readme (this repo)

read more: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards

**Comment by jfcg** [comment]
>     * cover >= 80%, today `58.9%`
coverage is now 91.1%

>     * example on project readme (this repo)
added comprehensive example in yell readme

**Comment by jfcg** [comment]
sorry, wrong button

**Pull request merged**
