### PR TITLE
Add `colorgo`, a `go build` colorizer

### PR DESCRIPTION
**Pull request by songgao**

### CODE REVIEW

**Comment by shurcooL** [comment]
Hi @songgao,

This looks like a cool tool!

However, I think it's in the wrong section. It's not a CLI library, but a tool for working with go tool. I think it should be moved somewhere under the [Tools](https://github.com/avelino/awesome-go#tools) section.

**Comment by songgao** [comment]
Make sense. I'll `git --amend` it then

**Comment by songgao** [comment]
@shurcooL Actually on a second thought, what do you think of the [Utilities](https://github.com/avelino/awesome-go#utilities) section?

**Comment by shurcooL** [comment]
Utilities is better than your original section, but I still think Tools section is better. Utilities contains general utilities for doing various things. Tools contains utilities specifically for working with Go.

**Comment by songgao** [comment]
@shurcooL Thanks for the explanation. I amended the commit to move it to Tools section. (I assumed you meant the [DevOps Tools](https://github.com/avelino/awesome-go#devops-tools) subsection)

**Comment by shurcooL** [comment]
I kinda wanted to see it under Code Analysis, but it's not exactly Code Analysis. I personally would want to see a similar section added there. But I suppose DevOps Tools will do too. I don't know about others, but DevOps means something else to me (and it seems to have quite a few things that IMO aren't ideal there).

If you're okay with it, LGTM, but I think you could also make a new subsection under Tools where your tool could go.

**Comment by shurcooL** [comment]
See https://github.com/avelino/awesome-go/issues/497 for a related discussion. I feel like we should add another section next to Code Analysis to fill the gap.

**Comment by songgao** [comment]
In fact I didn't think it was exactly a `DevOps Tool` either :D 

I like the idea of adding another subsection. How about "Build Tool" or "Coding Assistance"?

**Comment by shurcooL** [comment]
Between those two, I like "Build Tools" better.

However, I'd want to move tools like `gb,` `goimports`, `lint` and you tool in there. So it's not just build tools, but rather tools related to Go.

So how about "Go Tools" as the new subsection name?

**Comment by songgao** [comment]
Sounds good to me! I also updated this PR; I guess moving other packages should be in a separate PR?

**Comment by shurcooL** [comment]
Yep.

LGTM. Thanks!

**Comment by songgao** [comment]
Sure thing. Thanks for the suggestions!

**Comment by dukex** [comment]
@songgao You need put this new section in section index

**Comment by songgao** [comment]
@dukex Done! Sorry for overlooking that earlier

**Comment by shurcooL** [comment]
@dukex Thanks for catching that, I overlooked it.

**Comment by shurcooL** [comment]
LGTM.

**Comment by dukex** [comment]
Thanks @songgao and @shurcooL

**Comment by songgao** [comment]
Thanks for merging :D

**Pull request merged**
