### PR TITLE
Adding mssqlx (production library at iparking.vn)

### PR DESCRIPTION
**Pull request by linxGnu**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/linxGnu/mssqlx
- godoc.org: https://godoc.org/github.com/linxGnu/mssqlx
- goreportcard.com: https://goreportcard.com/report/github.com/linxGnu/mssqlx
- coverage service link: https://gocover.io/github.com/linxGnu/mssqlx

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by linxGnu** [comment]
Thanks you for quick reply. I would update test case and coverage soon.

**Comment by linxGnu** [comment]
Thanks a lot. I added test cover and pushed to github. Please review my new coverage.

cover.run go

**Comment by matrixik** [comment]
Lib look OK, just some random thought:
@linxGnu did you considered pushing your changes to sqlx? Instead of copying jmoiron/sqlx into your pkg.

**Comment by linxGnu** [comment]
I am planning to refer (instead of copying sqlx directly to my pkg) and cleanup code soon.

Thanks a lot for your suggestion @matrixik

**Pull request merged**
