### PR TITLE
Add go-OAS/docs

### PR DESCRIPTION
**Pull request by kaynetik**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: [repo => go-oas/docs](https://github.com/go-oas/docs)
- pkg.go.dev: [pkg.go.dev => go-oas/docs](https://pkg.go.dev/github.com/go-oas/docs)
- goreportcard.com: [report card => go-oas/docs](https://goreportcard.com/report/github.com/go-oas/docs)
- coverage service link: [coveralls](https://coveralls.io/github/go-oas/docs)

Very good coverage - currently ~94% => but planning to add a few more _QuickCheck_ tests to cover more edge cases.

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by kaynetik** [comment]
I've just made a few smaller improvements, and re-cached `pkg.go.dev` info - wasn't aware that it has to be forcefully re-cached per new tag each time. :relaxed:  So if you already started the review, please give it another go. :wave:

Thanks!

**Comment by kaynetik** [comment]
Hope you don't mind me commenting on this PR, and also that it's not against the rules (I did check the FAQ section).

I'm more than happy for a discussion if you are having second thoughts about including this project on your list?


Bear in mind that I just recently started and that there is a huge roadmap ahead - but being a part of the _Awesome_ crew would give me a bigger user base, which would, in turn, help me refine the product.
So if you think that something could (or should) be altered quickly before joining, feel free to submit an RFC.

**Comment by kaynetik** [comment]
Well, I'm not certain if something is missing here, or no one even took a look at the PR @avelino ?

If this doesn't meet some standards, I would really appreciate some feedback, to know what should be my next focus point.

**Comment by avelino** [comment]
> Hope you don't mind me commenting on this PR, and also that it's not against the rules (I did check the FAQ section).

@kaynetik feel free to comment and interact on the pull request (opened by you or anyone), here (issue and pull request) is an open communication channel

sorry for the delay in reviewing your contribution, unfortunately awesome-go is not my first job - I can't look at the project every week, if you are interested in contributing, **you are very welcome**

**Comment by kaynetik** [comment]
I'll check out the contribution guideline for reviewers, and put in some effort.

Thanks for the feedback.

**Pull request merged**
