### PR TITLE
Add Gridder

### PR DESCRIPTION
**Pull request by shomali11**
**Please provide package links to:**

- github.com repo: https://github.com/shomali11/gridder
- pkg.go.dev: https://pkg.go.dev/github.com/shomali11/gridder?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/shomali11/gridder
- gocover.io: https://gocover.io/github.com/shomali11/gridder

**Make sure that you've checked the boxes below before you submit PR:**
- [X] I have added my package in alphabetical order.
- [X] I have an appropriate description with correct grammar.
- [X] I know that this package was not listed before.
- [X] I have added pkg.go.dev link to the repo and to my pull request.
- [X] I have added goreportcard link to the repo and to my pull request.
- [X] I have added coverage service link to the repo and to my pull request.
- [X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: False

**Comment by panjf2000** [comment]
missing code coverage.

**Comment by shomali11** [comment]
@panjf2000 Added gocover link

**Comment by panjf2000** [comment]
Your code coverage is too low (27.1%), the minimum we request is 80%, so please add more unit tests to increase it.

**Comment by shomali11** [comment]
@panjf2000 Done. Improved it to be over 90%

**Pull request merged**
