### PR TITLE
Add Pirsch

### PR DESCRIPTION
**Pull request by Kugelschieber**
- github.com repo: https://github.com/pirsch-analytics/pirsch
- pkg.go.dev: https://pkg.go.dev/github.com/emvi/pirsch
- goreportcard.com: https://goreportcard.com/report/github.com/pirsch-analytics/pirsch
- coverage service link: https://app.circleci.com/pipelines/github/pirsch-analytics/pirsch/175/workflows/ae90411e-9c1d-4d96-8c94-b7e415f64244/jobs/168 (latest build, **82.7% code coverage**)

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: False

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
review:
- https://goreportcard.com/report/github.com/pirsch-analytics/pirsch#gocyclo
- public coverage link

**Comment by Kugelschieber** [comment]
Hm, it doesn't make much sense to fix the complexity "issues" of these functions. Especially the part in user_agent.go would make it more tedious to work with and potentially slower. I suppose you just look at the report without looking at the code. So you can either trust me that it makes sense to keep them longer or close this PR.

**Comment by avelino** [comment]
> Hm, it doesn't make much sense to fix the complexity "issues" of these functions. Especially the part in user_agent.go would make it more tedious to work with and potentially slower. I suppose you just look at the report without looking at the code?

> This is a descision of the project maintainers, I just made a recommendation.

I didn't see a link from the code coverage system

**Comment by Kugelschieber** [comment]
Oh sorry, I misunderstood that. Code coverage is here on CircleCI: https://app.circleci.com/pipelines/github/pirsch-analytics (83.1% right now).

This is the latest build: https://app.circleci.com/pipelines/github/pirsch-analytics/pirsch/184/workflows/9718d244-4927-4f90-8dd5-3c4d9496795f/jobs/174

**Pull request closed without merging**
