### PR TITLE
Add `water`, a TUN/TAP library

### PR DESCRIPTION
**Pull request by songgao**
- github.com repo: https://github.com/songgao/water
- godoc.org: https://godoc.org/github.com/songgao/water
- goreportcard.com: https://goreportcard.com/report/github.com/songgao/water
- coverage service link: http://gocover.io/github.com/songgao/water

### CODE REVIEW

**Comment by shurcooL** [comment]
LGTM.

**Comment by songgao** [comment]
Hi again! Any idea whether (or what changes need to be made so that) this can be merged?

**Comment by songgao** [comment]
Resolved the conflicts and rebased to master HEAD :D

**Comment by songgao** [comment]
It's been a year :) And not the repo has got 270+ stars. Please consider merging it :)

**Comment by shurcooL** [comment]
It looks like we missed this, sorry about that. There's no reason this shouldn't be merged after it's been reviewed with a LGTM.

I edited your original post to add the links from https://github.com/avelino/awesome-go/blob/master/.github/PULL_REQUEST_TEMPLATE.md (which probably didn't exist back when you made this PR).

**Comment by songgao** [comment]
Thanks for merging and updating the post!

**Pull request merged**
