### PR TITLE
gofal

### PR DESCRIPTION
**Pull request by xxjwxc**
fractional api for Go

Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/xxjwxc/gofal
- godoc.org:https://godoc.org/github.com/xxjwxc/gofal/fractional
- goreportcard.com:https://goreportcard.com/report/github.com/xxjwxc/gofal
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.)
https://gocover.io/github.com/xxjwxc/gofal/fractional

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by xxjwxc** [comment]
> https://github.com/xxjwxc/gofal/blob/master/fractional/fractional.go#L16

Actually, it's a bilingual way. the English translate on
 https://github.com/xxjwxc/gofal/blob/master/fractional/fractional.go#L15

**Comment by xxjwxc** [comment]
> Could you please translate https://github.com/xxjwxc/gofal/blob/master/fractional/fractional.go#L16 ?
> 
> Also, i am not really convinced by your tests. They obviously cover everything, but they do not guarantee that anything is actually working. You should hardcode some examples and check the results your code yields against the results that should come up

I have revised the test file. Please approve it.

**Comment by ceriath** [comment]
I was thinking about doing something like:
```
tmp := Model(1, 2)
tmp2 := Model(1,2)
result := Model(1,1)
actualResult := tmp.Add(tmp2)
if actualResult != result {
    t.Errorf("Expected %s, got %s", result, actualResult)
}
```

So esentially i am asking for a test that actually fails if it the result is not the expected one. Right now, you woud have to manually read and evaluate the test results

**Comment by xxjwxc** [comment]
> I was thinking about doing something like:
> 
> ```
> tmp := Model(1, 2)
> tmp2 := Model(1,2)
> result := Model(1,1)
> actualResult := tmp.Add(tmp2)
> if actualResult != result {
>     t.Errorf("Expected %s, got %s", result, actualResult)
> }
> ```
> 
> So esentially i am asking for a test that actually fails if it the result is not the expected one. Right now, you woud have to manually read and evaluate the test results

I get you mean.

**Comment by xxjwxc** [comment]
> > I was thinking about doing something like:
> > ```
> > tmp := Model(1, 2)
> > tmp2 := Model(1,2)
> > result := Model(1,1)
> > actualResult := tmp.Add(tmp2)
> > if actualResult != result {
> >     t.Errorf("Expected %s, got %s", result, actualResult)
> > }
> > ```
> > 
> > 
> > So esentially i am asking for a test that actually fails if it the result is not the expected one. Right now, you woud have to manually read and evaluate the test results
> 
> I get you mean.

How about this way now?

https://github.com/xxjwxc/gofal/blob/master/fractional/fractional_test.go

**Comment by ceriath** [comment]
yes, thanks!

**Comment by kirillDanshin** [comment]
@xxjwxc could you please also update this test? https://github.com/xxjwxc/gofal/blob/master/fractional/fractional_test.go#L56
you still need to check results manually there

**Comment by xxjwxc** [comment]
> @xxjwxc could you please also update this test? https://github.com/xxjwxc/gofal/blob/master/fractional/fractional_test.go#L56
> you still need to check results manually there

Yes, it's missing. It's been added.

**Pull request merged**
