### PR TITLE
Add covergates - Self-hosted code coverage report review and management service

### PR DESCRIPTION
**Pull request by blueworrybear**
**Required links to:**

- github.com repo: https://github.com/covergates/covergates
- pkg.go.dev: https://pkg.go.dev/github.com/covergates/covergates
- goreportcard.com: https://goreportcard.com/report/github.com/covergates/covergates
- coverage service link : https://covergates.com/report/github/covergates/covergates

[card](https://covergates.com/report/github/covergates/covergates)

> I'm a new coverage service =)

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: False

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by avelino** [comment]
@blueworrybear great software, how about developing a github bot to put badge (image) with the percentage of coverage of each PR made in awesome-go? We can support with server (infra structure) to run the service

automatically identify the repository URL (in the PR text) and generate a comment made by the bot containing the image.

**Comment by blueworrybear** [comment]
@avelino Thank you! I think it's a great idea. I would like to build a GitHub Bot for it. It would also be great if we could work together to make an awesome Go project! 😎

**Comment by blueworrybear** [comment]
> review pls

@avelino 

I have fixed the error. It seems like I miss `.` at the end of description.

Thanks for the review!

**Pull request merged**
