### PR TITLE
gowp

### PR DESCRIPTION
**Pull request by xxjwxc**
gowp is concurrency limiting goroutine pool.

Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/xxjwxc/gowp
- godoc.org:https://godoc.org/github.com/xxjwxc/gowp/workpool
- goreportcard.com:https://goreportcard.com/report/github.com/xxjwxc/gowp
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.)
https://gocover.io/github.com/xxjwxc/gowp/workpool

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@xxjwxc please translate docs and repo description to english.

**Comment by ceriath** [comment]
@kirillDanshin it actually is. its just bilingual

**Comment by kirillDanshin** [comment]
@ceriath actually, as I can see, the repo description used as the github tags, and godoc is actually quite hard to read in cases like this: https://godoc.org/github.com/xxjwxc/gowp/workpool#New

**Comment by xxjwxc** [comment]
has been revised into English.

**Comment by xxjwxc** [comment]
> @xxjwxc please translate docs and repo description to english.

has been revised into english.

**Comment by kirillDanshin** [comment]
@xxjwxc can you please also fix your comments format? don't forget the space between `//` and the first character on the line, this syntax is reserved and should be used only for comments like `//go:linkname`, `//nolint` and so on.

**Comment by xxjwxc** [comment]
> @xxjwxc can you please also fix your comments format? don't forget the space between `//` and the first character on the line, this syntax is reserved and should be used only for comments like `//go:linkname`, `//nolint` and so on.
how about right now?

**Comment by xxjwxc** [comment]
> @xxjwxc can you please also fix your comments format? don't forget the space between `//` and the first character on the line, this syntax is reserved and should be used only for comments like `//go:linkname`, `//nolint` and so on.

how about right now ?

**Comment by kirillDanshin** [comment]
@xxjwxc you still have them https://github.com/xxjwxc/gowp/blob/master/workpool/workpool.go#L100

**Comment by xxjwxc** [comment]
> @xxjwxc you still have them https://github.com/xxjwxc/gowp/blob/master/workpool/workpool.go#L100

how about right now ?

**Comment by kirillDanshin** [comment]
@xxjwxc I meant that you still have `//abc` comments instead of `// abc`, I'm not against bilingual comments inside the sources :)

**Comment by xxjwxc** [comment]
> @xxjwxc I meant that you still have `//abc` comments instead of `// abc`, I'm not against bilingual comments inside the sources :)

sorry , It's all right now.

**Comment by xxjwxc** [comment]
thx.

**Pull request merged**
