### PR TITLE
Add zenity

### PR DESCRIPTION
**Pull request by ncruces**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/ncruces/zenity
- pkg.go.dev: https://pkg.go.dev/github.com/ncruces/zenity
- goreportcard.com: https://goreportcard.com/report/github.com/ncruces/zenity
- coverage service link: https://gocover.io/github.com/ncruces/zenity

Very good coverage:
Automated coverage is bellow 80%. Good coverage (~100%) of the bits that are easier to *unit* test, and not that great elsewhere. Testing strategy is to add scripted tests that require specific user interaction, but those won't change automated coverage numbers.

Stable or progressing toward stable:
Progressing toward stable. API broke once in the history of project. But as long as there's significant [missing functionality](https://github.com/ncruces/zenity/issues/11), it seems wrong to tag v1.

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
review:
- cover >= 85%
- golint - this is a great number, but it can improve

**Comment by ncruces** [comment]
Thanks for the review.

I've worked on coverage a bit, but as I've noted above, useful, automated, coverage is hard to achieve here, particularly on CI. Ultimately, testing this package requires user interaction and a GUI.

BTW, running `go test -cover` on a Linux GUI environment with [`zenity`](https://help.gnome.org/users/zenity/) installed, and gives me 95% coverage already, whereas on [gocover.io](https://gocover.io/github.com/ncruces/zenity) it's 84% because it lacks a GUI.

As for `golint`, on [goreportcard.com](https://goreportcard.com/report/github.com/ncruces/zenity), I disagree with those 2 findings (but fixed the 3rd one). For some if statements, I like to keep if and else balanced, and that's the case here.

As I've said in the OP, I'll keep working on a testing regime. My plan is to create scripted tests that require the user to do a specific action, and then validate the result, run them on all 3 supported platforms before each tag. I already do this, but not as systematically. This, however, won't change automated coverage results on CI. Getting there would require complex GUI scripting, and CI infrastructure that I don't have, and I think my time is better spent elsewhere on this project.

If the 85% coverage is a hard rule, I'm afraid I won't be able to meet that bar. Feel free to close this, then.

**Comment by ncruces** [comment]
To be clear, this is what I mean for a scripted test:

https://github.com/ncruces/zenity/blob/7cceddda042a543dd9bd0f8d6d6a7809963e1225/color_test.go#L58-L81

I ask the user to do a certain action, and validate the result. On CI this bails on the `skip(err)` line, because there's no `zenity` and no `DISPLAY`, and I may eventually put this behind a flag, because they're tedious to run. But I do run them before a release, and I really don't think the investment of making something like this work headless is worth it at this point.

And obviously, if I do `go test -cover` locally with a GUI, coverage is higher than [gocover.io](https://gocover.io/github.com/ncruces/zenity).

**Pull request merged**
