### PR TITLE
add jfcg/sorty

### PR DESCRIPTION
**Pull request by jfcg**
- github.com repo: https://github.com/jfcg/sorty
- godoc.org: https://godoc.org/github.com/jfcg/sorty
- goreportcard.com: https://goreportcard.com/report/github.com/jfcg/sorty

On coverage: Please see *Parameter Tuning* part in sorty repo readme file. Tests take a long time and most files are identical, differeing in the data type of a slice to sort.

- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: True
- goreportcard.com: True
- coverage: False

**Comment by jfcg** [comment]
- short tests take 20 min, normal tests (for tuning parameters) take over an hour. gocover.io times out.
- for example, sortyF4.go and sortyF8.go differ only in the sorted slice's type.
- So effective coverage is %100

**Comment by jfcg** [comment]
Just released v0.4.3, improving tests & coverage.
`go test -short -timeout 1h -coverprofile sorty.cover` reports %93.4 coverage

**Comment by panjf2000** [comment]
Please resolve https://goreportcard.com/report/github.com/jfcg/sorty#ineffassign

**Comment by jfcg** [comment]
resolved, please see v0.4.5

**Pull request merged**
