### PR TITLE
Create Build Automation category and add taskflow

### PR DESCRIPTION
**Pull request by pellared**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/pellared/taskflow
- pkg.go.dev: https://pkg.go.dev/github.com/pellared/taskflow
- goreportcard.com: https://goreportcard.com/report/github.com/pellared/taskflow
- coverage service links: https://gocover.io/github.com/pellared/taskflow , https://codecov.io/gh/pellared/taskflow 

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by phanirithvij** [comment]
@pellared I think it can be added under Go Tools https://github.com/avelino/awesome-go#go-tools

cc: @avelino

**Review by phanirithvij — CHANGES_REQUESTED** [review]
@pellared I think it can be added under [Go Tools](https://github.com/avelino/awesome-go#go-tools) instead of uncategorized.

cc: @avelino

Once resolved, will merge.

**Comment by avelino** [comment]
**Data Structures**, works well

**Comment by pellared** [comment]
Moved under **Data Structures**

**Comment by phanirithvij** [comment]
@avelino
- `mmake - Modern Make.` is under `Utilities`
- https://go-gilbert.github.io `Build system and task runner for Go projects.` is under `Go tools`

Shouldn't this be in Go tools or Utilities?
Why Data Structures?

**Comment by pellared** [comment]
@phanirithvij @avelino 
I find that Go Tools/utils are CLI apps. Taskflow is a library to help building tiny programs that run a build pipeline. Therefore I find it as a not good category.

I am also not sure if Data Structure is a good category b/c I would suspect other stuff in there. 

Maybe it would be good to create a new category which would contain stuff like make, mage. taskflow, gorealeser named e.g. **Build automation**?

**Comment by avelino** [comment]
I think the **"Build Automation"** category is important, having more than 3 libraries we can create.

@pellared do you send this update?

**Comment by pellared** [comment]
@avelino
I updated the PR.
I also added https://github.com/magefile/mage as well as from my experience it is quite popular and worth adding to the list.

**Comment by avelino** [comment]
@pellared split in 2 PR
- add taskflow + create topic **Build Automation**
- add Mage

Why?
the test coverage is not working https://gocover.io/github.com/magefile/mage

**Comment by pellared** [comment]
@avelino 
Done

**Pull request merged**
