### PR TITLE
adding keel

### PR DESCRIPTION
**Pull request by rusenask**
Hello, adding Keel to the DevOps tools list! 

Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/rusenask/keel
- godoc.org: https://keel.sh/user-guide/ since this is a tool rather than library - Godoc doesn't make sense. 
- goreportcard.com: https://goreportcard.com/report/github.com/rusenask/keel (A+)
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `cover.run go`

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [N/A] I have added godoc link to the repo and to my pull request - There is a separate documentation website available at https://keel.sh/user-guide/
- [N/A] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by rusenask** [comment]
Hey, thanks for reviewing. I will update golint errors because it's just good hygiene but I am reluctant regarding `gofmt -s` as it doesn't even show why it is angry. I am using goreturns which in turn uses gofmt and goimports.

**Comment by rusenask** [comment]
Whatever I do it's not happy about those go:generate tags :(
```
//go:generate jsonenums -type=Notification
//go:generate jsonenums -type=Level
//go:generate jsonenums -type=PolicyType
//go:generate jsonenums -type=TriggerType
```
screen shot 2017-08-08 at 21 50 05

**Comment by rusenask** [comment]
@cassiobotaro could you comment on this one?

**Comment by cassiobotaro** [comment]
@rusenask add a blank line before package statement.
I see many errors on gofmt, also take a look please.

**Comment by avelino** [comment]
https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers

**Pull request closed without merging**
