### PR TITLE
Add google wire library

### PR DESCRIPTION
**Pull request by dsxack**
Compile-time Dependency Injection for Go

- github.com repo: https://github.com/google/wire
- godoc.org: https://godoc.org/github.com/google/wire
- goreportcard.com: https://goreportcard.com/report/github.com/google/wire
- coverage service link: https://codecov.io/gh/google/wire

Very good coverage

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [ ] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: True
- goreportcard.com: True
- coverage: True

**Comment by dsxack** [comment]
@panjf2000, I'm sorry. But it is google library, and I think it is too hard to increase its coverage. I think the goal does not justify the effort.

But. I start this PR only because I find in list another library with the name `wire` for the same `Dependency injection` section. But this library event doesn't have tests.

I think google's `wire` library is much better than the wire library in your list. Maybe I should send PR to remove the `wire` library from your list?

**Comment by panjf2000** [comment]
I appreciate your proposal but every repo in awesome-go list should be up to standard, even though it is from google.

So I'm closing this PR but still, thanks for your efforts.

**Comment by dsxack** [comment]
It is sad. The list of libraries that don't contain popular libraries because of too strict standards. 

It is non-sense. Thank you.

**Comment by MihailsKuzmins** [comment]
I would also like to have the Google's [wire](https://github.com/google/wire) on the list instead. It would help to get to know libraries which are used in the community most 🤔

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by panjf2000** [comment]
Reopen this PR to discuss whether we should make exceptions for those repositories with more stars regardless of our standards.

**Comment by avelino** [comment]
> Reopen this PR to discuss whether we should make exceptions for those repositories with more stars regardless of our standards.

@panjf2000 was discussed in this issue #1446

in short, star is not synonym of quality

**Comment by MihailsKuzmins** [comment]
> > Reopen this PR to discuss whether we should make exceptions for those repositories with more stars regardless of our standards.
> 
> @panjf2000 was discussed in this issue #1446
> 
> in short, star is not synonym of quality

But is it obvious that Google's wire is used more often than the wire in the current list. In this case it would be more beneficial for developers to get to know the Google's wire. Especially taking into account that their approach is much different than that of Fx or Inject. I doubt that Google would write a library which does not comply with good practices

**Comment by avelino** [comment]
sad

Screen Shot 2021-09-20 at 17 33 29

@MihailsKuzmins I'm willing to talk to the package maintainers and listen to what they have to say, the communication channel via issue is open for this

**Comment by MihailsKuzmins** [comment]
@avelino thank you for not giving up 🙏
I do understand your drive to have only the best packages in the list (it's a good one, no doubt), but I simply want this package to be in the list because of its unique approach to DI (all other packages implement it with `"reflect"`). So I think other developers might also be interested in it (again repeating myself, sorry...)
Well, it's not that much about starts the project has

**Pull request closed without merging**
