### PR TITLE
google-play-scraper

### PR DESCRIPTION
**Pull request by n0madic**
**Please provide package links to:**

* https://github.com/n0madic/google-play-scraper
* https://godoc.org/github.com/n0madic/google-play-scraper/pkg
* https://coveralls.io/github/n0madic/google-play-scraper
* [Go Report Card](https://goreportcard.com/report/github.com/n0madic/google-play-scraper)

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: True
- goreportcard.com: True
- coverage: True

**Comment by n0madic** [comment]
please review again

**Comment by appleboy** [comment]
@n0madic What is code coverage of the repo?

**Comment by n0madic** [comment]
Hmm, gocover.io don't support multi-package repo...
Add coveralls link
[Coverage Status](https://coveralls.io/github/n0madic/google-play-scraper?branch=master)
P.S. Since the test takes place on a live Google Play website, errors are not covered in cases of successful passing

**Comment by n0madic** [comment]
Coverage increased to 80%
https://coveralls.io/github/n0madic/google-play-scraper

**Pull request merged**
