### PR TITLE
feat: add minima in framework section

### PR DESCRIPTION
**Pull request by apoorvcodes**
> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc): https://github.com/gominima/minima
- pkg.go.dev: https://pkg.go.dev/github.com/gominima/minima
- goreportcard.com:https://goreportcard.com/report/github.com/gominima/minima
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.):https://gocover.io/github.com/gominima/minima

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below before you submit PR:**
_not every repository (project) will fit into every option, but most projects should_

- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by apoorvcodes** [comment]
@avelino Is there any problem during review, as the pr is still isn't merged

**Review by avelino — CHANGES_REQUESTED** [review]
Review:
- coverage: `Cannot get 'github.com/gominima/minima'`
- Golint

**Comment by apoorvcodes** [comment]
Aah okay, idk why isnt gocover working any fixes?

**Comment by phanirithvij** [comment]
@apoorvcodes you can try codecov or coveralls. Which are both free for public projects but requires GitHub oauth.

**Comment by phanirithvij** [comment]
Coverage seems to be only `23.17%`.
I enabled codecov on my fork to check coverage. https://app.codecov.io/gh/phanirithvij/minima
Please open a new PR when coverage reaches the required `> 80%` as per awesome-go [quality standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).

**Pull request closed without merging**
