### PR TITLE
Add Gowl to the Goroutines list

### PR DESCRIPTION
**Pull request by hamed-yousefi**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/hamed-yousefi/gowl
- pkg.go.dev: https://pkg.go.dev/github.com/hamed-yousefi/gowl
- goreportcard.com: https://goreportcard.com/report/github.com/hamed-yousefi/gowl
- coverage service link: https://app.codecov.io/gh/hamed-yousefi/gowl

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by hamed-yousefi** [comment]
> Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.
> 
> Automation body links content check:
> 
>     * godoc.org or pkg.go.dev: True
> 
>     * goreportcard.com: True
> 
>     * coverage: True
> 
> 
> > your project is about to be approved, it's under revision, _it may take a few days_

I have no idea why Travis build failed. I added a line to the readme file. Please let me know if I should change anything.

**Comment by avelino** [comment]
Awesome-Go has automated test to validate that your link is in alphabetical order 

Have you read the backtrace? It reports the error there:

```
=== RUN   TestAlpha/Tools_for_managing_and_working_with_Goroutines.
317    repo_test.go:109: expected 'gowl' but actual is 'goworker'
318    repo_test.go:109: expected 'goworker' but actual is 'gowl'
319    repo_test.go:113: expected order is:
320        ants
321        artifex
322        async
323        async
324        breaker
325        channelify
326        concurrency-limiter
327        conexec
328        cyclicbarrier
329        go-floc
330        go-flow
331        go-tools/multithreading
332        go-trylock
333        go-waitgroup
334        go-workers
335        goccm
336        gohive
337        gollback
338        gowl
339        goworker
340        gowp
341        gpool
342        grpool
343        hands
344        hunch
345        kyoo
346        neilotoole/errgroup
347        nursery
348        oversight
349        parallel-fn
350        pond
351        pool
352        queue
353        routine
354        semaphore
355        semaphore
356        stl
357        threadpool
358        tunny
359        worker-pool
360        workerpool
```

**Comment by hamed-yousefi** [comment]
Oh, sorry, I didn't see `goworker` there. So, my item must be above it. 

Thx @avelino

**Review by avelino — APPROVED** [review]
congratulations on the quality of the code - you positively surprised me, it was a pleasure to review your contribution 🥇

**Pull request merged**
