### PR TITLE
Add Gebug

### PR DESCRIPTION
**Pull request by moshebe**
Gebug - A tool that makes debugging of Dockerized Go applications super easy by enabling Debugger and Hot-Reload features, seamlessly.

Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/moshebe/gebug
- pkg.go.dev: https://pkg.go.dev/github.com/moshebe/gebug?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/moshebe/gebug
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/moshebe/gebug

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [V] I have added my package in alphabetical order.
- [V] I have an appropriate description with correct grammar.
- [V] I know that this package was not listed before.
- [V] I have added pkg.go.dev link to the repo and to my pull request.
- [V] I have added coverage service link to the repo and to my pull request.
- [V] I have added goreportcard link to the repo and to my pull request.
- [V] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

**Comment by moshebe** [comment]
Hi @avelino, thanks for the feedback!
I just fixed the issues you mentioned, you can take a look on the documentation also here:
https://godoc.org/github.com/moshebe/gebug

Please let me know if there need to add/change anything else

**Comment by moshebe** [comment]
Hi @avahidi,
Just following up to make sure you noticed the fixes I've done.
Thanks!

**Comment by avelino** [comment]
sorry, had missed updating this thread, thanks for charging me

**Pull request merged**
