### PR TITLE
add orm

### PR DESCRIPTION
**Pull request by posener**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/posener/orm
- godoc.org: https://godoc.org/github.com/posener/orm
- goreportcard.com: https://goreportcard.com/report/github.com/posener/orm
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `cover.run go`

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by posener** [comment]
Hi @cassiobotaro 
Thanks for the feedback.
Since this repository is mainly code generation, the coverage of the test as shown in a coverage report will not fulfill the required.
Most of the tests are end-to-end tests with the 3 supported database, and on generated code. Which will not be shown in a coverage report.
Do you have any advice?
Thanks

**Comment by posener** [comment]
@cassiobotaro , any advice?

**Comment by posener** [comment]
@cassiobotaro I think you miss understood.
The generated code is tested - with 3 different real database.
The generating code is the one that is not tested.

**Comment by jtemporal** [comment]
Hi @posener 
> The generating code is the one that is not tested.

That's what needs to change. The "generating code" also needs testing. Maybe you can mock the database interactions where needed. :wink:

**Comment by posener** [comment]
I think you don't understand.
The library has two parts: "runtime" which is tested, but most of it is code that generates code, which has some tests. But most of the tests are on the generated code itself.
Let's say you had a code that generates a function. Then the way to test is is not to check the text of the generated code itself, but that the generated function is covered sufficiently. Unfortunately the generated function is not committed to git, so you don't have the coverage on it.
I think that there are plenty of tests in the repository (Lot's of generated code for different struct, different functionality, and different databases) but they don't add up to a coverage report.

**Comment by avelino** [comment]
Not cover tests: https://gocover.io/github.com/posener/orm

**Comment by posener** [comment]
@avelino sorry to see you closing the PR, please see my comments above
This is not that the repository is not tested - it is how it is tested.

**Pull request closed without merging**
