### PR TITLE
Add go-resty library under Utilities.

### PR DESCRIPTION
**Pull request by jeevatkm**
Kindly have a look and add to the list, thanks.

### CODE REVIEW

**Comment by jeevatkm** [comment]
I have checked the build, it failing incorrectly. Library name is `resty`, it assumes as 'rerun' library. Please check. 

Build log:
```
2016/01/18 17:29:33 expected 'rerun' but actual is 'resty'
2016/01/18 17:29:33 expected 'resty' but actual is 'rerun'
````

**Comment by dukex** [comment]
@jeevatkm The log is about alphabetical order, please fix it to fix tests

**Comment by jeevatkm** [comment]
My bad, couldn't figure out issue is alphabetical order. Let me have a look, thanks.

**Comment by jeevatkm** [comment]
I have corrected it.

**Comment by matrixik** [comment]
When you have some time fix this, please:
http://goreportcard.com/report/go-resty/resty

Merging. Thank you.

**Comment by jeevatkm** [comment]
@matrixik Taken care, thanks.

**Pull request merged**
