### PR TITLE
Adding YANFF

### PR DESCRIPTION
**Pull request by aregm**
Hi again,
Adding a link to the YANFF - Yet Another Network Function Framework to the awesome-go. Framework for creating cloud native network scalable network functions.

- github.com repo: https://github.com/intel-go/yanff
- godoc.org: https://godoc.org/github.com/intel-go/yanff
- goreportcard.com: [Go Report Card](https://goreportcard.com/report/github.com/intel-go/yanff)
- coverage service link - This is a framework, it has external dependencies for the successful build, which cannot be done online. 

- [X] I have added my package in alphabetical order.
- [X] I have an appropriate description with correct grammar.
- [X] I know that this package was not listed before.
- [X] I have added godoc link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request. - cannot be done by coverage tool online
- [X] I have added goreportcard link to the repo and to my pull request.
- [X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by appleboy** [comment]
screen shot 2017-09-11 at 10 30 54 pm

**Comment by aregm** [comment]
@appleboy Can you be more specific?

**Comment by aregm** [comment]
@avelino What did your colleague mean?

**Comment by cassiobotaro** [comment]
@aregm many errors on go vet
image

**Comment by aregm** [comment]
@cassiobotaro Answered in the issue: "This is a feature of the project and not a flaw or some mistake. We are using unsafe memory to manipulate C memory from Go, modifying what pointer refers to without copying for performance reasons. It cannot be done in a "Go way" without copying and any other method also implies some copy. We know exactly what we are doing. And go_vet is kind of recommendation and not a rule. So if go_vet is a stopper for being included - fine."

**Comment by appleboy** [comment]
@aregm Thanks for your explanation.

**Comment by aregm** [comment]
Thanks!

**Pull request merged**
