### PR TITLE
Add goven

### PR DESCRIPTION
**Pull request by majolo**
> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc): https://github.com/SeldonIO/goven
- pkg.go.dev: https://pkg.go.dev/github.com/seldonio/goven@v0.2.1
- goreportcard.com: https://goreportcard.com/report/github.com/seldonio/goven
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/SeldonIO/goven

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below that apply before you submit PR.**
_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines for detials._

- [x] The package has been added to the list in alphabetical order.
- [x] The package has an appropriate description with correct grammar.
- [x] As far as I know, the package has not been listed here before.
- [x] The repo documentation has a pkg.go.dev link.
- [x] The repo documentation has a coverage service link.
- [x] The repo documenation has a goreportcard link.
- [x] The repo has a version-numbered release and a go.mod file.
- [x] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines), [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers) and [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).
- [x] The repo has a continuous integration process that automatically runs tests that must pass before new pull requests are merged.
- [x] The authors of the project do not commit directly to the repo, but rather use pull-requests that run the continuous-integration process.

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by spekary** [comment]
This looks like a very interesting project. However, your documentation is incomplete. All public functions and types should have a documentation header that will correctly describe the item at go.pkg.dev. You should strongly consider package level documentation too for your subdirectories. Also, please complete the TODO: items that are appearing in your documentation.

**Comment by majolo** [comment]
Thanks for your response @spekary. I'll work to fix those gaps in the documentation and TODOs as soon as I can. I'll update you when those are completed and hopefully we can merge this!

**Comment by spekary** [comment]
Looking better.

The parser package should either have a package description, or if those functions are really not meant to be publicly used, you could put them behind an "internal" directory to hide them from documentation. I couldn't tell whether you really wanted to expose the guts of your parse engine for use by others.

**Comment by majolo** [comment]
The Parser is intended to be exposed to allow for other users to build an adaptor for another "backend". Right now we only support conversion of the AST from the Parser to SQL but you could use it to generate PromQL or Elastic Query Language for example.

Perhaps I misunderstand your request but there is package level description for the Parser:

Screenshot 2022-04-13 at 1 03 38 pm

**Comment by spekary** [comment]
I was looking at the wrong branch. For some reason, go.pkg.dev is not picking up your latest branch. You should try to fix that, but I will approve this.

**Comment by majolo** [comment]
Yes I noticed that and am looking into it, it shows up but not as "latest" for some reason. Thanks!

**Pull request merged**
