### PR TITLE
Re-add Iris

### PR DESCRIPTION
**Pull request by kataras**
I think you have to undo your previous commit, @dlsniper read your article's julien's comments and I hope you will understand... if not just close this PR, I will still no have any problem with you.

### CODE REVIEW

**Comment by appleboy** [comment]
You still editing git history to be only contributor while closing users' pull requests is really bad idea.

**Comment by kataras** [comment]
Who did a PR which actually used inside Iris, except me ? 

You saw some old PRs from version 1 when iris was based onnet/http , (iris is v4 based on fasthtttp), **none of the (3) PRS with less than 5 lines of code exists in the project**, please think clear, the clear history happens because I had local issues with my git but this is not point, I develop iris for more than 7 months alone and you can see it if you want to .

**Comment by kataras** [comment]
@appleboy  Who did a PR which actually used inside Iris, except me ? saw me the code please. 

I'm getting very good messages every day from the Go Community, how I manage my project is up to me I think, So far I didn't disappointed the iris users

**Comment by kirillDanshin** [comment]
@kataras damn, do you really can't understand that you have huge community and only reasons of `I develop iris for more than 7 months alone` are that you're closing PRs, editing git history, editing issues and comments and removing third-party licenses? there is NO another reasons. and **`none of the (3) PRS with less than 5 lines of code exists in the project`** is **NEVER** be a reason to remove commit author from git history. and we all using git *every day* and we still smart enough to see that you editing git history and it can't be a `local issues with my git`.

**Comment by kataras** [comment]
You are locking conversions, you can't speak to me with that tune, please, think clear what you say to me... I just love to code and I'm doing that great,... I am not editing the git, that happens once before months because of my local git issues... show me code please that is written by PR and not written by me.

**Comment by kataras** [comment]
Anyway, I am starting to think an iris fans told me this morning, that you are just hating, you have no logical criteria, you even don't see the repo and commenting and spreading lies..

**Comment by appleboy** [comment]
https://github.com/kataras/iris/pull/56
https://github.com/kataras/iris/pull/33
https://github.com/kataras/iris/pull/29
https://github.com/kataras/iris/pull/28
https://github.com/kataras/iris/pull/8
https://github.com/kataras/iris/pull/11
https://github.com/kataras/iris/pull/12

But **only one contributor** in https://github.com/kataras/iris/graphs/contributors page.

**Comment by kirillDanshin** [comment]
Really? I'm locked that conversation because it was merged and all discussion needs a new issue or PR. what you can say about, for example, kataras/iris#219 and kataras/iris#230?
also I did used iris before. than I got a panic inside, start looking in issues and I saw that issues. it really means that you do not respect contributors and iris' users. and it isn't awesome. you've ignored the licenses *twice* and it means that you did it specially.

**Comment by kataras** [comment]
Show me the CODE, not the PRs FROM VERSION 1 NET/HTTP... you just don't know what you say and fetching old things....

**Comment by kirillDanshin** [comment]
even if the code isn't there, git history will stay with their names and commits, not yours.

**Comment by kataras** [comment]
@kirillDanshin If you saw the f*... LICENSE you should saw these names inside it but you didn't.

**Comment by dlsniper** [comment]
@kataras I've sent that PR because this commit: https://github.com/kataras/iris/commit/5c98c5a493198adb3d5cd05e12ebc89e6a0884b3#diff-9879d6db96fd29134fc802214163b95aL23 basically removed those third-party licenses (again).
Also from the git history it shows that some people did manage to get their PRs merged but you still denied them the contribution on how the project by flattening the history and not naming them.
Just disable the PRs section if you don't want people to send PRs to any of your projects.
But given how you conduct yourself here, it seems I was right about the project leadership.

I truly am sorry that for all the efforts you are putting in the project you cannot understand simple, basic, requirements. And this time around you cannot blame English on this, like it happened last time.

**Comment by kirillDanshin** [comment]
@kataras I saw the `f*...` LICENSE and I saw these names WAS NOT inside and of course I didn't because you've added it only 17 hours ago.

**Comment by kirillDanshin** [comment]
awesome. @kataras is now @geramaro. fukken awesome.

**Comment by dlsniper** [comment]
@kirillDanshin I think that's the point, he will not play by the rules unless he's called upon. The article he's referring to seems to have been read by a few people and it seems he would do anything to have a good image / stars on Github but otherwise wouldn't care.

From my point of view I think that we've just witnessed how the ecosystem was just broken by the latest rename of @kataras -> to @geramaro and this makes it too unstable to be used in any public usage.

@kirillDanshin if he cannot use a nice language, please don't go down to his level. Thank you.

**Comment by kataras** [comment]
Are you both idiots?

**Comment by kirillDanshin** [comment]
he almost fuck'd up a huge number of applications with their rename. he's back again.

**Comment by kataras** [comment]
You are...

**Comment by dlsniper** [comment]
@kirillDanshin Please lock up the conversation, this is going nowhere, fast.

**Comment by dlsniper** [comment]
and I would not be called names. If you can't have the decency to have a normal dialog, them I'm out.

**Comment by kirillDanshin** [comment]
yep, we're all saw this. thanks, iris now banned. good bye, @kataras.
@appleboy, @dlsniper thanks.

**Comment by kataras** [comment]
@dlsniper Read your posts on your articles please, your article is a failure and full of  lies as here

**Pull request closed without merging**
