### PR TITLE
Added levenshtein to Data Structures

### PR DESCRIPTION
**Pull request by agnivade**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

Please provide package links to:
- godoc.org: http://godoc.org/github.com/agnivade/levenshtein
- goreportcard.com: https://goreportcard.com/report/agnivade/levenshtein
- gocover.io: https://gocover.io/github.com/agnivade/levenshtein

Note, that new categories can be added only when there are 3 packages or more.

Make sure that you've checked the boxes below before you submit PR:
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link
- [x] I have added gocover.io link
- [x] I have added goreportcard link
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by jaytaylor** [comment]
Cool package @agnivade, FWIW LGTM!

**Comment by agnivade** [comment]
@jaytaylor  :smile:

**Comment by kirillDanshin** [comment]
@agnivade thanks!

**Pull request merged**
