### PR TITLE
Add lesismal/arpc

### PR DESCRIPTION
**Pull request by lesismal**
Arpc is a high-performance rpc package and more effective network communication support two-way-calling, notify, broadcast.

**Please provide package links to:**

- github.com repo: https://github.com/lesismal/arpc
- pkg.go.dev: https://pkg.go.dev/github.com/lesismal/arpc?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/lesismal/arpc
- coverage service link: https://codecov.io/gh/lesismal/arpc

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

**Comment by lesismal** [comment]
> check:
> 
> * test coverage should be >= 80% - https://codecov.io/gh/lesismal/arpc
> * go fmt is acceptable, but I know you can improve https://goreportcard.com/report/github.com/lesismal/arpc#gofmt
> 
> pls read: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards

done for coverage and go fmt, plz see it again, tks!

found that the Test func generated by vsc's plugin gets warn from goreport's  "gofmt -s", I would write the func body all by myself next time.

**Comment by lesismal** [comment]
> This PR has been automatically marked as closed because it has not had recent activity. They will wait 15 days for your interaction, after that the PR will be closed. Please read more in https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md

so, what should I do for the next?

**Comment by avelino** [comment]
@lesismal 
Screen Shot 2020-09-17 at 6 41 02 AM

- test coverage should be >= 80% - https://codecov.io/gh/lesismal/arpc

**Comment by lesismal** [comment]
> @lesismal
> Screen Shot 2020-09-17 at 6 41 02 AM
> 
> * test coverage should be >= 80% - https://codecov.io/gh/lesismal/arpc

codecov

I'm a little confused, what's the difference between "Line Coverage" and "Project Totals".

**Comment by avelino** [comment]
Strange, can you understand what is happening with your project so that this coverage reflects on the sum above the coverage systems?

**Comment by lesismal** [comment]
> Strange, can you understand what is happening with your project so that this coverage reflects on the sum above the coverage systems?


I don't know what happened. I used to look at the "Project Totals" result  and didn't notice that "Line Coverage" before.
I tried to delete the previous coverage data, now the "Line Coverage" disappeared but "Project Totals" is still there. I'm wondering how to generate the "Line Coverage" again :rofl:.

**Comment by lesismal** [comment]
image

well, it's OK now, maybe it's a bug of codecov.io

**Pull request merged**
