### PR TITLE
remove Non-standard repos

### PR DESCRIPTION
**Pull request by yinggaozhen**
**repo** : https://github.com/robfig/bind
**godoc.org :** https://godoc.org/github.com/robfig/bind
**go report :**  [Go Report Card](https://goreportcard.com/report/github.com/robfig/bind)
**maintenance :** 2014-08-17
**coverage service link :**
 - **coverall.io :** [Coverage Status](https://coveralls.io/github/robfig/bind?branch=master)
 - **gocover.io** : [Test coverage](https://gocover.io/github.com/robfig/bind)
 - **codecov** : [Coverage Status](https://codecov.io/gh/robfig/bind)

**reason for deletion :**

- [ ] : Missing godoc link
- [ ] : Missing the readme
- [x] : Not updated or maintained for too long
- [x] : Test coverage does not meet the requirements
- [ ] : The code quality is not high

_ _ _

**repo** : https://github.com/jyotiska/go-webcolors
**godoc.org :** https://godoc.org/github.com/jyotiska/go-webcolors
**go report :**  [Go Report Card](https://goreportcard.com/report/github.com/jyotiska/go-webcolors)
**maintenance :** 2015-08-21
**coverage service link :**
 - **coverall.io :** [Coverage Status](https://coveralls.io/github/jyotiska/go-webcolors?branch=master)
 - **gocover.io** : [Test coverage](https://gocover.io/github.com/jyotiska/go-webcolors)
 - **codecov** : [Coverage Status](https://codecov.io/gh/jyotiska/go-webcolors)

**reason for deletion :**

- [ ] : Missing godoc link
- [ ] : Missing the readme
- [x] : Not updated or maintained for too long
- [ ] : Test coverage does not meet the requirements
- [x] : The code quality is not high

_ _ _

**repo** : https://github.com/ThePaw/probab
**godoc.org :** https://godoc.org/github.com/ThePaw/probab
**go report :**  [Go Report Card](https://goreportcard.com/report/github.com/ThePaw/probab)
**maintenance :** 2015-09-14
**coverage service link :**
 - **coverall.io :** [Coverage Status](https://coveralls.io/github/ThePaw/probab?branch=master)
 - **gocover.io** : [Test coverage](https://gocover.io/github.com/ThePaw/probab)
 - **codecov** : [Coverage Status](https://codecov.io/gh/ThePaw/probab)

**reason for deletion :**

- [x] : Missing godoc link
- [x] : Missing the readme
- [x] : Not updated or maintained for too long
- [x] : Test coverage does not meet the requirements
- [ ] : The code quality is not high

_ _ _

**repo** : https://github.com/ian-kent/goose
**godoc.org :** https://godoc.org/github.com/ian-kent/goose
**go report :**  [Go Report Card](https://goreportcard.com/report/github.com/ian-kent/goose)
**maintenance :** 2014-12-21
**coverage service link :**
 - **coverall.io :** [Coverage Status](https://coveralls.io/github/ian-kent/goose?branch=master)
 - **gocover.io** : [Test coverage](https://gocover.io/github.com/ian-kent/goose)
 - **codecov** : [Coverage Status](https://codecov.io/gh/ian-kent/goose)

**reason for deletion :**

- [ ] : Missing godoc link
- [ ] : Missing the readme
- [x] : Not updated or maintained for too long
- [x] : Test coverage does not meet the requirements
- [ ] : The code quality is not high

_ _ _

**repo** : https://github.com/rookii/paicehusk
**godoc.org :** https://godoc.org/github.com/rookii/paicehusk
**go report :**  [Go Report Card](https://goreportcard.com/report/github.com/rookii/paicehusk)
**maintenance :** 2013-12-16
**coverage service link :**
 - **coverall.io :** [Coverage Status](https://coveralls.io/github/rookii/paicehusk?branch=master)
 - **gocover.io** : [Test coverage](https://gocover.io/github.com/rookii/paicehusk)
 - **codecov** : [Coverage Status](https://codecov.io/gh/rookii/paicehusk)

**reason for deletion :**

- [ ] : Missing godoc link
- [ ] : Missing the readme
- [x] : Not updated or maintained for too long
- [ ] : Test coverage does not meet the requirements
- [ ] : The code quality is not high

_ _ _

**repo** : https://github.com/aybabtme/portproxy
**godoc.org :** https://godoc.org/github.com/aybabtme/portproxy
**go report :**  [Go Report Card](https://goreportcard.com/report/github.com/aybabtme/portproxy)
**maintenance :** 2014-12-13
**coverage service link :**
 - **coverall.io :** [Coverage Status](https://coveralls.io/github/aybabtme/portproxy?branch=master)
 - **gocover.io** : [Test coverage](https://gocover.io/github.com/aybabtme/portproxy)
 - **codecov** : [Coverage Status](https://codecov.io/gh/aybabtme/portproxy)

**reason for deletion :**

- [x] : Missing godoc link
- [ ] : Missing the readme
- [x] : Not updated or maintained for too long
- [x] : Test coverage does not meet the requirements
- [ ] : The code quality is not high

_ _ _

**repo** : https://github.com/ThePaw/go-gt
**godoc.org :** https://godoc.org/github.com/ThePaw/go-gt
**go report :**  [Go Report Card](https://goreportcard.com/report/github.com/ThePaw/go-gt)
**maintenance :** 2015-09-14
**coverage service link :**
 - **coverall.io :** [Coverage Status](https://coveralls.io/github/ThePaw/go-gt?branch=master)
 - **gocover.io** : [Test coverage](https://gocover.io/github.com/ThePaw/go-gt)
 - **codecov** : [Coverage Status](https://codecov.io/gh/ThePaw/go-gt)

**reason for deletion :**

- [x] : Missing godoc link
- [x] : Missing the readme
- [x] : Not updated or maintained for too long
- [x] : Test coverage does not meet the requirements
- [x] : The code quality is not high

_ _ _

**repo** : https://github.com/rdrdr/hamcrest
**godoc.org :** https://godoc.org/github.com/rdrdr/hamcrest
**go report :**  [Go Report Card](https://goreportcard.com/report/github.com/rdrdr/hamcrest)
**maintenance :** 2011-02-15
**coverage service link :**
 - **coverall.io :** [Coverage Status](https://coveralls.io/github/rdrdr/hamcrest?branch=master)
 - **gocover.io** : [Test coverage](https://gocover.io/github.com/rdrdr/hamcrest)
 - **codecov** : [Coverage Status](https://codecov.io/gh/rdrdr/hamcrest)

**reason for deletion :**

- [ ] : Missing godoc link
- [ ] : Missing the readme
- [x] : Not updated or maintained for too long
- [x] : Test coverage does not meet the requirements
- [x] : The code quality is not high

_ _ _

**repo** : https://github.com/tv42/mockhttp
**godoc.org :** https://godoc.org/github.com/tv42/mockhttp
**go report :**  [Go Report Card](https://goreportcard.com/report/github.com/tv42/mockhttp)
**maintenance :** 2014-10-30
**coverage service link :**
 - **coverall.io :** [Coverage Status](https://coveralls.io/github/tv42/mockhttp?branch=master)
 - **gocover.io** : [Test coverage](https://gocover.io/github.com/tv42/mockhttp)
 - **codecov** : [Coverage Status](https://codecov.io/gh/tv42/mockhttp)

**reason for deletion :**

- [ ] : Missing godoc link
- [ ] : Missing the readme
- [x] : Not updated or maintained for too long
- [x] : Test coverage does not meet the requirements
- [ ] : The code quality is not high

_ _ _

**repo** : https://github.com/zach-klippenstein/goregen
**godoc.org :** https://godoc.org/github.com/zach-klippenstein/goregen
**go report :**  [Go Report Card](https://goreportcard.com/report/github.com/zach-klippenstein/goregen)
**maintenance :** 2016-03-04
**coverage service link :**
 - **coverall.io :** [Coverage Status](https://coveralls.io/github/zach-klippenstein/goregen?branch=master)
 - **gocover.io** : [Test coverage](https://gocover.io/github.com/zach-klippenstein/goregen)
 - **codecov** : [Coverage Status](https://codecov.io/gh/zach-klippenstein/goregen)

**reason for deletion :**

- [ ] : Missing godoc link
- [ ] : Missing the readme
- [x] : Not updated or maintained for too long
- [x] : Test coverage does not meet the requirements
- [ ] : The code quality is not high

_ _ _

**repo** : https://github.com/beyang/hgo
**godoc.org :** https://godoc.org/github.com/beyang/hgo
**go report :**  [Go Report Card](https://goreportcard.com/report/github.com/beyang/hgo)
**maintenance :** 2015-08-25
**coverage service link :**
 - **coverall.io :** [Coverage Status](https://coveralls.io/github/beyang/hgo?branch=master)
 - **gocover.io** : [Test coverage](https://gocover.io/github.com/beyang/hgo)
 - **codecov** : [Coverage Status](https://codecov.io/gh/beyang/hgo)

**reason for deletion :**

- [ ] : Missing godoc link
- [ ] : Missing the readme
- [x] : Not updated or maintained for too long
- [x] : Test coverage does not meet the requirements
- [ ] : The code quality is not high

_ _ _

**repo** : https://github.com/jimrobinson/kvbench
**godoc.org :** https://godoc.org/github.com/jimrobinson/kvbench
**go report :**  [Go Report Card](https://goreportcard.com/report/github.com/jimrobinson/kvbench)
**maintenance :** 2014-04-20
**coverage service link :**
 - **coverall.io :** [Coverage Status](https://coveralls.io/github/jimrobinson/kvbench?branch=master)
 - **gocover.io** : [Test coverage](https://gocover.io/github.com/jimrobinson/kvbench)
 - **codecov** : [Coverage Status](https://codecov.io/gh/jimrobinson/kvbench)

**reason for deletion :**

- [x] : Missing godoc link
- [ ] : Missing the readme
- [x] : Not updated or maintained for too long
- [x] : Test coverage does not meet the requirements
- [ ] : The code quality is not high

_ _ _

### CODE REVIEW

**Comment by kamilsk** [comment]
:fire:

**Comment by ceriath** [comment]
Thanks a lot for doing this! Right now i unfortunately don't have the time to review all of it, but i defintiely will in the next few weeks

**Comment by yinggaozhen** [comment]
> Thanks a lot for doing this! Right now i unfortunately don't have the time to review all of it, but i defintiely will in the next few weeks

En~

**Comment by appleboy** [comment]
Add maintainers @robfig @jimrobinson @beyang @zach-klippenstein @tv42 @rdrdr @ThePaw @jyotiska @ian-ken @rookii @aybabtme

**Comment by tv42** [comment]
Your definition of "standard" used here doesn't seem to match https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md

**Comment by yinggaozhen** [comment]
> Your definition of "standard" used here doesn't seem to match https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md

as [https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md)

> Tests, where practical. If the library/program is testable, then coverage should be >= 80% for non-data-related packages and >=90% for data related packages.

I found out from [gocover. io](https://gocover.io/github.com/tv42/mockhttp) that the current test coverage of your project is 68%, which does not meet the requirements.

**Comment by aybabtme** [comment]
i wonder why portproxy was there in the first place 🤪

**Comment by tv42** [comment]
@yinggaozhen You're missing the part about standard, as in "Non-standard documentation or Missing the readme". Also, please feel to remove everything written by me, these lists are silly.

**Comment by yinggaozhen** [comment]
> @yinggaozhen You're missing the part about standard, as in "Non-standard documentation or Missing the readme". Also, please feel to remove everything written by me, these lists are silly.

This is just something that I think is not very good, not official, so there will be review, it doesn't mean that these projects don't really meet the standards. Being removed doesn't really mean that the project is of poor quality, it just means that some indicators are temporarily not up to the standard. My goal is to promote the project maintainers to update and meet the standard as much as possible, not just to delete. In addition, I think the problem you mentioned is my fault, and I will adjust it. I'm sorry if anything hurt you.

**Comment by aybabtme** [comment]
@yinggaozhen im sure the effort is well meaning, but i think a problem with this approach is that many packages in this list have been added by people who weren't the authors of said package.

as a result, some people might feel it's a bit strange to be brought into a conversation about this, and to be "encouraged" to meet a standard for a list they never intended to join.

**Comment by yinggaozhen** [comment]
@aybabtme

Yes, you're right. I think we can remind the author or the person who submitted it before we remove it. If they don't have enough time to change it, maybe we can remove it from the list, and add it back later when the author has time to fix it

**Comment by tv42** [comment]
@yinggaozhen At this point all I'm hearing is that the "rules" are arbitrary and up to your whims. More evidence that these lists are silly and not "awesome".

**Comment by yinggaozhen** [comment]
@tv42 
You're right, this list doesn't look perfect, it might even make you feel "silly", that's why so many people are thinking about how to improve it and make it awesome(like #1446). of course Including this pull request.

But this PR seems that this has caused a lot of controversy. Maybe there is something wrong with the pull request itself, so I decided to close it for now

**Pull request closed without merging**
