### PR TITLE
Added new go projects

### PR DESCRIPTION
**Pull request by adranwit**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

Please provide package links to:
- godoc.org: 
- goreportcard.com: 
- gocover.io: 

Note, that new categories can be added only when there are 3 packages or more.

Make sure that you've checked the boxes below before you submit PR:
- [X] I have added my package in alphabetical order
- [X] I know that this package was not listed before
- [X] I have added godoc link
- [X] I have added gocover.io link
- [X] I have added goreportcard link
- [X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
?????
godoc.org:
goreportcard.com:
gocover.io:

**Comment by adranwit** [comment]
All links are part of README.md per project:  
Here are the links per project:
toolbox:
godoc.org: https://godoc.org/github.com/viant/toolbox
goreportcard.com:https://goreportcard.com/report/github.com/viant/toolbox
gocover.io: https://gocover.io/github.com/viant/toolbox
dsc:
godoc.org: https://godoc.org/github.com/viant/dsc
goreportcard.com:https://goreportcard.com/report/github.com/viant/dsc
gocover.io: https://gocover.io/github.com/viant/dsc
dsunit:
godoc.org: https://godoc.org/github.com/viant/dsunit
goreportcard.com:https://goreportcard.com/report/github.com/viant/dsunit
gocover.io: https://gocover.io/github.com/viant/dsunit
asc:
godoc.org: https://godoc.org/github.com/viant/asc
goreportcard.com:https://goreportcard.com/report/github.com/viant/asc
gocover.io: https://gocover.io/github.com/viant/asc
bgc:
godoc.org: https://godoc.org/github.com/viant/bgc
goreportcard.com:https://goreportcard.com/report/github.com/viant/bgc
gocover.io: https://gocover.io/github.com/viant/bgc

**Comment by kirillDanshin** [comment]
toolbox, dsc, dsunit, asc, bgc: 
~~wtf~~ what's going on with godoc? there are more license copies than real docs. fix this please. remember that you don't need to include licenses in all of your source files.
also you'll need to fix goreportcard issues.

===

toolbox:
low test coverage (~55%)

===

dsc:
low test coverage too (~60%)

===

dsunit:
very low test coverage (~20%)

===

asc, bgc:
almost untested package (~10%)

===

please fix this issues. thanks.

**Comment by adranwit** [comment]
This packages use actual datastore like mysql, aerospike, or big query 
Most of the test are skipped, unless env variable are set, 
For dsunit: you have to set DB_TEST_PASSWORD, DB_TEST_USER

**Comment by adranwit** [comment]
I'll talk to legal team to see if we can remove license from individual files. So far it has been recommended to include license in each file.

**Comment by kirillDanshin** [comment]
@adranwit you can do it in any another way that will not break godoc. but it's bad [when in 24-line file 18 lines is a license](https://github.com/viant/toolbox/blob/master/predicate.go).
also, your source files gets bigger because of the license that is bad too.
because of the license and `package %s` are not separated by an empty line licenses are parsed as package documentation.
so you need to
1) remove licenses or follow it by an empty line
2) add `Package %s ...` comment before a `package %s` and not follow it by an empty line
3) check that godoc looks right (remember that you can test it with a local godoc copy)
4) setup coveralls with travis (for example) so we can see real test coverage and you can track the build status

**Comment by adranwit** [comment]
What is your acceptable coverage level ?

**Comment by adranwit** [comment]
I have corrected the documentation, and increased significantly test coverage,
you can see real test coverage without travis, I have spin a test instance of aerospike, and  access test bg service

**Comment by adranwit** [comment]
Dump !!!

I have not hear from you for a while, see my last response was Jun23

Here is the latest coverage
toolbox: coverage: 90.0% of statements
dsc: coverage: 71.0% of statements
bgc:coverage: 75.6% of statements
asc: coverage: 83.2% of statements
dsunit:coverage: 74.5% of statements

**Comment by kirillDanshin** [comment]
@adranwit oh! I was shure that I leave a comment here. strange.
minimal coverage level for packages that work with data is 85-90%.

**Comment by adranwit** [comment]
Bump !

Here is the updated test coverage:

toolbox:90.0%
asc:    85.2%
bgc:    86.1%
dsc:    85.6%
dsunit: 85.3%

**Comment by adranwit** [comment]
Yet another Bump !

**Comment by adranwit** [comment]
Yet another Bump !

**Comment by adranwit** [comment]
Yet another Bump !
Two weeks passed and no response, is that typical ?

**Comment by kirillDanshin** [comment]
@adranwit it's typical if I want to test it in my production before merge.

**Comment by adranwit** [comment]
Great to hear it, have you ever consider changing/adding label, "testing in production" ?

**Comment by adranwit** [comment]
Yet another Bump !
What is the typical time range before a project gets reviewed,
 are we talking about weeks, months, 3 months+,  6 months+, years+ ?

**Comment by kirillDanshin** [comment]
merged, thanks.

**Pull request merged**
