### PR TITLE
Add lesismal/nbio

### PR DESCRIPTION
**Pull request by lesismal**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/lesismal/nbio
- pkg.go.dev: https://pkg.go.dev/github.com/lesismal/nbio?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/lesismal/nbio
- coverage service link: https://codecov.io/gh/lesismal/nbio

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by lesismal** [comment]
I see that the Travis CI failed, and I have re pr for two times, I'm confused about how to fix that:

```sh
--- FAIL: TestAlpha/Libraries_for_working_with_various_layers_of_the_network. (0.00s)
```

**Comment by avelino** [comment]
> I see that the Travis CI failed, and I have re pr for two times, I'm confused about how to fix that:

the position that you placed the link in the readme is not in alphabetical order, the order of the repository names should follow alphabetical order

**Comment by lesismal** [comment]
> > I see that the Travis CI failed, and I have re pr for two times, I'm confused about how to fix that:
> 
> the position that you placed the link in the readme is not in alphabetical order, the order of the repository names should follow alphabetical order

I'll check it and repr, close this, tks

**Comment by lesismal** [comment]
> > I see that the Travis CI failed, and I have re pr for two times, I'm confused about how to fix that:
> 
> the position that you placed the link in the readme is not in alphabetical order, the order of the repository names should follow alphabetical order

I'm still confused, look this:

image

**Comment by lesismal** [comment]
should I place "nbio" above the "NFF-Go"?

**Comment by lesismal** [comment]
> should I place "nbio" above the "NFF-Go"?

I did this, and it's ok now... the "NFF-Go“ made me lost :joy:

**Pull request closed without merging**
