### PR TITLE
Add syslog-format to logging section

### PR DESCRIPTION
**Pull request by smoya**
- github.com repo: https://github.com/smoya/syslog-format
- pkg.go.dev: https://pkg.go.dev/github.com/smoya/syslog-format
- goreportcard.com: https://goreportcard.com/report/github.com/smoya/syslog-format
- coverage service link: https://gocover.io/github.com/smoya/syslog-format 

90.5% coverage

- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

**Comment by smoya** [comment]
Would it be fine if I add an example of how to use it ?

**Comment by panjf2000** [comment]
Of course it would.

**Comment by smoya** [comment]
I realised that there is now a better alternative for my lib here https://github.com/influxdata/go-syslog. Obviously better maintained that mine. So I'm gonna add a message to my repo recommending it's usage instead.

This means we can close this PR. Thanks for your time @panjf2000 !

**Pull request closed without merging**
