### PR TITLE
Add docker-go-mingw

### PR DESCRIPTION
**Pull request by x1unix**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/x1unix/docker-go-mingw
- pkg.go.dev: **Not applicable**
- goreportcard.com: **Not applicable**
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): **Not applicable**

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by x1unix** [comment]
**Disclaimer:** code coverage is not applicable to this project, as this is a *docker image for building Go apps* for Windows, not Go library or software.

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: False
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — COMMENTED** [review]
doesn't sound like the best category for your docker image, I believe it fits better under **DevOps Tools**

what is your opinion?

**Comment by x1unix** [comment]
@avelino not sure, but looks like it's most suitable from all categories. Moved to **DevOps Tools**

**Pull request merged**
