### PR TITLE
 Adding in argoproj devops tools

### PR DESCRIPTION
**Pull request by jpoley**
> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

- repo link (github.com, gitlab.com, etc):
        - https://github.com/argoproj/argo-cd
        - https://github.com/argoproj/argo-events
        - https://github.com/argoproj/argo-rollouts
        - https://github.com/argoproj/argo-workflow

- pkg.go.dev:
        - https://pkg.go.dev/github.com/argoproj/argo-cd
        - https://pkg.go.dev/github.com/argoproj/argo-events
        - https://pkg.go.dev/github.com/argoproj/argo-rollouts
        - https://pkg.go.dev/github.com/argoproj/argo-workflow

- goreportcard.com:
        - https://goreportcard.com/report/github.com/argoproj/argo-cd
        - https://goreportcard.com/report/github.com/argoproj/argo-events
        - https://goreportcard.com/report/github.com/argoproj/argo-rollouts
        - https://goreportcard.com/report/github.com/argoproj/argo-workflow

- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.)
        - https://app.codecov.io/gh/argoproj/argo-cd
        - https://app.codecov.io/gh/argoproj/argo-events
        - https://app.codecov.io/gh/argoproj/argo-rollouts
        - https://app.codecov.io/gh/argoproj/argo-workflow

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below before you submit PR:**
_not every repository (project) will fit into every option, but most projects should_

- [ X] I have added my package in alphabetical order.
- [ X] I have an appropriate description with correct grammar.
- [ X] I know that this package was not listed before.
- [ X] I have added pkg.go.dev link to the repo and to my pull request.
- [X ] I have added coverage service link to the repo and to my pull request.
- [ X] I have added goreportcard link to the repo and to my pull request.
- [ X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by jpoley** [comment]
Please let me know if I've missed anything.

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by jpoley** [comment]
any updates? or changes? looks like it passed but wasn't merged yet.

**Review by avelino — CHANGES_REQUESTED** [review]
1 link per contribution (pull request), sorry

**Pull request closed without merging**
