### PR TITLE
Add go-fault

### PR DESCRIPTION
**Pull request by lingrino**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/github/go-fault
- pkg.go.dev: https://pkg.go.dev/github.com/github/go-fault?tab=doc
- goreportcard.com: https://goreportcard.com/report/github.com/github/go-fault
- coverage service link: https://github.com/github/go-fault/runs/679016162?check_suite_focus=true#step:7:365 (coverage is enforced using github actions and uploaded as an artifact on each run)

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: False

**Comment by lingrino** [comment]
I am adding the goreportcard link to our repo ([pr](https://github.com/github/go-fault/pull/2)). I've also added a section about code coverage in the README. We do not use a hosted code coverage tool, however coverage is enforced at 100% using github actions ([workflow](https://github.com/github/go-fault/blob/master/.github/workflows/validate.yml#L33-L50)) and coverage artifacts are uploaded on every CI run.

**Comment by lingrino** [comment]
I updated the go-fault readme with a goreportcard badge and a sentence about how we handle code coverage.

**Comment by avelino** [comment]
review:
- https://goreportcard.com/report/github.com/github/go-fault#ineffassign

> I recommend using coverage system integration, but the choice is yours, you who keep the project

**Comment by lingrino** [comment]
👋 Hi @avelino, the project runs [golangci-lint](https://github.com/golangci/golangci-lint) inside CI that catches all errors from goreportcard and more ([link](https://github.com/github/go-fault/blob/master/.golangci.yml#L1-L42)). The `ineffassign` that you linked is only for the example that appears in godoc, where we prefer to have a short working example over one that catches all errors ([example_test.go](https://github.com/github/go-fault/blob/master/example_test.go)). Unfortunately I don't think there's a way to ignore that with goreportcard. All code in the fault package is linted and tested/covered extensively.

**Comment by lingrino** [comment]
@avelino Is there anything else you're looking for from me before this is merged? I believe the project is ready. We have 100% test coverage and 100% compliance with a very strict golangci-lint file. These commitments are enforced in CI along with regular benchmarks and security scans that are tracked for degradations. Unfortunately goreportcard does not distinguish between code examples and package code, which is the only finding on that site. The tool does appear to be actively maintained, but if this PR (https://github.com/gojp/goreportcard/pull/298) is ever merged our report will be resolved.

**Pull request merged**
