### PR TITLE
Add Weaviate

### PR DESCRIPTION
**Pull request by bobvanluijt**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/semi-technologies/weaviate
- pkg.go.dev: https://pkg.go.dev/github.com/semi-technologies/weaviate
- goreportcard.com: https://goreportcard.com/report/github.com/semi-technologies/weaviate
- coverage service link: https://codecov.io/gh/semi-technologies/weaviate

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

**Comment by bobvanluijt** [comment]
Hi @avelin, just to make sure, is this related to the 80% coverage?

**Comment by avelino** [comment]
- coverage minimal 80%
- any warnings: https://goreportcard.com/report/github.com/semi-technologies/weaviate
- undocumented https://pkg.go.dev/github.com/semi-technologies/weaviate
- dont's example on readme: https://github.com/semi-technologies/weaviate#weaviate-

**Comment by bobvanluijt** [comment]
Gotcha, thanks

**Comment by avelino** [comment]
Fixed and reopen PR pls

**Pull request closed without merging**
