### PR TITLE
Removing fasttemplate.

### PR DESCRIPTION
**Pull request by spekary**
Fasttemplate appears to be abandoned. The most recent commit was 2 years ago.

Also, fasttemplate does not conform to current awesome-go quality standards.

@valyala, please respond if you would like to keep fasttemplate on awesome-go. Please review the current quality standards.

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: False
- coverage: False

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by phanirithvij** [comment]
@spekary reason for not removing?

**Comment by avelino** [comment]
> Fasttemplate appears to be abandoned. The most recent commit was 2 years ago.

@phanirithvij 👆

**Comment by spekary** [comment]
Hmm. I thought I merged this. Not sure. Could have beena  mouse slip.

**Pull request closed without merging**
