### PR TITLE
immortal, ssh-vault, violetear

### PR DESCRIPTION
**Pull request by nbari**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
### immortal
- github.com repo:  https://github.com/immortal/immortal/
- godoc.org: https://godoc.org/github.com/immortal/immortal
- goreportcard.com: https://goreportcard.com/report/github.com/immortal/immortal
- coverage service link: https://codecov.io/gh/immortal/immortal

### violetear
- github.com repo: https://github.com/nbari/violetear/
- godoc.org: https://godoc.org/github.com/nbari/violetear
- goreportcard.com: https://goreportcard.com/report/github.com/nbari/violetear
- coverage service link: https://coveralls.io/github/nbari/violetear?branch=master

### ssh-vault
- github.com repo: https://github.com/ssh-vault/ssh-vault
- godoc.org: https://godoc.org/github.com/ssh-vault/ssh-vault
- goreportcard.com: https://goreportcard.com/report/github.com/ssh-vault/ssh-vault
- coverage service link: https://coveralls.io/github/ssh-vault/ssh-vault?branch=master

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by nbari** [comment]
@avelino Hi, what exactly is missing or you mean with "need links"?

**Comment by appleboy** [comment]
```
github.com repo:
godoc.org:
goreportcard.com:
coverage service link (gocover, coveralls etc.):
```

You missing all links.

**Comment by nbari** [comment]
@appleboy Hi, Just updated the description, is there the place they should be?

**Comment by nbari** [comment]
@appleboy @avelino Hi, wondering if I need to do something else.

Regards.

**Pull request merged**
