### PR TITLE
Add Sendbird Server API

### PR DESCRIPTION
**Pull request by ippy04**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

Please provide package links to:
- godoc.org: https://godoc.org/github.com/ippy04/sendbird
- goreportcard.com: https://goreportcard.com/report/github.com/ippy04/sendbird
- gocover.io: https://coveralls.io/github/ippy04/sendbird?branch=master

Note, that new categories can be added only when there are 3 packages or more.

Make sure that you've checked the boxes below before you submit PR:
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [X] I have added godoc link
- [X] I have added gocover.io link
- [X] I have added goreportcard link
- [X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
???
godoc.org:
goreportcard.com:
gocover.io:

**Comment by ippy04** [comment]
Oops sorry had added them as badges in the README instead of the PR comment. Updated. Thanks!

**Comment by avelino** [comment]
new rules 8 day with label `pending-submitter-response`: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers

**Comment by ippy04** [comment]
@avelino I responded with the proper links....?

**Comment by ippy04** [comment]
godoc.org: https://godoc.org/github.com/ippy04/sendbird
goreportcard.com: https://goreportcard.com/report/github.com/ippy04/sendbird
gocover.io: https://coveralls.io/github/ippy04/sendbird?branch=master

**Comment by cassiobotaro** [comment]
@ippy04 There are many errors on reportcard, fix it pls
image

**Pull request closed without merging**
