### PR TITLE
Adds AWQL driver to database drivers section

### PR DESCRIPTION
**Pull request by rvflash**
Hi,

**Please provide package links to:**
- github.com repo: https://github.com/rvflash/awql-driver
- godoc.org: https://godoc.org/github.com/rvflash/awql-driver
- goreportcard.com: https://goreportcard.com/report/github.com/rvflash/awql-driver
- coverage service link (gocover, coveralls etc.): https://codecov.io/github/rvflash/awql-driver?branch=master

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thank you!

### CODE REVIEW

**Comment by kirillDanshin** [comment]
hi.
this package should be tested better.
also, are you sure that [driver.Open() godoc](https://godoc.org/github.com/rvflash/awql-driver#Driver.Open) is rendered as expected?

**Comment by rvflash** [comment]
Hi, yes I am sure, but i can change this part of the godoc in order to improve its readability.

One testing file is missing because it is in the gitignore. I must change it to remove real connections to Google API.

**Comment by kirillDanshin** [comment]
@rvflash you can change it to use e.g. encrypted API keys etc.

and please change it to improve doc's readability.

**Comment by rvflash** [comment]
Hi @kirillDanshin,
I have improved the doc's readability by moving and explaining the variants of the data source name in the README.
I have also began to externalize some tests.
I hope it is better now.

**Comment by kirillDanshin** [comment]
@rvflash note that you have a bug in the docs: https://godoc.org/github.com/rvflash/awql-driver#APIError

**Comment by rvflash** [comment]
It's fixed. Thanks for the code review @kirillDanshin.

**Comment by appleboy** [comment]
> Tests, where practical. If the library/program is testable, then coverage should be >= 80% for non-data-related packages and >=90% for data related packages. Notice: the tests will be reviewed too. We will check your coverage manually if your package's coverage is just a benchmark results.

https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard

**Comment by avelino** [comment]
new rules 8 days with label `pending-submitter-response`: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers

**Pull request closed without merging**
