### PR TITLE
Adding RichardKnop/go-fixtures

### PR DESCRIPTION
**Pull request by RichardKnop**
Hi,

This pull request adds [go-fixtures](https://github.com/RichardKnop/go-fixtures) to the database migrations section.

It is a useful tool to use in conjunction with database migrations to load YAML based fixtures. Similar to Django's fixtures.
- github.com repo: https://github.com/RichardKnop/go-fixtures
- godoc.org: https://godoc.org/github.com/RichardKnop/go-fixtures
- goreportcard.com: https://goreportcard.com/report/github.com/RichardKnop/go-fixtures
- coverage service link: https://codecov.io/gh/RichardKnop/go-fixtures
- travis CI link: https://travis-ci.org/RichardKnop/go-fixtures
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@RichardKnop your codeship CI is private.

**Comment by RichardKnop** [comment]
@kirillDanshin Replaced it with Travis CI link. That should be public.

**Comment by cassiobotaro** [comment]
@RichardKnop gocover ir broken
image

**Comment by RichardKnop** [comment]
@cassiobotaro Do you mean gocover.io? There is no way to create a test database afaik. So can't really use that.

See this line in travis config: https://github.com/RichardKnop/go-fixtures/blob/master/.travis.yml#L22

**Comment by cassiobotaro** [comment]
@RichardKnop we neeed coverage service link

**Comment by RichardKnop** [comment]
@cassiobotaro Hi. I have added codecov link and also badge.

**Comment by RichardKnop** [comment]
@cassiobotaro 👍

**Pull request merged**
