### PR TITLE
added spiritor ai

### PR DESCRIPTION
**Pull request by gregtzar**
## Developer Comments

Hey there. I am the developer/maintainer for this library. I just wanted to note that I do not have CI and/or unit testing running yet (hence the unchecked boxes below) but plan to in the future. This is challenging though, because this app is primarily a CLI that reads/writes from the local filesystem and building unit tests is a challenge. I need to research and figure out the best testing strategy for a package like this and that will be happening as the project progresses.

## We want to ensure high quality of the packages. Make sure that you've checked the boxes below before sending a pull request.

- [x] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines)
- [x] I have read the [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers)
- [x] I have read the [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards)

_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines for details._

- [x] The repo documentation has a pkg.go.dev link.
- [ ] The repo documentation has a coverage service link.
- [x] The repo documentation has a goreportcard link.
- [x] The repo has a version-numbered release and a go.mod file.
- [ ] The repo has a continuous integration process that automatically runs tests that must pass before new pull requests are merged.
- [ ] Continuous integration is used to attempt to catch issues prior to releasing this package to end-users.

## Please provide some links to your package to ease the review

- [x] forge link (github.com, gitlab.com, etc): https://github.com/spiritorai/spiritor
- [x] pkg.go.dev: https://pkg.go.dev/github.com/spiritorai/spiritor
- [x] goreportcard.com: https://goreportcard.com/report/github.com/spiritorai/spiritor
- [ ] coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.):

## Pull Request content

- [x] The package has been added to the list in alphabetical order.
- [x] The package has an appropriate description with correct grammar.
- [x] As far as I know, the package has not been listed here before.

## Category quality

_Note that new categories can be added only when there are 3 packages or more._

Packages added a long time ago might not meet the current guidelines anymore. It would be very helpful if you could check 3-5 packages above and below your submission to ensure that they also still meet the Quality Standards.

Please delete one of the following lines:

- [x] The packages around my addition still meet the Quality Standards.
- [ ] I removed the following packages around my addition: (please give a short reason for each removal)

Thanks for your PR, you're awesome! :sunglasses:

## Summary by CodeRabbit

- **Documentation**
  - Added SpiritorAI, a privacy-centric and open-source toolkit for writers and content creators, to the list of AI libraries in the README.

### CODE REVIEW

**Comment by phanirithvij** [comment]
Your project is too new, it's only been 4 days. I don't think it is stable enough. Please resubmit once you write tests, and it reaches a stable 1.0

**Comment by gregtzar** [comment]
@phanirithvij  Seriously? There's a ton of packages on your list that are still in v0.x.x. Being in v1.x.x isn't even a requirement in any of your docs. I may have only published this a few days ago but it's been around for a while. Lame.

**Comment by phanirithvij** [comment]
It's

**Comment by phanirithvij** [comment]
Sorry I shouldn't have closed it.

**Comment by Preacher27** [comment]
I feel I'm not free like 2 sims couture be an can I look at what the other person is doing

**Comment by Preacher27** [comment]
I'm going to take a break to see

**Comment by k-capehart** [comment]
@phanirithvij Go's own documentation states that a project is stable once it has reached v1.0.0. Maybe worth pointing out in the guidelines.

image

**Comment by phanirithvij** [comment]
@k-capehart thank you. I remember seeing it somewhere but forgot where.

**Comment by Preacher27** [comment]
What does this mean Sent from my iPhoneOn Jun 19, 2024, at 11:46 AM, Kyle Capehart ***@***.***> wrote:﻿
@phanirithvij Go's own documentation states that a project is stable once it has reached v1.0.0. Maybe worth pointing out in the guidelines.
image.png (view on web)

**Review by Pathi-subhash — APPROVED** [review]

**Comment by phanirithvij** [comment]
Please resubmit your project in 5 months or when it reaches v1.0.0.

I agree there are many projects which go from v0.x.x to v1.x.x in a span of few months and are in awesome-go but they will slowly be removed as those tend to be experimental and become outdated/unmaintained. Don't be offended by this rejection and I hope you will resubmit.

**Pull request closed without merging**
