### PR TITLE
Add YARF and gotext

### PR DESCRIPTION
**Pull request by leonelquinteros**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo: https://github.com/leonelquinteros/gotext https://github.com/yarf-framework/yarf
- godoc.org: https://godoc.org/github.com/leonelquinteros/gotext https://godoc.org/github.com/yarf-framework/yarf
- goreportcard.com: https://goreportcard.com/report/github.com/leonelquinteros/gotext https://goreportcard.com/report/github.com/yarf-framework/yarf
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/leonelquinteros/gotext https://gocover.io/github.com/yarf-framework/yarf 

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by kirillDanshin** [comment]
hi @leonelquinteros, thanks for your contribution.
please add YARF tests for cases with logger injected and fix goreportcard issues.

**Comment by leonelquinteros** [comment]
Hi @kirillDanshin, 

Thanks for reviewing! 
I've done both and pushed to the repo, please check it now.

**Comment by kirillDanshin** [comment]
@leonelquinteros gocover.io is broken again. we need to wait or you can add any other coverage service.
please fix gotext goreportcard issues too. thanks.

**Comment by leonelquinteros** [comment]
@kirillDanshin OK, lets wait for gocover.io to be back online (at this time is working for me). 

The goreportcard for gotext is fixed and got 100%

**Comment by kirillDanshin** [comment]
@leonelquinteros I see many issues with yarf tests. as I see many cases are not executed but they need to be tested. just for example, `*Context.GetClientIP()` uses only one case when it should be tested more carefully. please test other cases too.

**Comment by leonelquinteros** [comment]
@kirillDanshin Improved YARF test coverage up to 93.4%. 

Let me know if that's enough.

**Comment by leonelquinteros** [comment]
Added new coverage services for both repos: 

https://codecov.io/gh/yarf-framework/yarf
https://codecov.io/gh/leonelquinteros/gotext

**Comment by kirillDanshin** [comment]
@leonelquinteros thanks for your contribution, you're awesome :wink:

**Pull request merged**
