### PR TITLE
added GoKi, GoGi, Gide, and rasterx packages.

### PR DESCRIPTION
**Pull request by rcoreilly**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo:
- godoc.org:
- goreportcard.com:
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `[cover.run](https://cover.run/go?tag=golang-1.10&repo=github.com%2Fuser%2Frepository)`

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [ ] I have added my package in alphabetical order.
- [ ] I have an appropriate description with correct grammar.
- [ ] I know that this package was not listed before.
- [ ] I have added godoc link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request.
- [ ] I have added goreportcard link to the repo and to my pull request.
- [ ] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by rcoreilly** [comment]
https://goreportcard.com/report/github.com/goki/gi
https://godoc.org/github.com/goki/gi
https://goreportcard.com/report/github.com/goki/gide
https://godoc.org/github.com/goki/gide
https://goreportcard.com/report/github.com/goki/ki
https://godoc.org/github.com/goki/ki
https://goreportcard.com/report/github.com/srwiley/rasterx
https://godoc.org/github.com/srwiley/rasterx

**Comment by rcoreilly** [comment]
more links (github already in the README but adding them here again just in case):
https://github.com/goki/gi
https://github.com/goki/gide
https://github.com/goki/ki
https://github.com/srwiley/rasterx

other test links are still pending (site seems very slow) and gi and gide don't really have tests b/c they are GUI's.

**Comment by avelino** [comment]
What cover link?

**Comment by rcoreilly** [comment]
this is just hanging:

[cover.run](https://cover.run/go?tag=golang-1.10&repo=github.com%2Fgoki%2Fki)

**Comment by avelino** [comment]
> cannot use test profile flag with multiple packages

**Comment by rcoreilly** [comment]
here's the raw link w/out badge: https://cover.run/go?repo=github.com%2Fgoki%2Fki&tag=golang-1.10 -- seems like it is only checking the "ki" package?  or is it getting all the sub-packages too? I don't want to reorganize my code just to make the cover.run thing work!

**Comment by rcoreilly** [comment]
this works but gives very detailed info if you want to see it all: https://gocover.io/github.com/goki/ki

**Comment by rcoreilly** [comment]
anything more that you need from me at this point?

**Pull request closed without merging**
