### PR TITLE
Add gqlc

### PR DESCRIPTION
**Pull request by Zaba505**
Wasn't sure if it was better to create new PR or comment on old PR, #2508.

- github.com repo: [repo](https://github.com/gqlc/gqlc)
- godoc.org: [godoc](https://godoc.org/github.com/gqlc/gqlc)
- goreportcard.com: [report](https://goreportcard.com/report/github.com/gqlc/gqlc)
- coverage service link [codecov](https://codecov.io/gh/gqlc/gqlc)

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by Zaba505** [comment]
@avelino 
- gocyclo
    * `TestHelperProcess` is a pattern taken from the go std lib so I have no intent on refactoring
    * `parseValue` is bloated due to simple type cast checks and I feel would make the code less readable if they were factored out
    * `compare` is a simple test helper that is also bloated due to simple type cast checks. If necessary I could refactor this

- test cover
    I added some tests that should have probably already been there but yielded only ~+2%. Locally running `go test -race -cover ./...` in the root folder I get:
```bash
?   	github.com/gqlc/gqlc	[no test files]
ok  	github.com/gqlc/gqlc/cmd	1.032s	coverage: 80.4% of statements
ok  	github.com/gqlc/gqlc/cmd/plugin	4.041s	coverage: 81.6% of statements
```

**Comment by Zaba505** [comment]
@avelino test coverage is now at 80%: [codecov](https://codecov.io/gh/gqlc/gqlc).

**Comment by Zaba505** [comment]
@avelino Just checking to see if there is anything else that needs to be improved before it can be accepted?

**Comment by kirillDanshin** [comment]
Your project looks interesting, but it really need some better docs for the user.

I think, if you can keep the project going, write some more tests (particularly for some corner cases) and a nice "Get Started" guide, we can review your library again.

Feel free to open a new PR as soon as you fix those problems.

**Pull request closed without merging**
