### PR TITLE
1. add tagfmt command tool

### PR DESCRIPTION
**Pull request by bigpigeon**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: github.com/bigpigeon/tagfmt
- pkg.go.dev: https://pkg.go.dev/github.com/bigpigeon/tagfmt
- goreportcard.com: https://goreportcard.com/report/github.com/bigpigeon/tagfmt
- coverage service link ([codecov](https://codecov.io/gh/bigpigeon/tagfmt))

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
review:
- https://goreportcard.com/report/github.com/bigpigeon/tagfmt#gocyclo
- https://goreportcard.com/report/github.com/bigpigeon/tagfmt#golint
- coverage > 80%

**Comment by bigpigeon** [comment]
hi: 
  because this is a command tool, it has some code which only executed in the main function 
e.g  https://github.com/bigpigeon/tagfmt/blob/master/gofmt.go#L267-L309
It's hard to  cover it by  writing a unit test function

expect:
coverage >= 80% by  go test 

```
go test -covermode=atomic
PASS
coverage: 84.2% of statements
ok      github.com/bigpigeon/tagfmt     0.012s
```

**Comment by avelino** [comment]
> hi:
> because this is a command tool, it has some code which only executed in the main function
> e.g https://github.com/bigpigeon/tagfmt/blob/master/gofmt.go#L267-L309
> It's hard to cover it by writing a unit test function
> 
> expect:
> coverage >= 80% by go test
> 
> ```
> go test -covermode=atomic
> PASS
> coverage: 84.2% of statements
> ok      github.com/bigpigeon/tagfmt     0.012s
> ```

Screen Shot 2020-11-24 at 5 16 48 AM

**Pull request closed without merging**
