### PR TITLE
Add roveralls to continuous integration section

### PR DESCRIPTION
**Pull request by lawrencewoodman**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo: https://github.com/LawrenceWoodman/roveralls
- godoc.org: https://godoc.org/github.com/LawrenceWoodman/roveralls
- goreportcard.com: https://goreportcard.com/report/github.com/LawrenceWoodman/roveralls
- coverage service link (gocover, coveralls etc.):  https://coveralls.io/r/LawrenceWoodman/roveralls?branch=master

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [ x] I have added my package in alphabetical order
- [ x] I know that this package was not listed before
- [ x] I have added godoc link to the repo and to my pull request
- [ x] I have added coverage service link to the repo and to my pull request
- [ x] I have added goreportcard link to the repo and to my pull request
- [ x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Improve your test coverage

**Comment by LawrenceWoodman** [comment]
Thanks, I have increased the test coverage to 84%, is that high enough?

**Comment by cassiobotaro** [comment]
@lawrencewoodman coverage is ok, please take a look on these errors: 
image

**Comment by lawrencewoodman** [comment]
@cassiobotaro Thanks for letting me know.  I have got all the goreportcard entries up to 100% now and also increased the test coverage to 89%.

**Comment by cassiobotaro** [comment]
@lawrencewoodman Nice! Thanks!

**Pull request merged**
