### PR TITLE
Add enumer tool

### PR DESCRIPTION
**Pull request by alvaroloes**
- github.com repo: https://github.com/alvaroloes/enumer
- godoc.org: [GoDoc](https://godoc.org/github.com/alvaroloes/enumer)
- goreportcard.com: [Go Report Card](https://goreportcard.com/report/github.com/alvaroloes/enumer)
- coverage service link cover.run go

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

_Thank you for reviewing!!_

### CODE REVIEW

**Comment by jtemporal** [comment]
Today's coverage doesn't meet the quality standards on our contributing guide:
>Tests, where practical. If the library/program is testable, then coverage should be >= 80% for non-data-related packages and >=90% for data related packages.

**Comment by alvaroloes** [comment]
Hi, thank you for replying.

Actually, code coverage is 100% but the coverage tool can't get it. The issue is that in order to test the "main" function (`stringer.go:main`) there is a test that _compiles_ the project and then run the _command_ with several values. This test is located in file `endtoend_test.go`.
This obviously executes the main function, but the code coverage tool says the main function hasn't been called.

Please let me know if this is acceptable (changing those test to call the "main" function directly would require a considerable amount of work).

Thanks!

**Comment by alvaroloes** [comment]
@jtemporal Please let me know if I still need to do something

**Comment by jtemporal** [comment]
> Actually, code coverage is 100% but the coverage tool can't get it.

I think we can do better than this, don't you think? Even though it would _require a considerable amount of work_ to do, I'd only approve this with the increase of coverage.

**Comment by jtemporal** [comment]
Following our contributing guidelines, I'm closing this one since it has been 8 days without response from the pull request author:

> The maintainers will review your PR and notify you and tag it in case any information is still missing. They will wait 8 days for your interaction, after that the PR will be closed.

Please feel free to submit the pull request again with the necessary fixes :wink:

**Pull request closed without merging**
