### PR TITLE
Add mysql-go

### PR DESCRIPTION
**Pull request by pjebs**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/rocketlaunchr/mysql-go
- godoc.org: https://godoc.org/github.com/rocketlaunchr/mysql-go
- goreportcard.com: https://goreportcard.com/report/github.com/rocketlaunchr/mysql-go
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls]

It's too hard to do do tests since I require database connection.

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [* ] I have added my package in alphabetical order.
- [ *] I have an appropriate description with correct grammar.
- [* ] I know that this package was not listed before.
- [ *] I have added godoc link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request.
- [ *] I have added goreportcard link to the repo and to my pull request.
- [ *] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by ceriath** [comment]
Please fill in the PR template and fix the form of the entry

**Comment by pjebs** [comment]
done

**Comment by pjebs** [comment]
let me see what I can do.

**Comment by kirillDanshin** [comment]
@pjebs feel free to open a new PR as soon as you do some tests.

**Pull request closed without merging**
