### PR TITLE
Add https://github.com/fulldump/biff

### PR DESCRIPTION
**Pull request by fulldump**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/fulldump/biff
- godoc.org: https://godoc.org/github.com/fulldump/biff
- goreportcard.com: https://goreportcard.com/report/github.com/fulldump/biff
- coverage service link: https://gocover.io/github.com/fulldump/biff

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [X] I have added my package in alphabetical order.
- [X] I have an appropriate description with correct grammar.
- [X] I know that this package was not listed before.
- [X] I have added godoc link to the repo and to my pull request.
- [X] I have added coverage service link to the repo and to my pull request.
- [X] I have added goreportcard link to the repo and to my pull request.
- [X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by fulldump** [comment]
Of course yes, but I do not understand the golint message:


   -
      - Line 66 <https://github.com/fulldump/biff/blob/master/biff.go#L66>:
      warning: comment on exported type A should be of the form "A ..." (with
      optional leading article) (golint)

And the comment on exported type A is:

// A is a type passed to alternative functions to manage recursion status and
// keep human information information related to the test: `title` and
// `description`.
type A struct {

...


Maybe is it because the name is 'A' (an article)... ?

Any help on that is really appreciated.







2018-05-20 15:20 GMT+02:00 Bo-Yi Wu <notifications@github.com>:

**Comment by sgreben** [comment]
@fulldump: I was curious about the linter warning you got, and played around a bit - here's how you can fix it:

- Doesn't work:
    ```go
    // A is an empty struct
    type A struct{}
    ```
    > comment on exported type A should be of the form "A ..." (with optional leading article)

- Works:
    ```go
    // An A is an empty struct
    type A struct{}
    ``` 
    > (no issues)

**Comment by fulldump** [comment]
Thanks! I'm fixing it now.

Regarding the coverage...
https://gocover.io/github.com/fulldump/biff/biff.go is 100% covered but
assets.go is more difficult because all asserts ends up with os.Exit(1):
https://github.com/fulldump/biff/blob/master/asserts.go#L187-L197. I can
try but maybe the code will loose readability.



2018-05-20 17:44 GMT+02:00 Sergey Grebenshchikov <notifications@github.com>:

**Comment by fulldump** [comment]
[cover.run](https://cover.run/go?tag=golang-1.10&repo=github.com%2Ffulldump%2Fbiff)
Coverage up to 94.1%  https://cover.run/go?repo=github.com%2Ffulldump%2Fbiff&tag=golang-1.10

Finally it was easy by mocking `os.Error(1)` function.

**Comment by fulldump** [comment]
[image: cover.run]
<https://cover.run/go?tag=golang-1.10&repo=github.com%2Ffulldump%2Fbiff>
Coverage up to 94.1%
https://cover.run/go?repo=github.com%2Ffulldump%2Fbiff&tag=golang-1.10

Finally it was easy by mocking os.Error(1) function.


2018-05-20 17:50 GMT+02:00 Gerardo Oscar JT <gerardooscarjt@gmail.com>:

**Pull request merged**
