### PR TITLE
Added lestrrat-go/jwx library to Authentication section

### PR DESCRIPTION
**Pull request by renta**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/lestrrat-go/jwx
- pkg.go.dev: https://pkg.go.dev/github.com/lestrrat-go/jwx
- goreportcard.com: https://goreportcard.com/report/github.com/lestrrat-go/jwx
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.) https://codecov.io/github/lestrrat-go/jwx?branch=main

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [ ] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by renta** [comment]
@avelino Please, do not close this PR.

**Review by avelino — CHANGES_REQUESTED** [review]
review all itens it https://goreportcard.com/report/github.com/lestrrat-go/jwx
minimal cover is 85%

**Comment by lestrrat** [comment]
@avelino Hi, I don't see how I could improve the results on this page, because the errors indicate "out of memory". At least the linting via golangci-lint is passing, so the results should be at least a little bit better than whatever this site is reporting.

image

**Comment by avelino** [comment]
> @avelino Hi, I don't see how I could improve the results on this page, because the errors indicate "out of memory". At least the linting via golangci-lint is passing on my end, so the results should be at least a little bit better than whatever this site is reporting.
> 
> image

ok, and test coverage?

**Comment by lestrrat** [comment]
Ah, you require 85% _test_ coverage? No chance.
I use coverage info so we don't get things out of hand and I keep it steady around 70% give or take, but I don't play that game.  Unless somebody wants to play the game for me, I don't think my library will ever get there.

Sorry @renta. Please send test PRs if you want to see this happen.

**Comment by renta** [comment]
@lestrrat Ok, I'll check what I could do to increase a coverage of jwx. If I could gain >85% I'll reopen this PR.

**Pull request closed without merging**
