### PR TITLE
Add rest-layer

### PR DESCRIPTION
**Pull request by rs**
REST Layer is an API framework heavily inspired by the excellent Python Eve. It helps you create a comprehensive, customizable, and secure REST (graph) API on top of pluggable backend storages with no boiler plate code so you can focus on your business logic.

Godoc: https://godoc.org/github.com/rs/rest-layer
Report Card: https://goreportcard.com/report/github.com/rs/rest-layer
Cover:
http://gocover.io/github.com/rs/rest-layer/rest?version=1.6
http://gocover.io/github.com/rs/rest-layer/graphql
http://gocover.io/github.com/rs/rest-layer/schema
http://gocover.io/github.com/rs/rest-layer/resource

### CODE REVIEW

**Comment by kirillDanshin** [comment]
Hi, @rs. Thanks for your contribution!

`rest-layer/rest` needs more tests ~~(untested delete method scares me)~~
`rest-layer/graphql` don't have any tests
`rest-layer/schema` and `rest-layer/resource` needs more tests too

Please, add some tests and leave comment here. Thanks.

Anyway, the package looks pretty good and I'll be glad to see postgres support.

**Comment by rs** [comment]
Full test coverage is definitely on the TODO list. I will let you know when I get there.

**Comment by rs** [comment]
Hey,

I added a lot of test to improve the coverage:

```
ok  	github.com/rs/rest-layer/graphql	0.550s	coverage: 78.2% of statements
ok  	github.com/rs/rest-layer/resource	0.119s	coverage: 77.4% of statements
ok  	github.com/rs/rest-layer/rest 	 	0.024s	coverage: 93.2% of statements
ok  	github.com/rs/rest-layer/schema	0.450s	coverage: 68.7% of statements
```

It still not 100% but it covers the most important code paths. Tell me if it's enough to consider a merge.

**Comment by rs** [comment]
@kirillDanshin: any news?

**Comment by kirillDanshin** [comment]
@rs yep. I've reviewed the code. good library. thanks for your contribution, merged :)

**Comment by rs** [comment]
Thank you @kirillDanshin

**Pull request merged**
