### PR TITLE
Add Git Town to list of other software

### PR DESCRIPTION
**Pull request by kevgo**
- github.com repo: https://github.com/originate/git-town
- godoc.org: N/A since this is a CLI tool
- goreportcard.com: https://goreportcard.com/report/github.com/Originate/git-town
- coverage service link: N/A since testing via Cucumber written in Ruby (needed for parallelization of tests). We have 200 end-to-end feature specs in https://github.com/Originate/git-town/tree/master/features that cover the tool completely.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [ ] I have added godoc link to the repo and to my pull request. (N/A since this is a CLI tool)
- [ ] I have added coverage service link to the repo and to my pull request. (N/A due to tests written in Ruby)
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by cassiobotaro** [comment]
I kind a confuse about this package, it's looks good to me, but at the same time, unique tests are ruby. Can you help me @avelino ?

**Comment by kevgo** [comment]
Thanks for considering us for this awesome list! The end-to-end tests are in Ruby because we have such a comprehensive test suite that we need to run several rest runners in parallel (one per available CPU core) to keep the test suite time under 5 minutes. Ruby Cucumber supports that out of the box, Godog (Go Cucumber) not yet. The actual tool is 100% Go, and is shipped as pure Go binaries. Go has been a major success factor for this tool.

**Comment by felipeweb** [comment]
@kevgo @cassiobotaro is it possible to run tests as ruby project on codeclimate or other tool?

**Comment by felipeweb** [comment]
@kevgo  CLI tool can have a godoc too. you can take https://godoc.org/github.com/prest/prest as example

**Comment by kevgo** [comment]
Good feedback. Let me look into this and get back to you.

**Pull request closed without merging**
