### PR TITLE
Add wstest

### PR DESCRIPTION
**Pull request by posener**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo: https://github.com/posener/wstest
- godoc.org: https://godoc.org/github.com/posener/wstest
- goreportcard.com: https://goreportcard.com/report/github.com/posener/wstest
- coverage service link (gocover, coveralls etc.): https://codecov.io/gh/posener/wstest

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by kirillDanshin** [comment]
note: coverage level < 80%, but tests for uncovered code could be omitted while they stay as simple as `return structInstance.field`.

**Comment by cassiobotaro** [comment]
@kirillDanshin If has changes to be done, why you merged?

**Comment by kirillDanshin** [comment]
@cassiobotaro missclicked, but it'll be faster to fix those. the package itself is pretty useful now, so if changes will be applied today we can just leave and not revert it. but still -- merging this right now was my mistake. if changes will not applied today I'll revert the merge and create PR with fixes.
@posener FYI

**Comment by posener** [comment]
@kirillDanshin , no worries, will fix the issues today :-)

**Pull request merged**
