### PR TITLE
Added grequests

### PR DESCRIPTION
**Pull request by levigross**
Added the grequests library

### CODE REVIEW

**Comment by levigross** [comment]
I have no idea why this PR has been ignored but I am going to close it because no one seems to be managing the PRs

**Comment by shurcooL** [comment]
I think this PR wasn't reviewed this whole time is because there's just too many PRs in the backlog (71 open right now) and the maintainers don't have enough time to get through them all. I'm not sure what can be done to improve that, but it is a problem.

I only have limited time and I try to review/merge some PRs, but I can't look through them all.

**Comment by therealbill** [comment]
The only solutions are either committed and dedicated time to review for existing reviewers or more reviewers. Perhaps if the reviewers were in the gophers slack team and the #awesome channel had github integration on PRs more rapid visibility could be had, that *may* help. Sometimes things not on our mental "front page" kinda slip away in the cracks.

**Comment by levigross** [comment]
I would like to help and add some automation to the process (so that some
requests can be approved automatically). Lets take this discussion off the
PR and put it into an issue.

**Comment by avelino** [comment]
@levigross open issue about it, is a very important theme to have some automated approver.

We need to discuss about the algorithm to be used.

**Comment by levigross** [comment]
I am going to clone again and add again. Closing this PR

**Pull request closed without merging**
