### PR TITLE
Add Confetti Framework

### PR DESCRIPTION
**Pull request by reindert-vetter**
**Please provide package links to:**

- website: https://www.confetti-framework.com
- github.com repo: https://github.com/confetti-framework/confetti
- pkg.go.dev: https://pkg.go.dev/github.com/confetti-framework/confetti
- goreportcard.com: https://goreportcard.com/report/github.com/confetti-framework/confetti
- coverage service link [codecov](https://github.com/confetti-framework/confetti/blob/main/test/README.md)

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by reindert-vetter** [comment]
What can I do so that this PR can be merged?

**Comment by tami5** [comment]
@reindert-vetter truly amazing work, the codebase is so readable and make sense.

**Review by avelino — APPROVED** [review]
it is OK to enter awesome-go, but I recommend to take a look at the golint https://goreportcard.com/report/github.com/confetti-framework/confetti#golint

**Pull request merged**
