### PR TITLE
Add machine learning package - goml

### PR DESCRIPTION
**Pull request by mrfuxi**
As in title. Lib has set of algorithms to use

### CODE REVIEW

**Comment by alaska** [comment]
Considering the overlap with https://github.com/josephmisiti/awesome-machine-learning#go, I would think you'd either want to pull in all of the projects listed in that source or simply link there.  Thoughts?

**Comment by mrfuxi** [comment]
Nice find! I would also keep the list in once place. Question is where

**Comment by dukex** [comment]
For me it's ok keep listed here and there.

@avelino @mholt @shurcooL

**Comment by mholt** [comment]
LGTM.

**Comment by avelino** [comment]
LGTM

**Comment by alaska** [comment]
So long as you keep them in sync. Or at least do a one-time import of the entire section instead of just goml

**Comment by dgryski** [comment]
Could we just link to it like we do in the hardware section?

**Comment by shurcooL** [comment]
> Could we just link to it like we do in the hardware section?

That sounds like a much better way. Why spend effort keeping them in sync manually?

**Pull request merged**
