### PR TITLE
Add Gilbert task runner

### PR DESCRIPTION
**Pull request by x1unix**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/go-gilbert/gilbert
- godoc.org: https://godoc.org/github.com/go-gilbert/gilbert
- goreportcard.com: https://goreportcard.com/report/github.com/go-gilbert/gilbert
- coverage service link [cover.run](https://cover.run/go?tag=golang-1.12&repo=github.com%2Fgo-gilbert%2Fgilbert)

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by x1unix** [comment]
@cassiobotaro done - https://goreportcard.com/report/github.com/go-gilbert/gilbert

изображение

**Comment by x1unix** [comment]
@cassiobotaro can you review this PR?

**Comment by cassiobotaro** [comment]
image

**Comment by x1unix** [comment]
@cassiobotaro done, again :)

Forgot to run `golint` on latest release (usually I'm using `golangci-lint`, and looks like it doesn't cover all minor cases).

What about to add `goreportcard` check on pull request?

**Pull request merged**
