### PR TITLE
add Copygen

### PR DESCRIPTION
**Pull request by switchupcb**
> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc): https://github.com/switchupcb/copygen
- pkg.go.dev: https://pkg.go.dev/github.com/switchupcb/copygen
- goreportcard.com: https://goreportcard.com/report/github.com/switchupcb/copygen
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://github.com/switchupcb/copygen/tree/main/examples

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below that apply before you submit PR.**
_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines for detials._

- [x] The package has been added to the list in alphabetical order.
- [x] The package has an appropriate description with correct grammar.
- [x] As far as I know, the package has not been listed here before.
- [x] The repo documentation has a pkg.go.dev link.
- [ ] The repo documentation has a coverage service link.
- [x] The repo documenation has a goreportcard link.
- [x] The repo has a version-numbered release and a go.mod file.
- [x] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines), [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers) and [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).
- [x] The repo has a continuous integration process that automatically runs tests that must pass before new pull requests are merged.
- [x] The authors of the project do not commit directly to the repo, but rather use pull-requests that run the continuous-integration process.

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by phanirithvij** [comment]
- Coverage is 69% as of now, awesome go requires an 80% code coverage
  - Ran the following for coverage locally on my system
  - ```sh
    go test -coverpkg=./... -covermode=atomic -coverprofile=coverage.out ./examples/_tests
    go tool cover -func coverage.out
    ```

**Comment by switchupcb** [comment]
@phanirithvij Have you removed the examples `setup.go` files and [debug](https://github.com/switchupcb/copygen/tree/main/cli/models/debug)?

**Comment by switchupcb** [comment]
You should also remove the generated `copygen.go` files and template `.go` in examples.

**Comment by switchupcb** [comment]
@phanirithvij Added an additional test as well.

**Comment by switchupcb** [comment]
Added tests for more coverage in parsing.

**Comment by phanirithvij** [comment]
@switchupcb can you add a github action that automates uploading code coverage to codecov or coveralls?
You can set it up to account for all the things you've mentioned that require handpicking/removing generated files, etc.

As of now, the coverage is <details><summary><code>73.5%</code></summary>

```go
go test -coverpkg=./... -covermode=atomic -coverprofile=coverage.out ./examples/_tests
```
</details>

**Comment by switchupcb** [comment]
@phanirithvij Use the following test for `81.6%`.

Exclude generated code and debug code.
`(go list ./... | grep -v examples | grep -v debug | grep -v cli | tr '\n' ',' )`

Remove `github.com/switchupcb/copygen,github.com/switchupcb/copygen/cli` manually.

**Run coverage.**
`go test -coverpkg=github.com/switchupcb/copygen/cli/config,github.com/switchupcb/copygen/cli/generator,github.com/switchupcb/copygen/cli/generator/interpreter,github.com/switchupcb/copygen/cli/generator/interpreter/extract,github.com/switchupcb/copygen/cli/generator/template,github.com/switchupcb/copygen/cli/matcher,github.com/switchupcb/copygen/cli/models,github.com/switchupcb/copygen/cli/parser,github.com/switchupcb/copygen/cli/parser/options -covermode=atomic -coverprofile=coverage.out ./examples/_tests`

I didn't find any issues by adding more coverage; only by running the software at scale. I don't want to add coveralls or codecov cause it wants authorization, and coverage isn't a good metric for this project. Nonetheless, it meets the requirements now.

**Pull request merged**
