### PR TITLE
added vflow

### PR DESCRIPTION
**Pull request by mehrdadrad**
Thanks in advance!

Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo: https://github.com/VerizonDigital/vflow
- godoc.org: https://godoc.org/github.com/VerizonDigital/vflow/vflow
- goreportcard.com: https://goreportcard.com/report/github.com/VerizonDigital/vflow
- coverage service link (gocover, coveralls etc.): 

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [ x] I have added my package in alphabetical order
- [ x] I know that this package was not listed before
- [ x] I have added godoc link to the repo and to my pull request
- [ ] I have added coverage service link to the repo and to my pull request
- [x ] I have added goreportcard link to the repo and to my pull request
- [x ] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by mehrdadrad** [comment]
I tried gocover.io but looks there are experiencing issue. I can not add to coveralls as I don't have enough permission.

http://gocover.io/github.com/VerizonDigital/vflow

**Comment by kirillDanshin** [comment]
@mehrdadrad maybe you can try coveralls?

**Comment by mehrdadrad** [comment]
@kirillDanshin the repo is under Verizon and i don't have permission to add it to coveralls.

**Comment by mehrdadrad** [comment]
@kirillDanshin gocover.io works now pls see the below:
http://gocover.io/github.com/VerizonDigital/vflow/sflow
http://gocover.io/github.com/VerizonDigital/vflow/ipfix
http://gocover.io/github.com/VerizonDigital/vflow/packet
http://gocover.io/github.com/VerizonDigital/vflow/stress/hammer
http://gocover.io/github.com/VerizonDigital/vflow/mirror
http://gocover.io/github.com/VerizonDigital/vflow/producer

**Comment by mehrdadrad** [comment]
@kirillDanshin Thanks!

**Pull request merged**
