### PR TITLE
Added IP2Location.io Go SDK

### PR DESCRIPTION
**Pull request by ip2location**
> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc):
- https://github.com/ip2location/ip2location-io-go
- pkg.go.dev:
- https://pkg.go.dev/github.com/ip2location/ip2location-io-go
- goreportcard.com:
- https://goreportcard.com/report/github.com/ip2location/ip2location-io-go
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.):
- https://app.codecov.io/gh/ip2location/ip2location-io-go

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below that apply before you submit PR.**
_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines for details._

- [x] The package has been added to the list in alphabetical order.
- [x] The package has an appropriate description with correct grammar.
- [x] As far as I know, the package has not been listed here before.
- [x] The repo documentation has a pkg.go.dev link.
- [x] The repo documentation has a coverage service link.
- [x] The repo documentation has a goreportcard link.
- [x] The repo has a version-numbered release and a go.mod file.
- [x] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines), [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers) and [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).
- [ ] The repo has a continuous integration process that automatically runs tests that must pass before new pull requests are merged.
- [ ] Continuous integration is used to attempt to catch issues prior to releasing this package to end-users.

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by cassiobotaro** [comment]
@ip2location Is this project not testable?

**Comment by ip2location** [comment]
You can use the sample code at https://ip2location-io-go.readthedocs.io/en/latest/quickstart.html#sample-codes to test.

You can sign up for a free API key at http://www.ip2location.io/pricing

**Comment by cassiobotaro** [comment]
@ip2location I was referring to automated tests.

**Comment by ip2location** [comment]
No, there are no automated tests.

**Comment by cassiobotaro** [comment]
@ip2location  To be on the list, project repositories should adhere to the following [quality standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).

**Comment by ip2location** [comment]
If we add the automated tests and code coverage, that should meet the requirements, right?

**Comment by ip2location** [comment]
We've added the tests and the coverage.

**Comment by cassiobotaro** [comment]
@ip2location Coverage remains less than required. Could you write some more tests?

**Comment by ip2location** [comment]
We've added more tests.

**Pull request merged**
