### PR TITLE
added ThreeDotsLabs/watermill

### PR DESCRIPTION
**Pull request by roblaszczak**
Hello :)

- github.com repo: https://github.com/ThreeDotsLabs/watermill
- godoc.org: https://godoc.org/github.com/ThreeDotsLabs/watermill
- documentation website: http://watermill.io/
- goreportcard.com: https://goreportcard.com/report/github.com/ThreeDotsLabs/watermill
- coverage service link: [codecov](https://codecov.io/gh/ThreeDotsLabs/watermill)

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: True
- goreportcard.com: True
- coverage: False

**Comment by roblaszczak** [comment]
Hello, @appleboy data in goreportcard was not up-to-date (last refresh time 10 months ago). I did the update and fixed missing gofmt. 

There are still golint issues like:

> warning: exported function NewEventProcessor should have comment or be unexported (golint)

but IMO it's not really useful to add comments like:
```
// NewEventProcessor returns a new EventProcessor.
```

 etc., especially if EventProcessor is properly documented :)

Is it fine for you now?

**Comment by ceriath** [comment]
Your example would be okay, however i think something like this https://github.com/ThreeDotsLabs/watermill/blob/master/pubsub/tests/test_pubsub.go#L1125 still needs a comment

**Comment by panjf2000** [comment]
It's been more than 30 days without a reply from the PR owner, I'm closing this PR according to our [contributing guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers).

**Comment by roblaszczak** [comment]
Hello @panjf2000 @ceriath @appleboy and @avelino, I added the comments in all places where it made a sense: https://github.com/ThreeDotsLabs/watermill/commit/63b5247f69f7bcadd0846bf0872117a1c4e6d733

Could you take a look again?

Thanks!

**Comment by appleboy** [comment]
@roblaszczak improve your golint error in report card: https://goreportcard.com/report/github.com/ThreeDotsLabs/watermill#golint

**Comment by roblaszczak** [comment]
@appleboy I checked out and IMO all of the names are self-descriptive, I can, of course, add all comments like:

```
// ErrNonPositiveNumberOfRetries is returned when number of retries is non positive number 
var ErrNonPositiveNumberOfRetries = ...
```

but IMO it's making everything rather less readable than more ;)

**Pull request closed without merging**
