### PR TITLE
Add localtunnel

### PR DESCRIPTION
**Pull request by jweslley**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo:  https://github.com/jweslley/localtunnel
- godoc.org: https://godoc.org/github.com/jweslley/localtunnel
- goreportcard.com:  https://goreportcard.com/report/github.com/jweslley/localtunnel
- coverage service link: https://gocover.io/github.com/jweslley/localtunnel

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: False
- goreportcard.com: False
- coverage: True

**Comment by jweslley** [comment]
@panjf2000 Done!

**Comment by panjf2000** [comment]
Either you add only one project on README and remove else two or you should add three descriptions for those three projects, based on what you are requesting on README.

Besides, the current code coverage is 22.7%, which doesn't meet our quality standards (>=80%), please resolve it.

**Comment by avelino** [comment]
read more https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines

**Comment by panjf2000** [comment]
@jweslley 
Please resolve golint issues on go report card: https://goreportcard.com/report/github.com/jweslley/localtunnel#golint

**Comment by ceriath** [comment]
Closed due to inactivity. Please feel free to reopen.

**Pull request closed without merging**
