### PR TITLE
Add Skydive Project - An open source real-time network topology and p…

### PR DESCRIPTION
**Pull request by nplanel**
…rotocols analyzer

Signed-off-by: Nicolas PLANEL <nplanel@redhat.com>

Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo:
- godoc.org:
- goreportcard.com:
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `cover.run go`

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by nplanel** [comment]
github.com repo: https://github.com/skydive-project/skydive
godoc.org: http://skydive-project.github.io/skydive/
goreportcard.com: PR underway, will be merged soon to reflect in the README.MD https://goreportcard.com/report/github.com/skydive-project/skydive
coverage service link : https://coveralls.io/repos/github/skydive-project/skydive/badge.svg?branch=master

**Comment by cassiobotaro** [comment]
More than 8 days without answers. Feel free to submit again following the quality standards.

**Comment by nplanel** [comment]
sorry for the late response, but we have done a big pass on our code
Here the skydive PR under review : [Skydive PR goreportcard](https://github.com/skydive-project/skydive/pull/278)
You can see the reports cards [here](https://goreportcard.com/report/github.com/nplanel/skydive)

**Comment by nplanel** [comment]
could you re-open this PR please

**Comment by cassiobotaro** [comment]
Submit again following the quality standards.

**Pull request closed without merging**
