### PR TITLE
add package: `mchain`

### PR DESCRIPTION
**Pull request by prasannavl**
Add `mchain` package to middleware chains

- github.com repo: https://github.com/prasannavl/mchain
- godoc.org: https://godoc.org/github.com/prasannavl/mchain
- goreportcard.com: https://goreportcard.com/report/github.com/prasannavl/mchain
- coverage service link: https://cover.run/go/github.com/prasannavl/mchain

- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by prasannavl** [comment]
Done

**Comment by cassiobotaro** [comment]
@prasannavl description is ok, but your coverage is too low, pls write tests, or mchain will be removed.

**Comment by prasannavl** [comment]
My bad. Probably should have waited until I wrote them to add it. Will try
to do it over the weekend. It is tiny and simple enough that the
application tests covered it and was sufficient before sharing into the
public repo.

Will ping back once done. Thanks

**Comment by avelino** [comment]
https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers

**Pull request closed without merging**
