### PR TITLE
Add gofn

### PR DESCRIPTION
**Pull request by tiendc**
Add `gofn` to `Utilities` section

**Please provide package links to:**

repo link (github.com, gitlab.com, etc): https://github.com/tiendc/gofn
pkg.go.dev: https://pkg.go.dev/github.com/tiendc/gofn
goreportcard.com: https://goreportcard.com/report/github.com/tiendc/gofn
coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/tiendc/gofn

- [x] The package has been added to the list in alphabetical order.
- [x] The package has an appropriate description with correct grammar.
- [x] As far as I know, the package has not been listed here before.
- [x] The repo documentation has a pkg.go.dev link.
- [x] The repo documentation has a coverage service link.
- [x] The repo documentation has a goreportcard link.
- [x] The repo has a version-numbered release and a go.mod file.
- [x] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines), [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers) and [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).
- [x] The repo has a continuous integration process that automatically runs tests that must pass before new pull requests are merged.
- [x] The authors of the project do not commit directly to the repo, but rather use pull requests that run the continuous-integration process.

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: False
- coverage: False

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by tiendc** [comment]
Hi @avelino, it's been months since creation. All the tests pass. Could you help review this PR?

**Review by avelino — APPROVED** [review]
LGTM

**Comment by avelino** [comment]
> Hi @avelino, it's been months since creation. All the checks pass. Could you help review this PR?

sorry for the delay in looking at the PR (not just yours), there are many PR's I need to review and my work is draining a lot of time - again sorry

**Pull request merged**
