### PR TITLE
Add MTProto

### PR DESCRIPTION
**Pull request by ololosha228**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: [https://github.com/xelaj/mtproto](https://github.com/xelaj/mtproto)
- pkg.go.dev: [https://pkg.go.dev/github.com/xelaj/mtproto](https://pkg.go.dev/github.com/xelaj/mtproto)
- goreportcard.com: [https://goreportcard.com/report/github.com/xelaj/mtproto](https://goreportcard.com/report/github.com/xelaj/mtproto)
- coverage service link: [codebeat](https://codebeat.co/projects/github-com-xelaj-mtproto-master)

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1: 
You're awesome too!

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: False

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
Review:
- golint https://goreportcard.com/report/github.com/xelaj/mtproto#golint
- coverage public link, need percentage (%) - lock awesome-go PR recommendations

**Comment by ololosha228** [comment]
Hey, @avelino, thanks for response!

We'll try to fix golint warnings, but most of them says that exported functions are not documented) so, we can spend less than few days, so don't close this PR, i should fix it :+1: 

also, codebeat already has coverage percentage, if not, i can send here gotest report, if you want)

**Comment by ololosha228** [comment]
@avelino cancel that, accidentaly clicked! sorry

**Comment by ololosha228** [comment]
@avelino we don't have any plugged coverage tool except codebeat, which is already analyze respose coverage percentage.

Even though, there is [standard coverage report of gotest](https://gist.github.com/ololosha228/748962ae8fd9d08739333fd7d6efa4ed) and its [html version](https://gistpreview.github.io/?33365d5c2a1e3b149d663c1b57051e6a).

I honestly don't understand, what the problem to get std coverage report tool as report.

**Comment by avelino** [comment]
> I honestly don't understand, what the problem to get std coverage report tool as report.

we don't only review your library, we also review some libraries a week, download them all locally and test them more time consuming, that's why we ask you to use some tool for coverage

read more: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md

**Comment by ololosha228** [comment]
@avelino [codecov link](https://codecov.io/gh/xelaj/mtproto)

**Comment by avelino** [comment]
> @avelino [codecov link](https://codecov.io/gh/xelaj/mtproto)

very good, today coverage is `25.31%`, should be `> 80%`
Screen Shot 2020-11-24 at 3 29 24 PM

**Comment by ololosha228** [comment]
@avelino glad to hear that you happy to see this link, but unfortunately, this package can't be covered even on 50% due to large amount of generated code:
* [this file](https://github.com/xelaj/mtproto/blob/master/telegram/methods.go) contains 12000+ lines of code and at least 335 untestable methods (due to telegram doesn't provide testing sdk)
* [this file](https://github.com/xelaj/mtproto/blob/master/telegram/interfaces.go) contains 16000+ lines of code, which is, you know, untestable too.

Large amount of this package contains methods and functions, which can't be tested due to lack of testing sdk and even test data from telegram, so it can't be covered more than 25-30%

**Pull request closed without merging**
