### PR TITLE
Added binder - Go to Lua binding library, based on github.com/yuin/go…

### PR DESCRIPTION
**Pull request by alexeyco**
Binder

https://godoc.org/github.com/alexeyco/binder
https://coveralls.io/github/alexeyco/binder?branch=master
https://goreportcard.com/report/github.com/alexeyco/binder

Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo: https://github.com/alexeyco/binder
- godoc.org: https://godoc.org/github.com/alexeyco/binder
- goreportcard.com: https://goreportcard.com/report/github.com/alexeyco/binder
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/alexeyco/binder?branch=master

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by kirillDanshin** [comment]
hi @alexeyco 
is your PR based on latest awesome-go commits? I see fixed dup bug in the tests, so it should pass, if PR based on latest git state.
and please add required links. thanks.

**Comment by alexeyco** [comment]
Oh sry.

https://godoc.org/github.com/alexeyco/binder
https://coveralls.io/github/alexeyco/binder?branch=master
https://goreportcard.com/report/github.com/alexeyco/binder

Done.

**Comment by kirillDanshin** [comment]
@alexeyco you need to push a new commit to trigger our CI.
I've copied the links to your PR message.

**Comment by alexeyco** [comment]
@kirillDanshin, what if I have already removed the fork?

**Comment by kirillDanshin** [comment]
@alexeyco then close this PR and create a new one.

**Comment by shurcooL** [comment]
> is your PR based on latest awesome-go commits? I see fixed dup bug in the tests, so it should pass, if PR based on latest git state.

@kirillDanshin, we haven't merged #1341 yet for some reason. I'll do that now.

**Comment by kirillDanshin** [comment]
@shurcooL thanks.

**Comment by shurcooL** [comment]
I've restarted CI, it passed now.

**Comment by kirillDanshin** [comment]
thanks @alexeyco @shurcooL

**Comment by alexeyco** [comment]
Thanks guys ))

**Pull request merged**
