### PR TITLE
Add the golang G+ community

### PR DESCRIPTION
**Pull request by francoishill**

### CODE REVIEW

**Comment by matrixik** [comment]
Hi, thank you for contributing.
I think it should be in [Websites](https://github.com/avelino/awesome-go#websites) category. And we need at last 3 links to create new category.

**Comment by matrixik** [comment]
@francoishill Any thoughts?

**Comment by francoishill** [comment]
Now moved to Websites.

**Comment by matrixik** [comment]
Thank you.

**Pull request merged**
