### PR TITLE
Remove Gomail since it's unmaintained since 2016.

### PR DESCRIPTION
**Pull request by 3stadt**
Hi there!

With this PR, I would like to remove the [Gomail](https://github.com/go-gomail/gomail/) package.

It's unmaintained since 2016. Several forks exist, but I wasn't able to identify one as a valid replacement fitting the requirements to be added to the awesome list.

I'd suggest that if one of the owners of a fork wants it to be added to the list they should create a separate PR for this.

Kind regards, 3stadt

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: False
- goreportcard.com: False
- coverage: False

**Comment by panjf2000** [comment]
I don't think we can determine it as unmaintained just because the maintainer didn't update it for a long time, unless the maintainer marks the repo with "unmaintained".

You could open an issue to that repo, asking whether that repo is unmaintained or not. If you get a "YES" from the maintainer, then we will remove it from awesome-go list.

**Comment by xhit** [comment]
@panjf2000 unfortunately the maintainer is missing since 2016 and is impossible contact him because mail inbox is full , there are some forks.

The repo had a lot of issues and all new issues refer to this link explaining the situation: https://github.com/go-gomail/gomail/issues/104

I hope Gomail maintainer is good.

**Comment by panjf2000** [comment]
Oh, my! I just took a glance at [go-gomail/gomail#104](https://github.com/go-gomail/gomail/issues/104) and it was a real drama...

I get it now, removing this repo from the list.

**Comment by 3stadt** [comment]
Thank you very much guys! <3

**Pull request merged**
