### PR TITLE
Add Pixie to performance sectionn

### PR DESCRIPTION
**Pull request by ishanmkh**
Hi there  👋,  we've launched our community beta this week and would be great to add to share with community. I'd call out that our backend is in go but it is not on this repo as it houses our community scripts and documentations. I noticed other similar projects on the list so hope that is ok. 

Thanks!
Ishan

Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: n/a
- pkg.go.dev: n/a
- goreportcard.com: n/a
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.)

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [X] I have added my package in alphabetical order.
- [X] I have an appropriate description with correct grammar.
- [X] I know that this package was not listed before.
- [ ] I have added pkg.go.dev link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request.
- [ ] I have added goreportcard link to the repo and to my pull request.
- [X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: False
- coverage: True

**Comment by ishanmkh** [comment]
thanks @avelino !

**Comment by ishanmkh** [comment]
sure @ceriath.  had a question: the repo doesn't include go packages and includes the debugger modules (python syntax) used for perf debugging so the goreportcard.com wont be helpful. 

is that OK or do we need to modify to adhere to the checklist?

**Comment by ishanmkh** [comment]
Thanks!

**Pull request merged**
