### PR TITLE
Add go-twitter to third-party APIs

### PR DESCRIPTION
**Pull request by dghubble**
* https://github.com/dghubble/go-twitter
* https://dev.twitter.com/overview/api/twitter-libraries#go

### CODE REVIEW

**Comment by shurcooL** [comment]
Do you know how it compares with https://github.com/ChimeraCoder/anaconda?

**Comment by dghubble** [comment]
I'm the author who wrote `go-twitter` while a Twitter employee, so I'll try not to create debate here.

Both provide access to a similar set of APIs. . `go-twitter` tends to favor composability at the expense of not providing as many bells and whistles out of the box. For example, it doesn't choose an OAuth1 dependency, takes an `http.Client` directly, and supports multiple users as a result. It is designed much like `google/go-github`. `anaconda` tends to make choices for users, which can be convenient (handles request throttling for a user).` Same APIs, different designs and priorities (imo).

Both are listed in the Twitter Go Clients list https://dev.twitter.com/overview/api/twitter-libraries#go

**Comment by dghubble** [comment]
Many links in the list are named by the third party service. Here, it might be reasonable to label this `go-twitter` instead.

**Comment by shurcooL** [comment]
> Many links in the list are named by the third party service. Here, it might be reasonable to label this `go-twitter` instead.

I think that's a mistake, they should be named after the library name. So yeah, it should be `go-twitter` (which will need to be placed elsewhere due to alphabetization).

> It is designed much like `google/go-github`.

Awesome, thank you for describing the differences! That sounds awesome, I really like `google/go-github` style and I'm glad to hear `go-twitter` follows it (similarly to [`go-travis`](https://github.com/Ableton/go-travis#disclaimer)).

**Comment by shurcooL** [comment]
If you rename it to from `twitter` to `go-twitter` (to match the library name) and ensure correct alphabetize order, this can be merged.

**Comment by shurcooL** [comment]
LGTM. If it's ready from your side, I'll merge?

**Comment by dghubble** [comment]
:+1:

**Comment by shurcooL** [comment]
Thanks for contributing, this looks like an awesome Go package!

**Pull request merged**
