### PR TITLE
Add gitcs

### PR DESCRIPTION
**Pull request by knbr13**
> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc): https://github.com/knbr13/gitcs/
- pkg.go.dev: https://pkg.go.dev/github.com/knbr13/gitcs
- goreportcard.com: https://goreportcard.com/report/github.com/knbr13/gitcs
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://app.codecov.io/gh/knbr13/gitcs/

**Note**: This project is a CLI tool, hence, there is no documentation on `pkg.go.dev` (CLI tool not library, like some other popular CLI tools that don't have documentation on `pkg.go.dev`, example: [air](https://github.com/cosmtrek/air) ).

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below that apply before you submit PR.**
_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines for details._

- [X] The package has been added to the list in alphabetical order.
- [X] The package has an appropriate description with correct grammar.
- [X] As far as I know, the package has not been listed here before.
- [ ] The repo documentation has a pkg.go.dev link.
- [X] The repo documentation has a coverage service link.
- [X] The repo documentation has a goreportcard link.
- [X] The repo has a version-numbered release and a go.mod file.
- [X] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines), [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers) and [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).
- [X] The repo has a continuous integration process that automatically runs tests that must pass before new pull requests are merged.
- [X] Continuous integration is used to attempt to catch issues prior to releasing this package to end-users.

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by cassiobotaro** [comment]
@knbr13 The project lacks tests. See our [Quality Standard](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).

**Comment by vanlucard** [comment]
Do it the balance

**Comment by knbr13** [comment]
@cassiobotaro 
@vanlucard 
Unit tests and coverage service link added.
Thanks for reviewing the PR.

**Comment by Airbaby704** [comment]
Hay first user .how to used ...☺️

**Comment by cassiobotaro** [comment]
@knbr13 The test coverage does not yet adhere to our quality standards. Could you take a look?

**Comment by knbr13** [comment]
@cassiobotaro 
I previously added the unit tests for all of the code, you can took a closer look at the covered lines of code and see what is covered and what's not, the uncovered lines are for lines similar to this: `if err != nil { return ... }`, the tests are covering all of the functionalities and working as expected. 
If still not fulfilling your requirements, then close this PR, and I hope to meet your requirements the next time.

**Comment by cassiobotaro** [comment]
@knbr13 We have decided to close this issue. If you can meet our quality standards, please feel free to submit again. Thank you.

**Pull request closed without merging**
