### PR TITLE
Add golang-templates/seed

### PR DESCRIPTION
**Pull request by pellared**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/golang-templates/seed
- pkg.go.dev: https://pkg.go.dev/github.com/golang-templates/seed
- goreportcard.com: https://goreportcard.com/report/github.com/golang-templates/seed
- coverage service link: https://github.com/golang-templates/seed#how-to-integrate-with-codecov

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: False

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
how can i understand the quality of your go code without testing? Did you put a link explaining how your user uses codecov, but don't take your test?

**Comment by pellared** [comment]
@avelino 
I am not sure if I follow your comment.

>how can i understand the quality of your go code without testing? 

This is just a boilerplate (repository template).
The only Go code is here: https://github.com/golang-templates/seed/tree/master/cmd/seed and it has 100% coverage.

>Did you put a link explaining how your user uses codecov, but don't take your test?

I put instruction how to add codecov integration here: https://github.com/golang-templates/seed#how-to-integrate-with-codecov . Do you think it should be there out-of-the-box (in the template)?  I thought that adding codecov to the template may be too much, but I may change my mind.

**Comment by avelino** [comment]
example not working: https://gocover.io/github.com/golang-templates/seed

**Comment by pellared** [comment]
@avelino, I think you should look at https://gocover.io/github.com/golang-templates/seed/cmd/seed

Anyway, I took some time and added Codecov integration (see more: https://github.com/golang-templates/seed/pull/89). It is thanks to your feedback 😉

**Review by phanirithvij — APPROVED** [review]
@pellared maybe add a test for the main method to cover it https://stackoverflow.com/a/51277293/8608146?

But for a template repository that setups a dev environment, the tests for the example hello world aren't needed in my humble opinion.

**Comment by pellared** [comment]
> @pellared maybe add a test for the main method to cover it https://stackoverflow.com/a/51277293/8608146?
> 
> But for a template repository that setups a dev environment, the tests for the example hello world aren't needed in my humble opinion.

IMO it does not make sense and could lead to learn an anti-pattern: https://martinfowler.com/bliki/AssertionFreeTesting.html

In real code for CLI apps I try to extract whole code to get rid of globals which make unit testing problatic. Main func usually contains no more than https://github.com/pellared/taskflow/blob/master/cli.go and it is not covered. But the rest is. Sometimes I was doing a smoke test which exectues `go run`. It tests the main func without showing the coverage.

Anyway thanks a lot for comment 👍

**Pull request closed without merging**
