### PR TITLE
add go-plotly link

### PR DESCRIPTION
**Pull request by MetalBlueberry**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/MetalBlueberry/go-plotly
- pkg.go.dev: https://pkg.go.dev/mod/github.com/MetalBlueberry/go-plotly?tab=overview 
- goreportcard.com: https://goreportcard.com/report/github.com/MetalBlueberry/go-plotly
- coverage service link not applies

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

I just want to add that I do not include test coverage right now because I do not really know what to test. The library is basically autogenerated structures based on Plotly.js schema to help you to build figures. If it builds... it is a good indication that the code generation works well. It could be tested more deeply comparing the output generated from this package with Plotly.js validation system, but I think that can be really messy.

The small offline package may be suitable for testing when it evolves, right now it exists because it provides a few handy methods for the examples. In real use cases, I think people won't be using that package and rely totally on Pltoly.js to draw the figures.

Thank you for your attention.

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: False

**Comment by avelino** [comment]
review:
- https://goreportcard.com/report/github.com/MetalBlueberry/go-plotly#golint

why doesn't the **test coverage** system apply??

**Comment by MetalBlueberry** [comment]
For the version v0.1.0, the repository is mainly a set of structures to generate plotly.js figures and structures can't be tested apart from testing that the code compiles after generation.
For the few functions provided by the offline package. the output is mainly visual as HTML webpage so I do not know how to automatically test that without using external tooling.

I'm adding more code recently that can be tested. The main problem is that being an autogenerated code, the functions are long. Manually writing test for every case is tedious and automatically generate that test with the same system, feels like faking the coverage.

Thanks for your time :smile:

**Comment by panjf2000** [comment]
It's been more than 15 days without a reply from the PR owner, I'm closing this PR according to our [contributing guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers).

https://goreportcard.com/report/github.com/MetalBlueberry/go-plotly#misspell and https://goreportcard.com/report/github.com/MetalBlueberry/go-plotly#golint are still unfixed.

Feel free to reopen it once you resolve those issues.

**Pull request closed without merging**
