### PR TITLE
Add goseaweedfs (a SeaweedFS client)

### PR DESCRIPTION
**Pull request by linxGnu**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/linxGnu/goseaweedfs
- godoc.org: https://godoc.org/github.com/linxGnu/goseaweedfs
- goreportcard.com: https://goreportcard.com/report/github.com/linxGnu/goseaweedfs
- coverage service link: https://coveralls.io/github/linxGnu/goseaweedfs?branch=master

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by linxGnu** [comment]
Dear @cassiobotaro , I have just fixed lint issue and increase test coverage.

Please check it out again at https://goreportcard.com/report/github.com/linxGnu/goseaweedfs
 and https://coveralls.io/github/linxGnu/goseaweedfs

**Comment by cassiobotaro** [comment]
@linxGnu can you take a look in 
image

**Comment by linxGnu** [comment]
hi @cassiobotaro I fixed gofmt format. 

My codes is not formatted with -s, causing that issue. Please check it again: https://goreportcard.com/report/github.com/linxGnu/goseaweedfs

**Comment by cassiobotaro** [comment]
thanks @linxGnu !

**Comment by linxGnu** [comment]
@cassiobotaro and all. Thanks you a lot for quick review and approved. It's my mistake to modify wrong url in markdown to README.md.

I would update again and make a pull request. Please accept and merge.

**Comment by linxGnu** [comment]
I am so sorry for this inconvenient. 

@cassiobotaro and @crgimenes : I did make another pull request to update url to my goseaweedfs repo. Please accept the merge.

Thanks you so much, you are awesome!

**Pull request merged**
