### PR TITLE
Change repo

### LINKED ISSUE #1816: Package used here is a fork
I found this package https://github.com/aandryashin/ggr , but is a fork of https://github.com/aerokube/ggr
The fork doesn't updated

### PR DESCRIPTION
**Pull request by renatosuero**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/aerokube/ggr
- godoc.org: http://aerokube.com/ggr/latest/
- goreportcard.com: https://goreportcard.com/report/github.com/aerokube/ggr
- coverage service link ([cover.run](https://codecov.io/gh/aerokube/ggr)

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [X] I have added my package in alphabetical order.
- [X] I have an appropriate description with correct grammar.
- [X] I know that this package was not listed before.
- [X] I have added godoc link to the repo and to my pull request.
- [X] I have added coverage service link to the repo and to my pull request.
- [X] I have added goreportcard link to the repo and to my pull request.
- [X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

It closes #1816, I removed kallax(I've sent, but you don't accept, golint < 70% in goreportcard)

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Rebase and squash.

**Comment by robbyoconnor** [comment]
Favor `git pull --rebase` over `git pull` -- and rebase over merging -- as it doesnt make the PR unreadable.

**Comment by renatosuero** [comment]
thank you @robbyoconnor

**Comment by robbyoconnor** [comment]
You didn't do `git pull --rebase`

**Comment by robbyoconnor** [comment]
You also did not squash your commits..

**Comment by renatosuero** [comment]
@robbyoconnor git pull --rebase doesn't do anything , can you help me ?

**Comment by robbyoconnor** [comment]
at this stage -- it won't do anything since there is nothing to pull. I told you to do it for a reason(you wanted your changes placed on top of the remote changes -- not have a merge commit)  -- also you should squash the commits down to 1 of them. I suspect you're capable of this :)

**Pull request merged**
