### PR TITLE
Tripadvisor

### PR DESCRIPTION
**Pull request by mrbenosborne**
**Please provide package links to:**

- github.com repo: https://github.com/mrbenosborne/tripadvisor-golang
- godoc.org: https://godoc.org/github.com/mrbenosborne/tripadvisor-golang
- goreportcard.com: https://goreportcard.com/report/github.com/mrbenosborne/tripadvisor-golang

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by mrbenosborne** [comment]
> https://goreportcard.com/report/github.com/mrbenosborne/tripadvisor-golang

Yes sure, no worries. 👍

**Comment by mrbenosborne** [comment]
@ceriath I have added godoc link to my repo and to the PR :)

**Comment by ceriath** [comment]
@mrbenosborne sorry for the misunderstanding, i was talking about the missing documentation/comments mentioned by golint on https://goreportcard.com/report/github.com/mrbenosborne/tripadvisor-golang#golint

**Comment by mrbenosborne** [comment]
@ceriath All updated :)

**Pull request merged**
