### PR TITLE
Add Hotcoal package

### PR DESCRIPTION
**Pull request by motrboat**
> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc): https://github.com/motrboat/hotcoal
- pkg.go.dev: https://pkg.go.dev/github.com/motrboat/hotcoal
- goreportcard.com: https://goreportcard.com/report/github.com/motrboat/hotcoal
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): generate badge using CI https://github.com/motrboat/hotcoal/blob/main/.github/workflows/coverage.yaml

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below that apply before you submit PR.**
_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines for details._

- [x] The package has been added to the list in alphabetical order.
- [x] The package has an appropriate description with correct grammar.
- [x] As far as I know, the package has not been listed here before.
- [x] The repo documentation has a pkg.go.dev link.
- [x] The repo documentation has a coverage service link.
- [x] The repo documentation has a goreportcard link.
- [x] The repo has a version-numbered release and a go.mod file.
- [x] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines), [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers) and [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).
- [x] The repo has a continuous integration process that automatically runs tests that must pass before new pull requests are merged.
- [x] Continuous integration is used to attempt to catch issues prior to releasing this package to end-users.

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by motrboat** [comment]
please approve @phanirithvij

**Comment by phanirithvij** [comment]
If you don't mind me asking why are you pushing your very first repo to awesome-go?
Did you have a github account before this?

**Comment by motrboat** [comment]
Hello @phanirithvij Thank you for taking a look on my PR. Indeed this is not my first project / repo. Please review my package, and let me know if you're ok to add it to the awesome-go list.

**Comment by motrboat** [comment]
Hey @phanirithvij If you have time to review my package in the following weeks, if you need any help from my side, please let me know. This package helps people to secure their Golang services against SQL injection, and it's very easy to use, so if you can include it in the awesome-go list, that would be great.

**Pull request merged**
