### PR TITLE
authentication: add jeff

### PR DESCRIPTION
**Pull request by abraithwaite**
**Please provide package links to:**

- github.com repo: https://github.com/abraithwaite/jeff
- godoc.org: https://godoc.org/github.com/abraithwaite/jeff
- goreportcard.com: https://goreportcard.com/report/github.com/abraithwaite/jeff
- coverage service link: https://circleci.com/gh/abraithwaite/jeff/64 (under tests header)

Very good coverage

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by ceriath** [comment]
No idea what was up with this PR, seems like it was forgotten to tell you what issues there are.
However, please fix https://goreportcard.com/report/github.com/abraithwaite/jeff#golint

**Comment by abraithwaite** [comment]
Fixed all the changes I could in go lint.  Don't want to break users by changing the package names.  The go generate tag at the top of the file isn't a package doc, so that probably shouldn't trigger golint.

**Comment by abraithwaite** [comment]
@avelino, anything else I'm missing here? :-)

**Pull request merged**
