### PR TITLE
add a new networking lib

### PR DESCRIPTION
**Pull request by baiyutang**
> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc):https://github.com/cloudwego/netpoll
- pkg.go.dev:https://pkg.go.dev/github.com/cloudwego/netpoll
- goreportcard.com:https://goreportcard.com/report/github.com/cloudwego/netpoll
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.):https://gocover.io/github.com/cloudwego/netpoll

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below before you submit PR:**
_not every repository (project) will fit into every option, but most projects should_

- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Review by avelino — CHANGES_REQUESTED** [review]
need links, read pull request template

**Comment by baiyutang** [comment]
> need links, read pull request template

done! I have edited it

**Review by avelino — CHANGES_REQUESTED** [review]
review:
- gofmt https://goreportcard.com/report/github.com/cloudwego/netpoll#gofmt
- coverage `>= 80%`, today is `71.7%` by gocover.io

**Comment by baiyutang** [comment]
> review:
> 
> * gofmt https://goreportcard.com/report/github.com/cloudwego/netpoll#gofmt
> * coverage `>= 80%`, today is `71.7%` by gocover.io

ok, I will improve it.

**Comment by joway** [comment]
@baiyutang @avelino hi, I think it's a bug of goreportcard. As same as https://github.com/gojp/goreportcard/issues/314 mentioned, we use many of "+build" tags in our codes, and goreportcard cannot detect it but mark it as an error.

Another interesting thing is that I use the `gofmt -s  -w *.go` in my environment and cannot find any warning or modification. So I think it's not a gofmt's bug too. What's the goreportcard's gofmt version?

**Review by phanirithvij — CHANGES_REQUESTED** [review]
@baiyutang @joway current coverage report is 72.9%, is it possible/convenient to improve it?

**Comment by phanirithvij** [comment]
Coverage report as of today https://github.com/cloudwego/netpoll/runs/4837066057?check_suite_focus=true#step:8:109

**Pull request merged**
