### PR TITLE
Add gofeed

### PR DESCRIPTION
**Pull request by mmcdole**
Submitting a request to add [gofeed](https://github.com/mmcdole/gofeed), a feed parser, to awesome-go.

Please provide package links to:
- godoc.org: https://godoc.org/github.com/mmcdole/gofeed
- goreportcard.com: https://goreportcard.com/report/github.com/mmcdole/gofeed
- gocover.io: https://gocover.io/github.com/mmcdole/gofeed

Make shure that you've checked the boxes below before you submit PR:
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link
- [x] I have added gocover.io link
- [x] I have added goreportcard link
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@mmcdole thanks for your contribution. please fix low coverage on `feedparser.go`. also please add some examples to godoc. thanks.

**Comment by mmcdole** [comment]
@kirillDanshin I've added some `feedparser` examples and boosted the code coverage for that file.  

I also have around ~300 test cases devoted to the `Atom` and `RSS` packages.  I have some outstanding GH issues for adding some more translator tests, but they are a work in progress.

**Comment by mmcdole** [comment]
@kirillDanshin let me know if you need anything else before this gets merged.

**Comment by kirillDanshin** [comment]
@mmcdole looks good, merged

**Pull request merged**
