### PR TITLE
Add shabbyrobe/xmlwriter, create XML section

### PR DESCRIPTION
**Pull request by shabbyrobe**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/shabbyrobe/xmlwriter
- godoc.org: https://godoc.org/github.com/shabbyrobe/xmlwriter
- goreportcard.com: https://goreportcard.com/report/github.com/shabbyrobe/xmlwriter
- coverage service link cover.run go

Very good coverage: the unit test coverage is about 85%, but there is a separate tester in the repo which absolutely smashes the library with a huge corpus of test cases - every xml file on your hard drive can be used to drive the tester (about 80,000 on my computer). This tester has flushed out a crazy amount of bugs.

I created an XML section with all the existing XML repos as there isn't one and I think there should be.

Also, the Windows section was in the wrong spot in the file relative to the contents so I moved it into place.

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by shabbyrobe** [comment]
Golint errors fixed. Remaining golint errors are missing documentation warnings for testing package not intended to be used publicly.

**Comment by cassiobotaro** [comment]
@shabbyrobe if "not intended to be used publicly", please use lower case in their names. Gocyclo is also very high.

**Comment by shabbyrobe** [comment]
Fixed remaining golint errors
Fixed functions with high complexity(gocyclo)

**Comment by shabbyrobe** [comment]
@cassiobotaro, is this OK now?

**Pull request merged**
