### PR TITLE
Added Golang Crypto Trading Bot to "other software section"

### PR DESCRIPTION
**Pull request by saniales**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

Done

**Please provide package links to:**

- github.com repo: https://github.com/saniales/golang-crypto-trading-bot
- godoc.org: https://godoc.org/github.com/saniales/golang-crypto-trading-bot
- goreportcard.com: https://goreportcard.com/report/github.com/saniales/golang-crypto-trading-bot
- coverage service link : https://travis-ci.org/saniales/golang-crypto-trading-bot

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [X] I have added my package in alphabetical order.
- [X] I have an appropriate description with correct grammar.
- [X] I know that this package was not listed before.
- [X] I have added godoc link to the repo and to my pull request.
- [X] I have added coverage service link to the repo and to my pull request.
- [X] I have added goreportcard link to the repo and to my pull request.
- [X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by saniales** [comment]
Please let me know if I have to change something or provide extra information

**Comment by saniales** [comment]
tests on travis are now working (they depended on a third library compilation error, not directly related to the bot, I made a pr and made the dev merge it)
regarding the goreport card? you need at least which % of score?

**Comment by ceriath** [comment]
Alright thats good now! 
But it seems like you don't have any kind of tests right now? (Travis works, but isnt actually a coverage service like cover.run or gocover.io)

**Comment by saniales** [comment]
The reason of the absence of coverage is due to the fact that all exchange libraries are external and full coverage would be impossible. This software is used in production for a lot of trading bots. 
If you advise any free coverage service for open source projects I will integrate it

**Comment by ceriath** [comment]
Well, there is https://cover.run and https://gocover.io

However, i can totally see why this is hard to test. Are you going to add coverage where possible, then i'll wait, otherwise i am just going to approve this

**Comment by saniales** [comment]
You can approve, but in any case in later versions I will try to add coverage
Thanks for the amazing opportunity

**Comment by saniales** [comment]
@ceriath how does tagging work now? what's after pending-review?

**Comment by ceriath** [comment]
next is a second review and merge on approval :)

**Comment by saniales** [comment]
Awesome, see you soon then

**Comment by cassiobotaro** [comment]
Thanks @saniales !

**Comment by saniales** [comment]
You're welcome

**Pull request merged**
