### PR TITLE
Added asdine/storm

### PR DESCRIPTION
**Pull request by asdine**

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@asdine please, provide links to godoc, gocover and goreportcard.

**Comment by asdine** [comment]
Sure :

- gocover: [https://gocover.io/github.com/asdine/storm](https://gocover.io/github.com/asdine/storm)
- godoc: [https://godoc.org/github.com/asdine/storm](https://godoc.org/github.com/asdine/storm)
- goreportcart: [https://goreportcard.com/report/github.com/asdine/storm](https://goreportcard.com/report/github.com/asdine/storm)

Let me know if something is missing

Thank you!

**Comment by kirillDanshin** [comment]
@asdine please add tests for `storm.OpenWithOptions`, `*DB.Init()`. also, maybe it's possible to solve gocyclo issues? thanks!

**Comment by asdine** [comment]
@kirillDanshin The repo has been updated

**Comment by kirillDanshin** [comment]
@asdine please add godoc examples, comment errors and I'll merge it. thanks!

**Comment by bep** [comment]
I didn't notice this. Storm has now been added, so this can be closed.

**Comment by asdine** [comment]
Thank you @bep!

**Comment by avelino** [comment]
thanks @bep

**Pull request closed without merging**
