### PR TITLE
add Oto

### PR DESCRIPTION
**Pull request by faiface**
Hi! Oto is a low-level audio library for directly streaming audio samples to your speakers. Very simple, very useful.

GitHub: https://github.com/hajimehoshi/oto
GoDoc: https://godoc.org/github.com/hajimehoshi/oto
Go Report Card: https://goreportcard.com/report/github.com/hajimehoshi/oto

### CODE REVIEW

**Comment by faiface** [comment]
Hi! Thanks for the review, I'll address the concerns.

Regarding coverage. This is not a library that can be unit tested. It's all about direct hardware interaction. It either works, or it doesn't, but there's no way to find out by tests.

Regarding Go Report Card. The first two (possible misuse of `unsafe.Pointer`) are false positives. It's a low-level library that calls to C and requires working with `unsafe.Pointer`. The next four could be fixed, but are concering internal packages that are not to be imported by anyone outside. The last two definitely could be fixed. @hajimehoshi letting you know.

**Comment by hajimehoshi** [comment]
Hi @faiface, thank you for sending this PR!

I'm Hajime, one of the authors of Oto.

Actually I sent a PR before https://github.com/avelino/awesome-go/pull/1472 but gave up since `go vet` would never be satisfied for Oto's `unsafe.Pointer` usages. Another reason is that it would be really hard to write unittests for Oto since Oto uses low-level API for sounds.

> The last two definitely could be fixed.

Yes, but I doubt just fixing them would not make sense to satisfy golint...

**Comment by faiface** [comment]
@cassiobotaro Ping. I think all of the concerns have been addressed. Your quality standards say that tests should be where possible, well, they are not really possible here.

This package is absolutely essential for audio playback and I'm sure it deserves a place in Awesome Go.

I'll be happy to respond to more concerns, if you have some.

**Comment by faiface** [comment]
@cassiobotaro ping

**Comment by ceriath** [comment]
Please fix https://goreportcard.com/report/github.com/hajimehoshi/oto#golint and https://goreportcard.com/report/github.com/hajimehoshi/oto#misspell

**Comment by faiface** [comment]
@ceriath All fixed by [this PR](https://github.com/hajimehoshi/oto/pull/72).

**Comment by ceriath** [comment]
@faiface thanks!

**Pull request merged**
