### PR TITLE
Add CORS and XFF middlewares

### PR DESCRIPTION
**Pull request by rs**

### CODE REVIEW

**Comment by eMxyzptlk** [comment]
:+1:

**Comment by dukex** [comment]
Hi @rs, Do you can explain more this new subsection "Actual middlewares" ?

**Comment by rs** [comment]
The other subsection is about frameworks to build/bind middlewares, not actual middlewares.

**Comment by mholt** [comment]
He does have a point. LGTM. :+1:

**Comment by dukex** [comment]
Nice, I only think is necessary update the subsections to be like others subsections, e.g:

https://github.com/avelino/awesome-go#database-drivers
https://github.com/avelino/awesome-go#testing
https://github.com/avelino/awesome-go#text-processing

**Comment by rs** [comment]
You want me to create two sub sections inside middleware?

**Comment by mholt** [comment]
Sure - might as well

**Comment by rs** [comment]
done

**Comment by dukex** [comment]
Nice @rs, do you can fix the build?

**Comment by rs** [comment]
Fixed

**Comment by dukex** [comment]
Thanks @rs

**Pull request merged**
