### PR TITLE
Add CRUD to ORM libraries

### PR DESCRIPTION
**Pull request by azer**
:boom:

### CODE REVIEW

**Comment by avelino** [comment]
pls readme https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md
http://goreportcard.com/report/azer/crud

**Comment by azer** [comment]
@avelino goreportcard only says "this function should have comment", which is not really necessary for self documenting code.

**Comment by azer** [comment]
Do you require all projects to comment every single function and variable in the repo ?

**Comment by matrixik** [comment]
`golint` want all **exported** functions, methods and types to have documentation. It doesn't check documentation for unexported one.

**Comment by azer** [comment]
@matrixik fine, and should that be requirement for making our library discoverable in this list ?

**Comment by matrixik** [comment]
Well it's in https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard

**Comment by azer** [comment]
crud is way more tested and documented than many libraries in the readme. I see a double standard here but nevermind, I'm not gonna sit down and comment every global variable and function to make my library show up in this list.

**Comment by matrixik** [comment]
Sorry to disappoint you.

**Pull request closed without merging**
