### PR TITLE
Add remember-go

### PR DESCRIPTION
**Pull request by pjebs**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/rocketlaunchr/remember-go/
- godoc.org: https://godoc.org/github.com/rocketlaunchr/remember-go
- goreportcard.com: https://goreportcard.com/report/github.com/rocketlaunchr/remember-go
- coverage service link: https://gocover.io/github.com/rocketlaunchr/remember-go

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [ *] I have added my package in alphabetical order.
- [ *] I have an appropriate description with correct grammar.
- [ *] I know that this package was not listed before.
- [ *] I have added godoc link to the repo and to my pull request.
- [ *] I have added coverage service link to the repo and to my pull request.
- [ *] I have added goreportcard link to the repo and to my pull request.
- [* ] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by pjebs** [comment]
Addresses concerns in https://github.com/avelino/awesome-go/pull/2594 @kirillDanshin

**Comment by kirillDanshin** [comment]
@pjebs 

Your license states

```
The usage of this software must not be knowingly used for an application
that will be directly or indirectly used for military purposes.
```

when you build a a caching proxy or something like this, you know that your project may be used everywhere. Therefore, the "... indirectly ..." clause allows you to revoke license at any time as long as you know that the project that was built using your library is used somewhere in military. How a developer is supposed to prove that he didn't know about that possibility? There's a second option, to also deny military usage of a project that was built using your library, which is basically affects other projects recursively. I think I know what you were trying to state there, but atm your license looks quite dangerous to me.

**Comment by pjebs** [comment]
How is it relevant for awesome go? A user can read it and decide for themselves.

**Comment by kirillDanshin** [comment]
@pjebs there's no way people can trust our list if we recommend a project with dangerous license conditions.

**Comment by kirillDanshin** [comment]
@ceriath what do you think about this case? seems like this PR is related to #2712

**Comment by pjebs** [comment]
Awesome go is just a curated list of awesome packages. I make it quite clear the licensee is modified from standard MIT so user will read it and decide for themselves. 

Why should awesome go also dictate the licensee type?

**Comment by pjebs** [comment]
In terms of recursive nature of licensee. GPL based licensees are far more dangerous.

**Comment by kirillDanshin** [comment]
@pjebs I don't think we should _dictate_ license type, instead I think we should work out a ruleset and maybe a way to mark package with custom or GPL based license. in this case, I think license modification should be at least documented in the readme, but still this license is far too dangerous and I don't think that the license effects will be obvious to everyone who'll read it.

**Comment by pjebs** [comment]
image


How is this not clear that the license is not a standard MIT license?

**Comment by kirillDanshin** [comment]
@pjebs I'm talking about documenting the difference itself, I know you documented the use of modified license

**Comment by pjebs** [comment]
Okay I understand.

How about: 
image

This emoji next to my package??? You can write at the top of the readme that this symbol means a non-standand Open-source license.

**Comment by kirillDanshin** [comment]
@pjebs I'm still thinking about it, I already considered ⚠️ but I think this emoji can also be unclear. maybe, it's time to even consider adding a license name to the line format. I'm trying to come up with something simple and clean, but also really easy to understand, but it's quite tricky

**Comment by ceriath** [comment]
I'd say it's up to the person considering to use any library here to check the license of the project they want to use. Currently we do not state anything about licenses on this list, so it is up to the developers themselves. Maybe we could add the license to the list, but using a "warning" sign or something like that might not be the best idea, since some people might get scared for no reason to check out a library.
Therefore, i'd say merge it if it meets all the criterias, but this might be another reason to move forward with #2712

**Comment by pjebs** [comment]
The first time it loads directly from slowquery closure. Second time it loads from cache. So it's just warning up the cache.

**Comment by ceriath** [comment]
it's an ineffective assignment tho, as correctly reported by reportcard. Could you fix it?

**Comment by pjebs** [comment]
fixed up

**Comment by pjebs** [comment]
@kirillDanshin How about you let it through until you decide on your license package.

**Pull request merged**
