### PR TITLE
Adding go-mysql-lock

### PR DESCRIPTION
**Pull request by sanketplus**
**Please provide package links to:**

- github.com repo: https://github.com/sanketplus/go-mysql-lock
- pkg.go.dev: https://godoc.org/github.com/sanketplus/go-mysql-lock
- goreportcard.com: https://goreportcard.com/report/github.com/sanketplus/go-mysql-lock
- coverage service link: https://dev.azure.com/sanketplus/go-mysql-lock/_build/results?buildId=32&view=codecoverage-tab

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: False

**Comment by sanketplus** [comment]
@panjf2000 🙋‍♂️ coverage is coming from azure's pipeline and not from the tools people generally use. hope that'd be okay

**Comment by sanketplus** [comment]
done @panjf2000

**Comment by panjf2000** [comment]
Your coverage page is too slow to check out the result, what's the amount of the coverage?

**Comment by sanketplus** [comment]
Azure is acting up and the coverage tab is not loading. But here the same stat from execution log @panjf2000 it stands at 100%
image

**Comment by sanketplus** [comment]
Execution logs: https://dev.azure.com/sanketplus/go-mysql-lock/_build/results?buildId=39&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=5caf77c8-9b10-50ef-b5c7-ca89c63e1c86

**Pull request merged**
