### PR TITLE
 	Added some more libraries

### PR DESCRIPTION
**Pull request by pjebs**

### CODE REVIEW

**Comment by avelino** [comment]
pls check
http://goreportcard.com/report/pjebs/optimus-go
http://goreportcard.com/report/pjebs/restgate
http://goreportcard.com/report/pjebs/tokbox
http://goreportcard.com/report/pjebs/jsonerror

all libs with the low lint

**Comment by pjebs** [comment]
What is the minimum lint level rating allowed?

**Comment by shurcooL** [comment]
I don't think we have an exact number in our quality standard description:

https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard

But I expect lint scores should be quite high, 100% or at least 90-95% if there are some unavoidable false positives. Is there a valid reason to have a lower lint issue percentage?

**Comment by pjebs** [comment]
No, I'll fix up my libraries soon.

**Comment by avelino** [comment]
new rules 8 days with label `pending-submitter-response`: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers

**Pull request closed without merging**
