### PR TITLE
Add github.com/pascaldekloe/metrics

### PR DESCRIPTION
**Pull request by pascaldekloe**
https://github.com/pascaldekloe/metrics

[godoc](https://godoc.org/github.com/pascaldekloe/metrics)
[Go Report Card](https://goreportcard.com/report/github.com/pascaldekloe/metrics)
[cover.run](https://cover.run/go?tag=golang-1.10&repo=github.com%2Fpascaldekloe%2Fmetrics)

- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by pascaldekloe** [comment]
Are the coverage and Go report card links in the repository really necessary?

**Comment by cassiobotaro** [comment]
@pascaldekloe not necessary in your repo, only in PR description.

**Comment by pascaldekloe** [comment]
The vet errors looks like a bug. Both identifiers do exist (as a function). Also, godoc links the [examples](https://godoc.org/github.com/pascaldekloe/metrics#example-Must1LabelHistogram) correctly.

The linter warning is about missing documentation on the package [variables](https://godoc.org/github.com/pascaldekloe/metrics/gostat#pkg-variables). However, I think that this is a rare exception in which comments would actually harm documentation. Comment lines inbetween the metrics could distract from the "help" string arguments.

**Comment by pascaldekloe** [comment]
The godoc warning was resolved by a block comment. So that's why the warning was only about the last variable. 😁 Please let me know if you have any suggestions on the vet issue @cassiobotaro.

**Comment by ceriath** [comment]
@pascaldekloe Usually for _test.go files you would prefix functions with ``Test``. I think the issue might be that it is declared to be a test ``package metrics_test`` but does not contain any?
Or maybe renaming ``ExampleMust2LabelHistogram`` to ``Example_Must2LabelHistogram`` like the other functions helps? 

However, i also opened pascaldekloe/metrics#1 to further discuss it, since it should not really affect merging it

**Pull request merged**
