### PR TITLE
Add studygolang.com and ebook

### PR DESCRIPTION
**Pull request by polaris1119**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by cassiobotaro** [comment]
> I am fine with adding the community, however i am not entirely sure about the tutorial, since technically we have a requirement `Thoroughly documented (README, godoc comments, etc.) in english language, so everyone is able to understand the project's intention and how it works`
> I can totally see why a tutorial would not be multilingual and i do not want to reject it simply because of that. But i think it should at least be mentioned in the description, for example by changing it to
> 
> ```
> * [The Golang Standard Library by Example (Chinese)](https://github.com/polaris1119/The-Golang-Standard-Library-by-Example)
> ```
> 
> resulting in
> 
> * [The Golang Standard Library by Example (Chinese)](https://github.com/polaris1119/The-Golang-Standard-Library-by-Example)
> 
> Opinions?
> cc @avelino @cassiobotaro

Agree with you about specify the language. @polaris1119, can you fix it please?

**Comment by polaris1119** [comment]
OK~ Thank you

**Comment by avelino** [comment]
@polaris1119 update pls

**Comment by polaris1119** [comment]
had updated

**Pull request merged**
