### PR TITLE
Add goss, a server testing/validation tool

### PR DESCRIPTION
**Pull request by aelsabbahy**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- godoc.org: https://godoc.org/github.com/aelsabbahy/goss
- goreportcard.com: https://goreportcard.com/report/github.com/aelsabbahy/goss
- gocover.io or coveralls: 

Note, that new categories can be added only when there are 3 packages or more.

Make sure that you've checked the boxes below before you submit PR:
- [X] I have added my package in alphabetical order
- [X] I know that this package was not listed before
- [X] I have added godoc link to the repo and to my pull request
- [ ] I have added gocover.io or coveralls link to the repo and to my pull request
- [X] I have added goreportcard link to the repo and to my pull request
- [X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by aelsabbahy** [comment]
First of all, thank you for creating awesome-go, great reference!

That said, I would love to get feedback on this PR if there's stuff I need to do.

**Comment by kirillDanshin** [comment]
hi @aelsabbahy 
thanks.
please fix the links and goss documentation.

**Comment by avelino** [comment]
Pls read and resend PR: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md

**Comment by aelsabbahy** [comment]
Most of the Goss tests are done through integration tests utilizing docker. Would that be acceptable?

**Pull request closed without merging**
