### PR TITLE
ginrpc

### PR DESCRIPTION
**Pull request by xxjwxc**
Gin parameter automatic binding tool

Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo:https://github.com/xxjwxc/ginrpc
- godoc.org:https://godoc.org/github.com/xxjwxc/ginrpc
- goreportcard.com:https://goreportcard.com/report/github.com/xxjwxc/ginrpc
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.) https://gocover.io/github.com/xxjwxc/ginrpc

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by xxjwxc** [comment]
> To improve readabilty, `Newctx` in https://github.com/xxjwxc/ginrpc/blob/master/base/api/context.go#L16 should be `NewCtx` or `NewContext`
> 
> also, translating the comments would be nice

hi,I optimized it according to your suggestion.please reexamine

**Comment by xxjwxc** [comment]
> To improve readabilty, `Newctx` in https://github.com/xxjwxc/ginrpc/blob/master/base/api/context.go#L16 should be `NewCtx` or `NewContext`
> 
> also, translating the comments would be nice

I want to set comments in bilingual.

**Comment by ceriath** [comment]
@xxjwxc bilingual would be totally fine, however, in this file, i am missing the english versions of the comments https://github.com/xxjwxc/ginrpc/blob/master/base/api/context.go

**Comment by ceriath** [comment]
oh nvm, i just saw your explanation on #2723

**Comment by xxjwxc** [comment]
thx.

**Comment by xxjwxc** [comment]
> @xxjwxc bilingual would be totally fine, however, in this file, i am missing the english versions of the comments https://github.com/xxjwxc/ginrpc/blob/master/base/api/context.go

I did a new translation and tried to make it better.what about now ?
https://github.com/xxjwxc/ginrpc/blob/master/base/api/context.go

**Comment by xxjwxc** [comment]
> @xxjwxc bilingual would be totally fine, however, in this file, i am missing the english versions of the comments https://github.com/xxjwxc/ginrpc/blob/master/base/api/context.go

I did the translation to make it better.

**Pull request merged**
