### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vulogov**
Add ThreadComputation module in Embedding languages section

> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc):
- pkg.go.dev:
- goreportcard.com:
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.):

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below before you submit PR:**
_not every repository (project) will fit into every option, but most projects should_

- [ ] I have added my package in alphabetical order.
- [ ] I have an appropriate description with correct grammar.
- [ ] I know that this package was not listed before.
- [ ] I have added pkg.go.dev link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request.
- [ ] I have added goreportcard link to the repo and to my pull request.
- [ ] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: False
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by vulogov** [comment]
Which links ? I've submitted link to the code repo.

**Comment by phanirithvij** [comment]
@vulogov
repo link (github.com, gitlab.com, etc):
pkg.go.dev:
goreportcard.com:
coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.):

**Comment by vulogov** [comment]
README.md aslo updated with links

https://pkg.go.dev/github.com/vulogov/ThreadComputation
https://github.com/vulogov/ThreadComputation

**Comment by avelino** [comment]
> goreportcard.com:
> coverage service link

goreportcard.com:?
coverage service link?

the links must be placed here in the PR (in the body)

**Comment by vulogov** [comment]
https://goreportcard.com/report/github.com/vulogov/ThreadComputation

**Comment by vulogov** [comment]
Forget it. You are referring me to use commercial products for code coverage.

**Comment by phanirithvij** [comment]
@vulogov gocover isn't commercial.
And all of the listed coverage solutions are 100% free for opensource projects.
And everyone who added their project to awesome-go uses one.
And github is commercial.

**Comment by vulogov** [comment]
gocover said that it can not retrieve report from goreportcard and in others, I did not find how to submit to cover, but find the payment option. github doesn't charges me. Well, like I said, I rather focus on the code.

**Comment by phanirithvij** [comment]
Code coverage is a must for any open-source project that takes itself seriously.
That is why this is a requirement in awesome-go.

You are free to choose the code coverage option. There's no need to use one of the listed ones above.
If you don't want to choose a code coverage solution, you can provide instructions on how to test your project, which platforms it can be tested on, and mention how much the current code coverage is.

Coveralls and codecov don't ask for your payment info or charge you upfront, and you need to read their docs to know how to use them.
Or you can take a look at one of the projects listed here in the readme that uses coveralls or codecov and see how they have done it.

Usually, everyone uses github-actions, and there is a github action for almost every one of the listed code coverage solutions.

**Comment by vulogov** [comment]
I am preparing a test cases as I am progress with development. Github action has been set-up

https://github.com/vulogov/ThreadComputation/actions

**Comment by vulogov** [comment]
go build -v ./...
go test -v
=== RUN   TestBlock1
--- PASS: TestBlock1 (0.00s)
=== RUN   TestBlock2
--- PASS: TestBlock2 (0.00s)
=== RUN   TestEval2
--- PASS: TestEval2 (0.00s)
=== RUN   TestEval6
--- PASS: TestEval6 (0.00s)
=== RUN   TestEval21
--- PASS: TestEval21 (0.00s)
=== RUN   TestEval3
--- PASS: TestEval3 (0.00s)
=== RUN   TestEval31
--- PASS: TestEval31 (0.00s)
=== RUN   TestEval4
--- PASS: TestEval4 (0.00s)
=== RUN   TestEval41
--- PASS: TestEval41 (0.00s)
=== RUN   TestEval5
--- PASS: TestEval5 (0.00s)
=== RUN   TestEval51
--- PASS: TestEval51 (0.00s)
=== RUN   TestCmp1
--- PASS: TestCmp1 (0.00s)
=== RUN   TestCmp2
--- PASS: TestCmp2 (0.00s)
=== RUN   TestCmp3
--- PASS: TestCmp3 (0.00s)
=== RUN   TestCmp31
--- PASS: TestCmp31 (0.00s)
=== RUN   TestCmp4
--- PASS: TestCmp4 (0.00s)
=== RUN   TestCmp5
--- PASS: TestCmp5 (0.00s)
=== RUN   TestCmp51
--- PASS: TestCmp51 (0.00s)
=== RUN   TestStack1
--- PASS: TestStack1 (0.00s)
=== RUN   TestStack2
--- PASS: TestStack2 (0.00s)
=== RUN   TestStack3
--- PASS: TestStack3 (0.00s)
=== RUN   TestStack4
--- PASS: TestStack4 (0.00s)
=== RUN   TestStack5
--- PASS: TestStack5 (0.00s)
=== RUN   TestStack6
--- PASS: TestStack6 (0.00s)
=== RUN   TestStack7
--- PASS: TestStack7 (0.00s)
=== RUN   TestStack8
--- PASS: TestStack8 (0.00s)
=== RUN   TestStack9
--- PASS: TestStack9 (0.00s)
=== RUN   TestStack10
--- PASS: TestStack10 (0.00s)
=== RUN   TestString1
--- PASS: TestString1 (0.00s)
=== RUN   TestString2
--- PASS: TestString2 (0.00s)
=== RUN   TestString3
--- PASS: TestString3 (0.00s)
=== RUN   TestStdlib1
42
--- PASS: TestStdlib1 (0.00s)
=== RUN   TestStdlib11
42
--- PASS: TestStdlib11 (0.00s)
=== RUN   TestStdlib2
Hello world
--- PASS: TestStdlib2 (0.00s)
=== RUN   TestStdlib3
3.14
--- PASS: TestStdlib3 (0.00s)
=== RUN   TestStdlib4
true
--- PASS: TestStdlib4 (0.00s)
=== RUN   TestStdlib5
1
2
3
--- PASS: TestStdlib5 (0.00s)
=== RUN   TestStdlib6
3
2
1
--- PASS: TestStdlib6 (0.00s)
=== RUN   TestStdlib7
3
2
1
--- PASS: TestStdlib7 (0.00s)
=== RUN   TestStdlib8
--- PASS: TestStdlib8 (0.00s)
=== RUN   TestStdlib9
--- PASS: TestStdlib9 (0.00s)
=== RUN   TestStdlib10
--- PASS: TestStdlib10 (0.00s)
=== RUN   TestStdlib12
--- PASS: TestStdlib12 (0.00s)
=== RUN   TestStdlib13
`print
--- PASS: TestStdlib13 (0.00s)
=== RUN   TestStdlib131
`print[ 42 41 40 39 ]
--- PASS: TestStdlib131 (0.00s)
=== RUN   TestStdlib14
--- PASS: TestStdlib14 (0.00s)
=== RUN   TestStdlib141
--- PASS: TestStdlib141 (0.00s)
=== RUN   TestStdlib1412
--- PASS: TestStdlib1412 (0.00s)
=== RUN   TestStdlibMath1
--- PASS: TestStdlibMath1 (0.00s)
=== RUN   TestStdlibMath2
--- PASS: TestStdlibMath2 (0.00s)
=== RUN   TestStdlibMath3
--- PASS: TestStdlibMath3 (0.00s)
=== RUN   TestStdlibMath4
--- PASS: TestStdlibMath4 (0.00s)
=== RUN   TestStdlibMath5
--- PASS: TestStdlibMath5 (0.00s)
=== RUN   TestStdlibMath6
--- PASS: TestStdlibMath6 (0.00s)
=== RUN   TestStdlibMath61
--- PASS: TestStdlibMath61 (0.00s)
=== RUN   TestStdlibMath7
--- PASS: TestStdlibMath7 (0.00s)
=== RUN   TestStdlibMath8
--- PASS: TestStdlibMath8 (0.00s)
=== RUN   TestStdlibMath9
--- PASS: TestStdlibMath9 (0.00s)
=== RUN   TestStdlibMath10
--- PASS: TestStdlibMath10 (0.00s)
=== RUN   TestStdlibMath11
--- PASS: TestStdlibMath11 (0.00s)
=== RUN   TestStdlibMath12
--- PASS: TestStdlibMath12 (0.00s)
=== RUN   TestStdlibMath13
--- PASS: TestStdlibMath13 (0.00s)
=== RUN   TestStdlibMath14
--- PASS: TestStdlibMath14 (0.00s)
=== RUN   TestStdlibMath15
--- PASS: TestStdlibMath15 (0.00s)
=== RUN   TestStdlibMath16
--- PASS: TestStdlibMath16 (0.00s)
=== RUN   TestStdlibMath17
--- PASS: TestStdlibMath17 (0.00s)
=== RUN   TestStdlibMath18
--- PASS: TestStdlibMath18 (0.00s)
=== RUN   TestStdlibMath19
--- PASS: TestStdlibMath19 (0.00s)
=== RUN   TestStdlibMath20
--- PASS: TestStdlibMath20 (0.00s)
=== RUN   TestStdlibMath21
--- PASS: TestStdlibMath21 (0.00s)
=== RUN   TestStdlib15
--- PASS: TestStdlib15 (0.00s)
=== RUN   TestStdlib16
--- PASS: TestStdlib16 (0.00s)
=== RUN   TestStdlib17
--- PASS: TestStdlib17 (0.00s)
=== RUN   TestStdlib18
--- PASS: TestStdlib18 (0.00s)
=== RUN   TestStdlib19
--- PASS: TestStdlib19 (0.00s)
=== RUN   TestVfs1
--- PASS: TestVfs1 (0.00s)
=== RUN   TestVfs2
--- PASS: TestVfs2 (0.01s)
=== RUN   TestVfs3
--- PASS: TestVfs3 (0.01s)
=== RUN   TestVfs4
--- PASS: TestVfs4 (0.00s)
=== RUN   TestFunc1
ERRO[0000] Function: FunctionNotExists not found
--- PASS: TestFunc1 (0.00s)
=== RUN   TestFunc11
--- PASS: TestFunc11 (0.00s)
=== RUN   TestFunc12
--- PASS: TestFunc12 (0.00s)
=== RUN   TestFunc13
ERRO[0000] Function: FunctionNotExists not found
--- PASS: TestFunc13 (0.00s)
=== RUN   TestFunc2
--- PASS: TestFunc2 (0.00s)
=== RUN   TestFunc3
42
--- PASS: TestFunc3 (0.00s)
=== RUN   TestFunc31
--- PASS: TestFunc31 (0.00s)
=== RUN   TestFunc32
--- PASS: TestFunc32 (0.00s)
=== RUN   TestFunc4
--- PASS: TestFunc4 (0.00s)
=== RUN   TestFunc41
--- PASS: TestFunc41 (0.00s)
=== RUN   TestFunc5
--- PASS: TestFunc5 (0.00s)
=== RUN   TestFunc51
--- PASS: TestFunc51 (0.00s)
=== RUN   TestInitTS
--- PASS: TestInitTS (0.00s)
=== RUN   TestSetGet
--- PASS: TestSetGet (0.00s)
=== RUN   TestTake
--- PASS: TestTake (0.00s)
=== RUN   TestMode
--- PASS: TestMode (0.00s)
=== RUN   TestLeftRight
--- PASS: TestLeftRight (0.00s)
=== RUN   TestGLen
--- PASS: TestGLen (0.00s)
=== RUN   TestLen
--- PASS: TestLen (0.00s)
=== RUN   TestQ
--- PASS: TestQ (0.00s)
=== RUN   TestDel
--- PASS: TestDel (0.00s)
=== RUN   TestUUID
--- PASS: TestUUID (0.00s)
=== RUN   TestUserFunc1
--- PASS: TestUserFunc1 (0.00s)
=== RUN   TestUserFunc2
--- PASS: TestUserFunc2 (0.00s)
=== RUN   TestUserFunc3
--- PASS: TestUserFunc3 (0.00s)
=== RUN   TestUserFunc4
--- PASS: TestUserFunc4 (0.00s)
=== RUN   TestUserFunc5
--- PASS: TestUserFunc5 (0.00s)
=== RUN   TestUserFunc6
--- PASS: TestUserFunc6 (0.00s)
=== RUN   TestUserFunc7
--- PASS: TestUserFunc7 (0.00s)
=== RUN   TestUserFunc8
--- PASS: TestUserFunc8 (0.00s)
=== RUN   TestUserFunc10
--- PASS: TestUserFunc10 (0.00s)
=== RUN   TestVars1
--- PASS: TestVars1 (0.00s)
=== RUN   TestVars11
--- PASS: TestVars11 (0.00s)
=== RUN   TestVars2
--- PASS: TestVars2 (0.00s)
=== RUN   TestVars3
--- PASS: TestVars3 (0.00s)
=== RUN   TestVars4
--- PASS: TestVars4 (0.00s)
=== RUN   TestVars6
--- PASS: TestVars6 (0.00s)
=== RUN   TestVars7
--- PASS: TestVars7 (0.00s)
=== RUN   TestInit
--- PASS: TestInit (0.00s)
=== RUN   TestEval1
--- PASS: TestEval1 (0.00s)
=== RUN   TestEval7
--- PASS: TestEval7 (0.00s)
PASS
ok  	github.com/vulogov/ThreadComputation	0.636s

**Comment by phanirithvij** [comment]
This is an option https://github.com/codecov/codecov-action to use in github actions.

**Pull request closed without merging**
