### PR TITLE
Add scany to utilities section

### PR DESCRIPTION
**Pull request by georgysavva**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Package links:**

- github.com repo: https://github.com/georgysavva/scany
- pkg.go.dev: 
https://pkg.go.dev/github.com/georgysavva/scany - it's an empty landing package, that combines 3 sub-packages (listed below) that will be actually in use
https://pkg.go.dev/github.com/georgysavva/scany/pgxscan - 1st sub-package 
https://pkg.go.dev/github.com/georgysavva/scany/sqlscan - 2nd sub-package
https://pkg.go.dev/github.com/georgysavva/scany/dbscan- 3rd sub-package
- goreportcard.com: https://goreportcard.com/report/github.com/georgysavva/scany
- coverage service link: https://codecov.io/gh/georgysavva/scany

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

**Comment by georgysavva** [comment]
Hi. Thanks for the quick feedback. 

**pkg.go.dev** 
https://pkg.go.dev/github.com/georgysavva/scany - this is a landing package it does not contain the actual code. It combines 3 sub-packages that will be actually imported and used:  

- https://pkg.go.dev/github.com/georgysavva/scany/sqlscan
- https://pkg.go.dev/github.com/georgysavva/scany/dbscan
- https://pkg.go.dev/github.com/georgysavva/scany/pgxscan

**golint** 
Does it have to be 100% ? It wasn't clear for me from the quality-standard description. I thought "A+" mark is enough.

**Comment by georgysavva** [comment]
I fixed errors on goreportcard, now it 100% on all points. Also added pkg.go.dev links to actual packages and explain the situation in the PR description.

**Comment by georgysavva** [comment]
Hey. Any update on this @avelino?

**Pull request merged**
