### PR TITLE
Add gotemplate

### PR DESCRIPTION
**Pull request by cep21**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

- github.com repo: https://github.com/cep21/gotemplate
- godoc.org: https://godoc.org/github.com/cep21/gotemplate (Really it's in the README.md)
- goreportcard.com: (It's a minimal template repository)
- coverage service link: https://codecov.io/gh/cep21/gotemplate

- I have added my package in alphabetical order.
- I have an appropriate description with correct grammar.
- I know that this package was not listed before.
- I have added godoc link to the repo and to my pull request.
- I have added coverage service link to the repo and to my pull request.
- I have added goreportcard link to my pull request.
- I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@cep21 can you please rebase your PR or open a new one? thank you.

**Comment by panjf2000** [comment]
There is no any response from requester over 30 days, I'm closing this PR according to our [contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers).

**Comment by cep21** [comment]
Hi, i did what he asked 24 days ago.

**Comment by panjf2000** [comment]
But I didn't see you squash commits to one. There are still two commits. Maybe something went wrong during you did that?

**Pull request closed without merging**
