### PR TITLE
gojieba

### PR DESCRIPTION
**Pull request by yanyiwu**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

Please provide package links to:
- godoc.org: https://godoc.org/github.com/yanyiwu/gojieba
- goreportcard.com: https://goreportcard.com/report/github.com/yanyiwu/gojieba
- gocover.io: https://gocover.io/github.com/yanyiwu/gojieba
- coveralls.io: https://coveralls.io/github/yanyiwu/gojieba?branch=master

Note, that new categories can be added only when there are 3 packages or more.

Make shure that you've checked the boxes below before you submit PR:
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link
- [x] I have added gocover.io link
- [x] I have added goreportcard link
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome :+1:

[GoJieba](https://github.com/yanyiwu/gojieba) - This is a Go implementation of [jieba](https://github.com/fxsjy/jieba) which a Chinese word splitting algorithm.

[here](https://github.com/yanyiwu/gojieba/blob/master/README_EN.md) is its english README.md

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@yanyiwu please, add the links to gocover, godoc and goreportcard. thanks.

**Comment by yanyiwu** [comment]
@kirillDanshin added.

**Comment by yanyiwu** [comment]
@kidoman Is it anything else to do for merging the pull request?

**Comment by yanyiwu** [comment]
@kirillDanshin  hi, why it takes so long to merge ?

**Comment by kirillDanshin** [comment]
@yanyiwu oh, I'm sorry. merged.

**Pull request merged**
