### PR TITLE
add dht

### PR DESCRIPTION
**Pull request by shiyanhui**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo: https://github.com/shiyanhui/dht
- godoc.org: https://godoc.org/github.com/shiyanhui/dht
- goreportcard.com: https://goreportcard.com/report/github.com/shiyanhui/dht
- coverage service link (gocover, coveralls etc.): http://gocover.io/github.com/shiyanhui/dht

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by kirillDanshin** [comment]
hi @shiyanhui!
can you add some more tests?

**Comment by shurcooL** [comment]
This looks like a library, not a command, right? If so, it doesn't belong in Other Software section, it should be under [Distributed Systems](https://github.com/avelino/awesome-go/blob/master/README.md#distributed-systems). There's another BitTorrent DHT library there too.

**Comment by kirillDanshin** [comment]
@shurcooL agree :+1:

**Comment by shiyanhui** [comment]
OK, I will add more test as soon as I have spare time. Thanks.

**Pull request closed without merging**
