### PR TITLE
Add broccoli (brotli-powered) resource embedding tool

### PR DESCRIPTION
**Pull request by tucnak**
Hello!

We've recently developed a resource embedding tool called [🥦**Broccoli**](https://github.com/aletheia-icu/broccoli), it uses brotli compression for embedding. The primary motivation behind it was the fact that many existing tools (with an exception of statik maybe) either don't do any compression or don't really work on `wasm/js` target architecture, which was a big requirement for me personally.

Broccoli attracted a positive [disscussion](https://www.reddit.com/r/golang/comments/g12mfh/broccoli_we_wrote_the_most_efficient_static_file/) on Reddit (top 5 last week) and landed a front page in [#308 golang weekly](https://golangweekly.com/issues/308).

We're currently on `v1.0.3`, which means it's stable

- [Github repository](https://github.com/aletheia-icu/broccoli)
- [Documentation](https://pkg.go.dev/aletheia.icu/broccoli/fs?tab=doc)
- [A+ report card](https://goreportcard.com/report/aletheia.icu/broccoli)
- [88% codecov](https://codecov.io/gh/aletheia-icu/broccoli)

Hopefully the rather long-winded description won't hurt much. ```Using brotli compression to embed multiple resources efficiently via `go generate` (unlike many alternatives, works with `wasm/js` architecture, too!)``` (this is factually correct and as WASM Go becomes more popular, rather important to point out)

Cheers,
Ian

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

**Comment by tucnak** [comment]
@panjf2000 I did comply with the template and put in all the info you request, what's the problem here?

**Comment by panjf2000** [comment]
Why did you remove all check boxes?
A canonical PR should look like #3026

**Comment by tucnak** [comment]
Because there was nothing indicating that these checkboxes have to stay. I made sure I complied with all the requirements, put in all the required links and evidently passed the automated content check test.

Is this really that big of a deal?

**Comment by panjf2000** [comment]
It's a big deal, otherwise, why do you think we put those checkboxes in our PR template? The reviewers won't even enter the PR details page if they don't see all checkboxes are checked on the PR list, like this bad one:
image
I happened to enter this PR but you would be lucky every time, so please follow our rules strictly.

**Comment by panjf2000** [comment]
It's been more than 15 days without a reply from the PR owner, I'm closing this PR according to our [contributing guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers).

There is still the https://goreportcard.com/report/aletheia.icu/broccoli#ineffassign.

Feel free to reopen it once you resolve those issues.

**Pull request closed without merging**
