### PR TITLE
Update GopherCon Europe to Berlin

### PR DESCRIPTION
**Pull request by midnightrun**
The next location for GopherCon will be Berlin, Germany (https://twitter.com/gopherconeu) Just updated this small change :)

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for this beautiful list!

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: False
- goreportcard.com: False
- coverage: False

**Comment by panjf2000** [comment]
So it is about to be renewed every time it moving to a new location?

**Comment by midnightrun** [comment]
@panjf2000 yes. First conference was in reykjavik, second was Tenerife and now it will be Berlin.

**Comment by panjf2000** [comment]
I will merge it since the location is variable.
Just be curious, how often is this conference taken place?

**Comment by midnightrun** [comment]
So far, once a year. Cheers!

**Pull request merged**
