### PR TITLE
Add go-gpt3

### PR DESCRIPTION
**Pull request by sashabaranov**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: github.com/sashabaranov/go-gpt3
- pkg.go.dev: https://pkg.go.dev/github.com/sashabaranov/go-gpt3
- goreportcard.com: https://goreportcard.com/report/github.com/sashabaranov/go-gpt3
- https://gocover.io/github.com/sashabaranov/go-gpt3

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [*] I have added my package in alphabetical order.
- [*] I have an appropriate description with correct grammar.
- [*] I know that this package was not listed before.
- [*] I have added pkg.go.dev link to the repo and to my pull request.
- [*] I have added coverage service link to the repo and to my pull request.
- [*] I have added goreportcard link to the repo and to my pull request.
- [*] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by sashabaranov** [comment]
@avelino Fixed lint to 100% https://goreportcard.com/report/github.com/sashabaranov/go-gpt3

Test are [present](https://github.com/sashabaranov/go-gpt3/blob/master/api_test.go), but are challenging to run as this package is API wrapper and requires auth token.

**Comment by sashabaranov** [comment]
@avelino ping

**Comment by avelino** [comment]
your test not working:
```shell
❯ go-gpt3 (master) ✔ go test -v ./...
=== RUN   TestAPI
    api_test.go:12: Could not load auth token from .openai-token file
--- FAIL: TestAPI (0.00s)
FAIL
FAIL    _/Users/avelino/src/github.com/sashabaranov/go-gpt3     0.008s
FAIL
```

**Comment by sashabaranov** [comment]
@avelino yes, because it requires authentication to third-party API, there is no way to really test it this otherwise

**Comment by avelino** [comment]
> @avelino yes, because it requires authentication to third-party API, there is no way to really test it this otherwise
> 
> See details: https://openai.com/blog/openai-api/

why not test with mock?

**Pull request closed without merging**
