### PR TITLE
Added links for textql // gitql // surf

### PR DESCRIPTION
**Pull request by abhi18av**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

# gitql

- https://github.com/cloudson/gitql
- Doesn't have godocs but is quite popular and useful.

# surf

- https://github.com/headzoo/surf
- https://godoc.org/github.com/headzoo/surf

## textql

- https://github.com/dinedal/textql
- https://goreportcard.com/report/github.com/dinedal/textql

### CODE REVIEW

**Comment by abhi18av** [comment]
I'm not really sure what does "not alphabetical" tag means here. 

I've checked, it's as per the prescribed order in the actual list and I've changed the above request to reflect the order as well.

**Comment by shurcooL** [comment]
Take a look at the failure reason in CI. https://travis-ci.org/avelino/awesome-go/builds/212407159

**Comment by abhi18av** [comment]
@shurcooL , I'm sorry but I don't quite know what to look for. Could you give me a couple pointers?

**Comment by shurcooL** [comment]
Sure. Search for "fair".

First thing you'll see is `TestAlpha` failing. That's the test that checks if things are in alphabetic order or not.

image

Next thing you'll find is the exact place where things aren't in alphabetical order:

image

Look at expected order. You want to re-arrange your newly added lines to match that.

**Comment by avelino** [comment]
new rules 8 days with label `pending-submitter-response`: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers

**Comment by abhi18av** [comment]
Continuing a cleaner version of this PR at https://github.com/avelino/awesome-go/pull/1460

Sorry for late, but I've learned about more about Go and Github in the meantime.

**Comment by cassiobotaro** [comment]
No problems @abhi18av , thanks!

**Pull request closed without merging**
