### PR TITLE
Add hindsite

### PR DESCRIPTION
**Pull request by srackham**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/srackham/hindsite
- godoc.org: https://godoc.org/github.com/srackham/hindsite
- goreportcard.com: https://goreportcard.com/report/github.com/srackham/hindsite

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by srackham** [comment]
That's correct, there is no code coverage link.


Cheers, Stuart
--
Stuart Rackham
Mobile: +64 (21) 115 7168

**Comment by srackham** [comment]
Coverage link: https://cover.run/go?repo=github.com%2Fsrackham%2Fhindsite&tag=golang-1.10

**Comment by avelino** [comment]
No interaction, please read: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers
`gocyclo 46%`

**Comment by srackham** [comment]
Please explain: I submitted the requested coverage link 4 days ago.

**Comment by avelino** [comment]
srackham commented on May 26

**Comment by srackham** [comment]
OK, added to May 26 PR.

**Pull request closed without merging**
