### PR TITLE
Update README.md - Add Iris to the Web Frameworks

### PR DESCRIPTION
**Pull request by kataras**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

Please provide package links to:
- godoc.org: https://godoc.org/github.com/kataras/iris
- goreportcard.com: https://goreportcard.com/report/github.com/kataras/iris
- gocover.io: https://gocover.io/github.com/kataras/iris

### CODE REVIEW

**Comment by matrixik** [comment]
Thank you for contribution.

Could you address `go vet` errors before merging (fixing `golint` also would be nice)? https://goreportcard.com/report/github.com/kataras/iris#go_vet

**Comment by kataras** [comment]
@matrixik sorry I just woke up, all fixed now, check again and thanks I was too tired to fix them before

**Comment by matrixik** [comment]
No need to apologize, thank you for fixes.

**Comment by 0xmohit** [comment]
Curious that how was this PR made a day before the [project](https://github.com/kataras/iris) started?

From https://github.com/kataras/iris#support:

> I started to design iris the night of the 13 March 2016, some weeks later, iris started to became famous and I have to fix many issues and implement new features, but I didn't have time to work on Iris because I had a part time job and the (software engineering) colleague which I studied.

**Comment by kataras** [comment]
What do you mean? this PR made on March 15 and Iris started at 13 March....

**Comment by kataras** [comment]
@0xmohit You don't know the months, it's fine, go there : https://www.englishclub.com/vocabulary/time-months-of-year.htm and learn them, I am not native english too :) 

```go
3	March	Mar 	spring
```

**Project started at 13 March**, as readme link you pointed says.
**PR was made at 15 March** (**Mar = March**, as you should know before post a deflamation again) 

So this pr was made **two days after the project started**

Are we clear?

**Comment by kataras** [comment]
@0xmohit You don't know the months, it's fine, go there : https://www.englishclub.com/vocabulary/time-months-of-year.htm and learn them, I am not native english too :) 

```go
3	March	Mar 	spring
```

**Project started at 13 March**, as readme link you pointed says.
**PR was made at 15 March** (**Mar = March**, as you should know before post a deflamation again) 

So this pr was made **two days after the project started**

Are we clear?

lol2

**Pull request merged**
