### PR TITLE
Add Air

### PR DESCRIPTION
**Pull request by sheng**
**Please provide package links to:**
- github.com repo: https://github.com/sheng/air
- godoc.org: https://godoc.org/github.com/sheng/air
- goreportcard.com: https://goreportcard.com/report/github.com/sheng/air
- coverage service link (gocover, coveralls etc.): https://codecov.io/gh/sheng/air

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by sheng** [comment]
Fixed. @avelino

**Comment by appleboy** [comment]
@sheng Please fix conflicts.

**Comment by appleboy** [comment]
https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards

> Tests, where practical. If the library/program is testable, then coverage should be >= 80% for non-data-related packages and >=90% for data related packages. Notice: the tests will be reviewed too. We will check your coverage manually if your package's coverage is just a benchmark results.

**Comment by sheng** [comment]
Oh I see. I will close this PR until my project meets the requirements before sending a new one. Thx :) @appleboy

**Comment by appleboy** [comment]
@sheng Thanks.

**Pull request closed without merging**
