### PR TITLE
Add Validation section

### PR DESCRIPTION
**Pull request by joeybloggs**
Added Validation section for application data validation

### CODE REVIEW

**Comment by gevans** [comment]
Funny. A couple days ago, I spent a good amount of time searching GitHub for validation libraries. :+1:

**Comment by joeybloggs** [comment]
Awesome hope you like, will be adding many more validation functions

**Comment by shurcooL** [comment]
This is useful!

Will you also add `govet`, https://github.com/kisielk/errcheck, etc.?

**Comment by shurcooL** [comment]
Actually, `errcheck` is already added under [Code Analysis](https://github.com/avelino/awesome-go#code-analysis) section. It seems like there's some overlap there.

**Comment by joeybloggs** [comment]
errcheck, gotvet etc are used to help make better go code by reviewing, analizing and reporting on what it finds, in short code analysis.

Validation is used to check the data being used, input or passed around in an application. It doesn't validate a struct or fields correctness but rather the data within a field or structure.

A short example, in a web application there's registration page and after the user enteres his/her data they POST it to the server, validation code would verify that required fields like first and last name were entered before saving to the database, and the programming can inform the user of the bad data, if any, based on the errors found in the data. Errcheck would make sure the code used to do the above handled all possible errors that could make your programming crash.

To me there's a clear separation between code analasys vs data validation.

**Comment by gevans** [comment]
On that note, [govalidator](https://github.com/asaskevich/govalidator) might be moved into this section. It's currently under [text processing](https://github.com/avelino/awesome-go#text-processing).

**Comment by joeybloggs** [comment]
I agree, someone can make another pull request for that, or be merged in with this one.

**Comment by joeybloggs** [comment]
Is anything else needed for this to be merged?

**Comment by mholt** [comment]
@gevans Would you like to submit a PR with that change? I'll merge this now.

**Pull request merged**
