### PR TITLE
Add goreturns to code analysis section

### PR DESCRIPTION
**Pull request by hanjianwei**

### CODE REVIEW

**Comment by shurcooL** [comment]
The import path of this package is `sourcegraph.com/sqs/goreturns`, so I believe that would be a better link to use:

https://sourcegraph.com/sqs/goreturns

@sqs, can you confirm what the canonical URL to the home page of goreturns (not necessarily the same as its import path, but possibly so)?

**Comment by sqs** [comment]
Correct!

**Comment by shurcooL** [comment]
@hanjianwei, please update to the canonical home page URL and this can be merged afterwards.

**Comment by hanjianwei** [comment]
@shurcooL @sqs 

I've updated the URL.

Sorry for my mistake!

**Comment by shurcooL** [comment]
No worries, thanks for fixing it. LGTM.

**Pull request merged**
