### PR TITLE
Add countries package

### PR DESCRIPTION
**Pull request by biter777**
Add countries package: https://github.com/biter777/countries

Countries - ISO 3166 (ISO3166-1, ISO3166, Digit, Alpha-2, Alpha-3) countries codes and names (on eng and rus), ISO 4217 currency designators, ITU-T E.164 IDD calling phone codes, countries capitals, UN M.49 regions codes, IANA ccTLD countries domains, IOC/NOC and FIFA codes, VERY FAST, NO maps[], NO slices[], NO external links/files/data, NO interface{}, NO specific dependencies, Databases compatible, Emoji countries flags and currencies support, full support ISO-3166-1, ISO-4217, ITU-T E.164, Unicode CLDR and IANA ccTLD standarts.

Full support ISO-3166-1, ISO-4217, ITU-T E.164, Unicode CLDR and IANA ccTLD standarts.

Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/biter777/countries
- godoc.org: https://godoc.org/github.com/biter777/countries
- goreportcard.com: https://goreportcard.com/report/github.com/biter777/countries
- codacy.com: https://app.codacy.com/manual/biter777/countries/dashboard
- golangci.com: https://golangci.com/r/github.com/biter777/countries
- codeclimate.com: https://codeclimate.com/github/biter777/countries
- fossa.com: https://app.fossa.com/projects/git%2Bgithub.com%2Fbiter777%2Fcountries?ref=badge_shield
- coverage codecov.io: https://codecov.io/gh/biter777/countries
- coverage coveralls.io: https://coveralls.io/github/biter777/countries?branch=master
- coverage gocover.io: https://gocover.io/github.com/biter777/countries

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

Great thnx for you work and time!
You're awesome too! :)

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: True
- goreportcard.com: True
- coverage: True

**Comment by biter777** [comment]
Thnx for you response.

1) On your advice, I moved the package to the category Utilities.
https://github.com/biter777/awesome-go/blob/master/README.md
Do I need to create a new PR for that?

2) About misspell issue...
In this case, misspell is wrong.
Just example:

```go
case "PH", "PHL", "PHI", "PHILIPPINES", "PHILIPINES", "PI", "RP": //nolint
     return PHL
```

Misspell warning: "PHILIPINES" is a misspelling of "PHILIPPINES" (misspell)
But "PHILIPPINES" already added, and "PHILIPINES" added for the definition of the country if it's spelled incorrectly (which is not uncommon).

I added a "nolint" tags for such cases.

**Comment by panjf2000** [comment]
So you are saying that all those typos are on purpose?

**Comment by biter777** [comment]
Yes. All the typos, identified by misspell, have been added specifically, for a more accurate text-based definition.

**Comment by panjf2000** [comment]
Okay, I got your point here.

**Pull request merged**
