### PR TITLE
Add go-tarantool database driver

### PR DESCRIPTION
**Pull request by kokizzu**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/tarantool/go-tarantool
- pkg.go.dev: https://pkg.go.dev/github.com/tarantool/go-tarantool
- goreportcard.com: https://goreportcard.com/report/github.com/tarantool/go-tarantool
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.)
https://gocover.io/github.com/tarantool/go-tarantool (requires tarantool to start to test)

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
review:
- https://goreportcard.com/report/github.com/tarantool/go-tarantool#golint
- https://goreportcard.com/report/github.com/tarantool/go-tarantool#gocyclo
- https://goreportcard.com/report/github.com/tarantool/go-tarantool#misspell

cover dont's working
```
go: downloading gopkg.in/vmihailenco/msgpack.v2 v2.9.1 --- FAIL: TestClient (0.00s) tarantool_test.go:394: Failed to connect: dial tcp 127.0.0.1:3013: connect: connection refused --- FAIL: TestSchema (0.00s) tarantool_test.go:699: Failed to connect: dial tcp 127.0.0.1:3013: connect: connection refused --- FAIL: TestClientNamed (0.00s) tarantool_test.go:883: Failed to connect: dial tcp 127.0.0.1:3013: connect: connection refused --- FAIL: TestComplexStructs (0.00s) tarantool_test.go:975: Failed to connect: dial tcp 127.0.0.1:3013: connect: connection refused --- FAIL: ExampleConnection_Select (0.00s) got: error in prepare is dial tcp 127.0.0.1:3013: connect: connection refused want: response is []interface {}{[]interface {}{0x457, "hello", "world"}} response is []interface {}{[]interface {}{0x457, "hello", "world"}} --- FAIL: ExampleConnection_SelectTyped (0.00s) got: error in prepare is dial tcp 127.0.0.1:3013: connect: connection refused want: response is [{{} 1111 hello world}] response is [{{} 1111 hello world}] --- FAIL: Example (0.00s) got: want: Ping Code 0 Ping Data [] Ping Error Insert Error Insert Code 0 Insert Data [[10 test one]] Insert Error Duplicate key exists in unique index 'primary' in space 'test' (0x3) Insert Code 3 Insert Data [] Delete Error Delete Code 0 Delete Data [[10 test one]] Replace Error Replace Code 0 Replace Data [[13 1]] Update Error Update Code 0 Update Data [[13 4]] Select Error Select Code 0 Select Data [[15 val 15 bla]] Call17 Error Call17 Code 0 Call17 Data [2] Eval Error Eval Code 0 Eval Data [3] Fut 0 Error Fut 0 Data [{{} 12 test twelve} {{} 11 test eleven}] Fut 1 Error Fut 1 Data [[13 4]] Fut 2 Error Fut 2 Data [[15 val 15 bla]] FAIL coverage: 17.3% of statements FAIL github.com/tarantool/go-tarantool 0.013s --- FAIL: TestConnSuccessfully (0.00s) multi_test.go:63: Failed to connect: no active connections --- FAIL: TestReconnect (0.00s) multi_test.go:85: conn is nil after Connect --- FAIL: TestDisconnectAll (0.00s) multi_test.go:113: conn is nil after Connect --- FAIL: TestClose (0.00s) multi_test.go:147: conn is nil after Connect --- FAIL: TestRefresh (0.00s) multi_test.go:183: conn is nil after Connect FAIL coverage: 20.1% of statements FAIL github.com/tarantool/go-tarantool/multi 0.007s --- FAIL: TestFifoQueue (0.00s) queue_test.go:28: Failed to connect: dial tcp 127.0.0.1:3013: connect: connection refused --- FAIL: TestFifoQueue_GetExist_Statistic (0.00s) queue_test.go:53: Failed to connect: dial tcp 127.0.0.1:3013: connect: connection refused --- FAIL: TestFifoQueue_Put (0.00s) queue_test.go:104: Failed to connect: dial tcp 127.0.0.1:3013: connect: connection refused --- FAIL: TestFifoQueue_Take (0.00s) queue_test.go:147: Failed to connect: dial tcp 127.0.0.1:3013: connect: connection refused --- FAIL: TestFifoQueue_TakeTyped (0.00s) queue_test.go:243: Failed to connect: dial tcp 127.0.0.1:3013: connect: connection refused --- FAIL: TestFifoQueue_Peek (0.00s) queue_test.go:320: Failed to connect: dial tcp 127.0.0.1:3013: connect: connection refused --- FAIL: TestFifoQueue_Bury_Kick (0.00s) queue_test.go:379: Failed to connect: dial tcp 127.0.0.1:3013: connect: connection refused --- FAIL: TestFifoQueue_Delete (0.00s) queue_test.go:466: Failed to connect: dial tcp 127.0.0.1:3013: connect: connection refused --- FAIL: TestFifoQueue_Release (0.00s) queue_test.go:541: Failed to connect: dial tcp 127.0.0.1:3013: connect: connection refused --- FAIL: TestTtlQueue (0.00s) queue_test.go:630: Failed to connect: dial tcp 127.0.0.1:3013: connect: connection refused --- FAIL: TestTtlQueue_Put (0.00s) queue_test.go:683: Failed to connect: dial tcp 127.0.0.1:3013: connect: connection refused --- FAIL: TestUtube_Put (0.00s) queue_test.go:755: Failed to connect: dial tcp 127.0.0.1:3013: connect: connection refused FAIL coverage: 0.0% of statements FAIL github.com/tarantool/go-tarantool/queue 0.003s FAIL Cannot test 'github.com/tarantool/go-tarantool' 
```

**Comment by kokizzu** [comment]
yup, because it requires tarantool to run before coverage test..

**Comment by avelino** [comment]
> yup, because it requires tarantool to run before coverage test..

Why not use mock in tests? How can we prove the minimum quality without being able to see the tests working?

**Comment by kokizzu** [comment]
i guess the library creator prefer not to mock (classicist type)
https://martinfowler.com/articles/mocksArentStubs.html

**Pull request closed without merging**
