### PR TITLE
Added go-simple-mail

### PR DESCRIPTION
**Pull request by xhit**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/xhit/go-simple-mail
- godoc.org: https://godoc.org/github.com/xhit/go-simple-mail
- goreportcard.com: https://goreportcard.com/report/github.com/xhit/go-simple-mail
- coverage service link: https://gocover.io/github.com/xhit/go-simple-mail

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [CHECKED] I have added my package in alphabetical order.
- [CHECKED] I have an appropriate description with correct grammar.
- [CHECKED] I know that this package was not listed before.
- [CHECKED] I have added godoc link to the repo and to my pull request.
- [CHECKED] I have added coverage service link to the repo and to my pull request.
- [CHECKED] I have added goreportcard link to the repo and to my pull request.
- [CHECKED] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by xhit** [comment]
Hello @ceriath 

The Go Report Card was updated with following corrected:

- About GoCyclo in 60% for SMTP require a lot of validations for connect and send email cause building the Data to send to the SMTP Client need to be correct. 60% is fine.
- Executed gofmt -s, only one change
- Fixed typo in comment

And I upload an example_test.go with testing package.

Thanks for the time and you guys have a good project here!

**Comment by xhit** [comment]
auth.go and smtp.go were included because Google froze the package development and I modified them. Also is planned more modifications.

**Comment by panjf2000** [comment]
Your code coverage isn't up to standard, please add more unit tests for it.

**Comment by xhit** [comment]
@ceriath some changes was made to smtp and auth, also goreportcard is high in GoCyclo.

@panjf2000 coverage was updated from 24.2% to 30.9%, but this is because you never send and email and not all code is used.

You can't do a test without a smtp server ;) the coverage is high if you have a smtp server configured, also coverage is random depending the Encryption Type to login in the server (SSL, TLS, None)

Variables in example_test.go for smtp server and account configuration:

- host
- port
- username
- password
- encryptionType
- connectTimeout
- sendTimeout

**Comment by xhit** [comment]
Hello @panjf2000 I update test in last commit, this [link](https://buscamelo.net/dev/go-simple-mail/coverage/commit-3f53972/coverage.html) show the result because I can't test smtp in coverage online tools.

The percentage was 73.4% because test with TLS is not included yet, image [here](https://buscamelo.net/dev/go-simple-mail/coverage/commit-3f53972/coverage_percent.png)

[The coverage out file](https://buscamelo.net/dev/go-simple-mail/coverage/commit-3f53972/cp.out)

@ceriath link to Go authors License was included in smtp and auth. that files have a lot of modifications for working with my package because Google stop the package development.

Please any other requirement let me know.

**Pull request merged**
