### PR TITLE
Added ory/hydra and ory/oathkeeper

### PR DESCRIPTION
**Pull request by ASVBPREAUBV**
Great Tools for running a Oauth/OpenID Server

- github.com repo: https://github.com/ory/hydra https://github.com/ory/oathkeeper
- godoc.org: https://www.ory.sh/docs/
- goreportcard.com: 
https://goreportcard.com/report/github.com/ory/hydra
https://goreportcard.com/report/github.com/ory/oathkeeper
- coverage service link
https://coveralls.io/github/ory/hydra?branch=master
https://coveralls.io/github/ory/oathkeeper?branch=master
Very good coverage

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by ASVBPREAUBV** [comment]
Done. Thanks

**Comment by ASVBPREAUBV** [comment]
ok

**Comment by ceriath** [comment]
@ASVBPREAUBV so..are you intending to fix the issues? Otherwise i think this can be closed. 

As much as I'd personally like to see ory projects on this list since i also use them, they unfortunately don't meet the requirements

**Comment by ASVBPREAUBV** [comment]
What do you mean with issues? All good. You can close the issue.

**Pull request closed without merging**
