### PR TITLE
Add dpar and go2vec

### PR DESCRIPTION
**Pull request by danieldk**
Add two project to the Natural Language Processing section:

* dpar, a transition-based dependency parser.
* go2vec, a reader for word2vec embeddings.

### CODE REVIEW

**Comment by shurcooL** [comment]
LGTM, although `dpar` has quite a bit of golint issues.

**Comment by danieldk** [comment]
Thanks for pointing this out! Although not all of the issues are
resolvable, since quite many of them are in code that is automatically
generated using Ragel, I’ll fix all the other cases.

On Sun, Jan 10, 2016 at 12:36 AM, Dmitri Shuralyov <notifications@github.com

**Comment by shurcooL** [comment]
Also, in the dpar readme it says:

> Warning: dpar is not ready for use yet, APIs will break and burn.

> No usage information is provided yet, since dpar is not ready for use. If you want to hack on dpar, you are smart enough to figure it out :).

Is that still accurate? Make sure the package meets the [quality standard requirement](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

**Comment by danieldk** [comment]
I have updated the README and started adding more documentation to the Wiki. The parser itself is definitely stable when used through the command-line utilities and is used to parse large corpora. The API will still see some minor changes, however, the 'break and burn' part was definitely not accurate anymore :).

**Comment by avelino** [comment]
review pls
http://goreportcard.com/report/danieldk/go2vec
http://goreportcard.com/report/danieldk/dpar

**Comment by danieldk** [comment]
@avelino Thanks! go2vec is at 100% now. dpar is now nearly at 100%:

* The 97% for misspell seems to be caused by misspell not knowing the plural of 'guise'.
* The 97% for golint and gocyclo are in generated code (Ragel state compiler).

**Comment by client9** [comment]
hi @avelino -- once goreportcard updates misspell you should be at 100%  thanks @shurcooL for filing the bug.

**Pull request merged**
