### PR TITLE
Add go-aws-news

### PR DESCRIPTION
**Pull request by circa10a**
This PR adds go-aws-news to awesome-go. go-aws-news is both a configurable application and Go library to fetch, manipulate and post the latest product announcements from AWS news.

Signed-off-by: circa10a <caleblemoine@gmail.com>

Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/circa10a/go-aws-news
- godoc.org: https://godoc.org/github.com/circa10a/go-aws-news/news
- pkg.go.dev: https://pkg.go.dev/github.com/circa10a/go-aws-news?tab=overview
- goreportcard.com: https://goreportcard.com/report/github.com/circa10a/go-aws-news
- coverage service link ([codecov](https://codecov.io/gh/circa10a/go-aws-news))

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by circa10a** [comment]
@avelino 
- I added the godoc link to the MR description, there is a go reference link to pkg.go.dev already in the repo's readme. Not sure what else is missing.
- Coverage is now at 80%

**Comment by circa10a** [comment]
> review:
> 
> * godocs
> * https://codecov.io/gh/circa10a/go-aws-news >80%

@avelino I updated the MR to link to godocs, but there is a badge that links to the Go reference on pkg.go.dev, not sure if you meant something else? Coverage is also up to 80%.

**Comment by avelino** [comment]
Review coverage 
B7A10367-1C19-4035-BAEF-4B0643F7814D

**Comment by circa10a** [comment]
Not sure why codecov reports these numbers, here's the output of local tests

```
coverage: 88.3% of statements
ok      github.com/circa10a/go-aws-news/news    5.813s  coverage: 88.3% of statements
```

**Review by appleboy — APPROVED** [review]

**Pull request merged**
