### PR TITLE
Add go-wildcard

### PR DESCRIPTION
**Pull request by IGLOU-EU**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/IGLOU-EU/go-wildcard
- pkg.go.dev: https://pkg.go.dev/git.iglou.eu/Imported/go-wildcard
- goreportcard.com: https://goreportcard.com/report/git.iglou.eu/Imported/go-wildcard
- coverage service link: https://gocover.io/git.iglou.eu/Imported/go-wildcard

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: False

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by IGLOU-EU** [comment]
Hi, any good, open source and free (for free software) coverage service ?
thx :)

**Comment by avelino** [comment]
@IGLOU-EU there are several, it all depends on the needs of your project.

In the **awesome-go** issue template we recommend these:
- [codecov](https://codecov.io/)
- [coveralls](https://coveralls.io/)
- [gocover](http://gocover.io/)

**Comment by IGLOU-EU** [comment]
Unfortunately codecov and coveralls aren't open source I think.

**Pull request merged**
