### PR TITLE
Add prototype game library

### PR DESCRIPTION
**Pull request by gonutz**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: [prototype](https://github.com/gonutz/prototype)
- godoc.org: [godoc](https://godoc.org/github.com/gonutz/prototype/draw)
- goreportcard.com: [report](https://goreportcard.com/report/github.com/gonutz/prototype)
This has some issues but they are only in the samples.
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.)
[gocover](https://gocover.io/github.com/gonutz/prototype/draw) This site seems broken. It compains about an error for strconv.ParseFloat which is not called anywhere in the source code... The other site (coveralls) is not free/wants some access which I will not grant it.
Test coverage is about 0% anyway, the code is a wrapper for native rendering, audio and input APIs and was thus tested manually.

I use this library at work regularly, I have used it for Ludum Dare games and I know of one other person who has used it to mod a game jam game of mine.

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: True
- goreportcard.com: True
- coverage: True

**Comment by gonutz** [comment]
Could you please point me to the two issues that you mean. I only see false positives in remaining in the report.

What do you mean by

> I believe that gocover.io doesn't break because it works on other repositories

? I don't want to be smug here but since when has that been a measure of software quality? ;-)

Please `go get` my library and run the tests yourself. You should see no failing tests.

**Comment by panjf2000** [comment]
> Could you please point me to the two issues that you mean. I only see false positives remaining in the report.

I meant code issues on https://goreportcard.com/report/github.com/gonutz/prototype

> ? I don't want to be smug here but since when has that been a measure of software quality? ;-)

> Please go get my library and run the tests yourself. You should see no failing tests.

Since you want to add your repo into awesome-go list you have to follow our [Quality Standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards), which means you ought to provide an available code coverage link or show the code coverage by other means.

**Comment by gonutz** [comment]
I want to address the issues on that Go report card page. I am excluding all files in `samples` as they are mere example programs. They are short and demonstrate things concisely, I chose not to make it a lot of small files or functions.

Focussing on the actual "issues" in the library:

`gocyclo` reports cyclomatic complexity. As you know, a large switch statement in a function will artificially drive this measure up although a large switch is not necessarily hard to read. `rawInputToKey`, `handleMessage`, `(Key).String()`, `toGlfwKey` and `tokey` are such a cases. `RunWindow` is complex in this heuristic. Still I just looked it through and find it OK. It is the main window setup logic, it is long and has some if statements but no deep nestings of them.

`golint`'s problem is that I did not put a comment on these:

```
const (
	LeftButton MouseButton = iota
	MiddleButton
	RightButton
)
```
Would you say this needs more explanation? ;-)

`ineffassign` tells me that `rawInputToKey` has three ineffectual assignments. I am not sure why this is. They seem fine. The function that they are in is the Windows keyboard translation. I copied to code from a famous blog post about how to get the actual key that was pressed from the Windows messages. Again, this looks like a false positive heuristic.

As for the tests, here is the console output of running `go test` on the library:
```
...\go\src\github.com\gonutz\prototype>go test ./...
ok      github.com/gonutz/prototype/draw        0.394s
?       github.com/gonutz/prototype/samples/blocks      [no test files]
?       github.com/gonutz/prototype/samples/cookies     [no test files]
?       github.com/gonutz/prototype/samples/shooter     [no test files]
?       github.com/gonutz/prototype/samples/space_blocks        [no test files]
?       github.com/gonutz/prototype/samples/tennis      [no test files]
?       github.com/gonutz/prototype/samples/worm        [no test files]
```

**Comment by panjf2000** [comment]
Still missing code coverage and golint is one of our quality standards, so please  fix it.

**Comment by gonutz** [comment]
First let me say that I think you are behaving highly unprofessional and I would even say offensive here. I have tried discussing the issues but you are not reacting to what I say. You are not curating this "awesome" list in any way if all you do is see if some automatic tools give you a thumbs up. That is in fact the opposite of curation.

I just updated my Linux version of this library, both the GLFW and the SDL2 versions, and made sure all samples run. Everything now works as expected. I did have some issues on Linux, they are now resolved and I created my own forks of all dependencies. I now have full control over all the code used by my library and its dependencies. This should prevent it from getting out of date in the future.

That said, the gocover page saying there is a problem with strconv.ParseFloat is still bogus. Also that page is down right now. Very trustworthy. Again, if you want to curate the libraries, do so. When I run go test on Windows and Linux, all tests pass (as I said, there are not that many anyway, for good reason).

@avelino Is there any other maintainer of this repo who is willing to put in more effort to really curate the list? I suggest thinking again about letting @panjf2000 maintain this.

**Comment by panjf2000** [comment]
You're just being egocentric and making trouble out of nothing!

If you want to get your PR merged into other Github repositories, you have to follow the rules of those repositories, which is common sense, and on the contrary, you kept being egocentric and refusing to meet our [code quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards), and now you blame me for not making you an exception to merge this malformed PR? Why can other PR owners provide all links and docs to meet our standards and you can't? What makes you so special? That is ridiculous!

As a maintainer of awesome-go, our job is to roughly review the Github repo in a PR(checking out its README, docs, etc.) and ensure all links showing that the code quality is great or at least qualified which your repo isn't, and I'm not obligated to do those tedious and extra works like reviewing the full code of your repository, downloading your code and test it for you, I'm busy and my time is limited, so I prefer to spend my time on things that are really meaningful.

So why don't you try to grow up and stop being a baby? Just resolve those code issues and show me the code coverage of your repo!!!

@gonutz

**Comment by gonutz** [comment]
Calling me a baby and egocentric does not change things, it just reinforces my feeling of you being rude. The fact that you still bring up issues I already addressed is what I mean by unprofessional.

I pointed out that there is no code coverage - I assume you mean unit tests covering my code - as this is not the right target for unit tests.

Also, I can do nothing about gocover.io being broken. My time is valuable, just like yours. If you are not willing to run `go get` and `go test`, then what are you willing to do?

Of course you are not obliged to put any work into anything. That is why I suggest you step down from curating this list - it requires work. It is also why I am trying to get someone else to resolve this.

**Comment by panjf2000** [comment]
> it just reinforces my feeling of you being rude. 

I being ruled? You should go back and take a glance at your previous comments, then you will know who was being ruled all the time.

> The fact that you still bring up issues I already addressed is what I mean by unprofessional.

Which code issue have you addressed?
image
You didn't address any code issue! Like this [ineffassign]( https://github.com/gonutz/prototype/blob/master/draw/window_windows.go#L847), it means that the variable `scanCode` is useless and does nothing but being assigned over and over again. Yet you still stubbornly defined it as false positive and refused to fix it. All your sophistry about this doesn't justify you breaking our standards here.

> If you are not willing to run go get and go test, then what are you willing to do?

I can make all efforts to review a PR of awesome-go on condition that the PR owner provides all info we requested in [contributing guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md), so proving your code quality is your job, not mine. What if all PR owners ask me to clone & test their code on my computer locally? Do I have to meet everyone's needs? But no one else did that to me and you did, that is why you should be called egocentric and ruled.

And I can tell you that I spent lots of time reviewing PRs since I was invited to join awesome-go and I also made exceptions for some PR owners with some unresolved code issues and low code coverage when they got rational reasons, but you showed nothing to prove that you deserve to be an exception.

**Comment by gonutz** [comment]
You are right. It is my respnsibility to produce good code and I want to thank you for insisting on it. It made me fix the Linux issues which I would not have found had I not setup a fresh build environment to be extra sure.

Thank you for clarifying the ineffectual assignment metric, I was able to remove some code which is always a plus.

The other obvious issues were easy to fix but 11 issues in the [cyclomatic complexity metric](https://goreportcard.com/report/github.com/gonutz/prototype#gocyclo) remain. However, I really do consider all of these false positives, let me address them again:

The first three and the last item are the main functions of the samples. I thought about refactoring them but really the whole point of this library is to be able to easily prototype things in a short amount of code. That is why I put the whole logic of all sample games in the main function and I find they are easy to read and I like how I can use function closures to capture the game state in local variables inside the main function. These are really intended to look this way.

The next five and the second to last alarms are for large but simple switch statements, typical false positives for cyclomatic complexity.

The last remaining alarm is for the [main loop](https://github.com/gonutz/prototype/blob/master/draw/window_windows.go#L45) of the Windows version. I find that there are no highly indented if/for blocks but rather the function is just very long with a lot of statements. It sets up a window with the Windows API, initializes DirectX, both of which take many statements by design, and it runs the main loop. I think these are three things that the main function should do and that could be factored into separate functions. However I find it not necessarily more readable to extract functions in general when all you do is go through things top to bottom. There is not much real complexity in this function in my opinion and this would be the only thing where I would ask you to make an exception.

I appreciate that you took the time and addressed the issues and my misunderstanding of the ineffassign metric.

**Comment by panjf2000** [comment]
About code issues: https://github.com/avelino/awesome-go/pull/2939#issuecomment-606557950

About code quality standards of gocyclo and golint: https://github.com/avelino/awesome-go/pull/2932#issuecomment-600095967

> Since `cyclomatic complexity` is not an absolute standard of code quality and I'm not a big fan of it, so `gocyclo` is not a mandatory standard in awesome-go. 
>
> However, we demand other quality standards on goreportcard.com, therefore you should resolve the `golint` issue by any means.

This is my opinion about `cyclomatic complexity` and I would say you should try to resolve it first but if those cyclomatic issues are too hard to resolve or there is no replacement for those cyclomatic codes currently in the repo, then retaining those code is allowed.

Since we've reached an agreement that now we should concentrate on resolving code issues and trying to get this PR merged, then we can move on and re-discuss this PR.

**Comment by gonutz** [comment]
I have merged all recent changes of your upstream repo into my fork.

Regarding the gocyclo metric, as I explained I have reviewed the remaining issues carefully and want to keep the code as is.

As for the test coverage, as said earlier, this lib is bascally a wrapper around OS functions, graphics and sound libraries/frameworks and so my "tests" are sample programs that stress all the parts of the library. Since the API is minimal, all functions have been used in my programs many times. Besides the sample programs in the repo I have used the lib in Ludum Dare competitions and for many small tools at work. As I said, I had just fixed the latest Linux issues and took steps to avoid them in the future (dependecy freeze). As for gocover or other alternatives, the only test file [is for ellipse calculation](https://github.com/gonutz/prototype/blob/master/draw/ellipse_test.go) because that is not a native rendering primitive in the graphic frameworks I use. This tests runs on Windows and Linux.

**Comment by gonutz** [comment]
Thanks!

**Pull request merged**
