### PR TITLE
Added go-socket.io to web frameworks

### PR DESCRIPTION
**Pull request by pichuio**

### CODE REVIEW

**Comment by tripledes** [comment]
Sorry to ask this, but I don't see any golang in go-socket.io, in the github repo there seem to be only Elixir code + some JS and fron-end. Also, I think the mean Go, the game.

**Comment by dukex** [comment]
http://go-socket.io send you to https://github.com/go-socket/go-socket

This pull request is about https://github.com/googollee/go-socket.io repository, go-socket.io is the implement of socket.io in golang

**Comment by tripledes** [comment]
My bad, I gmail created a link out of go-socket.io and I clicked ... doh. Sorry.

**Comment by dukex** [comment]
No problems, thank you for your feedback!

**Pull request merged**
