### PR TITLE
add req

### PR DESCRIPTION
**Pull request by imroc**
> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc): https://github.com/imroc/req
- pkg.go.dev: https://pkg.go.dev/github.com/imroc/req/v3
- goreportcard.com: https://goreportcard.com/report/github.com/imroc/req/v3
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/imroc/req/branch/master

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below before you submit PR:**
_not every repository (project) will fit into every option, but most projects should_

- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by sashamelentyev** [comment]
review:
- have't repo link

**Comment by imroc** [comment]
> view:
> 
>     * have't repo

@sashamelentyev sorry, added now

**Review by avelino — CHANGES_REQUESTED** [review]
review:
- golint https://goreportcard.com/report/github.com/imroc/req#golint
- coverage >= 80%

**Comment by imroc** [comment]
> review:
> 
>     * golint https://goreportcard.com/report/github.com/imroc/req#golint
> 
>     * coverage >= 80%

sorry, it's version v3, so fix report url to: https://goreportcard.com/report/github.com/imroc/req/v3

there is some golint warning, but I don't think it need to be fixed.
e.g. 
1. `warning: don't use underscores in Go names; const http2cipher_TLS_NULL_WITH_NULL_NULL should be http2cipherTLSNULLWITHNULLNULL (golint)` this internal const style is the same way as go team does.
2. `warning: if block ends with a return statement, so drop this else and outdent its block`, this is a false warning, cuz the variable used in else is defined in if.

@avelino

**Pull request merged**
