### PR TITLE
Add one meetup, two projects

### PR DESCRIPTION
**Pull request by 3sky**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

1. Tekton Pipelines
  - github.com repo: [Tekton Pipelines](https://github.com/tektoncd/pipeline)
  - godoc.org:
  - goreportcard.com: [Go Report](https://goreportcard.com/report/github.com/tektoncd/pipeline)
  - coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.)

2. Flux
  - github.com repo: [Flux](https://github.com/fluxcd/flux)
  - godoc.org: [godoc](https://godoc.org/github.com/fluxcd/flux)
  - goreportcard.com: [Go Report](https://goreportcard.com/report/github.com/fluxcd/flux)
  - coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.) [CircleCI](https://circleci.com/gh/fluxcd/flux)

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: True
- goreportcard.com: True
- coverage: True

**Comment by panjf2000** [comment]
@3sky 
Please comply with our PR template and fill out all the required info.

**Comment by 3sky** [comment]
@panjf2000 You're taking about missing doc to Tekton ? There is directory with doc https://github.com/tektoncd/pipeline/tree/master/docs, but it's not `godoc`, also it's not my project I'm a user so I can't add `coveralls` for this...

**Comment by avelino** [comment]
send 1 change per PR, this simplifies maintainers review and PR stays less open time

_sorry for closing the PR, we were waiting for your PRs_

**Pull request closed without merging**
