### PR TITLE
add wellington and low level libsass wrapper

### PR DESCRIPTION
**Pull request by drewwells**
Adds the go-libsass lib for writing your own Sass tooling. The default
implementation, wellington, implements a tool for working on Sass
projects. Wellington adds the same spriting functions as available in Compass.

Signed-off-by: Drew Wells <drew.wells00@gmail.com>

### CODE REVIEW

**Comment by drewwells** [comment]
This has been sitting here for a while. Is there something you need me to change for acceptance?

**Comment by shurcooL** [comment]
No, it probably just slipped through because this project has a lot of traffic and not enough time from maintainers.

Looked it over, LGTM.

Although I had a hard time figuring out if `wellington` is a Go library or a binary tool. If it's the latter, it should go under another section. But I _think_ it's a library. Can you confirm?

**Comment by shurcooL** [comment]
Hmm, looking closer, I think it is primarily a binary after all. https://godoc.org/github.com/wellington/wellington is imported by [only one package](https://godoc.org/github.com/wellington/wellington?importers), `wt`, which is the binary.

Since this section is for Go library packages only, you should move `wellington` to somewhere under [Tools section](https://github.com/avelino/awesome-go#tools) please?

**Comment by drewwells** [comment]
wellington is more dedicated to the binary, the wrapper is more general purpose.

**Comment by drewwells** [comment]
moved it to other tools, it didn't appear to fit into any of the other tools categories. Thanks!

**Comment by shurcooL** [comment]
LGTM, thanks!

**Pull request merged**
