### PR TITLE
Added Structured Log Facade (SLF) and a reference implementation

### PR DESCRIPTION
**Pull request by osklyar**
Everything covered as requested, docs, tests, vetting etc.

### CODE REVIEW

**Comment by kirillDanshin** [comment]
Please, provide the links to godoc, gocover and goreportcard. Thanks!

**Comment by osklyar** [comment]
I do not quite understand: both projects have build, cover, goreportcard and godoc badges directly at the top of the README, so where do you want to have the links?

If you wish them here, well, here you go, as copied from the corresponding README.md:

# slf

[![Build status][buildimage]][build] [![Coverage][codecovimage]][codecov] [![GoReportCard][cardimage]][card] [![API documentation][docsimage]][docs]

[docs]: https://godoc.org/github.com/ventu-io/slf
[docsimage]: http://img.shields.io/badge/godoc-reference-blue.svg?style=flat

[build]: https://travis-ci.org/ventu-io/slf
[buildimage]: https://travis-ci.org/ventu-io/slf.svg?branch=master

[codecov]: https://codecov.io/github/ventu-io/slf?branch=master
[codecovimage]: https://codecov.io/github/ventu-io/slf/coverage.svg?branch=master

[card]: http://goreportcard.com/report/ventu-io/slf
[cardimage]: https://goreportcard.com/badge/github.com/ventu-io/slf
# slog
[![Build status][buildimage1]][build1] [![Coverage][codecovimage1]][codecov1] [![GoReportCard][cardimage1]][card1] [![API documentation][docsimage1]][docs1]

[docs1]: https://godoc.org/github.com/ventu-io/slog
[docsimage1]: http://img.shields.io/badge/godoc-reference-blue.svg?style=flat

[build1]: https://travis-ci.org/ventu-io/slog
[buildimage1]: https://travis-ci.org/ventu-io/slog.svg?branch=master

[codecov1]: https://codecov.io/github/ventu-io/slog?branch=master
[codecovimage1]: https://codecov.io/github/ventu-io/slog/coverage.svg?branch=master

[card1]: http://goreportcard.com/report/ventu-io/slog
[cardimage1]: https://goreportcard.com/badge/github.com/ventu-io/slog

**Comment by kirillDanshin** [comment]
thank you for your contribution! merged.

**Comment by osklyar** [comment]
Thanks Kirill, much appreciated!

**Comment by kirillDanshin** [comment]
@osklyar you're welcome :)

**Pull request merged**
