### PR TITLE
add russross/meddler

### PR DESCRIPTION
**Pull request by dannyvankooten**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/russross/meddler
- godoc.org: https://godoc.org/github.com/russross/meddler
- goreportcard.com: https://goreportcard.com/report/github.com/russross/meddler
- coverage service link: https://gocover.io/github.com/russross/meddler

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by dannyvankooten** [comment]
Done!

**Comment by jtemporal** [comment]
hi @dannyvankooten please improve golint :)

**Comment by jtemporal** [comment]
Hi @dannyvankooten :smile: 
>  without breaking backwards compatibility,

not breaking backwards compatibility is a very acceptable reason to discard the golint comment ;)

Could you also improve the coverage? As our contributing guide states:
> coverage should be >= 80% for non-data-related packages and >=90% for data related packages

and currently yours is bellow what is expected :)

Thanks

**Comment by dannyvankooten** [comment]
Hi @jtemporal,

Sure thing! I did the best I could and upped test coverage to ~80%.

**Comment by avelino** [comment]
Rules are made to follow, sorry!

**Pull request closed without merging**
