### PR TITLE
contributing guide: add 5-month maturity quality standard.

### PR DESCRIPTION
**Pull request by yassinebenaid**
This PR adds a new rule to contributing guide:

>Projects must have al least 5 months of history since their first commit

### CODE REVIEW

**Review by phanirithvij — APPROVED** [review]
Let's wait for @avelino's input

**Review by avelino — APPROVED** [review]
I like this rule, it will help us filter projects that have just been created and won't be maintained.

It's worth setting up an automatic check in GitHub Actions, so we don't have to do this work manually.

**Comment by avelino** [comment]
@yassinebenaid can you help us with this? https://github.com/avelino/awesome-go/pull/5473#pullrequestreview-2411744331

**Comment by yassinebenaid** [comment]
Sure, I'll work on a it.

**Pull request merged**
