### PR TITLE
remove gostat

### LINKED ISSUE #2045: Remove ematvey/gostat
https://github.com/ematvey/gostat
No docs, no tests, no examples, even code is not formatted 
#2036

### PR DESCRIPTION
**Pull request by cassiobotaro**
closes #2045 

No docs, no tests, no examples, even code is not formatted.

### CODE REVIEW

**Comment by appleboy** [comment]
cc @ematvey

**Comment by ematvey** [comment]
Fair enough

**Comment by JackChanw** [comment]
aaa

**Comment by appleboy** [comment]
need one maintainer's approval.

**Pull request merged**
