### PR TITLE
Adding Orbit

### PR DESCRIPTION
**Pull request by gulien**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/gulien/orbit
- godoc.org: https://godoc.org/github.com/gulien/orbit
- goreportcard.com: https://goreportcard.com/report/github.com/gulien/orbit
- coverage service link: N/A, my tests are not in the ROOT of the project 😞 

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [ ] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by gulien** [comment]
Thank your for the hint! I'll update the tests for more coverage and keep you updated!

**Comment by avelino** [comment]
https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers

**Comment by gulien** [comment]
@cassiobotaro @avelino 

I've updated the tests and added the coverage link (+ badge).
Should I open a new PR or just let your reopen this one?

Thank you for your time!

**Comment by avelino** [comment]
Low coverage
screenshot 2017-08-21 19 59 18

**Comment by gulien** [comment]
@avelino not sure why this line is so low, but the "real" coverage may be found here:
https://codecov.io/gh/gulien/orbit/commits

**Comment by gulien** [comment]
@avelino @cassiobotaro 
Alright, this line has been updated thanks to a new PR. I guess codecov simply needed a poke! 😄 

Thank you for your time!

**Comment by avelino** [comment]
Pls resend PR

**Pull request closed without merging**
