### PR TITLE
Add go-yara

### PR DESCRIPTION
**Pull request by hillu**

### CODE REVIEW

**Comment by mholt** [comment]
I wonder if this would be better situated in the Security category. (I realize it's 'text processing' too, but a very limited subset of it.) What do you think?

**Comment by hillu** [comment]
* Matt Holt:

> I wonder if this would be better situated in the Security category. (I
> realize it's 'text processing' too, but a very limited subset of it.)
> What do you think?

I agree Security is probably a better match since yara is more about
pattern matching than text processing.

Cheers,
-Hilko

**Comment by hillu** [comment]
Moved the go-yara entry to the Security section

**Comment by mholt** [comment]
Thanks!

**Pull request merged**
