### PR TITLE
Mention luks.go - a library to manage LUKS encrypted partitions

### PR DESCRIPTION
**Pull request by anatol**
> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc):
- pkg.go.dev:
- goreportcard.com:
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.):

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below that apply before you submit PR.**
_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines for details._

- [x] The package has been added to the list in alphabetical order.
- [x] The package has an appropriate description with correct grammar.
- [x] As far as I know, the package has not been listed here before.
- [ ] The repo documentation has a pkg.go.dev link.
- [ ] The repo documentation has a coverage service link.
- [ ] The repo documentation has a goreportcard link.
- [x] The repo has a version-numbered release and a go.mod file.
- [ ] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines), [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers) and [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).
- [ ] The repo has a continuous integration process that automatically runs tests that must pass before new pull requests are merged.
- [ ] The authors of the project do not commit directly to the repo, but rather use pull requests that run the continuous-integration process.

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: False
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by skydiver1980 — APPROVED** [review]

**Comment by yassinebenaid** [comment]
- No release (doesn't event have a single tag)
- No CI 
- Doesn't look to be maintained any more (open issues since 2022)

@anatol

**Comment by anatol** [comment]
Thank you for reviewing it.

Just to add context for the project request - luks.go is the only pure-go implementation of LUKS functionality, that itself the disk encryption standard at Linux ecosystem.

The library is actively in use by many projects, including booster - default initramfs at multiple Linux distros. The library is also used at my dayjob at Google.

> No release (doesn't event have a single tag)

It is the result of go build system to work perfectly fine without tags. It is quite common to skip tagging for libraries as it does not add much value. For example if you look at the list of the [luks.go dependencies itself](https://github.com/anatol/luks.go/blob/master/go.mod) you'll see that 7 out of 13 dependencies are not using tagging.

> No CI

Things are bit complicated here. Accessing Linux kernel LUKS ioctls requires privileged access. To run LUKS tests it needs `root` account, plus additional Linux modules. And then it needs to perform destructive operations with partitions.

To avoid the problems with running tests with `root` at my development machine I use QEMU with an image created with [following instructions](https://github.com/anatol/vmtest/blob/master/docs/prepare_image.md). The contains a custom kernel and userspace tools. But such testing setup is non-trivial, unfortunately. If you know how to run tests with qemu and custom images at github CI I am all ears.

> Doesn't look to be maintained any more (open issues since 2022)

That's simply not true. The [last issue been closed May 6 this year](https://github.com/anatol/luks.go/issues/11) the [last commit from the same day](https://github.com/anatol/luks.go/commit/92f8bb765f988446afc3ae13c2baffcb69ae1c41) adds tests for LUKS volumes conversion functionality.

As of **open** issues you mentioned - there are 2 right now:
 * one asks to convert the project from pure go to cgo bindings. it won't happen as it contradicts the goal of the project to be a pure-go implementation. This ticket should probably be closed.
 * the other is an umbrella issue I opened to track integration of encryption algorithms supported by Linux. Unfortunately some algorithms either do not have golang implementations or quality of the libraries are not great. The ticket is open to track the state in case if new libraries appear.

Hope it helps to clarify your concerns.

**Comment by phanirithvij** [comment]
Your comment answers all of the questions. I appreciate the clarification.

**Pull request merged**
