### PR TITLE
Added html2text and go-hostsfile packages.

### PR DESCRIPTION
**Pull request by jaytaylor**
Package links:

github.com:
- https://github.com/jaytaylor/go-hostsfile
- https://github.com/jaytaylor/html2text

godoc.org:
- https://godoc.org/github.com/jaytaylor/go-hostsfile
- https://godoc.org/github.com/jaytaylor/html2text

goreportcard.com: 
- https://goreportcard.com/report/github.com/jaytaylor/go-hostsfile
- https://goreportcard.com/report/github.com/jaytaylor/html2text

gocover.io: 
- https://gocover.io/github.com/jaytaylor/go-hostsfile
- https://gocover.io/github.com/jaytaylor/html2text

```
=== RUN   TestAlpha
--- PASS: TestAlpha (0.01s)
=== RUN   TestDuplicatedLinks
--- PASS: TestDuplicatedLinks (0.01s)
PASS
ok      github.com/avelino/awesome-go   0.070s
```

### CODE REVIEW

**Comment by jaytaylor** [comment]
@avelino Any word on these?

**Comment by avelino** [comment]
golint 0% in jaytaylor/html2text

**Comment by avelino** [comment]
new rules 8 days with label `pending-submitter-response`: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers

**Comment by jaytaylor** [comment]
Not clear on why this was closed.

```bash
jtaylor@jtaylor-mbp:~/go/src/github.com/jaytaylor/html2text$ golint -set_exit_status *.go
jtaylor@jtaylor-mbp:~/go/src/github.com/jaytaylor/html2text$ echo $?
0
```

Will you please clarify on what the issue is?  This package has taken off far beyond what I expected, people seem to love it!

Thanks,
Jay

**Pull request closed without merging**
