### PR TITLE
Adding Tinode chat to Messaging

### PR DESCRIPTION
**Pull request by or-else**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/tinode/chat
- godoc.org: N/A (not a library), API docs: https://github.com/tinode/chat/blob/master/API.md
- goreportcard.com: https://goreportcard.com/report/github.com/tinode/chat
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `cover.run go`

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [X] I have added my package in alphabetical order.
- [X] I have an appropriate description with correct grammar.
- [X] I know that this package was not listed before.
- [ ] I have added godoc link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request.
- [X] I have added goreportcard link to the repo and to my pull request.
- [X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by or-else** [comment]
What is exactly the issue? Too many lint warnings?

**Comment by or-else** [comment]
I've updated the code. The lint is now at 44%. a bunch of remaining warning are not that reasonable.

**Comment by or-else** [comment]
And lint is at 73% now.

**Comment by or-else** [comment]
Hi. Any chance for a human answer?

**Comment by or-else** [comment]
Thanks for the feedback. 

The lint is now at 88%. The remaining warnings are (a) underscores in package names, which are hard to fix because they have been published, (b) two warnings in types.go, which I believe should not be fixed because fixing them will reduce readability.

The `ineffassign` in line 1021 is a false positive. The `err` is used in lines 1038 and 1043.

There are no tests. It's not great for the project development but does not affect the end-users. Tinode is an application, not a library.

**Comment by cassiobotaro** [comment]
> The lint is now at 88%. The remaining warnings are (a) underscores in package names, which are hard to fix because they have been published, (b) two warnings in types.go, which I believe should not be fixed because fixing them will reduce readability.

package name suggestions:
push/fcm.go
auth/basic.go
push/stdout.go

Why not `m` as line 401?
https://github.com/tinode/chat/blob/master/server/store/types/types.go#L410

> The ineffassign in line 1021 is a false positive. The err is used in lines 1038 and 1043.

https://github.com/tinode/chat/blob/master/server/db/rethinkdb/adapter.go#L989

> There are no tests. It's not great for the project development but does not affect the end-users. Tinode is an application, not a library.

How you ensures that?

**Comment by or-else** [comment]
> package name suggestions:

The problem is not technical. There is a commercial third third party which implemented some of these adapters. It will be a breaking change.

> Why not m as line 401?

Because current names explain what's being done while `m` is non-obvious.
One is a non-commutative comparison, the other a non-commutative subtraction. A formal satisfaction of a lint requirement does not seem to justify a reduction in code quality.

> How you ensures that?

Right now the client applications act as integration tests. There are three clients: js, java, and python. In general yes, it would be nice to have test but thats a huge undertaking.

**Comment by or-else** [comment]
golint is at 97% now.

**Comment by jtemporal** [comment]
>There are no tests.

Our contributing guide states the following on tests:
> If the library/program is testable, then coverage should be >= 80% for non-data-related packages and >=90% for data related packages

And the following on the replying time:
> They will wait 8 days for your interaction, after that the PR will be closed.

So I'm closing this one, @or-else feel to open up a new PR once you got some testing done :wink:

**Pull request closed without merging**
