### PR TITLE
Added two projects

### PR DESCRIPTION
**Pull request by xyproto**
Added two projects:
* [permissions2](https://github.com/xyproto/permissions2)
* [algernon](https://github.com/xyproto/algernon)

### CODE REVIEW

**Comment by mholt** [comment]
Algernon appears to be full software rather than just a library/package. It should probably be moved somewhere under Tools/Software Packages.

**Comment by xyproto** [comment]
I agree. Made the suggested changes.

**Comment by mholt** [comment]
Can we put it in Other Software instead of its own category? (Unless you feel it would be more fitting in DevOps)

**Comment by xyproto** [comment]
A webserver is not a library and not a tool, though. How about a category for server applications?

**Comment by mholt** [comment]
Hmm. I admit "Tools" isn't the best name for that category. @shurcooL What if we refactor that into a "Software" category for Go software projects that aren't intended for use as stand-alone libraries?

**Comment by xyproto** [comment]
Could something like this work? Created a sub-category for server applications.

**Comment by shurcooL** [comment]
Looks okay to me.

**Comment by mholt** [comment]
Okay, we'll start with that. Thanks!

**Comment by xyproto** [comment]
Thanks for merging and thanks for maintaining awsome-go!

**Pull request merged**
