### PR TITLE
Add Colfer to serialization

### PR DESCRIPTION
**Pull request by pascaldekloe**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

Please provide package links to:
- godoc.org: https://godoc.org/github.com/pascaldekloe/colfer/cmd/colf (not a library
- goreportcard.com: https://goreportcard.com/report/github.com/pascaldekloe/colfer
- gocover.io: https://gocover.io/github.com/pascaldekloe/colfer (unit and fuzz tests cover the generated code, not the compiler itself)

Note, that new categories can be added only when there are 3 packages or more.

Make sure that you've checked the boxes below before you submit PR:
- [x] I have added my package in alphabetical order
- [ x ] I know that this package was not listed before
- [ x ] I have added godoc link
- [ x ] I have added gocover.io link
- [ x ] I have added goreportcard link
- [ x ] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@pascaldekloe first of all, thank you for your contribution.
you can use `- [x]` syntax to check the box in markdown.
please, fix goreportcard issues. 
also, ok, you have fuzz testing, but why you don't have unit tests for?
thanks!

**Comment by pascaldekloe** [comment]
The unit tests build code code in ./testdata (with go:generate) and test whether the resulting code works as expected. Go Report Card complains about the generated code, not mine. ;-)

**Comment by pascaldekloe** [comment]
https://github.com/pascaldekloe/colfer/blob/master/gen_test.go

https://github.com/pascaldekloe/colfer/blob/master/testdata/test.js
https://github.com/pascaldekloe/colfer/blob/master/testdata/test.java

**Comment by kirillDanshin** [comment]
@pascaldekloe sorry for taking so much time for response.
thanks for your contribution!

**Pull request merged**
