### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by brianvoe**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo: 
- godoc.org: 
- goreportcard.com: 
- coverage service link (gocover, coveralls etc.): 

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by joeybloggs** [comment]
@brianvoe missing repo, godoc, report card and coverage links

**Comment by brianvoe** [comment]
Im sorry maybe im missing something but the link goes to the github repo, the readme has a godoc link, A+ report card and testing.

screenshot from 2017-04-28 20-37-15

**Comment by brianvoe** [comment]
If a coverage percentage is needed i can add it, currently at 96%. i used travisci for testing, what would you recommend for coverage to readme

**Comment by joeybloggs** [comment]
@brianvoe links, including coverage, are to be added to the pull request itself.

Just helps us getting your package added without having to search around for them.

**Comment by brianvoe** [comment]
[Go Report Card](https://goreportcard.com/report/github.com/brianvoe/gofakeit) [Build Status](https://travis-ci.org/brianvoe/gofakeit) [codecov.io](https://codecov.io/github/brianvoe/gofakeit) [GoDoc](https://godoc.org/github.com/brianvoe/gofakeit)

**Comment by joeybloggs** [comment]
LGTM

In the future if you could add those links within the pull request template right below where it says 
"Please provide package links to:" that would be be awesome :)

**Comment by brianvoe** [comment]
Thanks

**Pull request merged**
