### PR TITLE
Add RAKE.Go to NLP section

### PR DESCRIPTION
**Pull request by Obaied**
A Go implementation of the Rapid Automatic Keyword Extraction (RAKE) algorithm as described in: Rose, S., Engel, D., Cramer, N., & Cowley, W. (2010). Automatic Keyword Extraction from Individual Documents. In M. W. Berry & J. Kogan (Eds.), Text Mining: Theory and Applications: John Wiley & Sons.

Originally implemented in Python and available at: https://github.com/aneesha/RAKE

The source code is released under the MIT License.

**Please provide package links to:**
- github.com repo: https://github.com/Obaied/RAKE.Go
- godoc.org: https://godoc.org/github.com/Obaied/RAKE.Go
- goreportcard.com: https://goreportcard.com/report/github.com/Obaied/RAKE.Go
- coverage service link (gocover, coveralls etc.): None

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [ ] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thank you, team Awesome :)

### CODE REVIEW

**Comment by shurcooL** [comment]
Thanks, this sounds like it could be useful!

The documentation can be improved though, see lint suggestions at https://goreportcard.com/report/github.com/Obaied/RAKE.Go#golint.

**Comment by Obaied** [comment]
@shurcooL Sure. Will do the needed adjustments in the next couple of days. Thanks for reviewing :D

**Comment by kirillDanshin** [comment]
@Obaied please check out https://github.com/Obaied/RAKE.Go/issues/1.

**Comment by Obaied** [comment]
Just updated the docs and report card is A+ now.
@kirillDanshin I made a commit to fix this issue. Thanks for pointing it out.

**Comment by kirillDanshin** [comment]
@Obaied Obaied/RAKE.Go#2

**Pull request merged**
