### PR TITLE
add pingtunnel

### PR DESCRIPTION
**Pull request by esrrhs**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo:https://github.com/esrrhs/pingtunnel
- pkg.go.dev:https://pkg.go.dev/github.com/esrrhs/pingtunnel
- goreportcard.com:https://goreportcard.com/report/github.com/esrrhs/pingtunnel
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.)https://gocover.io/github.com/esrrhs/pingtunnel

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [ ] I have added my package in alphabetical order.
- [ ] I have an appropriate description with correct grammar.
- [ ] I know that this package was not listed before.
- [ ] I have added pkg.go.dev link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request.
- [ ] I have added goreportcard link to the repo and to my pull request.
- [ ] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by phanirithvij** [comment]
@esrrhs gocover link has nothing in it, not sure why. https://gocover.io/github.com/esrrhs/pingtunnel

image

**Comment by esrrhs** [comment]
> 
> 
> @esrrhs gocover link has nothing in it, not sure why. https://gocover.io/github.com/esrrhs/pingtunnel
> 
> [Screenshot](https://user-images.githubusercontent.com/29627898/102965507-f7432500-4513-11eb-8d22-e2d06441a03b.png)
> 
> It is working for other repositories.

oh, I do not know either

**Review by appleboy — CHANGES_REQUESTED** [review]
Please rewrite the CLI usage with English.

**Comment by esrrhs** [comment]
> 
> 
> Please rewrite the CLI usage with English.

图片

the usage now is english and chinese, I think it's ok

**Pull request closed without merging**
