### PR TITLE
Add Skeleton

### PR DESCRIPTION
**Pull request by gadelkareem**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/gadelkareem/skeleton
- pkg.go.dev: 
- goreportcard.com:
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.)

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x ] I have added my package in alphabetical order.
- [x ] I have an appropriate description with correct grammar.
- [ x] I know that this package was not listed before.
- [ x] I have added pkg.go.dev link to the repo and to my pull request.
- [x ] I have added coverage service link to the repo and to my pull request.
- [ x] I have added goreportcard link to the repo and to my pull request.
- [ x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: False
- coverage: True

**Review by avelino — COMMENTED** [review]
I understand that your project is a proposal of architecture (skeleton) for a software that involves _"backend"_ (aka Go) and _"frontend"_

Given that the above statement is correct do you think it would be better for your repository to join the list (awesome-go) or a blogpost describing the use to join the list (awesome-go)?

thinking about the best use of your project would think about packaging in the blogpost

**Comment by ceriath** [comment]
I mean, it definitely fits in the category doesn't it?

**Comment by gadelkareem** [comment]
It fits under `Project Layout` because it is a boilerplate for any new project

**Comment by gadelkareem** [comment]
any updates on this?

**Comment by avelino** [comment]
your project is a layout to be used as a basis for real project development, in real project we use tests.

Where are the tests of your project?

**Comment by gadelkareem** [comment]
There are both backend and frontend tests. You can view the output of both tests on https://gitlab.com/gadelkareem/skeleton/-/jobs/733302048 and https://gitlab.com/gadelkareem/skeleton/-/jobs/733302051

**Comment by gadelkareem** [comment]
why was this closed?

**Comment by avelino** [comment]
@gadelkareem I didn't find the coverage percentage, where do I see it?

populate links:
pkg.go.dev:
goreportcard.com:
coverage service link (codecov, coveralls, gocover etc.)

**Comment by gadelkareem** [comment]
The test coverage is 95%
You need to run it via command line:
```
> cd skeleton/src/backend/
> go get golang.org/x/tools/cmd/cover
> go mod vendor
> go test -coverprofile fmtcoverage.html fmt
ok  	fmt	0.222s	coverage: 95.1% of statements
```

**Comment by avelino** [comment]
I need you to follow the rules described here: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md

**Comment by gadelkareem** [comment]
I think I did follow the contribution rules. Can you point out which ones I am missing?

**Pull request closed without merging**
