### PR TITLE
Add Gatus

### PR DESCRIPTION
**Pull request by TwinProduction**
**Please provide package links to:**

- github.com repo: https://github.com/TwinProduction/gatus
- pkg.go.dev: https://pkg.go.dev/github.com/TwinProduction/gatus?tab=overview
- goreportcard.com: https://goreportcard.com/report/github.com/TwinProduction/gatus
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.) https://codecov.io/gh/TwinProduction/gatus

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [X] I have added my package in alphabetical order.
- [X] I have an appropriate description with correct grammar.
- [X] I know that this package was not listed before.
- [X] I have added pkg.go.dev link to the repo and to my pull request.
- [X] I have added coverage service link to the repo and to my pull request.
- [X] I have added goreportcard link to the repo and to my pull request.
- [X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
review:
- coverage is 67.57%
[...] then coverage should be >= 80% for non-data-related packages and >=90% for data related packages [...]
- golint https://goreportcard.com/report/github.com/TwinProduction/gatus#golint

read more: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards

**Comment by TwinProduction** [comment]
@avelino It only shows 67.57% because the default filter is "Showing **min** per day coverage for the last 6 months".
If you set it to `max` or scroll down at the bottom of the coverage page, it'll show that it's actually 81.17%

That said, I'll make a couple of changes to improve the golint score given by goreportcard, which should allow the codecov's coverage to also reflect the new coverage percentage even with the default `min` filters.

**Comment by TwinProduction** [comment]
I've made the requested improvements for goreportcard's Golint section. I didn't see a specific % requirement in the documentation, so I had assumed that the only requirement was to get an A+ from goreportcard.

**Comment by TwinProduction** [comment]
@avelino Let me know if there's anything else that needs to be done.

**Comment by avelino** [comment]
very good, congratulations on the improvements and thanks for your contribution in awesome-go

**Pull request merged**
