### PR TITLE
Add paragraphical

### PR DESCRIPTION
**Pull request by dnnrly**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/dnnrly/paragraphical
- pkg.go.dev: https://pkg.go.dev/github.com/dnnrly/paragraphical
- goreportcard.com: https://goreportcard.com/report/github.com/dnnrly/paragraphical
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.) https://codecov.io/gh/dnnrly/paragraphical

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: False
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by dnnrly** [comment]
Hi, I'm not sure what further action is required during this PR.

**Comment by phanirithvij** [comment]
@dnnrly I think more functionality would help the wider go community. Because an additional dependency for this amount of functionality is not worth it. But otherwise LGTM

**Comment by dnnrly** [comment]
OK, thanks for clarifying this.

**Pull request closed without merging**
