### PR TITLE
Add Oto

### PR DESCRIPTION
**Pull request by hajimehoshi**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo:  https://github.com/hajimehoshi/oto
- godoc.org:  https://godoc.org/github.com/hajimehoshi/oto
- goreportcard.com: https://goreportcard.com/report/github.com/hajimehoshi/oto
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `cover.run go` *This doesn't work because of cgo*

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [ ] I have added coverage service link to the repo and to my pull request
- [ ] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by hajimehoshi** [comment]
No specific project link: https://github.com/hajimehoshi/oto is the project link I think.

**Comment by hajimehoshi** [comment]
Ah, sorry I was misunderstanding. Updated the links.

**Comment by appleboy** [comment]
@hajimehoshi Could you fix the `go vet` errors?

**Comment by hajimehoshi** [comment]
> Could you fix the go vet errors

The vet complains that 

`C.alcGetError((*C.struct_ALCdevice_struct)(unsafe.Pointer(device)))`

might be wrong, but I couldn't come up with the other way. OpenAL's ALCdevice pointer is a little special on macOS because this can be non-pointer value (like 0x18) so it is inevitable to treat this as just an unsafe.Pointer.

> and add testing code on your project?

Hmm, as most part of oto's implementation depends on lower API, it is really hard to write a test...

**Comment by hajimehoshi** [comment]
If the current state is not acceptable to awesome-go, I'll revisit this later, probably after OpenAL implementation is changed.

**Comment by cassiobotaro** [comment]
More than 8 days without fixes. Feel free to send again following the quality standards.

**Pull request closed without merging**
