### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by h4ck3rm1k3**
adding Cap'n Proto schema generator https://github.com/glycerine/bambam

### CODE REVIEW

**Comment by mholt** [comment]
I'm mobile so maybe I'm trippin but is this in alphabetical order? @dukex

**Comment by shurcooL** [comment]
@mholt It is in alphabetical order, because it's added as sublist under go-capnproto.

Look at the rendered version:

image

**Comment by mholt** [comment]
Ah got it! Sorry. Hard to tell on a phone.

**Comment by mholt** [comment]
Okay, I just had a chance to check it out. Looks like a command (software) more than a package. Maybe it should go down in the Tools -> Software Packages category.

**Comment by h4ck3rm1k3** [comment]
well it is an aux package for the main package capnpnp just so people dont overlook it, keep it together.

**Pull request merged**
