### PR TITLE
Added retry-backoff package

### PR DESCRIPTION
**Pull request by pjebs**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo: https://github.com/pjebs/backoff
- godoc.org: https://godoc.org/github.com/pjebs/backoff
- goreportcard.com: https://goreportcard.com/report/github.com/pjebs/backoff
- coverage service link (gocover, coveralls etc.): 

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [ ] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by pjebs** [comment]
The lint rating is 88%.
The complaints are about adding documentation to exported functions. The function names are self-explanatory and adding any documentation is just artificial.

**Comment by avelino** [comment]
Why send a fork not the official repository?

**Comment by pjebs** [comment]
The author has made it clear that it is no longer maintained. He considers it to be final much to a lot of people's frustration regarding not retrying fatal errors.

This package intends to keep the project going for the next few years with new features such as ability to not retry on fatal errors.

**Comment by avelino** [comment]
Where are you talking about this? According to the README he wants to keep the lib "small", with purpose to a common community use

**Comment by pjebs** [comment]
okay sorry wrong phrasing.
I mean development has stagnated. He's not adding any features due to backward compatibility but I can't find the comment he made about acknowledging the initial design was not perfect.

Essentially by package is EXACTLY the same with 1 very important change:
-Allows disable retry under certain error conditions:

Lots of people were asking for it such as here:
https://github.com/cenk/backoff/issues/22#issue-141351157
https://github.com/cenk/backoff/issues/26#issue-171732041

His suggestion is we escape from the library and just make the relevant changes in our own code.
My fork is essentially exactly that - but for the community since it an important improvement.

**Comment by avelino** [comment]
new rules 8 days with label `pending-submitter-response`: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers

**Pull request closed without merging**
