### PR TITLE
Add lancet(A comprehensive, efficient, and reusable util function library of go) to Utilities section.

### PR DESCRIPTION
**Pull request by thecodeworks**
Feat: add lancet in Utilities section

I find a good go utils function lib, it's lancet. May I add it to Utilities section? Please check blow info.

[lancet](https://github.com/duke-git/lancet)
[lancet-goreportcard](https://goreportcard.com/report/github.com/duke-git/lancet/v2)
[lancet-coverage](https://app.codecov.io/gh/duke-git/lancet)

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: False

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by Osasaluwa** [comment]
Good

**Comment by thecodeworks** [comment]
@avelino Hi, I just want to know what's status of this PR?, will it be merged?

**Comment by ceriath** [comment]
Those are a lot of utility functions, thanks for contributing! Next time please use the provided contribution template though

**Pull request merged**
