### PR TITLE
Added gojsonschema

### PR DESCRIPTION
**Pull request by asdine**

### CODE REVIEW

**Comment by mholt** [comment]
The godoc is about half-empty. I can understand the validation functions not needing any extra description, but some others are a bit bare. Any chance of filling that in?

**Comment by matrixik** [comment]
Hello @xeipuuv we would like to add your `gojsonschema` package to awesome-go list but it's look like documentation is lacking, do you plan to improve it?
And two files are not formatted properly:
http://goreportcard.com/report/xeipuuv/gojsonschema

**Comment by xeipuuv** [comment]
Hello and thanks for the interest. 
I absolutely lack time these days, but as soon as I have I will have a look at it all and let you know.

**Comment by matrixik** [comment]
Thank you for your time.

**Pull request closed without merging**
