### PR TITLE
Add flaggy

### PR DESCRIPTION
**Pull request by integrii**
I just released flaggy to the world yesterday.  Please add it to aewsome-go!

- github.com repo: github.com/integrii/flaggy
- godoc.org: [](http://godoc.org/github.com/integrii/flaggy)

- goreportcard.com: [Go Report Card](https://goreportcard.com/report/github.com/integrii/flaggy)
- coverage service link: [cover.run](https://cover.run/go?tag=golang-1.10&repo=github.com%2Fintegrii%2Fflaggy)

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [ x ] I have added my package in alphabetical order.
- [ x ] I have an appropriate description with correct grammar.
- [ x ] I know that this package was not listed before.
- [ x ] I have added godoc link to the repo and to my pull request.
- [ x ] I have added coverage service link to the repo and to my pull request.
- [ x ] I have added goreportcard link to the repo and to my pull request.
- [ x ] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by integrii** [comment]
The reason for low code coverage is that my checks for failures cause the app to call `os.Exit(1)` on the app, which stops testing.  This is because flags packages normally shut down immediately if the proper flags are denied.  When I do testing, I run it from my laptop to validate things are ok, then add a `t.Skip()` on the test so that the CI pipeline does not blow up.

The actual code coverage is much higher.  If this is enough to convince you to merge, then thanks.  If not, I will have to find some way to write tests that cause an `os.Exit()` call...

**Comment by integrii** [comment]
Code coverage upped to over 70%, but I don't think I can go much higher because flaggy exits on all the various ways a string can fail to parse to every type of value in go.  While I will continue to work toward every edge case I can simulate, I think 70% is good coverage for a package with this much error handling code.

Please look at it again and let me know what you think.

**Comment by appleboy** [comment]
@integrii Thanks for improving the code coverage. LGTM Waiting for another maintainer approval.

**Comment by integrii** [comment]
Thanks guys!!

**Pull request merged**
