### PR TITLE
adding almasbub - library to provide an easy and safe datatype cast in Go.

### PR DESCRIPTION
**Pull request by dhiemaz**
> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc): https://bitbucket.org/rctiplus/almasbub
- pkg.go.dev: https://pkg.go.dev/bitbucket.org/rctiplus/almasbub
- goreportcard.com: - 
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://sonarcloud.io/project/overview?id=rctiplus_almasbub

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below before you submit PR:**
_not every repository (project) will fit into every option, but most projects should_

- [ x] I have added my package in alphabetical order.
- [ x] I have an appropriate description with correct grammar.
- [ x] I know that this package was not listed before.
- [ x] I have added pkg.go.dev link to the repo and to my pull request.
- [ x] I have added coverage service link to the repo and to my pull request.
- [ x] I have added goreportcard link to the repo and to my pull request.
- [ x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by dhiemaz** [comment]
@avelino thank you for the information, is there any update for my PR?

**Review by avelino — CHANGES_REQUESTED** [review]
C3441A01-EE3E-467B-89AD-4C7B2037F291

**Comment by dhiemaz** [comment]
Hi @avelino I have updated the code and it seems there is an issue is in bitbucket-pipeline file script which integrates with sonarcloud, not in the go code. I am still finding a way to fix that. Here is the test I execute using master branch.

the test is passed.

Screenshot 2021-11-11 at 17 06 02

Thank you

**Comment by avelino** [comment]
to join awesome-go we ask for minimum quality, read more here 
https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards

**Pull request closed without merging**
