### PR TITLE
Add - Go library for PHP community with convenient functions

### PR DESCRIPTION
**Pull request by arthurkushman**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/arthurkushman/pgo
- godoc.org: https://godoc.org/github.com/arthurkushman/pgo
- goreportcard.com: https://goreportcard.com/report/github.com/arthurkushman/pgo
- coverage service link [codecov](https://codecov.io/gh/arthurkushman/pgo)

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by arthurkushman** [comment]
> Please fill PR template

Hi, I'd successfully provided package links.

**Comment by arthurkushman** [comment]
> @arthurkushman Please take a look
> image

Fixed ineffectual assignment

**Comment by ceriath** [comment]
I am honestly not entirely sure if it is "awesome go" to provide php-like functions :thinking: 
I agree, they can be convenient. I am just not sure if i'd consider it "awesome go"

**Comment by arthurkushman** [comment]
> I am honestly not entirely sure if it is "awesome go" to provide php-like functions 🤔
> I agree, they can be convenient. I am just not sure if i'd consider it "awesome go"

I have a lot of examples where my colleagues really wanted web-like helpers/functions in Go, because they didn't want to spend a lot of time re-inventing those useful algorithms + there are cases where developer need to do the same things over and over, e.g.: to replace multiple values you need to repeat loops etc:
```
	for k, v := range search {
		params.subject = strings.Replace(params.subject, v, replace[k], params.count)
	}
```

Here php is just the API which is implemented in Go and definitely will be helpful for large community of php-programmers that using Go in their projects + other web-developers writing Go-services.

**Pull request merged**
