### PR TITLE
add security package github.com/jptosso/coraza-waf

### PR DESCRIPTION
**Pull request by jptosso**
> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc): https://github.com/jptosso/coraza-waf
- pkg.go.dev: https://pkg.go.dev/github.com/jptosso/coraza-waf
- goreportcard.com: https://goreportcard.com/report/github.com/jptosso/coraza-waf
- coverage service link: https://sonarcloud.io/project/overview?id=jptosso_coraza-waf

**Make sure that you've checked the boxes below before you submit PR:**
_not every repository (project) will fit into every option, but most projects should_

- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards).

**Please note v1 is being deprecated and replaced with v2, most exported functions are now unexported.** and Coraza v2 does strict testing against:

- go-fmt
- go-vet
- go-lint
- go-imports
- go-cyclo
- no-go-testing
- golangci-lint
- go-critic
- go-unit-tests
- go-mod-tidy

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: False

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
review:
- golint https://goreportcard.com/report/github.com/jptosso/coraza-waf#golint
- coverage `>= 80%`, today is `60.8%`

**Comment by jptosso** [comment]
Hey @avelino , please notice the coverage is over 80%:

image
 
What you saw was the "coverage for the latest commit" instead of the overall.

https://sonarcloud.io/summary/overall?id=jptosso_coraza-waf

Thank you for you review

**Comment by avelino** [comment]
> Hey @avelino , please notice the coverage is over 80%:
> 
> image
> 
> What you saw was the "coverage for the latest commit" instead of the overall.
> 
> https://sonarcloud.io/summary/overall?id=jptosso_coraza-waf
> 
> Thank you for you review

oops, sorry
coverage it's ok, lack of looking at the lint

**Comment by jptosso** [comment]
Hey, is it possible to reopen this PR? 

This is the new report

image


@avelino

**Comment by spekary** [comment]
The branch has been deleted. You will need to resubmit.

**Pull request closed without merging**
