### PR TITLE
Add 1build - command line

### PR DESCRIPTION
**Pull request by gopinath-langote**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/gopinath-langote/1build
- godoc.org: https://godoc.org/github.com/gopinath-langote/1build
- goreportcard.com: https://goreportcard.com/report/github.com/gopinath-langote/1build
- coverage service link : https://app.codacy.com/manual/gopinath-langote/1build/dashboard

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: True
- goreportcard.com: True
- coverage: True

**Comment by gopinath-langote** [comment]
@panjf2000 
1. Fixed `gofmt` issues – https://goreportcard.com/report/github.com/gopinath-langote/1build

2. About code coverage – as the project is a command-line build tool to execute the commands - we chose to write integration test (testing binary) - hence we do not have coverage on the `project.
`Codacy` is the tool to show the code standards.

**Comment by panjf2000** [comment]
Then, is there any integration-test output we can checkup?

**Comment by gopinath-langote** [comment]
Sure, It's on travis-ci

https://travis-ci.org/gopinath-langote/1build/jobs/592824581

**Comment by panjf2000** [comment]
@gopinath-langote 
I just check out other repositories of command line in awesome-go and those do provide code coverage, so could you please set up the coverage？I believe it won't be hard to do since you've already written so many test code for it.

**Comment by gopinath-langote** [comment]
@panjf2000 
It's a bit tricky - We do have a lot of tests covering all flows.

But those are not `unit-test` those are `integration test` - testing the binary of the project.

Still, It gives the same level of confidence.

**Comment by panjf2000** [comment]
Although you got your reasons about the code coverage, I still insist on the the [Quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) of awesome-go for now but I'm also open to discuss with, so I'am adding @ceriath and @kirillDanshin to this discussion.

**Pull request merged**
