### PR TITLE
Add biogo

### PR DESCRIPTION
**Pull request by samuell**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

Please provide package links to:
- godoc.org: https://godoc.org/github.com/biogo/biogo
- goreportcard.com: https://goreportcard.com/report/github.com/biogo/biogo
- gocover.io: https://gocover.io/github.com/biogo/biogo

Note, that new categories can be added only when there are 3 packages or more.

Make sure that you've checked the boxes below before you submit PR:
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link
- [x] I have added gocover.io link
- [x] I have added goreportcard link
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@samuell hi
someone from biogo (@kortschak?): please fix golint, ineffassign and misspell issues from goreportcard.
As noted at biogo/biogo#2, it's a `Nice, but not friendly`. Wiki is turned off and I can't find any useful examples.

**Comment by kortschak** [comment]
>someone from biogo (@kortschak?): please fix golint, ineffassign and misspell issues from goreportcard.

golint - largely ignored (it is incorrect in a number of places and complains about generated code that is harder to read if made to conform to Go idiom - see unix philosophy axiom 16).
ineffassign - done
mispell - done

>As noted at biogo/biogo#2, it's a Nice, but not friendly. Wiki is turned off and I can't find any useful examples.

wiki now on - open to anyone in the first instance (I don't have time to maintain wiki pages right now). Real usage examples are in https://github.com/biogo/examples; small godoc examples exist in some packages.

**Comment by cassiobotaro** [comment]
new rules 8 days with label pending-submitter-response: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers

**Comment by kortschak** [comment]
Why?

There was no request from response from @samuell and I have addressed the comments.

**Comment by kortschak** [comment]
Please look at the repo. The head package is a document comment and a version constant. The rest of the packages are tested.

**Comment by cassiobotaro** [comment]
@avelino , plz take a look
image

**Comment by cassiobotaro** [comment]
@kortschak and about the errors on the reportcard?
image
lint have a lot of warnings too
image

**Comment by avelino** [comment]
Pls fixed quality and resend PR

**Comment by kortschak** [comment]
Thanks. When I have time, I'll go through and good those, though I can see no good reason to apply to a club.

**Pull request closed without merging**
