### PR TITLE
Add jump, a quick and fuzzy directory jumper

### PR DESCRIPTION
**Pull request by gsamokovarov**
Think [autojump](https://github.com/wting/autojump) or [z](https://github.com/rupa/z), but fuzzy and easy to integrate with the shell.

- https://github.com/gsamokovarov/jump

**Make sure that you've checked the boxes below before you submit PR:**
- [ ] I have added my package in alphabetical order
- [ ] I know that this package was not listed before
- [ ] I have added godoc link to the repo and to my pull request
- [ ] I have added coverage service link to the repo and to my pull request
- [ ] I have added goreportcard link to the repo and to my pull request
- [ ] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by cassiobotaro** [comment]
Pls update your PR following this [guide](https://github.com/avelino/awesome-go/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

**Comment by gsamokovarov** [comment]
Hey, @cassiobotaro, thanks for the ping. I have updated the links to the project and you can see the coverage in the travis build.

**Comment by avelino** [comment]
new rules 8 days with label `pending-submitter-response`: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers

**Comment by gsamokovarov** [comment]
Hey,

I can imagine you guys get a lot of traffic, so it only feels natural to try to filter it with some automation. However, some of those badges don't work for all the projects.

In my case, this is a CLI tool, and there is no code in `github.com/gsamokovarov/jump` except a `main.go` file. All the other packages are where the work is done and tests do live in there. You can even see the coverage at the travis run: https://travis-ci.org/gsamokovarov/jump/jobs/227392222

As for the docs, all the exposed types and functions are documented. There are even user-facing man pages, but, again, this is a CLI tool. Documentation in `godoc` does not make much sense for it, as it is not intended for library use, so I haven't generated it.

Anyway, thank you for taking a look and keep it up. 🍻

**Pull request closed without merging**
