### PR TITLE
Added Mailchain to awesome-go

### PR DESCRIPTION
**Pull request by robdefeo**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/mailchain/mailchain
- godoc.org: https://godoc.org/github.com/mailchain/mailchain
- goreportcard.com: https://goreportcard.com/report/github.com/mailchain/mailchain
- coverage service link: https://coveralls.io/github/mailchain/mailchain?branch=master

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [X] I have added my package in alphabetical order.
- [X] I have an appropriate description with correct grammar.
- [X] I know that this package was not listed before.
- [X] I have added godoc link to the repo and to my pull request.
- [X] I have added coverage service link to the repo and to my pull request.
- [X] I have added goreportcard link to the repo and to my pull request.
- [X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: True
- goreportcard.com: True
- coverage: True

**Comment by robdefeo** [comment]
@ceriath Thanks for taking the time to look at this, I have resolved many of the issues that https://goreportcard.com/report/github.com/mailchain/mailchain indicated by improving the developer documentation. Better documented repositories are always better. Let me know if there is anything else you would like me to address.

**Comment by ceriath** [comment]
It still has wayy too many issues imho. Also https://goreportcard.com/report/github.com/mailchain/mailchain#gofmt should defintely be fixed

**Comment by robdefeo** [comment]
Hi @ceriath  it now looks much better the codebase has improved during this process 😄  every check has past except one that is on a test function. Can you take another look at it.

**Comment by robdefeo** [comment]
@ceriath yes I will work on them also. Thanks for your help

**Pull request merged**
