### PR TITLE
Add Parsyl's parquet reader/writer lib

### PR DESCRIPTION
**Pull request by cswank**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/parsyl/parquet
- godoc.org: https://godoc.org/github.com/parsyl/parquet
- goreportcard.com: https://goreportcard.com/report/github.com/parsyl/parquet
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.) https://gocover.io/github.com/parsyl/parquet

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by cswank** [comment]
The overwhelming majority of the golint problems are in parquet/schema, which is 3rd party generated code (Apache Thrift) and there isn't much I can do about that.  Golint is supposed to ignore sub-packages that have certain comments, but apparently the comments in that sub-package don't meet the criteria.

I agree that the go-docs are not the best and I could work on better comments.   However, that code is not intended to be "worked with", as you say.  The code that gets generated by the parquetgen command is what actually uses everything in that godoc.  It's almost misleading to have a godoc page in the first place.  

I'm not sure how I could make that clear to users.  I was thinking of actually removing it and making it part of the code parquetgen creates.

**Comment by cswank** [comment]
I just pushed a commit that boosts the golint score (yay, it's green now)

**Comment by cswank** [comment]
I added more comments and got the golint score to 95% and I move some of the confusing functions out of the lib and into the generated code (hopefully causing less confusion).

**Comment by ceriath** [comment]
At least https://goreportcard.com/report/github.com/parsyl/parquet#gofmt should be also fixed.

Also, could you please rebase?

**Comment by cswank** [comment]
Done (gofmt -s and rebase)

**Comment by ceriath** [comment]
I'd approve it without technically meeting all requirements, but i think it's a package worth to have on the list. I'd like to have a second opinion tho

**Pull request merged**
