### PR TITLE
Add gnet to the networking section

### PR DESCRIPTION
**Pull request by panjf2000**
**gnet: A high-performance, lightweight, nonblocking, event-loop networking library written in pure Go.**

- github.com repo: https://github.com/panjf2000/gnet
- godoc.org: [Doc for panjf2000/gnet](https://gowalker.org/github.com/panjf2000/gnet?lang=en-US)
- goreportcard.com: [Go Report Card](https://goreportcard.com/report/github.com/panjf2000/gnet)
- coverage service link: [codecov for panjf2000/gnet](https://codecov.io/gh/panjf2000/gnet)

- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@panjf2000 as I can see, you've based your project on evio by @tidwall. please return his credit to the license, as you violating the MIT license chosen by @tidwall.

**Comment by panjf2000** [comment]
@kirillDanshin 
Sorry, I don't quite get it when you talk about `please return his credit to the license`, what does that mean? If you mean copyright, I believe I've kept his copyrights in all source code files from evio, or you are saying that I am missing the copyright in [gnet license](https://github.com/panjf2000/gnet/blob/master/LICENSE), right?
Thanks~

**Comment by kirillDanshin** [comment]
@panjf2000 actually, you got my message exactly right :)

also, can you please take a look into your http benchmarks? currently in your readme you don't state that you're comparing a production-ready http implementations and the one that user has to built on his own from ground up.

disclamer: I'm a fasthttp maintainer and I'm interested to see the benchmark sources as well :)

otherwise, LGTM

**Comment by panjf2000** [comment]
@kirillDanshin 
> also, can you please take a look into your http benchmarks? currently in your readme you don't state that you're comparing a production-ready http implementations and the one that user has to built on his own from ground up.
Make senses, I will add it later today.

> disclamer: I'm a fasthttp maintainer and I'm interested to see the benchmark sources as well :)
Sorry, I isolated the benchmark from the source code repo a few days ago and forgot to add a link in README, I will also add this today after work~
Here is benchmark of `gnet`: https://github.com/panjf2000/gnet_benchmarks, please note.

**Comment by kirillDanshin** [comment]
@panjf2000 I reviewed fasthttp implementation there, please take a look in the new issue in your benchmarks when you'll get some time

**Comment by panjf2000** [comment]
@kirillDanshin 
I've seen it and replied [here](https://github.com/panjf2000/gnet_benchmarks/issues/1#issuecomment-533390549).

**Pull request merged**
