### PR TITLE
Add grapes

### PR DESCRIPTION
**Pull request by yaronsumel**
Add grapes - distribute commands over ssh.

**Please provide package links to:**
- github.com repo:  https://github.com/yaronsumel/grapes
- godoc.org:  https://godoc.org/github.com/yaronsumel/grapes
- goreportcard.com: https://goreportcard.com/report/github.com/yaronsumel/grapes
- coverage service link (gocover, coveralls etc.): http://gocover.io/github.com/yaronsumel/grapes

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks! :+1:

### CODE REVIEW

**Comment by kirillDanshin** [comment]
hi @yaronsumel. travis is a CI service, not a coverage service.
your package has 8.8% coverage, can you work on it? for example, you can try to find ssh mocking package and run it before test start.

**Comment by yaronsumel** [comment]
hey .. @kirillDanshin . i'll try something to fix that. 10x.

**Comment by yaronsumel** [comment]
hey  @kirillDanshin .. PR has been updated with gocover [link](http://gocover.io/github.com/yaronsumel/grapes) .. currently with 89.2% cover .. 10x.

**Comment by shurcooL** [comment]
LGTM.

**Comment by kirillDanshin** [comment]
@yaronsumel thanks, merging it :smiley:

**Pull request merged**
