### PR TITLE
Add hex-monscape

### PR DESCRIPTION
**Pull request by harunalfat**
Adding [Hex Monscape](https://github.com/Haraj-backend/hex-monscape), a getting started guidelines in writing maintainable code using Hexagonal Architecture

**Package links:**

- repo link (github.com, gitlab.com, etc): https://github.com/Haraj-backend/hex-monscape
- pkg.go.dev: https://pkg.go.dev/github.com/Haraj-backend/hex-monscape
- goreportcard.com: https://goreportcard.com/report/github.com/Haraj-backend/hex-monscape
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): - https://coveralls.io/github/Haraj-backend/hex-monscape?branch=master

Note: *that new categories can be added only when there are 3 packages or more.*

Contribution Guidelines:
- [x] The package has been added to the list in alphabetical order.
- [x] The package has an appropriate description with correct grammar.
- [x] As far as I know, the package has not been listed here before.
- [x] The repo documentation has a pkg.go.dev link.
- [x] The repo documentation has a coverage service link.
- [x] The repo documentation has a goreportcard link.
- [x] The repo has a version-numbered release and a go.mod file.
- [x] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines), [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers) and [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).
- [x] The repo has a continuous integration process that automatically runs tests that must pass before new pull requests are merged.
- [x] The authors of the project do not commit directly to the repo, but rather use pull requests that run the continuous-integration process.

### CODE REVIEW

**Review by avelino — CHANGES_REQUESTED** [review]
Need links

**Comment by harunalfat** [comment]
> Need links 

Good day sir @avelino . Hope you're doing well. Can you elaborate what link that we need to add within this PR? We've only added the link to the Github repo itself

**Comment by harunalfat** [comment]
Hello @avelino , we've added the repo link, pkg.go.dev link, goreportcard link, and also coveralls link within the description. Please kindly recheck. Thank you very much

**Comment by harunalfat** [comment]
Hello folks @avelino @sashamelentyev @phanirithvij 👋 
Could someone kindly take a look at this PR and give us some feedback? That would be very great 😄

**Pull request merged**
