### PR TITLE
added new package pocache 

### PR DESCRIPTION
**Pull request by bnkamalesh**
## We want to ensure high quality of the packages. Make sure that you've checked the boxes below before sending a pull request.

- [x] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines)
- [x] I have read the [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers)
- [x] I have read the [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards)

_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines for details._

- [x] The repo documentation has a pkg.go.dev link.
- [x] The repo documentation has a coverage service link.
- [x] The repo documentation has a goreportcard link.
- [x] The repo has a version-numbered release and a go.mod file.
- [x] The repo has a continuous integration process that automatically runs tests that must pass before new pull requests are merged.
- [x] Continuous integration is used to attempt to catch issues prior to releasing this package to end-users.

## Please provide some links to your package to ease the review

- [x] forge link (github.com, gitlab.com, etc): https://github.com/naughtygopher/pocache
- [x] pkg.go.dev: https://pkg.go.dev/github.com/naughtygopher/pocache
- [x] goreportcard.com: https://goreportcard.com/report/github.com/naughtygopher/pocache
- [x] coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://coveralls.io/github/naughtygopher/pocache?branch=main

## Pull Request content

- [x] The package has been added to the list in alphabetical order.
- [x] The package has an appropriate description with correct grammar.
- [x] As far as I know, the package has not been listed here before.

Please delete one of the following lines:

- [x] The packages around my addition still meet the Quality Standards.

Thanks for your PR, you're awesome! :sunglasses:

### CODE REVIEW

**Comment by ccoVeille** [comment]
Thanks for sharing. It looks like a good project

**Review by Israelgladys — APPROVED** [review]

**Comment by bnkamalesh** [comment]
hey @phanirithvij any help here. 

p.s: tagging you since you merged my previous PR 😅

**Comment by phanirithvij** [comment]
Apologies, we have a new hard rule against accepting < 5 months old projects.
I can ask you to re-submit it in 5 months.
Or we can keep this pr open and I will label it appropriately.

**Comment by phanirithvij** [comment]
Since this was requested to be added before this rule change, I can accept it.

**Pull request merged**
