### PR TITLE
Add go-deepcopy

### PR DESCRIPTION
**Pull request by tiendc**
## We want to ensure high quality of the packages. Make sure that you've checked the boxes below before sending a pull request.

- [x] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines)
- [x] I have read the [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers)
- [x] I have read the [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards)

_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines for details._

- [x] The repo documentation has a pkg.go.dev link.
- [x] The repo documentation has a coverage service link.
- [x] The repo documentation has a goreportcard link.
- [x] The repo has a version-numbered release and a go.mod file.
- [x] The repo has a continuous integration process that automatically runs tests that must pass before new pull requests are merged.
- [x] Continuous integration is used to attempt to catch issues prior to releasing this package to end-users.

## Please provide some links to your package to ease the review

- [x] forge link (github.com, gitlab.com, etc): https://github.com/tiendc/go-deepcopy
- [x] pkg.go.dev: https://pkg.go.dev/github.com/tiendc/go-deepcopy
- [x] goreportcard.com: https://goreportcard.com/report/github.com/tiendc/go-deepcopy
- [x] coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): https://codecov.io/gh/tiendc/go-deepcopy

## Pull Request content

- [x] The package has been added to the list in alphabetical order.
- [x] The package has an appropriate description with correct grammar.
- [x] As far as I know, the package has not been listed here before.

## Category quality

_Note that new categories can be added only when there are 3 packages or more._

Packages added a long time ago might not meet the current guidelines anymore. It would be very helpful if you could check 3-5 packages above and below your submission to ensure that they also still meet the Quality Standards.

Please delete one of the following lines:

- [x] The packages around my addition still meet the Quality Standards.

Thanks for your PR, you're awesome! :sunglasses:

### CODE REVIEW

**Comment by yassinebenaid** [comment]
- The exported types are not documented (mostly).

[_CONTRIBUTING.md_](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards)
> be thoroughly documented (README, pkg.go.dev doc comments, etc.) in the English language, so everyone is able to understand the project's intention and how it works. All public functions and types should have a Go-style documentation header;

**Comment by tiendc** [comment]
@yassinebenaid 
I added some docs. Could you review it again?
Thanks

**Comment by phanirithvij** [comment]
This is not in a right category

**Comment by tiendc** [comment]
> This is not in a right category

I see another Copier one is in the group, DeepCopier. Could you point out which is the one more suitable?

**Comment by yassinebenaid** [comment]
Should we add a new category called `Reflection` (or similar) under which all reflect based projects will be listed ? @phanirithvij 

Examples:
- [Deepcopier](https://github.com/ulule/deepcopier) - Simple struct copying for Go.
- [copy](https://github.com/gotidy/copy) - Package for fast copying structs of different types.
- [gpath](https://github.com/tenntenn/gpath) - Library to simplify access struct fields with Go's expression in reflection.
- [objwalker](https://github.com/rekby/objwalker) - Walk by go objects with reflection.
- [reflectutils](https://github.com/muir/reflectutils) - Helpers for working with reflection: struct tag parsing; recursive walking; fill value from string.

And
-  [go-deepcopy](https://github.com/tiendc/go-deepcopy) - Fast deep copy library.

**Review by yassinebenaid — COMMENTED** [review]
This project was added by #5422 .

**Comment by yassinebenaid** [comment]
Thanks for contribution 👍

**Pull request closed without merging**
