### PR TITLE
Add Mattermost as a DevOps tool to awesome-go list

### PR DESCRIPTION
**Pull request by jasonblais**
Add Mattermost as a DevOps tool: https://github.com/mattermost/mattermost-server

**Please provide package links to:**

- github.com repo: https://github.com/mattermost/mattermost-server
- pkg.go.dev: https://pkg.go.dev/mod/github.com/mattermost/mattermost-server
- goreportcard.com: https://goreportcard.com/report/github.com/mattermost/mattermost-server
- coverage service link: https://codecov.io/gh/mattermost/mattermost-server

**Make sure that you've checked the boxes below before you submit PR:**
- [X] I have added my package in alphabetical order.
- [X] I have an appropriate description with correct grammar.
- [X] I know that this package was not listed before.
- [X] I have added pkg.go.dev link to the repo and to my pull request.
- [X] I have added coverage service link to the repo and to my pull request.
- [X] I have added goreportcard link to the repo and to my pull request.
- [X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

**Comment by avelino** [comment]
revew:
- https://goreportcard.com/report/github.com/mattermost/mattermost-server#golint
- cover today 49.11 https://codecov.io/gh/mattermost/mattermost-server

read pls: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards

**Comment by jasonblais** [comment]
@avelino thank you. Is there a minimum score that must be achieved for golint?

**Comment by jasonblais** [comment]
Given we don't meet this criteria

> Tests, where practical. If the library/program is testable, then coverage should be >= 80% for non-data-related packages and >=90% for data related packages. Notice: the tests will be reviewed too. We will check your coverage manually if your package's coverage is just a benchmark results.

I'll close this PR for now and reopen once we've met the quality standard.

**Pull request closed without merging**
