### PR TITLE
Add Watermill

### PR DESCRIPTION
**Pull request by frederikhors**
> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc): https://github.com/ThreeDotsLabs/watermill
- pkg.go.dev: https://pkg.go.dev/github.com/threedotslabs/watermill
- goreportcard.com: https://goreportcard.com/report/github.com/ThreeDotsLabs/watermill
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/ThreeDotsLabs/watermill

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below that apply before you submit PR.**
_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines for detials._

- [x] The package has been added to the list in alphabetical order.
- [x] The package has an appropriate description with correct grammar.
- [x] As far as I know, the package has not been listed here before.
- [x] The repo documentation has a pkg.go.dev link.
- [x] The repo documentation has a coverage service link.
- [x] The repo documenation has a goreportcard link.
- [x] The repo has a version-numbered release and a go.mod file.
- [x] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines), [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers) and [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).
- [x] The repo has a continuous integration process that automatically runs tests that must pass before new pull requests are merged.
- [x] The authors of the project do not commit directly to the repo, but rather use pull-requests that run the continuous-integration process.

Thanks for your PR, you're awesome! :+1:

@roblaszczak I tried again. We hope.

### CODE REVIEW

**Review by phanirithvij — CHANGES_REQUESTED** [review]
- golint
- gofmt (with -s flag)
- The documentation is outdated on pkg.go.dev because the last release was ~2 years ago.
- codecov coverage is out of date (shows coverage for a commit which was made 3 years ago)

**Comment by m110** [comment]
Thanks for submitting watermill @frederikhors. Most of the issues mentioned above are already fixed on the master branch. We need to wrap up some more documentation and we're going to release v1.2.0 soon.

**Review by avelino — CHANGES_REQUESTED** [review]
we are almost there, your package is just a few steps away from being accepted at awesome-go
- golint https://goreportcard.com/report/github.com/ThreeDotsLabs/watermill#golint
- coverage `78.99%`, need minimal `80%`

**Comment by aneshas** [comment]
Coverage seems to be at 84% now

**Comment by aneshas** [comment]
golint seems to be fine, or am I wrong? (it's not showing up at all in go report card)

**Comment by phanirithvij** [comment]
@m110 @frederikhors please comment here when v1.2.0 is released and when the pkg.go.dev, codecov sites reflect the latest version.

@aneshas you are correct that the golint section is absent in goreportcard, it won't show up for projects using go1.18 (generics) so golint will be ignored in the review.

And codecov is still showing a commit from 2019. The 84% is from the commit from [2019](https://codecov.io/gh/ThreeDotsLabs/watermill/commit/66eb3e08ea37c18f1b775364f4f39a5eb35f49c3)
The latest code coverage is 77% from my [fork](https://app.codecov.io/gh/phanirithvij/watermill) (with no code changes).

**Comment by m110** [comment]
Hey @phanirithvij @avelino

Watermill v1.2.0 has been released now, with codecov, pkg.go.dev and go report card links updated. Can we reopen the PR, please?

**Review by phanirithvij — APPROVED** [review]

**Comment by avelino** [comment]
Screenshot 2023-02-09 at 16 53 33

@m110 the list of files in the coverage system only shows 2 files, is this correct?

**Comment by m110** [comment]
@avelino nice catch, thanks! This should be running correct now.

**Pull request merged**
