### PR TITLE
Add Go swagger

### PR DESCRIPTION
**Pull request by MichelAquino**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo: https://github.com/go-swagger/go-swagger
- godoc.org: https://godoc.org/github.com/go-swagger/go-swagger
- goreportcard.com: https://goreportcard.com/report/github.com/go-swagger/go-swagger
- coverage service link (gocover, coveralls etc.): http://gocover.io/github.com/go-swagger/go-swagger

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by kirillDanshin** [comment]
hi @MichelAquino.
I see two changes in your PR.
please add links for second package or remove the link.
also please squash commits if you can.

**Comment by MichelAquino** [comment]
Hi @kirillDanshin .
I have merged with master.
The "go-torch" link refes to PR #1140

**Comment by kirillDanshin** [comment]
Please choose one link and remove other. Our guidelines allows only one link per item. Thanks.

**Comment by MichelAquino** [comment]
Hi @kirillDanshin 
Look the files changed, please.

**Comment by kirillDanshin** [comment]
I see two links here:

**Comment by MichelAquino** [comment]
@kirillDanshin Done!

**Pull request merged**
