### PR TITLE
Update Storm phrase and category

### PR DESCRIPTION
**Pull request by asdine**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo: [https://github.com/asdine/storm](https://github.com/asdine/storm)
- godoc.org: [https://godoc.org/github.com/asdine/storm](https://godoc.org/github.com/asdine/storm)
- goreportcard.com: [https://goreportcard.com/report/github.com/asdine/storm](https://goreportcard.com/report/github.com/asdine/storm)
- coverage service link (gocover, coveralls etc.): 

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [ ] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by appleboy** [comment]
need coverage service link.

**Comment by asdine** [comment]
@appleboy Sorry, here is the coverage link: https://gocover.io/github.com/asdine/storm

I have fixed some errors but still got some `gocyclo` warnings on some low level recursive functions that would require too much work IMO.

Btw, i forgot to mention, this PR is for updating an already submitted package

**Comment by appleboy** [comment]
@asdine I got it.

**Comment by asdine** [comment]
Thank you !

**Pull request merged**
