### PR TITLE
Add iuliia-go to Natural Language Processing

### PR DESCRIPTION
**Pull request by mehanizm**
`iuliia` is the port of the incredible python library [iuliia](https://github.com/nalgeon/iuliia-py) made by @nalgeon.

Transliteration means representing Cyrillic data (mainly names and geographic locations) with Latin letters. It is used for international passports, visas, green cards, driving licenses, mail and goods delivery etc.

Why use Iuliia:
* 20 transliteration schemas (rule sets), including all main international and Russian standards.
* Correctly implements not only the base mapping, but all the special rules for letter combinations and word endings (AFAIK, Iuliia is the only library which does so).
* Simple API and zero third-party dependencies.

**Please provide package links to:**

- [github.com repo](https://github.com/mehanizm/iuliia-go)
- [pkg.go.dev](https://pkg.go.dev/github.com/mehanizm/iuliia-go)
- [goreportcard.com](https://goreportcard.com/report/github.com/mehanizm/iuliia-go)
- [codecov](https://codecov.io/gh/mehanizm/iuliia-go)

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

**Comment by mehanizm** [comment]
I've fixed fmt issues in code generation. There are still some issues corresponding to variables name but I won't change the because it is the original schema names that are required by the original library.

**Comment by mehanizm** [comment]
Hi, @panjf2000 
Would you mind to review changes, please

**Comment by mehanizm** [comment]
@panjf2000 thanks a lot!

What should I do next to make merge done?

**Pull request merged**
