### PR TITLE
Adding kelindar/bitmap

### PR DESCRIPTION
**Pull request by kelindar**
Hi folks,

I'm adding a high quality implementation of a dense bitmap/bitset which supports various logical operations, iterating over, filtering and is SIMD-enabled (AVX2) for large dense bitsets. AVX-512 contributions would be welcome, if anyone has CPU that supports these.

- github.com repo: https://github.com/kelindar/bitmap
- pkg.go.dev: https://pkg.go.dev/github.com/kelindar/bitmap
- goreportcard.com: https://goreportcard.com/report/github.com/kelindar/bitmap
- coverage service link: https://coveralls.io/github/kelindar/bitmap (**97% coverage**)

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for reviewing this!

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by kelindar** [comment]
Any issue with this?

**Comment by nikolaydubina** [comment]
Hey, @avelino looks like a bunch of PRs got into backlog and marked as stale! 👋🏻

**Comment by nikolaydubina** [comment]
Maybe there should be a work group to unblock PRs. Also might be good to revisit all the entries to check if projects are maintained and working. Must be a great effort so team would be good.

**Pull request merged**
