### PR TITLE
Add tcod-go

### PR DESCRIPTION
**Pull request by Joakker**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/Joakker/tcod-go
- pkg.go.dev: https://pkg.go.dev/github.com/Joakker/tcod-go
- goreportcard.com: https://goreportcard.com/badge/github.com/Joakker/tcod-go
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.) https://travis-ci.com/Joakker/tcod-go

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.

- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: False
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
Review:
- misspell  https://goreportcard.com/report/github.com/Joakker/tcod-go#misspell
- coverage public link

**Comment by Joakker** [comment]
There we go, I corrected spelling mistakes and added the travis-ci build badge to the README.md

**Comment by avelino** [comment]
> There we go, I corrected spelling mistakes and added the travis-ci build badge to the README.md

I did not find the percentage of coverage in the travis log, I recommend using a coverage system

follows some recommendations:
- [codecov](https://codecov.io/)
- [coveralls](https://coveralls.io/)
- [gocover](http://gocover.io/)

**Comment by Joakker** [comment]
There, sorry it took so long, life got on the way.

**Comment by phanirithvij** [comment]
@Joakker coverage seems to be < 80% https://codecov.io/gh/Joakker/tcod-go, could you please improve it.

**Comment by Joakker** [comment]
I'll work on the library some more and open a pull request when everything is ready then
Thanks :smiley:

**Pull request closed without merging**
