### PR TITLE
Add Concourse

### PR DESCRIPTION
**Pull request by sfrique**
The main repo does not contain all source code, it relies on different repos, not sure how to add the links bellow. I added the main repo for the first line, but the main server code for the others.

**Please provide package links to:**

- github.com repo: https://github.com/concourse/concourse
- godoc.org: https://godoc.org/github.com/concourse/atc
- goreportcard.com: https://goreportcard.com/report/github.com/concourse/atc
- coverage service link cover.run go

Good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [X] I have added my package in alphabetical order.
- [X] I have an appropriate description with correct grammar.
- [X] I know that this package was not listed before.
- [X] I have added godoc link to the repo and to my pull request.
- [X] I have added coverage service link to the repo and to my pull request.
- [X] I have added goreportcard link to the repo and to my pull request.
- [X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by sfrique** [comment]
@cassiobotaro what do you mean?

**Comment by cassiobotaro** [comment]
@sfrique fix: 
- [ ] https://goreportcard.com/report/github.com/concourse/atc#golint 
- [ ] https://goreportcard.com/report/github.com/concourse/atc#ineffassign
- [ ] https://goreportcard.com/report/github.com/concourse/atc#gofmt
- [ ] https://goreportcard.com/report/github.com/concourse/atc#go_vet

**Comment by sfrique** [comment]
Oh, I'm just using the program.
If it needs 100%, i can't help the project right now.

I missed the 33% one, otherwise i would not have submitted. 

Sorry about it.

**Comment by cassiobotaro** [comment]
@sfrique Don't worry about that. Maybe you should open an issue in the project. I'm closing this PR but feel free to submit again later.

**Comment by chendrix** [comment]
Why are these requirements? Golint is a list of suggestions, and is explicitly not meant to be run in an automated fashion and held as a style guide?

**Comment by sfrique** [comment]
@cassiobotaro what about now?
From the report now, everything is above 95% except golint.

Thanks

**Pull request closed without merging**
