### PR TITLE
Added gody package

### PR DESCRIPTION
**Pull request by guiferpa**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/guiferpa/gody
- godoc.org: https://godoc.org/github.com/guiferpa/gody
- goreportcard.com: https://goreportcard.com/report/github.com/guiferpa/gody
- coverage service link: https://coveralls.io/github/guiferpa/gody?branch=master

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: True
- goreportcard.com: True
- coverage: True

**Comment by guiferpa** [comment]
1. - [x] Fix the code issues of go_vet and golint
https://goreportcard.com/report/github.com/guiferpa/gody

2. - [x] Increase the code coverage to meet our standard(>=80%), it is 76% currently.
https://coveralls.io/github/guiferpa/gody?branch=master

**cc** @panjf2000

**Comment by panjf2000** [comment]
@guiferpa 
Unfortunately, there is a conflict between the previous commit and your commit and you have to resolve it.

**Comment by guiferpa** [comment]
Done @panjf2000

**Pull request merged**
