### PR TITLE
Added cachet client library

### PR DESCRIPTION
**Pull request by andygrunwald**
[Go(lang)](https://golang.org/) client library for [Cachet (open source status page system)](https://cachethq.io/).

Please provide package links to:
- godoc.org: https://godoc.org/github.com/andygrunwald/cachet
- goreportcard.com: https://goreportcard.com/report/github.com/andygrunwald/cachet
- coveralls.io: https://coveralls.io/github/andygrunwald/cachet

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@andygrunwald sorry for taking so much time. please, fix go 1.6 build. I see that you support it, but build failed. thanks.

**Comment by andygrunwald** [comment]
@kirillDanshin Done
The build is green now :)

Checkout https://travis-ci.org/andygrunwald/cachet

**Comment by andygrunwald** [comment]
@kirillDanshin Any update here?

**Comment by kirillDanshin** [comment]
thanks for your contribution.
also please also fix auth and cachet.go tests asap.

**Pull request merged**
