### PR TITLE
Adding oc to Data Structures

### PR DESCRIPTION
**Pull request by jasonmoo**

### CODE REVIEW

**Comment by mholt** [comment]
Needs godocs

**Comment by jasonmoo** [comment]
Link is at the bottom of the readme

**Comment by mholt** [comment]
No godoc comments - a list of functions and types do not qualify as documentation.

**Comment by cassiobotaro** [comment]
@jasonmoo  For  quality standards please follow:  https://github.com/avelino/awesome-go/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Pull request closed without merging**
