### PR TITLE
Add go-steam, library to interact with Steam servers

### PR DESCRIPTION
**Pull request by kidoman**
Ref: https://developer.valvesoftware.com/wiki/Source_RCON_Protocol

### CODE REVIEW

**Comment by shurcooL** [comment]
The linked repo has an import path of `github.com/sostronk/go-steam`, but the readme says:

```
go get github.com/kidoman/go-steam
```

Which is the right import path?

**Comment by norwack** [comment]
@shurcooL The first one was updated in february, the latter was last updated in december. "sostronk" is an organization with only @kidoman as a member, so i'd assume `github.com/sostronk/go-steam` is the correct import path.

It's also 8 commits ahead of kidoman:master.

**Comment by shurcooL** [comment]
In that case, it's README should be updated to match.

**Comment by kidoman** [comment]
Will do that!

**Comment by shurcooL** [comment]
LGTM.

**Comment by dukex** [comment]
The project has a documentation?

**Comment by shurcooL** [comment]
Its godoc is at https://godoc.org/github.com/sostronk/go-steam.

**Pull request merged**
