### PR TITLE
Added go-live

### PR DESCRIPTION
**Pull request by antsankov**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/antsankov/go-live
- pkg.go.dev: https://pkg.go.dev/github.com/antsankov/go-live@v1.0.0
- goreportcard.com: https://goreportcard.com/report/github.com/antsankov/go-live
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.)

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [X] I have added my package in alphabetical order.
- [X] I have an appropriate description with correct grammar.
- [X] I know that this package was not listed before.
- [X] I have added pkg.go.dev link to the repo and to my pull request.
- [X] I have added coverage service link to the repo and to my pull request.
- [X] I have added goreportcard link to the repo and to my pull request.
- [X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
review:
- https://goreportcard.com/report/github.com/antsankov/go-live#golint
- coverage link

> Tests, where practical. If the library/program is testable, then coverage should be >= 80% for non-data-related packages and >=90% for data related packages

**Comment by antsankov** [comment]
In its current state the codebase is so small and static that unit tests
seem like overkill, however happy to write them if truly necessary.

The idea is that this package is changed very rarely since it’s a shell
utility, and the codebase is under 300 LOC.

Awaiting further guidance.

**Comment by avelino** [comment]
We cannot accept your contribution without having as validity the quality of the package.
I would be happy to accept your contribution, but without testing I cannot.

**Comment by antsankov** [comment]
ACK @avelino - will be release 1.1 go-live with bug fixes and unit tests added in next few weeks.

**Pull request closed without merging**
