### PR TITLE
doc: add protoncheck

### PR DESCRIPTION
**Pull request by servusdei2018**
# protoncheck
[](https://goreportcard.com/report/github.com/servusdei2018/protoncheck) [Go Reference](https://pkg.go.dev/github.com/servusdei2018/protoncheck) [](https://sonarcloud.io/project/overview?id=servusdei2018_protoncheck)

 ProtonMail module for waybar/polybar/yabar/i3blocks 

## Package Links
- repo link: https://github.com/servusdei2018/protoncheck
- pkg.go.dev: https://pkg.go.dev/github.com/servusdei2018/protoncheck
- goreportcard.com: https://goreportcard.com/report/github.com/servusdei2018/protoncheck
- coverage: https://app.codecov.io/gh/servusdei2018/protoncheck
## Checklist
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: False

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
need coverage
Screen Shot 2022-01-05 at 14 47 42

**Comment by avelino** [comment]
> Updated coverage: https://app.codecov.io/gh/servusdei2018/protoncheck

today is `29.17%`, for your package to enter awesome-go we ask for a minimum of `80%`
read more [here](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards)

**Comment by servusdei2018** [comment]
Hmm, I was able to increase code coverage to 75.00%, but I'm afraid there's no way for the unit tests to cover more as the rest of the code is dependent upon successful Authentication with ProtonMail's API and it would be impractical to include auth secrets in CI pipelines.

**Pull request merged**
