### PR TITLE
Add muesli/termenv

### PR DESCRIPTION
**Pull request by mjarkk**
So lately i have used this list to get another text color library for lazygit with support for RGB colors, sadly there seems to be only one library in here that is not a logger and has RGB text color support (https://github.com/gookit/color) sadly that library has a lot of problems for my use case:
- No single interface for switching between 16-color (4-bit), 256-color (8-bit) and true color (24-bit, RGB) (so i needed to write at least 100 lines for a general abstraction)
- A lot of chinese in it's docs and source code
- Seems to miss a lot of helper functions for advanced usage
Github just recommended https://github.com/muesli/termenv and if only that library was in this list because it solves all the problems from above and supports all the terminal color outputs just fine and thus would have saved me lots of time

**Please provide package links to:**

- repo link: https://github.com/muesli/termenv
- pkg.go.dev: https://pkg.go.dev/github.com/muesli/termenv
- goreportcard.com: https://goreportcard.com/report/github.com/muesli/termenv
- coverage service: https://coveralls.io/github/muesli/termenv?branch=master

The code coverage is not great but i hope i can convince you with the intro

**Make sure that you've checked the boxes below before you submit PR:**
_not every repository (project) will fit into every option, but most projects should_

- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by phanirithvij** [comment]
The coverage is < 80%.

**Comment by mjarkk** [comment]
@phanirithvij yes I know but did you even read the pr?  
This library can save a lot of people a lot of time.

**Comment by phanirithvij** [comment]
@mjarkk yes I did read the PR and I also created an issue in that repo to try get the code coverage up.
If you truly believe this is a useful library and will help a lot of people, I think it would be best to wait for it to be well tested before suggesting it to people. That is why the quality standards exist.

And yes, I do agree with you that it is useful.

**Comment by phanirithvij** [comment]
Seems like it's hard to do integration tests with terminal. https://github.com/muesli/termenv/issues/43#issuecomment-890623677

**Pull request merged**
