### PR TITLE
Add sched

### PR DESCRIPTION
**Pull request by romshark**
- github.com repo: https://github.com/romshark/sched
- pkg.go.dev: https://pkg.go.dev/github.com/romshark/sched
- goreportcard: https://goreportcard.com/report/github.com/romshark/sched
- test coverage: https://coveralls.io/github/romshark/sched?branch=main

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
review golint (https://goreportcard.com/report/github.com/romshark/sched#golint)

**Comment by romshark** [comment]
I generally try to avoid comments like these ([go lint complaint](https://github.com/romshark/sched/blob/master/sched.go#L18)):
```go
// Nanosecond is a nanosecond
Nanosecond = time.Nanosecond
```
Since these kinds of symbols are self-explanatory.

**Comment by ncruces** [comment]
Not disagreeing with you, but you can comment the block, you don't need to comment each contant individually.

**Pull request merged**
