### PR TITLE
add smart-home to the IoT category

### PR DESCRIPTION
**Pull request by e154**
## We want to ensure high quality of the packages. Make sure that you've checked the boxes below before sending a pull request.

- [x] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines)
- [x] I have read the [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers)
- [x] I have read the [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards)

_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines for details._

- [x] The repo documentation has a pkg.go.dev link.
- [x] The repo documentation has a coverage service link.
- [x] The repo documentation has a goreportcard link.
- [x] The repo has a version-numbered release and a go.mod file.
- [x] The repo has a continuous integration process that automatically runs tests that must pass before new pull requests are merged.
- [x] Continuous integration is used to attempt to catch issues prior to releasing this package to end-users.

## Please provide some links to your package to ease the review

- [x] forge link (github.com, gitlab.com, etc): https://github.com/e154/smart-home
- [x] pkg.go.dev: https://pkg.go.dev/github.com/e154/smart-home
- [x] goreportcard.com: https://goreportcard.com/report/github.com/e154/smart-home
- [x] coverage service link (codecov, coveralls, etc.): https://app.codecov.io/gh/e154/smart-home

## Pull Request content

- [x] The package has been added to the list in alphabetical order.
- [x] The package has an appropriate description with correct grammar.
- [x] As far as I know, the package has not been listed here before.

## Category quality

_Note that new categories can be added only when there are 3 packages or more._

Packages added a long time ago might not meet the current guidelines anymore. It would be very helpful if you could check 3-5 packages above and below your submission to ensure that they also still meet the Quality Standards.

Please delete one of the following lines:

- [x] The packages around my addition still meet the Quality Standards.

Thanks for your PR, you're awesome! :sunglasses:

### CODE REVIEW

**Comment by riccardopinosio** [comment]
@e154 I think you're missing the full stop "." at the end of the added line

**Comment by e154** [comment]
> @e154 I think you're missing the full stop "." at the end of the added line

thanks for the note, fixed it

**Comment by phanirithvij** [comment]
Is it not possible to improve the code coverage or atleast have e2e tests? I can think of having a self-hosted github actions runner and do integration tests (test all features basically) or do you have something similar like a test rig? If so I don't mind the low code coverage.

**Comment by kalapee** [comment]
Okay

**Comment by e154** [comment]
In the application, important parts of the functional code are covered by unit tests and e2e tests in the test directories. I test the rest of the parts locally. I won’t be able to fully cover it with automated tests, because the application is very large and I don’t have enough effort and resources. Hopefully this will improve over time as the app's community of users expands and more helpers appear.

**Pull request merged**
