### PR TITLE
Add gosocsvr

### PR DESCRIPTION
**Pull request by Rakeki**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/Rakeki/gosocsvr
- godoc.org: https://godoc.org/github.com/Rakeki/gosocsvr
- goreportcard.com: https://goreportcard.com/report/github.com/Rakeki/gosocsvr
- coverage service link: https://gocover.io/github.com/Rakeki/gosocsvr

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [*] I have added my package in alphabetical order.
- [*] I have an appropriate description with correct grammar.
- [*] I know that this package was not listed before.
- [*] I have added godoc link to the repo and to my pull request.
- [*] I have added coverage service link to the repo and to my pull request.
- [*] I have added goreportcard link to the repo and to my pull request.
- [*] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: True
- goreportcard.com: True
- coverage: True

**Comment by Rakeki** [comment]
This has now been actioned.

**Comment by panjf2000** [comment]
@Rakeki 
You are not putting it alphabetically, please correct it:
```
        repo_test.go:135: expected order is:
            arp
            buffstreams
            canopus
            cidranger
            dhcp6
            dns
            ether
            ethernet
            fasthttp
            fortio
            ftp
            gev
            gmqtt
            gnet
            gnxi
            go-getter
            go-powerdns
            go-stun
            gobgp
            golibwireshark
            gopacket
            gopcap
            goshark
            gosnmp
            **gosocsvr**
            gotcp
            grab
            graval
            httplab
```

**Comment by Rakeki** [comment]
Amended order

**Comment by panjf2000** [comment]
Please squash your commits to only one before this PR gets merged.

**Comment by Rakeki** [comment]
flattened.

**Comment by panjf2000** [comment]
There are still two commits, please squash them into one.

**Comment by Rakeki** [comment]
Done.

**Pull request merged**
