### PR TITLE
Add nject/npoint dependency injection frameworks

### PR DESCRIPTION
**Pull request by muir**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/BlueOwlOpenSource/nject
- pkg.go.dev: https://pkg.go.dev/github.com/BlueOwlOpenSource/nject
- goreportcard.com: https://goreportcard.com/report/github.com/BlueOwlOpenSource/nject
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://gocover.io/github.com/BlueOwlOpenSource/nject/nject & https://gocover.io/github.com/BlueOwlOpenSource/nject/npoint

Npoint has a bunch of one-line wrapper functions that bring down its coverge numbers

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

With regards to the quality standards, aside from a little touch-up today, nject hasn't been touched in the last couple of years.  On the other hand, it's used in every part of large closed source project and we haven't found any bugs in nject the last couple of years.

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by muir** [comment]
> The maintainers will review your PR and notify you and tag it in case any information is still missing. They will wait 15 days for your interaction, after that the PR will be closed.

> This PR has been automatically marked as closed because it has not had recent activity. They will wait 15 days for your interaction, after that the PR will be closed. Please read more in https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md

Nothing was tagged as missing.  This should not be marked stale since there was no un-fulfilled request.

**Comment by muir** [comment]
> This PR has been automatically marked as closed because it has not had recent activity

Umm, I see that a "stale" tag was added, but this still seems open.   How can I get the "stale" tag removed?

**Review by avelino — APPROVED** [review]
lint is good, but can be improved https://goreportcard.com/report/github.com/BlueOwlOpenSource/nject#golint

**Comment by avelino** [comment]
> Umm, I see that a "stale" tag was added, but this still seems open. How can I get the "stale" tag removed?

sorry for the delay in reviewing your contribution, unfortunately awesome-go is not my first job - I can't look at the project every week, if you are interested in contributing, **you are very welcome**

**Pull request merged**
