### PR TITLE
add maja42/goval

### PR DESCRIPTION
**Pull request by maja42**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/maja42/goval
- pkg.go.dev: [GoDoc](https://pkg.go.dev/github.com/maja42/goval) 
- goreportcard.com: [Go Report Card](https://goreportcard.com/report/github.com/maja42/goval)
- coverage service link [Coverage Status](https://coveralls.io/github/maja42/goval?branch=master)
Note: Low coverage is caused by auto-generated, unreachable code

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by maja42** [comment]
Since I didn't hear anything back, and the issue is now marked as stale - is there any information you need from me?
Or is awesome-go no longer maintained?

**Review by avelino — CHANGES_REQUESTED** [review]
review lint pls https://goreportcard.com/report/github.com/maja42/goval#golint

**Comment by avelino** [comment]
> Since I didn't hear anything back, and the issue is now marked as stale - is there any information you need from me?
> Or is awesome-go no longer maintained?

@maja42 sorry for the delay in reviewing your contribution, unfortunately awesome-go is not my first job - I can't look at the project every week, if you are interested in contributing, **you are very welcome**

**Comment by maja42** [comment]
Thank you for your time, I completely understand that.
I just wasn't sure about how active this project still is, since a lot of PR before me already went stale.

Regarding the lint problems:
Those are from an internal package that is not accessible by library users - simlar to unexported functions. So I'd guess that it's not needed / useful to write goDoc comments there? (There's not really a difference to an actually unexported function from a users' perspective.)
If you want, I can of course document everything to get 100% go-vet compliance. But if you're willing to share, I'm curious about the reasoning behind documenting internal packages. Maybe there's a reason the vet-check doesn't supress those warnings...

**Comment by maja42** [comment]
Note: There's an issue about this in the golint project dating back to 2019, but without any real discussion: https://github.com/golang/lint/issues/442

**Pull request merged**
