### PR TITLE
added new jwt library

### PR DESCRIPTION
**Pull request by adam-hanna**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo: 
- godoc.org: 
- goreportcard.com: 
- coverage service link (gocover, coveralls etc.): 

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by adam-hanna** [comment]
Thank you for considering my package and please accept my apologies for not adding the necessary links in my original submission.

I have made the necessary changes and now believe my repo now meets all of your requirements.

Thanks again.

**Comment by adam-hanna** [comment]
Just brought my fork up to date with your master

**Comment by avelino** [comment]
We need to put the links here in PR to validate, please read
https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines

**Comment by adam-hanna** [comment]
[Build Status](https://travis-ci.org/adam-hanna/jwt-auth) [Coverage Status](https://coveralls.io/github/adam-hanna/jwt-auth?branch=feature%2Ftravis_ci) [Go Report Card](https://goreportcard.com/report/github.com/adam-hanna/jwt-auth) [GoDoc](https://godoc.org/github.com/adam-hanna/jwt-auth/jwt)


Thanks!

**Comment by avelino** [comment]
@adam-hanna recheck you go lint pls: https://goreportcard.com/report/github.com/adam-hanna/jwt-auth#golint

**Comment by adam-hanna** [comment]
@avelino, most of those are in my examples subfolder `jwt-auth/examples/`

**Comment by kirillDanshin** [comment]
@adam-hanna please check go vet please. also maybe you can fix go lint and go cyclo issues too?

**Comment by avelino** [comment]
```
Line 83: warning: don't use underscores in Go names; struct field Auth_Token should be AuthToken (golint)
Line 84: warning: don't use underscores in Go names; struct field Refresh_Token should be RefreshToken (golint)
```

rename struct field

**Comment by adam-hanna** [comment]
Do you guys require a 100% score in every category?

**Comment by kirillDanshin** [comment]
@adam-hanna yes, if it possible.

**Comment by adam-hanna** [comment]
@kirillDanshin, @avelino: thanks for your patience and sorry for the abundant hassle.

I've made the changes to the code. There are three unit tests that could be improved from a cyclomatic complexity perspective, but the source code itself is all receiving a 100% score. Let me know if this is unacceptable.

https://goreportcard.com/report/github.com/adam-hanna/jwt-auth

**Comment by kirillDanshin** [comment]
@adam-hanna please fix tests too as soon as possible. anyway, LGTM.

**Pull request merged**
