### PR TITLE
Add CSS-Checker

### PR DESCRIPTION
**Pull request by zhcalvin**
> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc): https://github.com/ruilisi/css-checker
- pkg.go.dev: https://pkg.go.dev/github.com/ruilisi/css-checker
- goreportcard.com:
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.):

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below that apply before you submit PR.**
_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines for detials._

- [x] The package has been added to the list in alphabetical order.
- [x] The package has an appropriate description with correct grammar.
- [x] As far as I know, the package has not been listed here before.
- [x] The repo documentation has a pkg.go.dev link.
- [ ] The repo documentation has a coverage service link.
- [x] The repo documenation has a goreportcard link.
- [x] The repo has a version-numbered release and a go.mod file.
- [x] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines), [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers) and [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).
- [x] The repo has a continuous integration process that automatically runs tests that must pass before new pull requests are merged.
- [x] The authors of the project do not commit directly to the repo, but rather use pull-requests that run the continuous-integration process. // I am one of the contributors and we push to a git service with CICD enabled by pull request, once the pr merged into the css-checker repo inside our git service, the drone service with automatically force-push to github main branch. You can check the process by click "build success" button in this repo

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: False
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by spekary** [comment]
Thank you for your contribution. This looks like a great idea.

However, the submission doesn't meet our guidelines. You checked that the repo documentation has links to Go Report Card, but I did not see that in your README file. If it is somewhere else, please include that. You also need a code coverage report.

Also a suggestion:

This appears to be a standalone executable. That it is written in Go does not necessarily make it useful to the Go community. However, if you are also making available to the Go community some functions that can be used in other Go code, you can reorganize your code to help communicate that:

- Any code that is specific to the command line execution of the application should go into a "cmd" directory.
- Any code that is useful for other Go applications should go in a "pkg" directory.
- Any code that is used by code in the cmd and/or pkg directory that you would like to prevent other Go applications from using should go in an "internal" directory.

**Comment by phanirithvij** [comment]
@zhcalvin code coverage is `24.2%` from `make test-models`.
awesome-go requires > 80% code coverage as per the [quality standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).

**Review by phanirithvij — CHANGES_REQUESTED** [review]
@zhcalvin code coverage is `24.2%` from `make test-models`.
awesome-go requires > 80% code coverage as per the [quality standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).
Also golint issues: https://goreportcard.com/report/github.com/ruilisi/css-checker#golint

**Comment by zhcalvin** [comment]
Thanks for feedbacks, I will check it.

**Pull request closed without merging**
