### PR TITLE
slowpoke - Key-value store with persistence

### PR DESCRIPTION
**Pull request by recoilme**
**Package links:**

- github.com repo: https://github.com/recoilme/slowpoke
- godoc.org: https://godoc.org/github.com/recoilme/slowpoke
- goreportcard.com:https://goreportcard.com/report/github.com/recoilme/slowpoke
- coverage service link:cover.run go
https://cover.run/go/github.com/recoilme/slowpoke?tag=golang-1.10

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by recoilme** [comment]
@appleboy  looks like it fixed, or I must create new PR?

**Comment by recoilme** [comment]
Is goreport card ok now? (It has gocyclo > 15 in one method but I need it)

**Comment by appleboy** [comment]
code coverage? link broken

**Comment by recoilme** [comment]
Sorry - is this right code coverage link? 
https://cover.run/go/github.com/recoilme/slowpoke?tag=golang-1.10

**Comment by recoilme** [comment]
@appleboy hello, any news?

**Comment by appleboy** [comment]
@recoilme LGTM

**Pull request merged**
