### PR TITLE
Add hydra to the list oauth2 apps

### PR DESCRIPTION
**Pull request by raravena80**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/ory/hydra
- godoc.org: https://godoc.org/github.com/ory/hydra
- goreportcard.com: https://goreportcard.com/report/github.com/ory/hydra
- coverage service link: [coveralls](https://coveralls.io/github/ory/hydra?branch=master)

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x ] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by raravena80** [comment]
I'm not the maintainer for hydra, so we can just leave this open until they fix it. Or you can close and we can add it later.

I've open https://github.com/ory/hydra/issues/818 to track the issue.

**Comment by arekkas** [comment]
> That’s not a big deal. Most issues are regarding tests or undocumented exports. The latter doesn’t really matter because this isn’t a library. Why do you see this as an issue and why is it important to you?

**Comment by jtemporal** [comment]
I'm closing this one due to inactivity. If Hydra improves it's lint score feel free to send a PR :wink:

**Comment by arekkas** [comment]
Is the explanation on why lint coverage is not important (especially if you look at the lint issues specifically) not satisfying? Also linting does not appear in the [contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard). The score is A+ after all, only the exported functions which are used internally across packages are what lint is reporting about. And again, it's not a big deal because it's not supposed to be used as a library.

**Pull request closed without merging**
