### PR TITLE
add goribot

### PR DESCRIPTION
**Pull request by zhshch2002**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/zhshch2002/goribot
- godoc.org: https://godoc.org/github.com/zhshch2002/goribot
- goreportcard.com: https://goreportcard.com/report/github.com/zhshch2002/goribot
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://codecov.io/gh/zhshch2002/goribot

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: True
- goreportcard.com: True
- coverage: True

**Comment by panjf2000** [comment]
Please make the percentage of golint 100%, https://goreportcard.com/report/github.com/zhshch2002/goribot#golint

**Comment by zhshch2002** [comment]
@panjf2000 the issues of golint was fixed https://goreportcard.com/report/github.com/zhshch2002/goribot#golint

**Comment by panjf2000** [comment]
Two leftovers:
1. You got some typos in README: ues->use, for instance, [basic-ues](https://github.com/zhshch2002/goribot#basic-ues). please correct them all
2. Don't put any Chinese in the English README: [TODO](https://github.com/zhshch2002/goribot#todo), just translate them into English.

**Comment by zhshch2002** [comment]
Thank you for your correction, these two issues have been fixed.

**Pull request merged**
