### PR TITLE
Add Orion as one of frameworks

### PR DESCRIPTION
**Pull request by hothero**
> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc): https://github.com/carousell/Orion
- pkg.go.dev: https://pkg.go.dev/github.com/carousell/Orion/orion
- goreportcard.com: https://goreportcard.com/report/github.com/carousell/Orion
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/carousell/Orion

Very good coverage

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below before you submit PR:**
_not every repository (project) will fit into every option, but most projects should_

- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards).

### CODE REVIEW

**Review by avelino — CHANGES_REQUESTED** [review]
take your time to read the [pull request template](https://github.com/avelino/awesome-go/blob/master/.github/PULL_REQUEST_TEMPLATE.md) (you deleted without reading) and the [quality guide](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards)

**Comment by phanirithvij** [comment]
@hothero Can you please check why the coverage isn't showing up on codecov?

**Comment by hothero** [comment]
@phanirithvij I'm figuring out why the admin panel still shows no coverage report uploaded after everything setup. Will try to get it done asap

**Comment by hothero** [comment]
Done. Please help review again @phanirithvij @avelino

**Review by avelino — CHANGES_REQUESTED** [review]
review:
- coverage > 80%, today it is 58.35%
- golint https://goreportcard.com/report/github.com/carousell/Orion#golint

**Pull request closed without merging**
