### PR TITLE
add kcptun

### PR DESCRIPTION
**Pull request by xtaci**
add kcptun
an extremely simple & fast udp tunnel based on kcp protocol

### CODE REVIEW

**Comment by kirillDanshin** [comment]
hi again @xtaci 
please add english readme. also, please add tests and any coverage tracking service. 
thanks.

**Comment by xtaci** [comment]
added godoc/travis/goreport/coverage

english readme will come later, a lots of translation need to be done.

**Comment by xtaci** [comment]
https://github.com/xtaci/kcptun/blob/master/README.en.md
english readme has commited

**Comment by kirillDanshin** [comment]
@xtaci hi! thanks for english translation.
I can't find your coverage link.

**Comment by xtaci** [comment]
@kirillDanshin   coverage link have had added before, but it seemed not quite applicable to kcptun; because it's only a wrapper to kcp-go, which contains only a main.go file.  see [kcp-go](https://github.com/xtaci/kcp-go) for more. If the coverage is a must, structure changes have to be made to main.go.

**Comment by kirillDanshin** [comment]
ok, I see.
thanks @xtaci

**Comment by xtaci** [comment]
:ok_hand:

**Pull request merged**
