### PR TITLE
Add Bigbucket to Database section

### PR DESCRIPTION
**Pull request by adrianchifor**
- github.com repo: https://github.com/adrianchifor/Bigbucket
- pkg.go.dev: https://pkg.go.dev/github.com/adrianchifor/Bigbucket?tab=overview
- goreportcard.com: https://goreportcard.com/report/github.com/adrianchifor/Bigbucket
- coverage service link

[Custom tests suite](https://github.com/adrianchifor/Bigbucket#tests) with very good functionality coverage.

- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: False

**Comment by adrianchifor** [comment]
Updated

**Comment by adrianchifor** [comment]
> Please fix https://goreportcard.com/report/github.com/adrianchifor/Bigbucket#golint

Done

**Comment by adrianchifor** [comment]
> > Please see link to custom tests suite. It's separate and covers end-to-end functionality for the different components, coverage won't work as it doesn't refer to code directly.
> 
> Then where is your test suite?

The link is in the first comment, see [here](https://github.com/adrianchifor/Bigbucket#tests)

**Comment by adrianchifor** [comment]
> But you didn't add `-cover` arg in your `go test` cmd, please add it so that the coverage will be shown in the output.

The tests are functional/end-to-end, not unit, so `-cover` won't do anything as there's no direct functions being called.

**Comment by panjf2000** [comment]
As I can remember, `-cover` still work even if it's end-to-end test, you can give it a try.

**Comment by adrianchifor** [comment]
> As I can remember, `-cover` still work even if it's end-to-end test, you can give it a try.

Nope, the tests are not calling code directly. I run the binary and check expected functionality from requests.

Here's the output with `-cover`
```
$ make test bucket=gs://adrian-test-bigbucket
go fmt
go mod download
go build -o bin/bigbucket
tests/run_tests.sh gs://adrian-test-bigbucket

Running bigbucket server

Running row tests
ok      command-line-arguments  4.239s  coverage: [no statements]

Running column tests
ok      command-line-arguments  0.318s  coverage: [no statements]

Running table tests
ok      command-line-arguments  0.115s  coverage: [no statements]

Running bigbucket cleaner

Running bigbucket cleaner tests
ok      command-line-arguments  6.707s  coverage: [no statements]

Killing bigbucket cleaner

Running bigbucket cleaner as HTTP server

Running HTTP cleaner tests
ok      command-line-arguments  1.081s  coverage: [no statements]

Cleaning up test bucket
Cleaning up bigbucket processes
Done
```

**Comment by adrianchifor** [comment]
@panjf2000 ping

**Comment by avelino** [comment]
not working on https://gocover.io/github.com/adrianchifor/Bigbucket

**Comment by adrianchifor** [comment]
> not working on https://gocover.io/github.com/adrianchifor/Bigbucket

Please see comments above. Custom tests suite cover end-to-end functionality. `go test` will not work as it tries to talk to GCS, hence why gocover doesn't pass that step.

**Pull request closed without merging**
