### PR TITLE
Add ews - Go package wrapper for Exchange Web Service

### PR DESCRIPTION
**Pull request by mhewedy**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/mhewedy/ews
- pkg.go.dev: https://pkg.go.dev/github.com/mhewedy/ews
- goreportcard.com: https://goreportcard.com/report/github.com/mhewedy/ews
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/mhewedy/ews

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

**Comment by mhewedy** [comment]
I noticed the original repo has 5 commits that were committed before 4 years ago. So I felt I will have much liberty if I do make own fork (especially as mentioned in the repo description; I am using this as a helper for another project https://github.com/mhewedy/mego)

Also, I did many changes, I  borrow the idea from the original repo and do many changes. ( as appears if you compare the functions implemented and the code base)

You can also check the forks insights https://github.com/mhewedy/ews/network/members

**Comment by panjf2000** [comment]
OK, then you just resolve those code issues and increase the code coverage before this PR gets merged.

**Comment by mhewedy** [comment]
Will try to work on once have time. thanks.

**Comment by panjf2000** [comment]
It's been more than 15 days without a reply from the PR owner, I'm closing this PR according to our [contributing guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers).

Feel free to reopen it once you resolve those issues.

**Pull request closed without merging**
