### PR TITLE
Added Gitote

### PR DESCRIPTION
**Pull request by Unicorn0x1**
**Please provide package links to:**

- github.com(gitote.in) repo: https://gitote.in/gitote/gitote
- godoc.org: https://godoc.org/gitote.in/gitote/gitote
- goreportcard.com: https://goreportcard.com/report/gitote.in/gitote/gitote

**Our Product Release Blog:** https://dev.to/gitote/gitote-has-been-launched-m35
**We became famous:** https://dev.to/gitote/how-gitote-mitigated-massive-ddos-attack--115l

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by Unicorn0x1** [comment]
https://app.codacy.com/project/Gitote/gitote/dashboard

**Comment by Unicorn0x1** [comment]
I think it is already in Good Grade (A)

**Comment by appleboy** [comment]
Please fix the all warnings from go report card.

**Comment by CodingPurple** [comment]
Hello @Unicorn0x1, Thanks for Adding [Gitote](https://gitote.in)!

**Comment by appleboy** [comment]
@CodingPurple Are you an author of Gitote?

**Comment by CodingPurple** [comment]
I'm the Founder of [Gitote](https://gitote.in) @appleboy

**Comment by appleboy** [comment]
@CodingPurple Gitote forked from Gogs right?

**Comment by CodingPurple** [comment]
Yeah of course! But is made for public.

**Comment by lunny** [comment]
@CodingPurple but you should not remove the copyright on all the files head.

**Comment by ceriath** [comment]
Until https://gitote.in/gitote/gitote/issues/83 is resolved there is no way this will be accepted.

**Comment by CodingPurple** [comment]
We have fixed it @ceriath please check now!

**Comment by ceriath** [comment]
@CodingPurple thanks! however, goreportcard is still in a bad state, please fix it, as asked earlier multiple times

**Comment by CodingPurple** [comment]
Fixing GoReportcard issues will take too much time! However it is still in **A** Grade i think!

**Comment by ceriath** [comment]
@CodingPurple since you apparently have no intentions to fix goreportcard, i am closing this PR. Feel free to resubmit when goreportcard is fixed.
cc @Unicorn0x1

**Comment by yocorn** [comment]
Hello @ceriath, Now we have updated our code and we got **A+** in go report card

We are still working on it! Can you repoen it?

**Comment by appleboy** [comment]
@yocorn Please fix the `gofmt`, `go_vet`, `golint` and `ineffassign` warning to 100%

**Comment by yocorn** [comment]
ok @appleboy I'm working hard on it!

**Pull request closed without merging**
