### PR TITLE
added alioygur/gores

### PR DESCRIPTION
**Pull request by alioygur**
Please check if what you want to add to `awesome-go` list meets 
[quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) 
before sending pull request. Thanks!

Link to [godoc.org](https://godoc.org/): https://godoc.org/github.com/alioygur/gores

Link to [goreportcard.com](https://goreportcard.com): https://goreportcard.com/report/github.com/alioygur/gores

Link to [gocover.io](https://gocover.io/): https://gocover.io/github.com/alioygur/gores

### CODE REVIEW

**Comment by alioygur** [comment]
updated

**Comment by matrixik** [comment]
Hello, thank you for contribution.

Some comments: 

- The name of the language is **Go** not **GO**
- Please remove Sublime Text files. They are unnecessary.
- https://gotools.org/github.com/alioygur/gores?tests=#gores-go-L99-L101 is same as `_json`
- https://gotools.org/github.com/alioygur/gores?tests=#gores-go-L142-L145 is same as `_xml`
- You don't need to import your own package in test. Use functions directly (this way you can test private functions).

Other than that looks good, small, useful package.

P.S. You could also investigate https://github.com/golang/go/wiki/TableDrivenTests at future.

**Comment by alioygur** [comment]
@matrixik I have refactored my source code, based your comments.

with which tool did you detect these issues?

https://gotools.org/github.com/alioygur/gores?tests=#gores-go-L99-L101 is same as _json
https://gotools.org/github.com/alioygur/gores?tests=#gores-go-L142-L145 is same as _xml

thank you.

**Comment by matrixik** [comment]
Wow, thank you for fast fixes.

Personally I used one of my most valuable tools, my eyes.
But maybe https://github.com/mibk/dupl would find it, I don't know.
You could also check https://github.com/alecthomas/gometalinter

**Comment by alioygur** [comment]
:) thank you.

**Pull request merged**
