### PR TITLE
Add laitos project into the list

### PR DESCRIPTION
**Pull request by HouzuoGuo**
laitos is a cloud-compatible single-executable personal web infrastructure software, plus interface to the public Internet for PSTN, SMS, chatbots, and satellite terminals.

- github.com repo: https://github.com/HouzuoGuo/laitos
- coverage: https://circleci.com/gh/HouzuoGuo/laitos
- report card: https://goreportcard.com/badge/github.com/HouzuoGuo/laitos

### CODE REVIEW

**Comment by HouzuoGuo** [comment]
@appleboy report card link is now placed in the initial comment

**Comment by HouzuoGuo** [comment]
thanks @jtemporal , while projects certainly should pursue after 100% score, but in terms of the evaluations made by awesome-go, is there a threshold value target?

**Comment by jtemporal** [comment]
@HouzuoGuo 
>  there a threshold value target?

Always 100% :stuck_out_tongue_closed_eyes:

**Comment by HouzuoGuo** [comment]
Thanks for your feedback, in that case I'll give this another try later.

**Pull request closed without merging**
