### PR TITLE
Add awless, a mighty CLI for AWS

### PR DESCRIPTION
**Pull request by fxaguessy**
This pull request propose to add `awless` to `awesome-go`. It has a very good test coverage except for code that is generated (a main part of `awless` code) or code that is directly related to the connection with AWS. Godoc and coverage are not on our repo, as we do not build a library but rather a CLI tool.

- github.com repo: https://github.com/wallix/awless
- godoc.org: https://godoc.org/github.com/wallix/awless/template
- goreportcard.com: https://goreportcard.com/report/github.com/wallix/awless
- coverage service link: cover.run go

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [ ] I have added godoc link to the repo and to my pull request
- [ ] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for this repo, you're awesome! :+1:

### CODE REVIEW

**Comment by fxaguessy** [comment]
Most Go report card warning are in generated code and can not be easily fixed.

**Comment by appleboy** [comment]
awless/config/getters.go
awless/config/version.go

There are many none generated files. Please check again.

**Comment by cassiobotaro** [comment]
More than 8 days without answers. Feel free to send again following the quality standards.

**Comment by fxaguessy** [comment]
Sorry, I forgot that I needed to answer this topic.
You can keep it closed for now, as we won't fix most errors in the following days.

We are currently thinking to a major rewrite of our generated code that might fix most `go_vet` errors.

However, we will not comment the code, as comments are generally out of date after a few days and as we are building a tool and not a lib.  We try to write easily-understandable code, with good variable names, etc. to keep things easily understandable. But, as a result, `awless` will keep many `golint` warnings. If this is a major problem to add the link here we can't add it, which is a shame as it is a fastly growing project (3k stars in a few months).

Thanks for your time.

**Pull request closed without merging**
