### PR TITLE
Add go-finance package.

### PR DESCRIPTION
**Pull request by ackleymi**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

Please provide package links to:
github.com repo: https://github.com/FlashBoys/go-finance
godoc.org: https://godoc.org/github.com/FlashBoys/go-finance
goreportcard.com: https://goreportcard.com/report/github.com/Flashboys/go-finance
coverage service link (gocover, coveralls etc.): https://codecov.io/github/FlashBoys/go-finance?branch=master

Note, that new categories can be added only when there are 3 packages or more.

Make sure that you've checked the boxes below before you submit PR:
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link
- [x] I have added gocover.io link
- [x] I have added goreportcard link
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@ackleymi hi! please fill in the PR template. thanks!

**Comment by ackleymi** [comment]
@kirillDanshin I think I'm all set here. Good to merge?

**Comment by appleboy** [comment]
I don't see any link on this PR

```
Please provide package links to:

godoc.org:
goreportcard.com:
gocover.io:
```

Nothing.

**Comment by appleboy** [comment]
Please also fix goreport card errors: https://goreportcard.com/report/github.com/Flashboys/go-finance

**Comment by ackleymi** [comment]
@appleboy ah gotcha. Added the links, pushed a few fixes suggested by report card.

**Comment by appleboy** [comment]
@ackleymi Thanks for your contribution.

**Pull request merged**
