### PR TITLE
Add statsviz

### PR DESCRIPTION
**Pull request by arl**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: github.com/arl/statsviz
- pkg.go.dev: https://pkg.go.dev/github.com/arl/statsviz
- goreportcard.com: https://goreportcard.com/report/github.com/arl/statsviz
- coverage service link: there is no automated coverage, there are some tests but the Go code part is relatively tiny, most of the code is a single page application served by the Go package.

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: False

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by avelino** [comment]
We need to keep the minimum quality of the packages on the list, so we ask for tests

https://gocover.io/github.com/arl/statsviz

read more here: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md

**Comment by arl** [comment]
@avelino 

> We need to keep the minimum quality of the packages on the list, so we ask for tests

Totally agree with you.
statsviz does have a test suite though -> https://github.com/arl/statsviz/actions

What it doesn't have at the moment though are:
 -  automatic coverage service
 - README badge for github-actions test suite

Anyway, I'm working on adding both of these
:+1:

**Comment by arl** [comment]
@avelino 
I've just merged 2 pull-requests in the main branch:
 - automatic coverage reporting and coverage badge in README 
 - github action test workflow badge in README

Thank for the awesome list!  :D

**Review by avelino — CHANGES_REQUESTED** [review]
we are almost there
- exempla on README file
- https://codecov.io/gh/arl/statsviz >80%

congratulations on the improvements made

**Comment by arl** [comment]
@avelino  hey there
We should be there:
 - full coverage
 - example usage in the README

Thank you

**Pull request merged**
