### PR TITLE
Added golang transliterator

### PR DESCRIPTION
**Pull request by alexsergivan**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/alexsergivan/transliterator
- pkg.go.dev: https://pkg.go.dev/github.com/alexsergivan/transliterator
- goreportcard.com: https://goreportcard.com/report/github.com/alexsergivan/transliterator
- coverage service link: https://coveralls.io/github/alexsergivan/transliterator

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

**Comment by alexsergivan** [comment]
Hey @panjf2000, thanks for the review.
gofmt issues have been fixed. But it's not possible to fix misspell issues because it's complaining about ASCII codes table.

**Comment by panjf2000** [comment]
So you were saying that those misspells are on purpose?

**Comment by alexsergivan** [comment]
yes, because they are not words, it's just an ASCII representation of some Unicode symbols.
It's. I.e  "Ї" => 0x407 => "Yi",

As examplpe: 
`var x0d3 = []string{
	"tim",    // 0x00
	"tib",    // 0x01
	"tibs",   // 0x02
	"tis",    // 0x03
	"tiss",   // 0x04
	"ting",   // 0x05
	"tij",    // 0x06
	"tic",    // 0x07
	"tik",    // 0x08
	"tit",    // 0x09
	"tip",    // 0x0a
	"tih",    // 0x0b
	"pa",     // 0x0c
	"pag",    // 0x0d
	"pagg",   // 0x0e
	"pags",   // 0x0f
	"pan",    // 0x10
}`

**Pull request merged**
