### PR TITLE
add shoutrrr

### PR DESCRIPTION
**Pull request by simskij**
also add a `uncategorized` category to make it clearer that it's not a continuation of the `strings` category.

- [github.com repo](https://github.com/containrrr/shoutrrr)
- [pkg.go.dev](https://pkg.go.dev/github.com/containrrr/shoutrrr?tab=doc)
- [goreportcard.com](https://goreportcard.com/report/github.com/containrrr/shoutrrr)
- [coverage service link](https://codecov.io/github/containrrr/shoutrrr/)

- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

**Comment by simskij** [comment]
> Please fix
> https://goreportcard.com/report/github.com/containrrr/shoutrrr

Thank you. I will let you know once that's done.

**Comment by simskij** [comment]
@ceriath goerportcard now reports 100%.

**Comment by ceriath** [comment]
Also thanks for the "Uncategorized"

**Pull request merged**
