### PR TITLE
Add Falcon And Straf

### PR DESCRIPTION
**Pull request by SonicRoshan**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/SonicRoshan/falcon, https://github.com/SonicRoshan/straf
- godoc.org: https://godoc.org/github.com/SonicRoshan/falcon,  https://godoc.org/github.com/SonicRoshan/straf
- goreportcard.com: https://goreportcard.com/report/github.com/SonicRoshan/falcon, https://goreportcard.com/report/github.com/SonicRoshan/straf
- coverage service link https://gocover.io/github.com/SonicRoshan/falcon, https://gocover.io/github.com/SonicRoshan/straf

- I have added my package in alphabetical order.
- I have an appropriate description with correct grammar.
- I know that this package was not listed before.
- I have added godoc link to the repo and to my pull request.
- I have added coverage service link to the repo and to my pull request.
- I have added goreportcard link to the repo and to my pull request.
- I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@SonicRoshan please fix your comments format. Don't forget the space between `//` and the first letter of the line.

**Comment by SonicRoshan** [comment]
I will surely do that by today

**Comment by kirillDanshin** [comment]
@SonicRoshan thanks for a prompt reply. keep us updated.

**Comment by SonicRoshan** [comment]
I have updated both of my repositories with the new comments format

**Comment by SonicRoshan** [comment]
I have added spaces after // and the first letter of the comment

**Comment by SonicRoshan** [comment]
@kirillDanshin thanks for approving my libraries 👍

**Pull request merged**
