### PR TITLE
build(ci): fix first comment github action

### PR DESCRIPTION
**Pull request by paulburlumi**
This fixes the error seen creating a new pull request.

Fixes https://github.com/avelino/awesome-go/issues/4868

### CODE REVIEW

**Comment by paulburlumi** [comment]
These changes appear to work in a PR on my fork, see https://github.com/paulburlumi/awesome-go/pull/4

**Comment by paulburlumi** [comment]
I believe the failure is intentional for PRs triggered by public repository forks.
See https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#restrictions-on-repository-forks

**Comment by phanirithvij** [comment]
@paulburlumi the updated version should work as you've modified it to use the GITHUB_TOKEN, let's test it over your fork, I've sent a PR from my fork of yours.

**Comment by paulburlumi** [comment]
@phanirithvij ok. Submitting a PR to change the trigger that only runs when a PR is opened is painful.

I've updated my branch to use `pull_request_target` instead of `pull_request` as this seems to be exactly what is needed here.
See https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
From the article..
```
The reason to introduce the pull_request_target trigger was to enable workflows to label PRs (e.g. needs review) or to comment on the PR.
```
In order to trigger it I will close this PR and open a new PR. sigh.

**Pull request closed without merging**
