### PR TITLE
Add skipper http proxy

### PR DESCRIPTION
**Pull request by szuecs**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

* github.com repo: https://github.com/zalando/skipper
* pkg.go.dev: https://pkg.go.dev/github.com/zalando/skipper
* goreportcard.com: https://goreportcard.com/report/github.com/zalando/skipper
* coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://codecov.io/gh/zalando/skipper

Coverage is not yet >=80% but ~75%, I hope it's good enough.

**Make sure that you've checked the boxes below before you submit PR:**

* [x]  I have added my package in alphabetical order.
* [x]  I have an appropriate description with correct grammar.
* [x]  I know that this package was not listed before.
* [x]  I have added pkg.go.dev link to the repo and to my pull request.
* [x]  I have added coverage service link to the repo and to my pull request.
* [x]  I have added goreportcard link to the repo and to my pull request.
* [x]  I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
review:
- https://goreportcard.com/report/github.com/zalando/skipper#golint
- https://goreportcard.com/report/github.com/zalando/skipper#misspell
- > Tests, where practical. If the library/program is testable, then coverage should be >= 80% for non-data-related packages and >=90% for data related packages

**Comment by szuecs** [comment]
@avelino misspell: `An error occurred while running this test (exit status 3)`, whatever this means and golint would be only happy if we do breaking changes, which we won't like to do.

**Comment by avelino** [comment]
> @avelino misspell: `An error occurred while running this test (exit status 3)`, whatever this means and golint would be only happy if we do breaking changes, which we won't like to do. What value do we need to pass golint, maybe I can do some changes that help to achieve it?

About me it helps: lately I'm in an extremely short time, I can't look at awesome-go as I would like, for contribution with other projects I'm in less time, sorry :(

**Pull request closed without merging**
