### PR TITLE
Add thinkgo web framework

### PR DESCRIPTION
**Pull request by henrylee2cn**
Please check if what you want to add to awesome-go list meets quality standards before sending pull request. Thanks!

Please provide package links to:

github.com repo: https://github.com/henrylee2cn/thinkgo
godoc.org: https://godoc.org/github.com/henrylee2cn/thinkgo
goreportcard.com: https://goreportcard.com/report/github.com/henrylee2cn/thinkgo
coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/henrylee2cn/thinkgo
Note: that new categories can be added only when there are 3 packages or more.

Make sure that you've checked the boxes below before you submit PR:

I have added my package in alphabetical order
I know that this package was not listed before
I have added godoc link to the repo and to my pull request
I have added coverage service link to the repo and to my pull request
I have added goreportcard link to the repo and to my pull request
I have read Contribution guidelines and Quality standard.
Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by henrylee2cn** [comment]
@avelino  https://github.com/henrylee2cn/thinkgo

**Comment by appleboy** [comment]
@henrylee2cn Can you add the English version of readme or document?

**Comment by henrylee2cn** [comment]
@appleboy No problem, wait for the update in English documents, notify you

**Comment by appleboy** [comment]
@henrylee2cn Thanks. Although I can read chinse document, this is English conversation.

**Comment by henrylee2cn** [comment]
@appleboy Has been added in English documents, please review! Thanks.

**Comment by appleboy** [comment]
@henrylee2cn Please follows the Pull Request format.

https://github.com/avelino/awesome-go/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by henrylee2cn** [comment]
Please check if what you want to add to awesome-go list meets quality standards before sending pull request. Thanks!

Please provide package links to:

github.com repo: https://github.com/henrylee2cn/thinkgo
godoc.org: https://godoc.org/github.com/henrylee2cn/thinkgo
goreportcard.com: https://goreportcard.com/report/github.com/henrylee2cn/thinkgo
coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/henrylee2cn/thinkgo
Note: that new categories can be added only when there are 3 packages or more.

Make sure that you've checked the boxes below before you submit PR:

 I have added my package in alphabetical order
 I know that this package was not listed before
 I have added godoc link to the repo and to my pull request
 I have added coverage service link to the repo and to my pull request
 I have added goreportcard link to the repo and to my pull request
 I have read Contribution guidelines and Quality standard.
Thanks for your PR, you're awesome! :+1:

**Comment by henrylee2cn** [comment]
@appleboy Thanks for the guidance and review!

**Comment by appleboy** [comment]
@henrylee2cn You need to update the top of your comment.

**Pull request closed without merging**
