### PR TITLE
Add consul tool in Server Applications category

### PR DESCRIPTION
**Pull request by yanc0**

### CODE REVIEW

**Comment by therealbill** [comment]
+1 I'll vouch for it being awesome as well as stable and well documented.

**Comment by avelino** [comment]
@yanc0 update source pls

**Comment by yanc0** [comment]
@avelino I've set the link pointing to the dedicated/official website. Is that OK?

**Comment by yanc0** [comment]
Fail to merge, my fault, sorry. Recreating at #710

**Pull request closed without merging**
