### PR TITLE
Please include Caire - content aware image resize library

### PR DESCRIPTION
**Pull request by esimov**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/esimov/caire
- godoc.org: https://godoc.org/github.com/esimov/caire

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
cover.run go: https://cover.run/go/github.com/esimov/caire

**Comment by kamilsk** [comment]
I see incredibly cool package `github.com/esimov/caire` and the one from the "awesome" list like `https://github.com/thedevsaddam/retry` which has two commits and only 79 line of code with comments (and already has two alternatives in [the list](https://github.com/avelino/awesome-go#utilities))... Is there anything wrong with the selection criteria? I don't want to offend anyone, I was just wondering (and yes, I know about [Quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards)).

**Comment by esimov** [comment]
I think quality standards is not all about code coverage. It's not quite easy to make a code coverage in image processing over to 80%.

**Comment by RHao1996** [comment]
Masterofcards

**Pull request closed without merging**
