### PR TITLE
Adding Canopus, a CoAP Library for Go

### PR DESCRIPTION
**Pull request by zubairhamed**
Adding Canopus, a CoAP Library for Go

### CODE REVIEW

**Comment by shurcooL** [comment]
It doesn't really have docs, but it implements a known standard (the only Go package on this list for RFC 7252), so I think we can let that pass. But docs would be a good addition.

LGTM.

**Comment by zubairhamed** [comment]
I'll increase code documentation after i've increased code coverage for the library

**Comment by shurcooL** [comment]
Sounds good.

**Comment by zubairhamed** [comment]
Sorry, cocked up my fork. i'll resubmit this pull request

**Pull request closed without merging**
