### PR TITLE
Added 'templify' and 'feiertage'

### PR DESCRIPTION
**Pull request by wlbr**
### feiertage:

https://godoc.org/github.com/wlbr/feiertage
https://goreportcard.com/report/github.com/wlbr/feiertage
### templify:

https://godoc.org/github.com/wlbr/templify
https://goreportcard.com/report/github.com/wlbr/templify

gocover.io is not working currently.

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@wlbr please document your code, setup any coverage service and send us a link. thanks.

**Comment by wlbr** [comment]
## feiertage:
Src: https://godoc.org/github.com/wlbr/feiertage
Reportcard: https://goreportcard.com/report/github.com/wlbr/feiertage
Coverage: https://coveralls.io/github/wlbr/feiertage?branch=master
Doc: https://godoc.org/github.com/wlbr/feiertage


## templify:
Src: https://godoc.org/github.com/wlbr/templify
Reportcard: https://goreportcard.com/report/github.com/wlbr/templify
Coverage: https://coveralls.io/github/wlbr/templify?branch=master
Doc: https://godoc.org/github.com/wlbr/templify

templify is rather simple and basicaly just a one-file command, so the test is really simple.


That took a while to find the time, sorry.

**Comment by avelino** [comment]
templify has 8% coverage, you can improve

**Comment by wlbr** [comment]
yes, I know.

Templify is a simple but handy command line tool (or go generate too as stringer). It's all just flagging and a main function. The parts that are a little bit more complicated are tested, the rest is trivial. Tests would be more complicated than the code itself, for example to test the correct use of the flags package.

I would suggest not insist on the coverage percentage, as that indicator does not really work on really small programs. They are so small, that the boilerplate code is a major part of them, so that the coverage is leading in the wrong direction.

**Comment by wlbr** [comment]
Please add at least 'Feiertage', see above. Coverage is high and everything else is fine.


Templifies untested code is the main()-function and commandline flagging processing - there are no really useful ways to test automatically that within the reach of coveralls. 

I see that you disagree after carefully looking into the coveralls report. So just drop templify, but please add feiertage.

**Comment by avelino** [comment]
@wlbr If you judge to be a wrong direction put test coverage, could get help `awesome-go` with idea and read `Contribution Guidelines`

**Comment by wlbr** [comment]
Hi, I didn't judge anything. I just asked to add 'feiertage' and to drop 'templify'.
Thanks.

**Comment by wlbr** [comment]
Guys, can we have any progress on this?

first - please add 'Feiertage'. Everything metric is fine there.

secondly - either drop or add 'Templify'. Its test coverage is low, but this is reasonably low. AND a number of already existing projects on the list don't have any test or a automatic build or a test coverage tool (see github.com/rakyll/statik). So i think 'Templify' would be an improvement and I don't see a reason not to include it. But if you wish to do so - it is your project, just go for it. But please go and move on.

Thanks.

**Comment by wlbr** [comment]
Hi Guys, another quarter of a year is gone. Is it possible to go ahead with this pull request?

**Comment by kirillDanshin** [comment]
sorry for long reply.

**Comment by wlbr** [comment]
Thanks a lot for the response!!

**Pull request merged**
