### PR TITLE
Added g3n - Go 3D Game Engine!

### PR DESCRIPTION
**Pull request by danaugrs**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/g3n/engine
- godoc.org: https://godoc.org/github.com/g3n/engine
- goreportcard.com: https://goreportcard.com/report/github.com/g3n/engine
- coverage service: Can't automate visual testing! We've developed a comprehensive test program - [g3nd](https://github.com/g3n/engine) - which is updated when changes to the engine are made. It tests all features of the engine. It's prominently linked in the main repo)

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request. (**Can't automate visual testing!**)
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

For reference, [Azul3D](https://github.com/azul3d/engine) is in the list and its goreportcard score is a [D](https://goreportcard.com/report/github.com/azul3d/engine) while g3n's is an [A+](https://goreportcard.com/report/github.com/g3n/engine).

### CODE REVIEW

**Comment by fanus** [comment]
> For reference, Azul3D is in the list and its goreportcard score is a D while g3n's is an A+.

Man has a point...

**Comment by danaugrs** [comment]
I've just committed significant improvements - please review our [goreportcard](https://goreportcard.com/report/github.com/g3n/engine) again.

**Comment by justinclift** [comment]
Excellent.  Thanks @avelino. :smile:

**Comment by danaugrs** [comment]
Thanks!

**Pull request merged**
