### PR TITLE
[WIP] add go.uik link

### PR DESCRIPTION
**Pull request by kirillDanshin**
### Disclaimer

```
This pull request is created to speed up my work.
Also, maybe someone will help me with something from TODO list below.

Please, don't close it.
Thank you.
```
### TODO:
- [ ] Documentation
- [ ] 95%+ golint score
- [x] 100% gofmt score
- [x] 100% govet score
- [ ] 95%+ gocyclo score
- [x] Choose the license
- [ ] Write tests
- [ ] Configure CI
### Template data

Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

Please provide package links to:
- godoc.org:
  - https://godoc.org/github.com/kirillDanshin/go.uik
  - [GoDoc](https://godoc.org/github.com/kirillDanshin/go.uik)
- goreportcard.com:
  - https://goreportcard.com/report/github.com/kirillDanshin/go.uik
  - [Go Report Card](https://goreportcard.com/report/github.com/kirillDanshin/go.uik)
- gocover.io:
  - https://gocover.io/github.com/kirillDanshin/go.uik
  - [coverage](https://gocover.io/github.com/kirillDanshin/go.uik)

### CODE REVIEW

**Comment by kirillDanshin** [comment]
Note: test failed because of travis-ci issue.

**Comment by kirillDanshin** [comment]
**Note**: goreportcard is now  **A+** instead of **D**.

For now, I don't know how to test it without getting [this issue](/kirilldanshin/go.uik/issues/2) solved.
Now the lib doesn't have a single state, the state is everywhere and everything may be a state.

So, after solving score issues, I want to write the docs, clone this to another branch and rewrite the whole core. Then I'll need to rewrite the docs again, but for new API.

And when I get it done, API will be frozen, and I will be able to write the tests: I'll be able to call some function, wait some time and check the state, and if the state is modified as expected, the test passed. Maybe then I'll find a method to test how the state is rendered.

**Comment by matrixik** [comment]
Thank you for reviving this library.

**Comment by kirillDanshin** [comment]
@matrixik glad to hear it :) let's see what happens.

**Comment by kirillDanshin** [comment]
Working on go.uik backend - go.wde.
Forked in mirrored repo [here](https://github.com/kirillDanshin/go-wde).

**Pull request closed without merging**
