### PR TITLE
Add go-up library

### PR DESCRIPTION
**Pull request by ufoscout**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/ufoscout/go-up
- godoc.org: https://godoc.org/github.com/ufoscout/go-up
- goreportcard.com: https://goreportcard.com/report/github.com/ufoscout/go-up
- coverage service link: https://codecov.io/gh/ufoscout/go-up

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by ufoscout** [comment]
@jtemporal actually golint wants me to change the package name from "go_up" to "goup" but I do really want to keep it separated, any advice?

**Comment by jtemporal** [comment]
> any advice?

Not really, since [naming conventions](https://golang.org/doc/effective_go.html#package-names) state that 
> packages are given lower case, single-word names; there should be no need for underscores or mixedCaps.

I would not go with the name you choose. And `go lint` will give out an warning either if you have `_` or mixedCaps in the package name ¯\_(ツ)_/¯

**Comment by ufoscout** [comment]
All issues fixed.

**Comment by appleboy** [comment]
wait for @jtemporal approval.

**Pull request merged**
