### PR TITLE
Reorganizing text processors

### PR DESCRIPTION
**Pull request by spekary**
This is a reorganization of the Text Processing category into sub-categories to make it easier to peruse.

Also removed the "inject" package since the author officially archived the project and is no longer supporting it. All other packages remain.

I reviewed all of the packages in this category, and while most don't fit current quality standards, most of them are simply mature projects with 1 or 2 open issues, and are still quite useful.

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: False
- coverage: False

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by spekary** [comment]
Oops. Hold up. I see there is a whole natural language category now. I will merge those in there.

Also, I see that some categories are using html headers rather than outlining for sub categories. I think that looks better so I am going to change to that.

**Comment by spekary** [comment]
OK, should be good now. I reorganized the Natural Lanugage section too.

I removed https://github.com/nuance/go-nlp since it is officially archived and abandoned by the author.

**Comment by spekary** [comment]
@avelino What do you think about this? Personally, I think giving better granularity by using subcategories makes the list more useful. I would like to continue going through each category looking for abandoned projects, but while I am there, if I can offer better organization, I would like to do that too. I don't want to proceed until I know whether this is acceptable.

**Review by avelino — APPROVED** [review]
LGTM, I like your proposal

> sorry for the delay in reviewing the contribution

**Pull request merged**
