### PR TITLE
Add ebook 'The Power of Go: Tools'

### PR DESCRIPTION
**Pull request by bitfield**
Thanks for `awesome-go`; may this PR increase its awesomeness, by just a little.

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: False
- coverage: False

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by bitfield** [comment]
Here is some recent activity to stop the bot automatically marking the PR as closed!

**Comment by bitfield** [comment]
Still not stale.

**Review by avelino — CHANGES_REQUESTED** [review]
There is no point in this book getting on the list, it is a paid book
If we accept this contribution we would have to list all the books of go

ref: https://github.com/avelino/awesome-go/pull/3701#pullrequestreview-745617902

**Comment by bitfield** [comment]
> we would have to list all the books of go

Sorry, I thought that was the point! I didn't see anywhere that your list only covers free books.

If that's the case, then I've opened #3952 to remove the existing non-free books from the list.

**Pull request closed without merging**
