### PR TITLE
Add sqlc in "SQL Query Builder" section

### PR DESCRIPTION
**Pull request by raflimr**
> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc):
   [https://github.com/kyleconroy/sqlc](https://github.com/kyleconroy/sqlc)

- pkg.go.dev:
   [https://pkg.go.dev/github.com/kyleconroy/sqlc](https://pkg.go.dev/github.com/kyleconroy/sqlc)

- goreportcard.com:
   [https://goreportcard.com/report/github.com/kyleconroy/sqlc](https://goreportcard.com/report/github.com/kyleconroy/sqlc)

- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.):
   [https://github.com/kyleconroy/sqlc/actions/workflows/ci.yml](https://github.com/kyleconroy/sqlc/actions/workflows/ci.yml)

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below before you submit PR:**
_not every repository (project) will fit into every option, but most projects should_

- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by phanirithvij** [comment]
@raflimr not in alphabetical order.
@avelino can we make an exception and allow golint issues for this, as the majority of them are in `internal/`?

**Comment by raflimr** [comment]
> @raflimr not in alphabetical order. @avelino can we make an exception and allow golint issues for this, as the majority of them are in `internal/`? Also, code coverage is not being considered by the project but has a large number of tests.

Fixed, thank you.

**Review by avelino — CHANGES_REQUESTED** [review]
review:
- golint https://goreportcard.com/report/github.com/kyleconroy/sqlc#golint
- misspell https://goreportcard.com/report/github.com/kyleconroy/sqlc#misspell

you need to look calmly at the two items above, it is low coverage

**Comment by frederikhors** [comment]
Please do not close this PR. sqlc is amazing.

**Comment by frederikhors** [comment]
@avelino.

**Comment by avelino** [comment]
> Please do not close this PR. sqlc is amazing, @avelino.

@frederikhors closing is an automatic process, if your contribution (PR) is closed, feel free to open it again once you have corrected it

**Comment by frederikhors** [comment]
This is not a contribution of mine. Anyway what is the problem with this PR?

**Comment by avelino** [comment]
> review:
> 
>     * golint https://goreportcard.com/report/github.com/kyleconroy/sqlc#golint
> 
>     * misspell https://goreportcard.com/report/github.com/kyleconroy/sqlc#misspell
> 
> 
> you need to look calmly at the two items above, it is low coverage

added comment above

**Comment by frederikhors** [comment]
@kyleconroy for a wonderful project like `sqlc` it is important to be here too. Can we correct these two points?

**Comment by phanirithvij** [comment]
It is non-trivial to fix that many lint issues.

I think we can make an exception for sqlc, as its code coverage is good.
- Check coverage [here](https://app.codecov.io/gh/phanirithvij/sqlc), I enabled coverage in my [fork](https://github.com/phanirithvij/sqlc/commit/9abe680c58c53416f85c4c1071f4bfa2be446635) to test it.
- I'm not sure how to add code coverage for kotlin tests. so I left it out.

**Comment by spekary** [comment]
We either need to change our quality standards or enforce them. Yes, its not trivial to meet them. It takes great effort. That is what sets this list apart. 

Most of the lint errors are due to incorrect or missing comments on exported code inside the "internal" directory. Since this code is not meant to be shared with the world, and the linters do not complain about private methods not being documented, I think this should be acceptable.

We should modify the quality standards to mention that we will not worry about these doc issues for internal code.

However, I would like to see a code coverage link in the README file. That really helps us monitor ongoing quality in a continuously updated project.

**Comment by avelino** [comment]
> We should modify the quality standards to mention that we will not worry about these doc issues for internal code.

@spekary I agree, we can update our contribution guide with this annotation about `internals` packages

**Comment by spekary** [comment]
I think the only thing left to do on this is to put a code coverage link in the repo documentation somewhere. The code coverage link submitted originally was simply a link showing that CI tests are running. See the comment above from @phanirithvij about the link he created on a separate branch. Perhaps you can merge that in and mention it in your README file.

The misspell error looks like a problem with goreportcard itself. Probably due to the inclusion of other languages in the repo. Not much the author can do about that.

**Pull request merged**
