### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by danceyoung**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo:https://github.com/danceyoung/goslayer

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [ 1] I have added my package in alphabetical order.
- [ 1] I have an appropriate description with correct grammar.
- [ 1] I know that this package was not listed before.
- [ 1] I have added pkg.go.dev link to the repo and to my pull request.
- [ 1] I have added coverage service link to the repo and to my pull request.
- [ 1] I have added goreportcard link to the repo and to my pull request.
- [ 1] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: False
- coverage: False

**Comment by danceyoung** [comment]
@avelino 
GoSLayer is a tool that helps you to create a golang project in seconds.

- layered base on a standard architecture layout (for chinese)
- followed by Package-Oriented-Design guideline
- creating a runnable Rest ful Web Service

The tool is not a package, just a tool

**Comment by avelino** [comment]
> @avelino
> GoSLayer is a tool that helps you to create a golang project in seconds.
> 
> * layered base on a standard architecture layout (for chinese)
> * followed by Package-Oriented-Design guideline
> * creating a runnable Rest ful Web Service
> 
> The tool is not a package, just a tool

if your project is a skeleton (architectural proposal) it should fall into this category:
https://github.com/avelino/awesome-go#project-layout

even though it's skeleton doesn't prevent us from having tests, I see an example of this project [scaffold](https://github.com/catchplay/scaffold#scaffold)

I recommend reading: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines

**Comment by danceyoung** [comment]
> > @avelino
> > GoSLayer is a tool that helps you to create a golang project in seconds.
> > 
> > * layered base on a standard architecture layout (for chinese)
> > * followed by Package-Oriented-Design guideline
> > * creating a runnable Rest ful Web Service
> > 
> > The tool is not a package, just a tool
> 
> if your project is a skeleton (architectural proposal) it should fall into this category:
> https://github.com/avelino/awesome-go#project-layout
> 
> even though it's skeleton doesn't prevent us from having tests, I see an example of this project [scaffold](https://github.com/catchplay/scaffold#scaffold)
> 
> I recommend reading: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines

ok

**Pull request closed without merging**
