### PR TITLE
Created new Dynamic DNS category, added existing projects and new pro…

### PR DESCRIPTION
**Pull request by alcastle**
**Please provide package links to:**

- github.com repo: https://gitlab.com/alcastle/dyndns
- godoc: https://godoc.org/gitlab.com/alcastle/dyndns
- goreportcard.com: https://goreportcard.com/report/gitlab.com/alcastle/dyndns
- gocoverage: https://gocover.io/gitlab.com/alcastle/dyndns

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines]

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: False
- goreportcard.com: True
- coverage: False

**Comment by alcastle** [comment]
Edited with the missing go doc and coverage links.

**Comment by panjf2000** [comment]
I am not sure whether we should add gitlab repo into awesome-go so I'm going to let @avelino decide this PR.

**Comment by alcastle** [comment]
There's approximately 161 project links that are not Github.com listed on awesome-go. Including GitLab, BitBucket, and self-hosted source control repository. 

Additionally, the Contribution Guidelines state 
> At least 3 items are needed to create a new category.

Which has been satisfied.

**Pull request merged**
