### PR TITLE
Add terraform-provider-openapi

### PR DESCRIPTION
**Pull request by dikhan**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/dikhan/terraform-provider-openapi
- godoc.org: https://godoc.org/github.com/dikhan/terraform-provider-openapi
- goreportcard.com: https://goreportcard.com/report/github.com/dikhan/terraform-provider-openapi
- coverage service link ([gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.): https://codecov.io/gh/dikhan/terraform-provider-openapi/

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: True
- goreportcard.com: True
- coverage: True

**Comment by dikhan** [comment]
Done :) fixed all the easily fixable problems. remaining issues about golint and gofmt are related to autogenerated code which is used for examples purposes only.

**Comment by ceriath** [comment]
ineffassign still has two errors.

https://github.com/dikhan/terraform-provider-openapi/blob/b7e7c52139120031db879ddd0a750046df2bffaa/openapi/data_source_factory.go#L48

I think ``err`` should be returned here 

https://github.com/dikhan/terraform-provider-openapi/blob/b7e7c52139120031db879ddd0a750046df2bffaa/openapi/openapi_spec_resource_schema_definition.go#L57

this assignment does not make any sense

**Comment by dikhan** [comment]
Thanks @ceriath , pushed fixes for those.

**Pull request merged**
