### PR TITLE
Add go-mode into Editor Plugins

### PR DESCRIPTION
**Pull request by grafov**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo: https://github.com/dominikh/go-mode.el 
- godoc.org: 
- goreportcard.com: 
- coverage service link (gocover, coveralls etc.): 

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [ ] I have added godoc link to the repo and to my pull request
- [ ] I have added coverage service link to the repo and to my pull request
- [ ] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@felipeweb you are kidding us, right?

**Comment by felipeweb** [comment]
@kirillDanshin I have not seen the repository yet, because it is missing link, but now i see it is not Go sorry

**Comment by grafov** [comment]
Probably contributing rules should be corrected for reflecting cases for non-go projects that still awesome for go :)

**Comment by kirillDanshin** [comment]
@grafov our rules defines only rules for go projects, so it was just @felipeweb mistake. sorry. merged.

**Comment by grafov** [comment]
No problems, thank you.

**Pull request merged**
