### PR TITLE
Add testfixtures

### PR DESCRIPTION
**Pull request by andreynering**
- Source: https://github.com/go-testfixtures/testfixtures
- godoc.org: https://godoc.org/github.com/go-testfixtures/testfixtures
- goreportcard.com: https://goreportcard.com/report/github.com/go-testfixtures/testfixtures

### CODE REVIEW

**Comment by kirillDanshin** [comment]
> tl;dr: List items should be sorted alphabetically.

Please, read [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md).

**Comment by andreynering** [comment]
Fixed.

**Comment by matrixik** [comment]
Thank you for contributing. Nice package.

Personally I would give bigger warning in README that it will wipe database so everyone should remember to use test db (random thought: maybe you can check if `dbname` contain word `test`?).

**Comment by andreynering** [comment]
Yeah, thats important. I added a bigger warning. :smile: 

Thanks!

**Pull request merged**
