### PR TITLE
added banjo to web frameworks list

### PR DESCRIPTION
**Pull request by gdwrd**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/nsheremet/banjo
- godoc.org: https://godoc.org/github.com/nsheremet/banjo
- goreportcard.com: https://goreportcard.com/report/github.com/nsheremet/banjo
- coverage service link [Coverage Status](http://codecov.io/github/nsheremet/banjo?branch=master)

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by kirillDanshin** [comment]
hi

please log errors or return them ([example](https://github.com/nsheremet/banjo/blob/master/context.go#L33))

**Comment by nsheremet** [comment]
@kirillDanshin updated.

**Review by avelino — APPROVED** [review]
You can improve:
- gofmt: 90%
- test cover: 86%

**Review by cassiobotaro — CHANGES_REQUESTED** [review]
please fix name description(upper and lower case), also take a look: https://goreportcard.com/report/github.com/nsheremet/banjo#gofmt

**Comment by nsheremet** [comment]
Thank you guys. 
@avelino I will improve that soon.
@cassiobotaro are you talking about name? `BANjO/Banjo/banjo`. 
And with `goreportcard` it's strange because I run `gofmt` to all files and nothing is changed.

**Comment by cassiobotaro** [comment]
@nsheremet try `gofmt -s`

**Review by cassiobotaro — APPROVED** [review]

**Pull request merged**
