### PR TITLE
Add revive as suggestion

### PR DESCRIPTION
**Pull request by RoestVrijStaal**
Because tl;dr (the devs of) golang/lint suck: https://github.com/golang/lint/issues/186#issuecomment-171163152

Yes, I've rewritten the description of the revive project to one sentence. Also "fast" & "beautiful" is relative to the ~~moment~~ situation they're stated. They could be invalid in the future.

Any suggestions to get this PR though are very welcome~

Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:** 

- github.com repo: https://github.com/mgechev/revive
- godoc.org: https://godoc.org/github.com/mgechev/revive 
- goreportcard.com: https://goreportcard.com/report/github.com/mgechev/revive
- coverage service link: https://travis-ci.org/mgechev/revive

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.
Well, since this PR makes there are 3 linters in this list, it IS an idea to do so....

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x ] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: True
- goreportcard.com: True
- coverage: False

**Comment by RoestVrijStaal** [comment]
Unfortunately I'm only an user of the tool who found it awesome. ...And not the owner of the repository. What should I do now? /0\

**Comment by ceriath** [comment]
You could still do the changes and open a pull request on their project, if you want to help to improve "revive"

**Comment by ceriath** [comment]
Closing this due to inactivity. Please feel free to reopen.

**Pull request closed without merging**
