### PR TITLE
adding mockingjay

### PR DESCRIPTION
**Pull request by quii**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

Please provide package links to:
- godoc.org: https://godoc.org/github.com/quii/mockingjay-server
- goreportcard.com: https://goreportcard.com/report/github.com/quii/mockingjay-server
- gocover.io: https://gocover.io/github.com/quii/mockingjay-server

Note, that new categories can be added only when there are 3 packages or more.

Make sure that you've checked the boxes below before you submit PR:
- [ ] I have added my package in alphabetical order
- [ ] I know that this package was not listed before
- [ ] I have added godoc link
- [ ] I have added gocover.io link
- [ ] I have added goreportcard link
- [ ] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome :+1:

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@quii looks pretty good and useful. please, fix `go vet` errors and I'll merge it. thanks!

**Comment by quii** [comment]
Hi @kirillDanshin thanks for the kind words and the motivation to finally look into that warning, it's fixed now :)

**Comment by quii** [comment]
Hey @kirillDanshin any chance of a merge? :)

**Comment by kirillDanshin** [comment]
@quii yep, sorry for taking so much time. merging. also, it will be great if you add some more tests. thanks for your contribution, you're awesome :wink:

**Pull request merged**
