### PR TITLE
Added hprose-golang

### PR DESCRIPTION
**Pull request by andot**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo:  http://github.com/hprose/hprose-golang
- godoc.org: https://godoc.org/github.com/hprose/hprose-golang
- goreportcard.com: https://goreportcard.com/report/github.com/hprose/hprose-golang
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/hprose/hprose-golang?branch=master

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by kirillDanshin** [comment]
hi @andot.
I see that your package is panic instead of handling or returning errors. please don't panic.

**Comment by andot** [comment]
@kirillDanshin Thank you for your suggestion, but I don't think panic is entirely evil. it's circumstance, sometimes panic is better than return error.

**Comment by kirillDanshin** [comment]
@andot 
*[Yep](https://github.com/hprose/hprose-golang/blob/23383929f6b2a94142975eb1ccd4ea5a593d4e09/io/bool_decoder.go#L57). [Determined by the user](https://github.com/hprose/hprose-golang/blob/23383929f6b2a94142975eb1ccd4ea5a593d4e09/io/bool_decoder.go#L75). [No](https://github.com/hprose/hprose-golang/blob/404cf3e96c02ab0e3845a8bf3e04c3d166422067/rpc/unix_client.go#L54) [forcing](https://github.com/hprose/hprose-golang/blob/404cf3e96c02ab0e3845a8bf3e04c3d166422067/rpc/unix_client.go#L56), [n](https://github.com/hprose/hprose-golang/blob/0cae1493e90f975d959683f7d0ca51d19486e397/rpc/client.go#L120)[e](https://github.com/hprose/hprose-golang/blob/404cf3e96c02ab0e3845a8bf3e04c3d166422067/rpc/unix_client.go#L58)[v](https://github.com/hprose/hprose-golang/blob/404cf3e96c02ab0e3845a8bf3e04c3d166422067/rpc/unix_client.go#L60)[e](https://github.com/hprose/hprose-golang/blob/404cf3e96c02ab0e3845a8bf3e04c3d166422067/rpc/unix_client.go#L63)[r](https://github.com/hprose/hprose-golang/blob/0cae1493e90f975d959683f7d0ca51d19486e397/rpc/client.go#L112). [At](https://github.com/hprose/hprose-golang/blob/230c177fb93e096fa0687f1d00f00711652eda87/rpc/unix_server.go#L50) [all](https://github.com/hprose/hprose-golang/blob/c2a9e97d33ebd33d48dc4804ccf526b6d139eb59/rpc/http_service.go#L137). [Really](https://github.com/hprose/hprose-golang/blob/77d94cab376fb90c035ec81e67e7cc8cd6621bd1/rpc/handler.go#L91).*

Just joking ;)

You give _no_ ability to handle error or just panic to user. In my previous message I mean to remove panics at all or give the user more control over error handling/panics. Also errors can have stack trace too.

**Comment by andot** [comment]
```go
type Stub struct {
	Hello1      func(string) (string, error)  `name:"hello"`
	Hello2      func(string) (string)  `name:"hello"`
}

func main() {
	client := rpc.NewHTTPClient("http://127.0.0.1:8080/")
	var stub *Stub
	client.UseService(&stub)
	fmt.Println(stub.Hello1("world"))
	fmt.Println(stub.Hello2("world"))
}
```

if you use `Hello1` to call remote method `hello`, when an error occured, the error will be returned as the result.

if you use `Hello2` to call remote method `hello`, when an error occured, it will panic.

**Comment by kirillDanshin** [comment]
@andot seriously? you really think it's useful?

**Comment by andot** [comment]
@kirillDanshin 

It is just an example to show what hprose-golang can do. In real case, the users will not define the same remote method in both of those forms. but the users can choose one form they need in their programs. so I think it's really useful.

**Comment by on99** [comment]
hprose-golang is a serialization library similar to `encoding/json`. Built on top of the serialization, it provides dynamic RPC which is also similar to `jsonrpc`.

I would say `panic` in serialization process is acceptable because it shouldn't be wrong and `json` also panics.

The example @andot provides above indicates that hprose-golang is flexible and smart enough to know when to panic or return an error based on how users use it which is also well-documented.

**Pull request closed without merging**
