### PR TITLE
Removal of mdns (not maintained anymore) and addition of zeroconf

### PR DESCRIPTION
**Pull request by gromain**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/aelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/grandcat/zeroconf
- godoc.org: https://godoc.org/github.com/grandcat/zeroconf
- goreportcard.com: https://goreportcard.com/report/github.com/grandcat/zeroconf
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `cover.run go`: no code tests (just like the previous library had none)

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [X] I have added my package in alphabetical order.
- [X] I have an appropriate description with correct grammar.
- [X] I know that this package was not listed before.
- [X] I have added godoc link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request.
- [X] I have added goreportcard link to the repo and to my pull request.
- [X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by cassiobotaro** [comment]
@gromain ptal

**Comment by cassiobotaro** [comment]
https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers

**Comment by gromain** [comment]
@cassiobotaro I'm not sure what was needed here?

**Comment by cassiobotaro** [comment]
@gromain zeroconf don't have test's. As I requested changes 12 days ago without response, the issue was closed. But feel free to submit again, but firstly write tests.

**Pull request closed without merging**
