### PR TITLE
Added StatusOk Software to DevOps Tools

### PR DESCRIPTION
**Pull request by sanathp**

### CODE REVIEW

**Comment by sanathp** [comment]
Ping !!!

**Comment by kirillDanshin** [comment]
@sanathp please rebase your PR
thanks

**Comment by cassiobotaro** [comment]
@sanathp Pls update your PR following this [guide](https://github.com/avelino/awesome-go/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

**Comment by kamilsk** [comment]
@cassiobotaro, I think it can be closed (fixed here https://github.com/avelino/awesome-go/commit/74f0101d2a4f78dd7e376d96b58993e642a833f9)

**Pull request closed without merging**
