### PR TITLE
remove low quality repo

### PR DESCRIPTION
**Pull request by yinggaozhen**
|  repo | update  |reason  |
|  ----  | ----  | ----  |
| https://github.com/jimrobinson/kvbench | 2014-04-20 | TODO |
| https://github.com/diankong/GoDocTooltip | 2016-01-30 | TODO |
| https://github.com/codemodus/catena | 2018-08-26 | TODO |
| https://github.com/beyang/hgo | 2015-08-25 | TODO |
| https://github.com/poorny/translate | 2016-02-28 | TODO |
| https://github.com/dietsche/textbelt | 2015-09-04 | TODO |
| https://github.com/Omie/rrdaclient | 2014-09-20 | TODO |
| https://github.com/chonthu/go-google-analytics | 2015-06-09 | TODO |
| https://github.com/Aorioli/gcm | 2015-12-04 | TODO |
| https://github.com/zach-klippenstein/goregen | 2016-03-04 | TODO |
| https://github.com/endeveit/enca | 2016-03-15 | TODO |
| https://github.com/hscells/doi | 2017-08-21 | TODO |
| https://github.com/tv42/mockhttp | 2014-10-30 | TODO |
| https://github.com/rdrdr/hamcrest | 2011-02-15 | TODO |
| https://github.com/ThePaw/go-gt | 2015-09-14 | TODO |
| https://github.com/aybabtme/portproxy | 2014-12-13 | TODO |
| https://github.com/a2800276/porter | 2013-10-03 | TODO |
| https://github.com/rookii/paicehusk | 2013-12-16 | TODO |
| https://github.com/goodsign/libtextcat | 2012-12-28 | TODO |
| https://github.com/rjohnsondev/golibstemmer | 2014-06-18 | TODO |
| https://github.com/zhulik/go_mediainfo | 2015-12-25 | TODO |
| https://github.com/mengzhuo/cookiestxt | 2017-10-09 | TODO |
| https://github.com/TreyBastian/colourize | 2016-05-10 | TODO |
| https://github.com/ian-kent/envconf | 2014-10-26 | TODO |
| https://github.com/ian-kent/purl | 2014-12-08 | TODO |
| https://github.com/robfig/bind | 2014-08-17 | TODO |
| https://github.com/GlenKelley/go-collada | 2013-09-27 | TODO |
| https://github.com/jyotiska/go-webcolors | 2015-08-21 | TODO |
| https://github.com/ftrvxmtrx/tga | 2015-05-24 | TODO |
| https://github.com/sanbornm/mp | 2016-05-12 | TODO |
| https://github.com/alexcesaro/log | 2015-09-16 | TODO |
| https://github.com/e-dard/godist | 2015-05-11 | TODO |
| https://github.com/ThePaw/probab | 2015-09-14 | TODO |
| https://github.com/ian-kent/goose | 2014-12-21 | TODO |
| https://github.com/go-xkg/xkg | 2015-01-08 | TODO |

### CODE REVIEW

**Comment by uded** [comment]
As I do not agree with stars rating being the only measurement of quality, it would be awesome if on awesome-go.com that information (to be specific: stars and last update) could be included. I am avoiding repositories that have 2-3 years since the last update, and the number of stars is an excellent way to determine at which libraries in the given category I am going to look at first...

I am certain this information would be easy to add while generating the website itself. Happy to do it myself if no one will opt-in.

**Comment by ceriath** [comment]
@uded you might want to have a look into #1931

**Comment by uded** [comment]
@ceriath thanks for the info, I missed that one

**Comment by kirillDanshin** [comment]
@ceriath I'd ignore the github stars column and look into last update date while reviewing each library from that list, actually

**Comment by ceriath** [comment]
@kirillDanshin I'd agree on that, i was just wondering if @yinggaozhen had any other criteria.
Just keep in mind, just because there are no updates, it doesn't necessarily mean it's bad, since it could be stable

**Comment by yinggaozhen** [comment]
@ceriath @kirillDanshin @uded 

I was carried out in accordance with the star, and update the time for a preliminary screening, because the two measures can help me to screen out most of the does not accord with a standard feature of the repo is not necessarily do not accord with) (of course, the final screen is about 180 repo, I am each to check one by one, finally selected 35 I personally think that don't conform to the standard of warehouse, I am in document is complete, the maintenance, if there is a better substitute, etc., star is just a screening, and is definitely not the deciding factor.

However, it is only my personal standard after all. If some repo are in line with the standard but deleted, please inform me, and I will restore ~

**Comment by yinggaozhen** [comment]
@kirillDanshin Please give me some time, I will add the reason for deletion

**Comment by yinggaozhen** [comment]
@ceriath @kirillDanshin 
I opened a new PR and added the reason for deletion, I hope you can help review it again. 
**New Pull Request** : [https://github.com/avelino/awesome-go/pull/2734](https://github.com/avelino/awesome-go/pull/2734)

**Pull request closed without merging**
