### PR TITLE
Add id3v2

### PR DESCRIPTION
**Pull request by bogem**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo: https://github.com/bogem/id3v2
- godoc.org: https://godoc.org/github.com/bogem/id3v2
- goreportcard.com: https://goreportcard.com/report/github.com/bogem/id3v2
- coverage service link (gocover, coveralls etc.): 

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [ ] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by shurcooL** [comment]
This is great, it's the first ID3v2 parsing library we have. Thank you!

LGTM.

Btw, you have a few minor golint issues, fixing them is an opportunity to make your library better. See https://goreportcard.com/report/github.com/bogem/id3v2#golint.

**Comment by bogem** [comment]
It can't parse id3v2 tags yet. In future releases it will.
Now it can only write tags in music file.

Ok, I will fix them today :)

**Comment by shurcooL** [comment]
> It can't parse id3v2 tags yet. In future releases it will.
> Now it can only write tags in music file.

Yep, I saw that. It's still better than not being able to read or write them, which was the case before. ;)

**Comment by bogem** [comment]
There are some libraries for go, which can read tags ([this](https://github.com/wtolson/go-taglib), [this](https://github.com/ascherkus/go-id3) and [this](https://github.com/mikkyang/id3-go)), but can't stably write them. That's why I wrote it 😊

**Comment by shurcooL** [comment]
Good to know. They're not on this list though, sadly. Actually, go-taglib is (under the name "taglib"), but I didn't find it because I searched for "ID3" specifically.

**Pull request merged**
