### PR TITLE
feat: add gophers artwork and learning go by example tutorial

### PR DESCRIPTION
**Pull request by scraly**
I added one link to my Gophers artwork and one link to a serie of articles with concrete applications examples.

### CODE REVIEW

**Review by phanirithvij — CHANGES_REQUESTED** [review]
Needs to be in alphabetical order.

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: False
- coverage: False

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by scraly** [comment]
Hi
I don't understand. You need me to fix my PR? ^^

**Comment by avelino** [comment]
> Hi
> I don't understand. You need me to fix my PR? ^^

Sorry for the delay in reviewing, my work days are hectic

**Comment by scraly** [comment]
No problem! 🙂

**Pull request merged**
