### PR TITLE
adding the conjungo merge library

### PR DESCRIPTION
**Pull request by dselans**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: [conjungo](https://github.com/InVisionApp/conjungo)
- godoc.org: [godoc](https://godoc.org/github.com/InVisionApp/conjungo)
- goreportcard.com: [reportcard](https://goreportcard.com/report/github.com/InVisionApp/conjungo)
- coverage service link: https://codecov.io/gh/InVisionApp/conjungo

Very good coverage: 100%

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [ X ] I have added my package in alphabetical order.
- [ X ] I have an appropriate description with correct grammar.
- [ X ] I know that this package was not listed before.
- [ X ] I have added godoc link to the repo and to my pull request.
- [ X ] I have added coverage service link to the repo and to my pull request.
- [ X ] I have added goreportcard link to the repo and to my pull request.
- [ X ] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by dselans** [comment]
No problem, will fix shortly. Thanks!

**Comment by dselans** [comment]
Hello - godoc comments have been updated; reportcard is showing 100% on everything.

@cassiobotaro can you check again? Thanks!

**Comment by dselans** [comment]
@appleboy @cassiobotaro can you guys take a peek at this once more? All has been fixed.

Thanks!

**Comment by cassiobotaro** [comment]
@dselans sorry for the late reply, thanks for contributing! :smile:

**Pull request merged**
