### PR TITLE
Added "goav".

### PR DESCRIPTION
**Pull request by jonathanmarvens**

### CODE REVIEW

**Comment by kirillDanshin** [comment]
goav is already in the list.
please don't ignore our PR template.
thanks.

**Comment by jonathanmarvens** [comment]
@kirillDanshin: I didn’t ignore the template. In my experience, most folks use __[FFmpeg](https://ffmpeg.org)__ for audio-related tasks, so while it’s fine that __goav__ is already in the “*Libraries for manipulating video.*” category, I don’t see the problem with also having it in the “*Libraries for manipulating audio.*” category if the __true__ goal of this project is to help folks find the best tools for their projects.

**Comment by kirillDanshin** [comment]
@jonathanmarvens ok, you didn't ignore the template, you've just remove it.

in my experience most folks use ffmpeg for video-related tasks. look into the lib name. [FF**mpeg**. MPEG == **Moving Picture** Experts Group](https://en.wikipedia.org/wiki/Moving_Picture_Experts_Group). most folks [know moving picture (a.k.a. moving media) as video](https://en.wikipedia.org/wiki/Video).

also if you read the PR and our guidelines you know that to create a new category we need at least 3 libs.

**Comment by jonathanmarvens** [comment]
Hahaha, did you really just link me to the MPEG Wikipedia page?!?

Not only are you insulting my intelligence (as if IDK what MPEG is), but you’re also *wrong* … the *very first* sentence of the Wikipedia page that *you* linked to says: “*The Moving Picture Experts Group (MPEG) is a working group of authorities that was formed by ISO and IEC to set standards for __audio__ and video compression and transmission.*”

Have you ever listened to an MP3 audio file? Yeah, that’s actually an *__MPEG__-2 Audio Layer III* file. Don’t play this game with me.

Honestly, I don’t have the time to make a big deal with you over something so minuscule like this. Folks like you are why so many open-source projects fail. You chose to passive-aggressively attack a contributor simply trying to improve the project.

I thought @avelino’s goal for this project, like all of the other “*awesome*” projects, was to be a helpful resource. Software projects can span categories and __FFmpeg__ does … I use __FFmpeg__ almost daily for audio-related tasks and I’m currently using *goav* for an audio project.

Also, I never asked to create a new category, so I don’t understand your last point there.

Anyways, it seems that your only goal here is to turn me down or passive-aggressively attack me, and as I said, I don’t have the time to argue over something like this, which, IMO, shouldn’t even be a big deal.

**Comment by kirillDanshin** [comment]
I choose to not merge link's duplicates because I remember that our guidelines says that any library should be added just once.

> Have you ever listened to an MP3 audio file?
I'm a sound engineer with three years of experience.

but thanks, I wasn't knew that folks like me are the reason why so many open-source projects fail. early I think that a reason for that are insufficient time and motivation but not a folk that just closed your pull request.
and I'm sorry, I misread your sentence about having *it in* category but not having a category itself.
now I think we done with it. if you want to add something - you're welcome, we'll be glad to see a new PRs. but not dups.
good bye.

**Pull request closed without merging**
