### PR TITLE
add kcp-go

### PR DESCRIPTION
**Pull request by xtaci**
https://godoc.org/github.com/xtaci/kcp-go
https://goreportcard.com/report/github.com/xtaci/kcp-go
https://gocover.io/github.com/xtaci/kcp-go

### CODE REVIEW

**Comment by mmcdole** [comment]
@xtaci you are missing links for godoc.org, goreportcard.com, and gocover.io.

**Comment by xtaci** [comment]
https://godoc.org/github.com/xtaci/kcp-go
https://goreportcard.com/report/github.com/xtaci/kcp-go
https://gocover.io/github.com/xtaci/kcp-go

**Comment by mmcdole** [comment]
@xtaci I'm not involved with this repository, but based on past pull requests I think they are going to ask you to update your code so that your lint score is higher.  

Yours is currently at 0%:
https://goreportcard.com/report/github.com/xtaci/kcp-go

**Comment by xtaci** [comment]
it's not possible, i have to keep 100% compatible with C version

**Comment by kirillDanshin** [comment]
@mmcdole you're right. thanks for your help with PR review.
@xtaci you can fix issues with comments like [this](https://github.com/xtaci/kcp-go/blob/master/kcp.go#L30).
Thanks, I'll review the code manually. When you fix comments, please, leave a comment here.

**Comment by xtaci** [comment]
I think golint is not suitable for all kinds of libraries, i still got 0% on golint after i modified many comments.

**Comment by xtaci** [comment]
please review the code.

**Comment by kirillDanshin** [comment]
@xtaci thanks for your contribution.

**Pull request merged**
