### PR TITLE
Added information about rlog.

### PR DESCRIPTION
**Pull request by jbrendel**
Goreportcard.com: https://goreportcard.com/report/github.com/romana/rlog
Godoc.com: https://godoc.org/github.com/romana/rlog
Gocover.io: http://gocover.io/github.com/romana/rlog

### CODE REVIEW

**Comment by avelino** [comment]
@brendel I recommend following the guide line
read pls:
- https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md
- https://github.com/avelino/awesome-go/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by jbrendel** [comment]
Hi! Thank you for looking at this. Yes, I read it. Admittedly, there are no tests. However, the goreportcard and godoc links were included, yet it was marked as "needs links". There is also a "quality standard" mark. Could you elaborate on that, please?

**Comment by avelino** [comment]
Not run test (auto) http://gocover.io/github.com/romana/rlog

**Comment by kirillDanshin** [comment]
@jbrendel why there are no tests?

**Comment by jbrendel** [comment]
rlog now has tests. The coverage link for gocover.io has been added to the README and to this PR here.

**Comment by avelino** [comment]
new rules 8 days with label `pending-submitter-response`: https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers

**Pull request closed without merging**
