### PR TITLE
add TarsGo

### PR DESCRIPTION
**Pull request by sandyskies**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/TarsCloud/TarsGo
- godoc.org:  https://godoc.org/github.com/TarsCloud/TarsGo/tars
- goreportcard.com:  https://goreportcard.com/report/github.com/TarsCloud/TarsGo
- coverage service link: [cover.run](https://cover.run/go?tag=golang-1.10&repo=https%3A%2Fgodoc.org%2Fgithub.com%2FTarsCloud%2FTarsGo%2Ftars)

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by ceriath** [comment]
Could you please fix the alphabetical order? Also https://goreportcard.com/report/github.com/TarsCloud/TarsGo has at least some stuff that should be fixed

**Comment by sandyskies** [comment]
@ceriath  already fix the Alphabetical order problem and fix some goreportcard issue too，pleas check again！

**Comment by ceriath** [comment]
@sandyskies at least misspell, go_vet and ineffassign should be 100%, golint also has a lot of stuff thats easily fixable. About gocyclo, at least everything >25 should be fixed.

**Comment by sandyskies** [comment]
@ceriath  I will work on the missspell ，go_vet  and gocyclo， but some golint can't be done，it‘s because that some code was generated by tools，it’s historical reason.

**Comment by ceriath** [comment]
@sandyskies reportcard looks okay now, however, it seems like something broke your tests. 
The link you provided contains "godoc.org" in its url which will obviously not work ;) 
https://gocover.io/github.com/TarsCloud/TarsGo/tars gives an error: `strconv.ParseFloat: parsing "": invalid syntax`

**Comment by ceriath** [comment]
Closing this due to inactivity. Please reopen after you fixed the coverage issues!

**Pull request closed without merging**
