### PR TITLE
Added bbConvert

### PR DESCRIPTION
**Pull request by CalebQ42**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo: https://github.com/CalebQ42/bbConvert
- godoc.org: https://godoc.org/github.com/CalebQ42/bbConvert
- goreportcard.com: https://goreportcard.com/report/github.com/CalebQ42/bbConvert
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/CalebQ42/bbConvert

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by CalebQ42** [comment]
I've added links

**Comment by kirillDanshin** [comment]
@CalebQ42 your package has low test coverage. please improve it.

**Comment by CalebQ42** [comment]
I'm going to continue to work on it tonight. I'm at 50% now.

**Comment by CalebQ42** [comment]
I've gotten my test coverage up to 88%

**Comment by kirillDanshin** [comment]
@CalebQ42 as I see you've got test coverage up to 95%. good. thanks. please add a license, fix misspell and gocyclo (see goreportcard).

**Comment by kirillDanshin** [comment]
@CalebQ42 also as I see your tests will always passed. please, write a fair tests.

**Comment by CalebQ42** [comment]
What exactly do you mean by a fair test? (Sorry, I've never made or used _test for testing, I usually just make a simple program that uses it)

**Comment by kirillDanshin** [comment]
@CalebQ42 please [read](https://www.golang-book.com/books/intro/12) or [search](http://bfy.tw/6wgS) some information about it.

**Comment by corburn** [comment]
Here is a concrete example of a fair test:

```go
func TestStandard(t *testing.T) {
	testStr := "[ol][b]Item 1[/b]\n[i]Item 2[/i]\n[font='Times New Roman' size=20 color=red variant=smallcaps]Item 3[/font][/ol]\nNext Paragraph\nAnd the next\n[i]<Orphan tag :)"
	expect := "<ol><li><b>Item 1</b></li><li><i>Item 2<i></li><li><span style=\"font-size:20;font-variant:small-caps;color:red;font-family:'Times New Roman';\">Item 3</span></li></ol><p>Next Paragraph</p><p>And the next</p><p>[i]<Orphan tag :)</p>"

	conv := CreateConverter(true, true)
	result := conv.Convert(testStr))

	if result != expect {
		t.Failf("Got: %q, Expected: %q", testStr, expect)
	}
}

```

**Comment by CalebQ42** [comment]
Thanks! I'll definitely start to changing the test to something like that.

**Comment by CalebQ42** [comment]
I have redone the tests to be more like how they should be and have gotten my coverage back up to 86%

**Comment by CalebQ42** [comment]
I also added the license and fixed the spelling mistake. For the gocyclo, I probably won't be able to fix that easily, it would require a complete dissection and rewrite of the most important parts of the code.

**Comment by kirillDanshin** [comment]
@CalebQ42 thanks for your work and contribution.
@corburn thanks for your help.

you're awesome :wink:

**Pull request merged**
