### PR TITLE
add fake data generators and helpers

### PR DESCRIPTION
**Pull request by morenoh149**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

Please provide package links to:
- godoc.org: 
- goreportcard.com: 
- gocover.io: 

Note, that new categories can be added only when there are 3 packages or more.

Make shure that you've checked the boxes below before you submit PR:
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [ ] I have added godoc link
- [ ] I have added gocover.io link
- [ ] I have added goreportcard link
- [ ] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome :+1:

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@morenoh149 thanks for your contribution. please leave a comment when the links will be added and you'll check all boxes. thanks.

**Comment by morenoh149** [comment]
just to clarify, you don't want additions that simply link to the github project? you'd like a godoc.org link instead?

other listing within this same mock group simply link to the github project

**Comment by kirillDanshin** [comment]
@morenoh149 yep, I think we need to add github.com link to godoc/goreportcard/gocover list. also, maybe we could add godoc links or badges to the list ( @avelino @matrixik @shurcooL any objections?).

**Comment by morenoh149** [comment]
@kirillDanshin your comment refers to the github issue template. Could you answer my question and clarify if I should add or remove information to this PR?

**Comment by kirillDanshin** [comment]
@morenoh149 oh, sorry for misunderstanding.
please, send links in comment.

**Comment by morenoh149** [comment]
comment? there are already github link in the PR. Would you like me to add godoc links to the PR?

**Comment by kirillDanshin** [comment]
ok, let me show you:

https://github.com/icrowley/fake
https://godoc.org/github.com/icrowley/fake (ok)
https://goreportcard.com/report/github.com/icrowley/fake (A+, good)
https://gocover.io/github.com/icrowley/fake (but there are no test files)

===

https://github.com/manveru/faker
https://godoc.org/github.com/manveru/faker (needs docs)
https://goreportcard.com/report/github.com/manveru/faker (C, needs to be fixed)
https://gocover.io/github.com/manveru/faker (but there are no test files too)

===

https://github.com/wawandco/fako
https://godoc.org/github.com/wawandco/fako (needs examples)
https://goreportcard.com/report/github.com/wawandco/fako (A+, good, but golint issues needs to be fixed)
https://gocover.io/github.com/wawandco/fako (covered, but using `icrowley/fake` that was added above, that wasn't tested)

===

https://github.com/Pallinder/go-randomdata
https://godoc.org/github.com/Pallinder/go-randomdata (needs minor docs fixes and examples)
https://goreportcard.com/report/github.com/Pallinder/go-randomdata (A, issues needs to be fixed)
https://gocover.io/github.com/Pallinder/go-randomdata (covered)

===

https://github.com/yields/phony
https://godoc.org/github.com/yields/phony (needs docs and examples)
https://goreportcard.com/report/github.com/yields/phony (C, issues needs to be fixed)
https://gocover.io/github.com/yields/phony (but there are no test files too)
https://gocover.io/github.com/yields/phony/pkg/phony (100% covered, cool)

===

so, `fake` needs tests, `faker` needs tests and docs, `fako` needs examples, `go-randomdata` needs docs fixes and reportcard fixes and `phony` needs docs and examples before we can merge this PR. thanks!

**Comment by morenoh149** [comment]
ah but I have little to no control over the individual projects. So as far as I'm concerned I should simply close this PR as none of the projects pass awesome-go 's quality standards.

**Comment by cassiobotaro** [comment]
Packages out of quality standards.

**Pull request closed without merging**
