### PR TITLE
Add "Better Go Playground" service

### PR DESCRIPTION
**Pull request by x1unix**
**Please provide package links to:**

- github.com repo: https://github.com/x1unix/go-playground
- pkg.go.dev: https://pkg.go.dev/github.com/x1unix/go-playground
- goreportcard.com: https://goreportcard.com/report/github.com/x1unix/go-playground
- coverage service link: https://coveralls.io/github/x1unix/go-playground

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: False
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by x1unix** [comment]
@avelino this is a web service, not a software/library. Why it's necessary to provide coverage data?

**Comment by avelino** [comment]
> @avelino this is a web service, not a software/library. Why it's necessary to provide coverage data?

I think your tool is great, as it is written in Go and we presume quality would be important to have test and we can ensure minimum quality

**Comment by x1unix** [comment]
@avelino thank you for response. I'll take a look at coverage and fix mentioned issues.

**Comment by x1unix** [comment]
@avelino something went wrong with gocover.io :(
image

**Comment by avelino** [comment]
> @avelino something went wrong with gocover.io :(

you can use other coverage software, the issue template has some recommendations
- https://codecov.io/
- https://coveralls.io/
- https://gocover.io/

**Comment by x1unix** [comment]
@avelino updated GoReportCard (one symbol is not documented because it's monaco-editor binding and it has a separate documentation URL). GoDoc is still not cached package documentation, so it might return 404 error.

Code coverage report is in progress

**Comment by x1unix** [comment]
@avelino added test coverage report

**Pull request merged**
