### PR TITLE
Added remember-go

### PR DESCRIPTION
**Pull request by pjebs**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/rocketlaunchr/remember-go/
- godoc.org: https://godoc.org/github.com/rocketlaunchr/remember-go
- goreportcard.com: https://goreportcard.com/report/github.com/rocketlaunchr/remember-go
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: It's hard to add tests when I need redis running.

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [* ] I have added my package in alphabetical order.
- [ *] I have an appropriate description with correct grammar.
- [* ] I know that this package was not listed before.
- [* ] I have added godoc link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request.
- [ *] I have added goreportcard link to the repo and to my pull request.
- [ *] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by ceriath** [comment]
Please fill in the PR template and fix the form of the entry

**Comment by pjebs** [comment]
It's hard to run tests when I require redis/ memcached running.

**Comment by pjebs** [comment]
- I fixed up golint issues
- I added tests for the "in-memory" driver. I can't use redis/memcache in gocover.io.

https://gocover.io/github.com/rocketlaunchr/remember-go

**Comment by pjebs** [comment]
@ceriath Is there a reason for the delay in merge?

**Comment by ceriath** [comment]
@pjebs it requires 2 reviews to be merged. And currently it seems like most maintainers are enjoying their summer holidays

**Comment by kirillDanshin** [comment]
Please, create more tests. I'm a little bit concerned about your `if prefix {` in `CreateKey`. We require >= 80% coverage in our [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards).

**Comment by kirillDanshin** [comment]
feel free to open a new PR as soon as you'll get some tests

**Comment by pjebs** [comment]
@kirillDanshin The prefix section has now been covered. There is nothing more I can test.

**Pull request closed without merging**
