### PR TITLE
Add gopherjs

### PR DESCRIPTION
**Pull request by andela-earinde**
Link to project: [gopherjs](https://github.com/gopherjs/gopherjs)

I don't think I added this project in the proper section, I think a new section needs to be created for it.

### CODE REVIEW

**Comment by shurcooL** [comment]
Adding GopherJS is great!

About the section, it doesn't quite fit the _Embedding other languages inside your go code_ description, but it is close.

It's a compiler (written in Go) for compiling Go code to JavaScript.

Are there other Go compilers that could be added? We'd [need 3](https://github.com/avelino/awesome-go/pull/576#issuecomment-143523839) for a new section.

I know of https://github.com/go-llvm/llgo, but not a 3rd one... Any suggestions?

**Comment by neelance** [comment]
3rd one: https://github.com/tardisgo/tardisgo

**Comment by shurcooL** [comment]
Great, with 3 compilers, this can be made into a new section "Go Compilers".

Can you update this PR @andela-earinde?

**Comment by andela-earinde** [comment]
Sure @shurcooL

**Comment by shurcooL** [comment]
Great, thanks! :sparkles:

**Comment by andela-earinde** [comment]
Deleting this patch for a new branch.

**Pull request closed without merging**
