### PR TITLE
Add https://github.com/rocketlaunchr/react

### PR DESCRIPTION
**Pull request by pjebs**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/rocketlaunchr/react
- godoc.org: https://godoc.org/github.com/rocketlaunchr/react
- goreportcard.com: https://goreportcard.com/report/github.com/rocketlaunchr/react
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `[![cover.run]
It's too hard to do tests since it's a Front End Development bindings

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [* ] I have added my package in alphabetical order.
- [ *] I have an appropriate description with correct grammar.
- [* ] I know that this package was not listed before.
- [* ] I have added godoc link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request.
- [* ] I have added goreportcard link to the repo and to my pull request.
- [* ] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by ceriath** [comment]
Please fill in the PR template

**Comment by pjebs** [comment]
done

**Comment by pjebs** [comment]
@ceriath golint issues fixed. Not possible to do tests.

**Comment by kirillDanshin** [comment]
actually, it's possible to do e2e tests

**Comment by kirillDanshin** [comment]
Feel free to open a new PR as soon as you do some tests.

**Comment by pjebs** [comment]
How do I do e2e test

**Comment by kirillDanshin** [comment]
@pjebs 

keeping in mind that it's a rect bindings,
1) You develop a full testcase program
2) You write a test using, for example, cypress
3) you run a server serving your testcase
4) you run cypress and looking in the results

**Pull request closed without merging**
