### PR TITLE
Added links for gitql and textql

### PR DESCRIPTION
**Pull request by abhi18av**
## gitql

*REPO* : https://github.com/cloudson/gitql
*GODOC* : http://godoc.org/github.com/cloudson/gitql
*GOREPORTCARD* : https://goreportcard.com/report/github.com/cloudson/gitql
*COVERAGE* : https://cover.run/go/github.com/cloudson/gitql

## textql

*REPO*: https://github.com/dinedal/textql
*GODOC*: http://godoc.org/github.com/dinedal/textql
*GOREPORTCARD*: https://goreportcard.com/report/github.com/dinedal/textql
*COVERAGE* : https://cover.run/go/github.com/dinedal/textql

### CODE REVIEW

**Comment by cassiobotaro** [comment]
@abhi18av please follow this PR template: https://github.com/avelino/awesome-go/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by abhi18av** [comment]
Mmm, could anyone help me out with the coverage part? I'm unable to set it up properly.

**Comment by cassiobotaro** [comment]
@abhi18av gitql uses libgit2, then you have to set an environment to run test and caught coverage, and textql was build in a non buildable way. I think the soluition is to open issues on each project to solve that problems.

**Comment by cassiobotaro** [comment]
@abhi18av any news??

**Comment by abhi18av** [comment]
Whoops, sorry. No no news as of yet. 

Will notify gitql about the issue.

**Comment by abhi18av** [comment]
Tracking this on gitql via 
https://github.com/cloudson/gitql/issues/53

**Comment by cassiobotaro** [comment]
@abhi18av We are closing this issue, but feel free to send again following the quality standards when the thirdy-party libraries answer you.

**Pull request closed without merging**
