### PR TITLE
added silk to utilities

### PR DESCRIPTION
**Pull request by chrispassas**
Added library to read silk files.
Silk project website: https://tools.netsa.cert.org/silk/docs.html
Normally you need to use their C code to read silk files but this package allows reading them with native Go code.

Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/chrispassas/silk
- godoc.org: https://godoc.org/github.com/chrispassas/silk
- goreportcard.com: https://goreportcard.com/report/github.com/chrispassas/silk
- coverage service link [cover.run](https://cover.run/go?tag=golang-1.10&repo=github.com%2Fchrispassas%2Fsilk)

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by chrispassas** [comment]
Added silk package

**Comment by chrispassas** [comment]
Sorry I haven't done this before. Gadded the cover.run link to my projects read me. Do I need to provide anything else?

[cover.run](https://cover.run/go?tag=golang-1.10&repo=github.com%2Fchrispassas%2Fsilk)

**Comment by chrispassas** [comment]
OK, Updated the issues mentioned above. goreportcard now A+

**Comment by chrispassas** [comment]
It's not clear to me if I need to do anything else. I see the travis-ci failed but not sure if that has anything to do with my pull request?

**Comment by ceriath** [comment]
@chrispassas seems like something went broken with a commit that happened since you created the fork. Could you accept my PR chrispassas/awesome-go#1?

**Comment by chrispassas** [comment]
@ceriath pull accepted.

**Comment by ceriath** [comment]
Apparently #2329 did not merge correctly for whatever reason. however, i fixed it. Now we just gonna wait until someone else approves this :)

**Comment by chrispassas** [comment]
@ceriath Thank you

**Comment by cassiobotaro** [comment]
thanks @chrispassas !

**Pull request merged**
