### PR TITLE
add igo

### PR DESCRIPTION
**Pull request by pjebs**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/rocketlaunchr/igo
- godoc.org: N/A
- goreportcard.com: N/A
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: N/A

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [ *] I have added my package in alphabetical order.
- [* ] I have an appropriate description with correct grammar.
- [ *] I know that this package was not listed before.
- [ ] I have added godoc link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request.
- [ ] I have added goreportcard link to the repo and to my pull request.
- [* ] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by ceriath** [comment]
Please fill in the PR template

**Comment by pjebs** [comment]
The code is a tool for transpiling alternative go syntax. It is not a package.

**Comment by pjebs** [comment]
I will sort this out ASAP.

**Comment by kirillDanshin** [comment]
@pjebs do you have any "golden" tests?

**Comment by kirillDanshin** [comment]
Feel free to open a new PR as soon as you do some tests.

Also, if you have some questions about the type of testing that can be done in your project, feel free to ask me.

**Pull request closed without merging**
