### PR TITLE
Add jcli add a devops tool

### PR DESCRIPTION
**Pull request by LinuxSuRen**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/jenkins-zh/jenkins-cli
- godoc.org: https://godoc.org/github.com/jenkins-zh/jenkins-cli
- goreportcard.com: https://goreportcard.com/report/github.com/jenkins-zh/jenkins-cli
- coverage service link ([sonarqube](https://sonarcloud.io/dashboard?id=jenkins-zh_jenkins-cli))

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: False
- goreportcard.com: True
- coverage: True

**Comment by LinuxSuRen** [comment]
Can not pass the test coverage. See also vieux/gocover.io#41

**Comment by ceriath** [comment]
What exactly does the "WIP" in the title mean? Is the library WIP? Or do you intend to change this PR?

**Comment by LinuxSuRen** [comment]
`WIP` means `working in progress`. I cannot use the gocover getting a cover result. Just put the link of sonarqube.

**Comment by ceriath** [comment]
Yeah i know that it is "work in progress". I was just asking if the PR or the lib is work in progress

**Comment by LinuxSuRen** [comment]
@ceriath it’s ready now.

**Comment by LinuxSuRen** [comment]
@ceriath got it

**Pull request merged**
