### PR TITLE
Adding Emitter

### PR DESCRIPTION
**Pull request by Kelindar**
**Links to:**

- github.com repo: https://github.com/emitter-io/emitter
- godoc.org: https://godoc.org/github.com/emitter-io/emitter
- goreportcard.com: https://goreportcard.com/report/github.com/emitter-io/emitter
- coverage service link: https://coveralls.io/github/emitter-io/emitter?branch=master

[Coverage Status](https://coveralls.io/github/emitter-io/emitter?branch=master)

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Latest test coverage report:
```
?       github.com/emitter-io/emitter   [no test files]
ok      github.com/emitter-io/emitter/broker    1.142s  coverage: 57.3% of statements
ok      github.com/emitter-io/emitter/broker/cluster    0.501s  coverage: 21.1% of statements
ok      github.com/emitter-io/emitter/broker/message    0.022s  coverage: 91.7% of statements
ok      github.com/emitter-io/emitter/broker/storage    0.035s  coverage: 98.5% of statements
ok      github.com/emitter-io/emitter/broker/subscription       0.036s  coverage: 82.5% of statements
ok      github.com/emitter-io/emitter/collection        0.031s  coverage: 100.0% of statements
ok      github.com/emitter-io/emitter/config    0.021s  coverage: 100.0% of statements
ok      github.com/emitter-io/emitter/logging   0.024s  coverage: 33.3% of statements
ok      github.com/emitter-io/emitter/network/address   0.478s  coverage: 57.8% of statements
ok      github.com/emitter-io/emitter/network/http      0.026s  coverage: 64.3% of statements
ok      github.com/emitter-io/emitter/network/listener  0.501s  coverage: 81.1% of statements
?       github.com/emitter-io/emitter/network/mock      [no test files]
ok      github.com/emitter-io/emitter/network/mqtt      0.111s  coverage: 96.6% of statements
ok      github.com/emitter-io/emitter/network/websocket 0.024s  coverage: 12.2% of statements
ok      github.com/emitter-io/emitter/security  0.033s  coverage: 93.5% of statements
ok      github.com/emitter-io/emitter/security/mock     0.022s  coverage: 100.0% of statements
ok      github.com/emitter-io/emitter/security/usage    0.020s  coverage: 48.7% of statements
ok      github.com/emitter-io/emitter/utils     0.027s  coverage: 100.0% of statements
```

### CODE REVIEW

**Comment by Kelindar** [comment]
@cassiobotaro thanks for the review. Fixed all the linter issues and will make it part of our build as well. The one govet issue left is a non-issue in reality. https://goreportcard.com/report/github.com/emitter-io/emitter

**Comment by Kelindar** [comment]
@cassiobotaro this is weird, I just tried it a couple of times and had no issues on my end. Unable to write a file for some reason?

**Comment by Florimond** [comment]
@cassiobotaro What if you build "manually" with go build, then start emitter?

**Comment by cassiobotaro** [comment]
@Florimond @Kelindar I was following the README
image

**Comment by Kelindar** [comment]
Oh I was able to reproduce it on another laptop, I believe it's a issue in a dependency - will fix this asap.

**Comment by Florimond** [comment]
@cassiobotaro we released the update on the latest master for this issue, if you run ```go get -u github.com/emitter-io/emitter && emitter```  again it should work now. The readme file was updated accordingly.

**Comment by cassiobotaro** [comment]
@Florimond i will try asap.

**Comment by cassiobotaro** [comment]
```
2017/11/15 22:33:49 [service] unable to find a license, make sure 'license' value is set in the config file or EMITTER_LICENSE environment variable
2017/11/15 22:33:49 [service] generated new license: k2EAQXxZ7pTN5U6WnYhjhngYQ-OK8t4fAAAAAAAAAAI
2017/11/15 22:33:49 [service] generated new secret key: gMhj4brK9jSPfTLlOF9t_FuZtWkFC8PV
```
Please configure some coverage service or provide a better way to verify that.

**Comment by Kelindar** [comment]
@cassiobotaro I updated with coveralls link: https://coveralls.io/github/emitter-io/emitter?branch=master

**Comment by cassiobotaro** [comment]
thanks @Kelindar @Florimond !

**Pull request merged**
