### PR TITLE
Add `appy` web framework

### PR DESCRIPTION
**Pull request by cayter**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/appist/appy
- pkg.go.dev: [Go Doc](https://pkg.go.dev/github.com/appist/appy?tab=doc)
- goreportcard.com: [Go Report Card](https://goreportcard.com/report/github.com/appist/appy)
- coverage service link: [Coverage Status](https://codecov.io/gh/appist/appy)

Very good coverage (93%)

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

**Comment by cayter** [comment]
> You didn't put this repo on README alphabetically, please fix it.

`appy` is after `aah` right?

**Comment by panjf2000** [comment]
The Travis CI build failed, you should go to the detail page and check out the reason.

**Comment by cayter** [comment]
@panjf2000 Thanks. Just checked the code, yeah it's case insensitive. Just fixed it, sorry and thanks.

**Pull request merged**
