### PR TITLE
add ccbrown/api-fu

### PR DESCRIPTION
**Pull request by ccbrown**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/ccbrown/api-fu
- pkg.go.dev: https://pkg.go.dev/github.com/ccbrown/api-fu
- goreportcard.com: https://goreportcard.com/report/github.com/ccbrown/api-fu (A+)
- coverage service link: https://codecov.io/gh/ccbrown/api-fu (83%)

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

**Comment by ceriath** [comment]
Please resolve the issues of https://goreportcard.com/report/github.com/ccbrown/api-fu#golint

I see why certain things would not need a documentation, but some definitely should be documented.

**Comment by ccbrown** [comment]
I've taken other pass at resolving golint warnings. All exported members of the top level and graphql packages are now fully commented. These are the only two packages the vast majority of users are expected to look at or use. The others are for internal use / power users, much like go/ast, go/parser, etc. I have commented on a pretty significant portion of those packages as well though, and surprisingly, even if moved to an "internal" directory, which prevents them from being imported by users, golint still generates just as many warnings.

This brings golint's results from 50% to 65% with almost all of the remaining warnings being within these internal packages.

**Comment by ccbrown** [comment]
So is there some way to get a bot to remove the "pending-submitter-response" or do I just wait?

**Pull request merged**
