### PR TITLE
Added the Go Formatter library to the Awesome list.

### PR DESCRIPTION
**Pull request by tymonx**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://gitlab.com/tymonx/go-formatter
- pkg.go.dev: https://pkg.go.dev/gitlab.com/tymonx/go-formatter/formatter
- goreportcard.com: https://goreportcard.com/report/gitlab.com/tymonx/go-formatter (**A+**)
- coverage service link: https://tymonx.gitlab.io/go-formatter/coverage (**100%**)
- codacy quality report: https://app.codacy.com/gl/tymonx/go-formatter (**A**)

Very good coverage, it hits **100%**.

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by avelino** [comment]
gocover no working? https://gocover.io/gitlab.com/tymonx/go-formatter
we need you to have a real-time updated coverage (test) environment not static file  https://tymonx.gitlab.io/go-formatter/coverage/#file0

**Comment by tymonx** [comment]
Hi @avelino 

Thanks for your response. It works: https://gocover.io/gitlab.com/tymonx/go-formatter/formatter ->  **100%**. The same results like in the uploaded static file.

This static html file is automatically generated using  `go test -coverprofile coverage.out ./...` command invocation and uploaded by GitLab CI/CD.

Job: https://gitlab.com/tymonx/go-formatter/-/jobs/805010512 

File is uploaded using [GitLab Pages](https://docs.gitlab.com/ee/user/project/pages/) feature: https://gitlab.com/tymonx/go-formatter/-/jobs/805010513

The `gocover.io` seems buggy. I'm running the `go test -coverprofile coverage.out ./...` command normally from cloned project at the root with output `ok      gitlab.com/tymonx/go-formatter/formatter        0.005s  coverage: 100.0% of statements`.

**Comment by tymonx** [comment]
Buggy `gocover.io`. First time using:
image

After copy link to second web browser tab:
image

Several refreshes later, it works again...

**Comment by tymonx** [comment]
Thanks!

**Comment by tymonx** [comment]
@avelino FYI -> https://github.com/vieux/gocover.io/issues/15 It may be my case. Root project is without source files and tests but each package directory have source files with provided tests. They don't run `./...` that recursively will collect all results.

**Pull request merged**
