### PR TITLE
add nfigure

### PR DESCRIPTION
**Pull request by muir**
> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc): https://github.com/muir/nfigure
- pkg.go.dev: https://pkg.go.dev/github.com/muir/nfigure
- goreportcard.com: https://goreportcard.com/report/github.com/muir/nfigure
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): https://app.codecov.io/gh/muir/nfigure

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below that apply before you submit PR.**
_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines for detials._

- [x] The package has been added to the list in alphabetical order.
- [x] The package has an appropriate description with correct grammar.
- [x] As far as I know, the package has not been listed here before.
- [x] The repo documentation has a pkg.go.dev link.
- [x] The repo documentation has a coverage service link.
- [x] The repo documenation has a goreportcard link.
- [x] The repo has a version-numbered release and a go.mod file.
- [x] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines), [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers) and [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).
- [x] The repo has a continuous integration process that automatically runs tests that must pass before new pull requests are merged.
- [ ] The authors of the project do not commit directly to the repo, but rather use pull-requests that run the continuous-integration process.

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
review:
- golint
- gocyclo
- misspell
- coverage now ~66%, need +80%

**Comment by muir** [comment]
Where do you get the 66%?

`go test` reports > 80% and codecov reports 74%.   Codecov counts differently than go test -- the difference relates to how statements with partial coverage are counted.

Getting this one up to 80% took quite a bit of work.

```
go test -coverprofile=coverage.out ./...
ok      github.com/muir/nvelope 0.209s  coverage: 80.6% of statements
```

**Comment by phanirithvij** [comment]
@muir might be from this  
[screenshot](https://user-images.githubusercontent.com/29627898/161427468-75564203-5f9b-46e6-b21b-aea48416a69c.jpg)

**Comment by muir** [comment]
Sorry, my mistake.  nfigure vs nvelope.
Nfigure does need more coverage.

**Comment by muir** [comment]
After much effort coverage is now at 80%.   Getting there fixed a couple of bugs so a bunch of that effort was worth it.

**Pull request merged**
