### PR TITLE
Add dgraph-io/badger

### PR DESCRIPTION
**Pull request by francoishill**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: [github.com/dgraph-io/badger](https://github.com/dgraph-io/badger)
- godoc.org: [godoc.org/github.com/dgraph-io/badger](https://godoc.org/github.com/dgraph-io/badger)
- goreportcard.com: [goreportcard.com/report/github.com/dgraph-io/badger](https://goreportcard.com/report/github.com/dgraph-io/badger)
- coveralls.io: [coveralls.io/github/dgraph-io/badger](https://coveralls.io/github/dgraph-io/badger?branch=master)

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by francoishill** [comment]
@cassiobotaro, coveralls is now added to the repo

**Comment by deepakjois** [comment]
@cassiobotaro Those golint warnings are for packages that are used internally in Badger. The public API is  well documented, and in the latest report, the coverage is up to 72%.

**Comment by deepakjois** [comment]
All go lint and go vet checks are passing:

screenshot from 2017-09-09 09-02-08

screenshot from 2017-09-09 09-03-52

**Comment by cassiobotaro** [comment]
@deepakjois ptal 
image

**Comment by deepakjois** [comment]
@cassiobotaro Please take another look.

screenshot from 2017-09-11 11-28-51

As for the typo in the original pull request, @francoishill can you fix it? Since it is such a minor change, it seems whoever commits the pull request can make that change. Maybe they could do that, to move things along? I could open another pull request, but that seems a bit too much noise for such a minor thing.

**Comment by cassiobotaro** [comment]
@deepakjois I don't reject because of "ineffassign", but because you have to add a period at description.

**Comment by deepakjois** [comment]
@cassiobotaro Oh ok. Understood. But I fixed it anyway.

I did not create the pull request, @francoishill did. So I cannot edit it to add a period. So I guess we may have to wait for him.

**Comment by francoishill** [comment]
@cassiobotaro, @deepakjois the period was added

**Comment by cassiobotaro** [comment]
thanks @francoishill !

**Comment by francoishill** [comment]
Awesome stuff @cassiobotaro

**Pull request merged**
