### PR TITLE
Add GJSON.

### PR DESCRIPTION
**Pull request by fiatjaf**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo: https://github.com/tidwall/gjson
- godoc.org: https://godoc.org/github.com/tidwall/gjson
- goreportcard.com: https://goreportcard.com/report/github.com/tidwall/gjson
- coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/tidwall/gjson

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by appleboy** [comment]
Please fix the errors from go report card. https://goreportcard.com/report/github.com/tidwall/gjson

**Comment by fiatjaf** [comment]
Oh, I'm sorry, the errors we're talking about are those related to "cyclomatic complexity", right?

Is that so important? The thing is a raw JSON string parser contained in a small library, so it is natural that its complex. The whole thing is very mature, used in lots of projects and carefully tested. Can't we ignore these "complexity" complaints?

**Comment by joeybloggs** [comment]
@appleboy IMO I think that in this circumstance cyclomatic complexity shouldn't hold this back it isn't that bad once taking a look.

But having said that @fiatjaf there are a few places for improvement eg. https://github.com/tidwall/gjson/blob/master/gjson.go#L1763 the if at this line and the next 2 it's could be combined into a single if statement with some && and ||'s

**Comment by fiatjaf** [comment]
Yes, I agree. The problem is that this library is not mine, I'm just a user. Should I try to contact the maintainers?

**Comment by fiatjaf** [comment]
@joeybloggs Can you please take a look now? The complexity has been reduced and GJSON is now scoring an "A+    Excellent! ".

**Comment by joeybloggs** [comment]
@fiatjaf because this package is data related it requires >= 90% test coverage

I would also expect that all Exposed/Public functions would be tested as well eg.
coverage-gjson

I realize that this is not your package, but I think that this will be the last thing needed :)

**Comment by joeybloggs** [comment]
Tests now > 90% Thanks @fiatjaf and @tidwall

**Pull request merged**
