### PR TITLE
Add Easegress

### PR DESCRIPTION
**Pull request by benja-wu**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: [https://github.com/megaease/easegress](https://github.com/megaease/easegress)
- pkg.go.dev: [https://pkg.go.dev/github.com/megaease/easegress]( https://pkg.go.dev/github.com/megaease/easegress)
- goreportcard.com:  A+ [https://goreportcard.com/report/github.com/megaease/easegress](https://goreportcard.com/report/github.com/megaease/easegress)
- coverage service link ([codecov](https://codecov.io/gh/megaease/easegress))

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by benja-wu** [comment]
Excuse me, can we continue processing this PR? Thx @avelino

**Review by avelino — CHANGES_REQUESTED** [review]
review:
- golint
- cover page (link)

**Comment by benja-wu** [comment]
> review:
> 
> * golint
> * cover page (link)
Hi, The missing link has been filled.

golint: https://goreportcard.com/report/github.com/megaease/easegress#golint
cover: https://app.codecov.io/gh/megaease/easegress

**Comment by avelino** [comment]
> cover: https://app.codecov.io/gh/megaease/easegress

@benja-wu converage >= 85%, today this `58.46%`

read more https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards

**Comment by benja-wu** [comment]
> > cover: https://app.codecov.io/gh/megaease/easegress
> 
> @benja-wu converage >= 85%, today this `58.46%`
> 
> read more https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards

Thank you for the review and remainder.
We are working on raising the coverage rate to match the standard. :-)

**Comment by phanirithvij** [comment]
Does this go under Dev ops tools category?

**Comment by benja-wu** [comment]
> The coverage is >80% now. This can be merged but I have a doubt, doesn't this go under Dev ops tools category?

HI, @phanirithvij , 
* Easegress is a cloud-native traffic orchestration. It's widely used as an HTTP1/2 reverse proxy, just like `algernon` and `Caddy`. (But Easegress also supported more powerful features such as workflow too. :-) )
* Since `algernon` and `Caddy` are currently in the `Server Applications` catalog, I think Easegress is suitable in it too.

**Pull request merged**
