### PR TITLE
Add go-twitch library

### PR DESCRIPTION
**Pull request by knspriggs**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo: https://github.com/knspriggs/go-twitch
- godoc.org: https://godoc.org/github.com/knspriggs/go-twitch
- goreportcard.com:  https://goreportcard.com/report/github.com/knspriggs/go-twitch
- coverage service link (gocover, coveralls etc.): https://coveralls.io/github/knspriggs/go-twitch

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by shurcooL** [comment]
Not sure what to say about the documentation. It keeps `golint` happy, but it's really blank for the most part. Aside from that, looks good.

**Comment by knspriggs** [comment]
I'll tidy that up, and I'll post back here when it's updated. Cheers 🍻

**Comment by kirillDanshin** [comment]
@shurcooL submitted an issue to golint https://github.com/golang/lint/issues/265

**Comment by knspriggs** [comment]
Docs cleaned up, and coverage link added. 🍻

**Pull request merged**
