### PR TITLE
Add emperror

### PR DESCRIPTION
**Pull request by sagikazarmark**
I would like to suggest adding my error handling library to this list. I'm working on it for a few years now and I feel it's really close to 1.0.0.

I actually submitted two libraries: one is a drop-in replacement for `errors` and `github.com/pkg/errors` packages. It contains quite a few additional features. The other one is a set of tools to make error handling itself easier.

I wrote about using these tools here: https://banzaicloud.com/blog/error-handling-go/

I'm not 100% sure whether I should have submitted the project itself (since there are quite a few more libraries in the project) or not, but I felt these two libraries are the most important ones.

Thank you for considering my package!

(Note: some goreportcard warnings are not fixed intentionally. Some test files are downloaded from the stdlib `errors` and `github.com/pkg/errors` packages to ensure compatibility and those files are not modified except for package names.)

**Please provide package links to:**

Errors package:
- github.com repo: https://github.com/emperror/errors
- godoc.org: https://godoc.org/emperror.dev/errors
- goreportcard.com: https://goreportcard.com/report/emperror.dev/errors
- coverage service link: https://gocover.io/emperror.dev/errors

Emperror package:
- github.com repo: https://github.com/emperror/emperror
- godoc.org: https://godoc.org/emperror.dev/emperror
- goreportcard.com: https://goreportcard.com/report/emperror.dev/emperror
- coverage service link: https://gocover.io/emperror.dev/emperror

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by sagikazarmark** [comment]
As I explained in the PR description, that's kinda intentional. The marked files are copied from the standard library and I did not want to change them. But if that's a deal breaker, I'm happy tobrun gofmt on them.

**Comment by sagikazarmark** [comment]
👏 Thanks @kirillDanshin !

**Comment by kirillDanshin** [comment]
@sagikazarmark keep it going bud, those projects looks nice

**Comment by sagikazarmark** [comment]
Thanks! 🙂 I really appreciate it.

**Pull request merged**
