### PR TITLE
Add xgo(a mocking library), remove awterman/monkey and pasdam/mockit

### PR DESCRIPTION
**Pull request by xhd2015**
## We want to ensure high quality of the packages. Make sure that you've checked the boxes below before sending a pull request.

- [x] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines)
- [x] I have read the [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers)
- [x] I have read the [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards)

_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines for details._

- [x] The repo documentation has a pkg.go.dev link.
- [x] The repo documentation has a coverage service link.(It outputs coverage with github action)
- [x] The repo documentation has a goreportcard link.
- [x] The repo has a version-numbered release and a go.mod file.
- [x] The repo has a continuous integration process that automatically runs tests that must pass before new pull requests are merged.
- [x] Continuous integration is used to attempt to catch issues prior to releasing this package to end-users.

## Please provide some links to your package to ease the review

- [x] forge link (github.com, gitlab.com, etc): https://github.com/xhd2015/xgo
- [x] pkg.go.dev: https://pkg.go.dev/github.com/xhd2015/xgo
- [x] goreportcard.com: https://goreportcard.com/report/github.com/xhd2015/xgo
- [x] coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): it run tests in github action, the core library has 81.3% coverage

## Pull Request content

- [x] The package has been added to the list in alphabetical order.
- [x] The package has an appropriate description with correct grammar.
- [x] As far as I know, the package has not been listed here before.

## Category quality

_Note that new categories can be added only when there are 3 packages or more._

Packages added a long time ago might not meet the current guidelines anymore. It would be very helpful if you could check 3-5 packages above and below your submission to ensure that they also still meet the Quality Standards.

Please delete one of the following lines:

- [x] The packages around my addition still meet the Quality Standards.
- [x] I removed the following packages around my addition: (please give a short reason for each removal)

  - Removing https://github.com/awterman/monkey
     - just a wrapper around gomonkey
     - just one go source file, hard to be a library
     - less pupular
     - 8 commits in total
  - Removing https://github.com/pasdam/mockit
     - archived
     - last update 4 years ago(excluding .github/workflow, go.mod update) 

Thanks for your PR, you're awesome! :sunglasses:

### CODE REVIEW

**Comment by xhd2015** [comment]
awesome-go, awesome gophers!
The requirement/guideline of this project helps me make my project better, great work. Thank you, guys.

**Comment by xhd2015** [comment]
Coverage(81.3%) information  : https://github.com/xhd2015/xgo/actions/runs/8490630857/job/23261907499

```go
> cd runtime && go tool cover --func ../cover-runtime.out
github.com/xhd2015/xgo/runtime/core/func.go:[4](https://github.com/xhd2015/xgo/actions/runs/8490599772/job/23261844048#step:6:5)4:			DisplayName				100.0%
github.com/xhd2015/xgo/runtime/core/func.go:[5](https://github.com/xhd2015/xgo/actions/runs/8490599772/job/23261844048#step:6:6)7:			ParseFuncName				87.5%
github.com/xhd2015/xgo/runtime/core/version.go:20:		init					[6](https://github.com/xhd2015/xgo/actions/runs/8490599772/job/23261844048#step:6:7)6.7%
github.com/xhd2015/xgo/runtime/core/version.go:31:		checkVersion				36.4%
github.com/xhd2015/xgo/runtime/functab/functab.go:1[7](https://github.com/xhd2015/xgo/actions/runs/8490599772/job/23261844048#step:6:8):		init					100.0%
github.com/xhd2015/xgo/runtime/functab/functab.go:23:		__xgo_link_retrieve_all_funcs_and_clear	0.0%
github.com/xhd2015/xgo/runtime/functab/functab.go:2[8](https://github.com/xhd2015/xgo/actions/runs/8490599772/job/23261844048#step:6:9):		__xgo_link_on_init_finished		0.0%
github.com/xhd2015/xgo/runtime/functab/functab.go:32:		__xgo_link_get_pc_name			0.0%
github.com/xhd2015/xgo/runtime/functab/functab.go:44:		GetFuncs				100.0%
github.com/xhd2015/xgo/runtime/functab/functab.go:4[9](https://github.com/xhd2015/xgo/actions/runs/8490599772/job/23261844048#step:6:10):		InfoFunc				0.0%
github.com/xhd2015/xgo/runtime/functab/functab.go:61:		InfoPC					100.0%
github.com/xhd2015/xgo/runtime/functab/functab.go:67:		Info					[10](https://github.com/xhd2015/xgo/actions/runs/8490599772/job/23261844048#step:6:11)0.0%
github.com/xhd2015/xgo/runtime/functab/functab.go:77:		GetFuncByPkg				80.0%
github.com/xhd2015/xgo/runtime/functab/functab.go:103:		GetFuncByFullName			100.0%
github.com/xhd2015/xgo/runtime/functab/functab.go:[11](https://github.com/xhd2015/xgo/actions/runs/8490599772/job/23261844048#step:6:12)1:		GetTypeMethods				100.0%
github.com/xhd2015/xgo/runtime/functab/functab.go:116:		getInterfaceOrGenericByFullName		90.9%
github.com/xhd2015/xgo/runtime/functab/functab.go:141:		ensureMapping				86.7%
github.com/xhd2015/xgo/runtime/functab/functab.go:261:		ensureTypeMapping			92.9%
github.com/xhd2015/xgo/runtime/functab/functab.go:283:		getFuncPC				100.0%
github.com/xhd2015/xgo/runtime/mock/mock.go:26:			Mock					100.0%
github.com/xhd2015/xgo/runtime/mock/mock.go:30:			MockByName				75.0%
github.com/xhd2015/xgo/runtime/mock/mock.go:39:			MockMethodByName			80.0%
github.com/xhd2015/xgo/runtime/mock/mock.go:59:			AddFuncInterceptor			0.0%
github.com/xhd2015/xgo/runtime/mock/mock.go:66:			mockByFunc				60.0%
github.com/xhd2015/xgo/runtime/mock/mock.go:81:			mock					90.9%
github.com/xhd2015/xgo/runtime/mock/mock.go:134:		CallOld					0.0%
github.com/xhd2015/xgo/runtime/test/mock_by_name/sub/sub.go:3:	F					100.0%
github.com/xhd2015/xgo/runtime/test/mock_by_name/sub/sub.go:7:	f					100.0%
github.com/xhd2015/xgo/runtime/test/mock_by_name/sub/sub.go:14:	F					100.0%
github.com/xhd2015/xgo/runtime/test/mock_by_name/sub/sub.go:18:	f					100.0%
github.com/xhd2015/xgo/runtime/test/mock_by_name/sub/sub.go:26:	F					0.0%
github.com/xhd2015/xgo/runtime/test/mock_by_name/sub/sub.go:30:	f					100.0%
github.com/xhd2015/xgo/runtime/test/mock_by_name/sub/sub.go:34:	Call_f					100.0%
github.com/xhd2015/xgo/runtime/test/mock_by_name/sub/sub.go:38:	Call_sF					100.0%
github.com/xhd2015/xgo/runtime/test/mock_by_name/sub/sub.go:43:	Call_sf					100.0%
github.com/xhd2015/xgo/runtime/test/mock_by_name/sub/sub.go:48:	GetS					100.0%
github.com/xhd2015/xgo/runtime/test/mock_by_name/sub/sub.go:52:	GetNS					100.0%
github.com/xhd2015/xgo/runtime/test/mock_by_name/sub/sub.go:58:	Call_sf_instance			100.0%
github.com/xhd2015/xgo/runtime/test/mock_by_name/sub/sub.go:62:	Call_nsf_instance			100.0%
github.com/xhd2015/xgo/runtime/trace/stack.go:32:		Export					66.7%
github.com/xhd2015/xgo/runtime/trace/stack.go:44:		Export					100.0%
github.com/xhd2015/xgo/runtime/trace/stack.go:55:		Export					83.3%
github.com/xhd2015/xgo/runtime/trace/stack.go:75:		ExportFuncInfo				66.7%
github.com/xhd2015/xgo/runtime/trace/trace.go:30:		init					100.0%
github.com/xhd2015/xgo/runtime/trace/trace.go:49:		__xgo_link_on_test_start		0.0%
github.com/xhd2015/xgo/runtime/trace/trace.go:54:		__xgo_link_getcurg			0.0%
github.com/xhd2015/xgo/runtime/trace/trace.go:59:		__xgo_link_on_goexit			0.0%
github.com/xhd2015/xgo/runtime/trace/trace.go:62:		__xgo_link_init_finished		0.0%
github.com/xhd2015/xgo/runtime/trace/trace.go:68:		__xgo_link_peek_panic			0.0%
github.com/xhd2015/xgo/runtime/trace/trace.go:75:		Enable					57.1%
github.com/xhd2015/xgo/runtime/trace/trace.go:91:		Collect					0.0%
github.com/xhd2015/xgo/runtime/trace/trace.go:104:		Options					100.0%
github.com/xhd2015/xgo/runtime/trace/trace.go:108:		Name					0.0%
github.com/xhd2015/xgo/runtime/trace/trace.go:113:		OnComplete				100.0%
github.com/xhd2015/xgo/runtime/trace/trace.go:118:		Collect					100.0%
github.com/xhd2015/xgo/runtime/trace/trace.go:[12](https://github.com/xhd2015/xgo/actions/runs/8490599772/job/23261844048#step:6:13)2:		setupInterceptor			90.1%
github.com/xhd2015/xgo/runtime/trace/trace.go:264:		collect					85.7%
github.com/xhd2015/xgo/runtime/trace/trace.go:289:		getTraceOutput				100.0%
github.com/xhd2015/xgo/runtime/trace/trace.go:295:		SetMarshalStack				0.0%
github.com/xhd20[15](https://github.com/xhd2015/xgo/actions/runs/8490599772/job/23261844048#step:6:16)/xgo/runtime/trace/trace.go:299:		fmtStack				44.4%
github.com/xhd2015/xgo/runtime/trace/trace.go:318:		emitTrace				76.5%
github.com/xhd2015/xgo/runtime/trap/inspect.go:20:		Inspect					100.0%
github.com/xhd2015/xgo/runtime/trap/inspect.go:25:		InspectPC				81.8%
github.com/xhd2015/xgo/runtime/trap/interceptor.go:[19](https://github.com/xhd2015/xgo/actions/runs/8490599772/job/23261844048#step:6:20):		__xgo_link_getcurg			0.0%
github.com/xhd2015/xgo/runtime/trap/interceptor.go:24:		__xgo_link_init_finished		0.0%
github.com/xhd[20](https://github.com/xhd2015/xgo/actions/runs/8490599772/job/23261844048#step:6:21)15/xgo/runtime/trap/interceptor.go:29:		__xgo_link_on_goexit			0.0%
github.com/xhd2015/xgo/runtime/trap/interceptor.go:32:		__xgo_link_get_pc_name			0.0%
github.com/xhd2015/xgo/runtime/trap/interceptor.go:37:		init					100.0%
github.com/xhd2015/xgo/runtime/trap/interceptor.go:49:		AddInterceptor				100.0%
github.com/xhd2015/xgo/runtime/trap/interceptor.go:70:		WithInterceptor				100.0%
github.com/xhd2015/xgo/runtime/trap/interceptor.go:76:		GetInterceptors				100.0%
github.com/xhd2015/xgo/runtime/trap/interceptor.go:80:		GetLocalInterceptors			100.0%
github.com/xhd2015/xgo/runtime/trap/interceptor.go:89:		ClearLocalInterceptors			0.0%
github.com/xhd2015/xgo/runtime/trap/interceptor.go:93:		GetAllInterceptors			100.0%
github.com/xhd2015/xgo/runtime/trap/interceptor.go:108:		addLocalInterceptor			88.0%
github.com/xhd2015/xgo/runtime/trap/interceptor.go:151:		clearLocalInterceptorsAndMark		100.0%
github.com/xhd2015/xgo/runtime/trap/object.go:31:		appendFields				100.0%
github.com/xhd2015/xgo/runtime/trap/object.go:45:		GetField				75.0%
github.com/xhd2015/xgo/runtime/trap/object.go:54:		GetFieldIndex				100.0%
github.com/xhd2015/xgo/runtime/trap/object.go:58:		NumField				0.0%
github.com/xhd2015/xgo/runtime/trap/object.go:62:		GetErr					100.0%
github.com/xhd2015/xgo/runtime/trap/object.go:66:		Name					0.0%
github.com/xhd2015/xgo/runtime/trap/object.go:70:		Set					100.0%
github.com/xhd2015/xgo/runtime/trap/object.go:73:		Ptr					100.0%
github.com/xhd2015/xgo/runtime/trap/object.go:77:		Value					100.0%
github.com/xhd2015/xgo/runtime/trap/object.go:81:		MarshalJSON				88.9%
github.com/xhd2015/xgo/runtime/trap/trap.go:15:			ensureTrapInstall			100.0%
github.com/xhd2015/xgo/runtime/trap/trap.go:[21](https://github.com/xhd2015/xgo/actions/runs/8490599772/job/23261844048#step:6:22):			__xgo_link_set_trap			0.0%
github.com/xhd2015/xgo/runtime/trap/trap.go:31:			Skip					0.0%
github.com/xhd2015/xgo/runtime/trap/trap.go:33:			GetTrappingPC				80.0%
github.com/xhd2015/xgo/runtime/trap/trap.go:47:			trapImpl				85.6%
github.com/xhd2015/xgo/runtime/trap/trap.go:[22](https://github.com/xhd2015/xgo/actions/runs/8490599772/job/23261844048#step:6:23)5:		setTrappingMark				100.0%
github.com/xhd2015/xgo/runtime/trap/trap.go:[23](https://github.com/xhd2015/xgo/actions/runs/8490599772/job/23261844048#step:6:24)6:		clearTrappingMark			100.0%
github.com/xhd2015/xgo/runtime/trap/trap.go:[24](https://github.com/xhd2015/xgo/actions/runs/8490599772/job/23261844048#step:6:25)1:		setTrappingPC				100.0%
github.com/xhd2015/xgo/runtime/trap/trap.go:246:		clearTrappingPC				100.0%
total:								(statements)				81.3%
```

**Comment by Noroz-77** [comment]
> Thank you for contributing to [awesome-go](https://awesome-go.com/). We will review your contribution as soon as possible.
> 
> Make sure you add the links in the body of the pull request that are requested in the [contribution guide](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md):
> - repo link
> - pkg.go.dev
> - goreportcard.com
> - coverage
> 
> > Your project is under review. It may take a few days to be approved.

**Comment by Noroz-77** [comment]
xhd2015:xhd2015-add-xgo

**Comment by xhd2015** [comment]
@phanirithvij Hi may I know how do you think of this PR? Does this repository meets the quality guideline?

**Comment by xhd2015** [comment]
@phanirithvij Thanks I will add the awesome-go badge back to the xgo repository.

**Comment by adarx1** [comment]
Apı

**Pull request merged**
