### PR TITLE
Add roumon

### PR DESCRIPTION
**Pull request by becheran**
**Please provide package links to:**

- github.com repo: https://github.com/becheran/roumon
- pkg.go.dev: https://pkg.go.dev/github.com/becheran/roumon
- goreportcard.com: https://goreportcard.com/report/github.com/becheran/roumon

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [ ] I have added my package in alphabetical order.
- [ ] I have an appropriate description with correct grammar.
- [ ] I know that this package was not listed before.
- [ ] I have added pkg.go.dev link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request.
- [ ] I have added goreportcard link to the repo and to my pull request.
- [ ] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: False

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
review:
- golint https://goreportcard.com/report/github.com/becheran/roumon#golint
- coverage link

**Comment by becheran** [comment]
@avelino 

Thanks for the review.

I fixed the go linter issues: https://goreportcard.com/report/github.com/becheran/roumon#golint

Unfortunately GoCover.io fails to run the cover test in an not interactive shell. I guess due to the termui dependency. https://gocover.io/github.com/becheran/roumon. Though I do have unit tests for the parts that can run outside an interactive shell. Executing `go test -cover ./internal/...` result:

```
ok      github.com/becheran/roumon/internal/client      (cached)        coverage: 82.4% of statements
ok      github.com/becheran/roumon/internal/collection  (cached)        coverage: 100.0% of statements
ok      github.com/becheran/roumon/internal/model       0.074s  coverage: 82.1% of statements
?       github.com/becheran/roumon/internal/ui  [no test files]
```

**Comment by avelino** [comment]
> Unfortunately GoCover.io fails to run the cover test in an not interactive shell. I guess due to the termui dependency. https://gocover.io/github.com/becheran/roumon. Though I do have unit tests for the parts that can run outside an interactive shell. Executing `go test -cover ./internal/...` result:
> 
> ```
> ok      github.com/becheran/roumon/internal/client      (cached)        coverage: 82.4% of statements
> ok      github.com/becheran/roumon/internal/collection  (cached)        coverage: 100.0% of statements
> ok      github.com/becheran/roumon/internal/model       0.074s  coverage: 82.1% of statements
> ?       github.com/becheran/roumon/internal/ui  [no test files]
> ```

there are other coverage systems, I recommend looking at: codecov OR coveralls

**Comment by becheran** [comment]
@avelino thanks for the hints. Though codecove also does not work for me (https://app.codecov.io/gh/becheran/roumon/commits?page=1
) and coveralls seems not to work with github actions? At least I did not find a tutorial. But in the end it has the same problem I guess. 

Is the coverage is really all that important for a CLI tool? Roumon is not a go library, but a command line tool which helps to debug/monitor go programs.

**Comment by avelino** [comment]
in coveralls you push the generated file to them, I believe it should work for you
https://docs.coveralls.io/go

**Comment by becheran** [comment]
@avelino many thanks! Yes it was actually very easy to do it via the command line. Link: https://coveralls.io/github/becheran/roumon

**Pull request merged**
