### PR TITLE
Add afero to miscellaneous category

### PR DESCRIPTION
**Pull request by VorT3x**
- godoc.org: https://godoc.org/github.com/spf13/afero
- goreportcard.com: https://goreportcard.com/report/github.com/spf13/afero
- gocover.io: https://gocover.io/github.com/spf13/afero

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@VorT3x sorry for taking so much time. Please, add more tests. Thanks!

**Comment by VorT3x** [comment]
@kirillDanshin in awesome-go or Afero?

**Comment by kirillDanshin** [comment]
.@VorT3x in Afero. As I see sftp wasn't tested at all, for example.

**Comment by VorT3x** [comment]
@kirillDanshin 

Coverage is always a problem, but this library is actually quiet solid: Afero has 555 stars, 16 contributors and author is Steve Francia (@spf13)

screen shot 2016-04-04 at 15 41 36

sftp.go is minor part of this code ;)

**Comment by kirillDanshin** [comment]
@VorT3x I see that some tests are turned off, like `sftp_test_go` instead of `sftp_test.go`.
Just read some code from Afero and some issues.
Good package. Thanks for contribution, you're awesome! :wink:

**Pull request merged**
