### PR TITLE
Added to authentication

### PR DESCRIPTION
**Pull request by brianvoe**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/brianvoe/sjwt
- godoc.org: https://godoc.org/github.com/brianvoe/sjwt
- goreportcard.com: https://goreportcard.com/report/github.com/brianvoe/sjwt
- coverage service link: https://codecov.io/github/brianvoe/sjwt

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by ceriath** [comment]
Please fill in the PR template

**Comment by brianvoe** [comment]
github.com repo: https://github.com/brianvoe/sjwt
godoc.org: https://godoc.org/github.com/brianvoe/sjwt
goreportcard.com: https://goreportcard.com/report/github.com/brianvoe/sjwt
coverage service link: https://codecov.io/github/brianvoe/sjwt

**Comment by brianvoe** [comment]
Any update on this. Let me know if you need me to do anything else

**Comment by ceriath** [comment]
@brianvoe Currently there is nothing you can do. Pull Requests to this list require two approvals, however it seems like noone else had the chance to review this yet

**Comment by brianvoe** [comment]
ok ill just patiently wait

**Pull request merged**
