### PR TITLE
Add github.com/artonge/go-gtfs

### PR DESCRIPTION
**Pull request by artonge**
- github.com repo: https://github.com/artonge/go-gtfs
- godoc.org: https://godoc.org/github.com/artonge/go-gtfs
- goreportcard.com: https://goreportcard.com/report/github.com/artonge/go-gtfs
- coverage service link: https://cover.run/go/github.com/artonge/go-gtfs

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by artonge** [comment]
Sorry for the title, wrong copy past :)

**Comment by artonge** [comment]
Hmm, wrong commit message to, closing and redoing a pull request

**Comment by artonge** [comment]
Don't need to change the commit message then ?

**Comment by avelino** [comment]
@artonge yep, send rebase

**Pull request merged**
