### PR TITLE
Add Apache Phoenix/Avatica database/sql driver.

### PR DESCRIPTION
**Pull request by F21**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

Please provide package links to:
- godoc.org: https://godoc.org/github.com/Boostport/avatica
- goreportcard.com: https://goreportcard.com/report/github.com/Boostport/avatica
- gocover.io: https://coveralls.io/github/Boostport/avatica

Note, that new categories can be added only when there are 3 packages or more.

Make sure that you've checked the boxes below before you submit PR:
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link
- [x] I have added gocover.io link
- [x] I have added goreportcard link
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@F21 please, add more tests. thanks.

**Comment by jaytaylor** [comment]
@kirillDanshin What do you mean?  I see you posting this same comment a lot around here, and I think it would be more helpful if you provide more detail on what you are dissatisfied with compared to just saying "more tests please!".

**Comment by kirillDanshin** [comment]
@jaytaylor ok, if for some reason it unclear for you, here some more details on why I want more tests.
any library in this list needs to be tested enough so anybody can trust to package's quality.
in this case @F21 propose to add the database driver to the list. database drivers require many tests to check data consistence and many more. this package now has only 15.9% code coverage so I can't recommend this package to anybody, so I can't merge this pull request now. when @F21 will finish the tests I definitely merge this. 
hope now you understand my point.

**Comment by jaytaylor** [comment]
That is a lot more clear, thanks @kirillDanshin !

**Comment by F21** [comment]
Hey @kirillDanshin, thanks for looking at my PR!

The reason the coverage is so low at the moment is that the bulk of the tests are end-to-end tests against a real phoenix server (running in docker) on wercker. Because gocover just runs the test without spinning up the docker images, the test fails early and nothing is tested, hence the low coverage.

I believe there should be a way to export the real coverage from wercker using another tool. Would that be acceptable?

**Comment by F21** [comment]
@kirillDanshin I've added coverage information using coveralls.io.

The coveralls.io badge has been added to the README and here is the coverage of the latest build: https://coveralls.io/builds/6376153

**Comment by kirillDanshin** [comment]
@F21 coverage is still low now. please add some more tests. thanks.
also, check out Boostport/avatica#3 that I just opened. thanks.

**Comment by F21** [comment]
@kirillDanshin I've pushed a few more tests and am pretty happy with the coverage. Tests now cover all driver operations sufficiently other than unmockable things like network failures.

**Comment by cassiobotaro** [comment]
image

**Comment by F21** [comment]
@cassiobotaro Thanks for the heads up. I added some checks to the tests to assert the error type.

The reason gocover fails is because the tests test the driver against a real Phoenix Query Server in a docker container. Unfortunately, gocover does not know how to do this and can only run simple tests without any dependency services, hence the failures. For the latest test run, see here: https://app.wercker.com/boostport/avatica/runs/build/5944ac1d13964a0001346dfc

**Comment by cassiobotaro** [comment]
@F21 coverage ok, thanks! https://coveralls.io/github/Boostport/avatica

**Comment by F21** [comment]
@cassiobotaro Thanks for the review!

- This PR has been rebased.

- The warnings in the Go Report Card has been fixed, except for the go vet warning about discarding the cancel func in `context.WithTimeout()`, which is a false positive.

**Comment by cassiobotaro** [comment]
@F21 https://github.com/Boostport/avatica/blob/master/driver_go18_test.go#L36 Why not return the cancel function?

**Comment by F21** [comment]
@cassiobotaro We use context for timeouts in case the database hangs. The test do not need to manually cancel the context at all.

**Comment by F21** [comment]
friendly ping @cassiobotaro

**Pull request merged**
