### PR TITLE
Add secdl, Golang implementation of Lighttpd ModSecDownload algorithm

### PR DESCRIPTION
**Pull request by xor-gate**
- godoc.org: https://godoc.org/github.com/xor-gate/secdl
- goreportcard.com: https://goreportcard.com/report/github.com/xor-gate/secdl
- gocover.io: https://gocover.io/github.com/xor-gate/secdl

- [X] I have added my package in alphabetical order
- [X] I know that this package was not listed before
- [X] I have added godoc link
- [X] I have added gocover.io link
- [X] I have added goreportcard link
- [X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by kirillDanshin** [comment]
Hi,
please, improve your tests and add more docs - include some useful examples.
fix goreportcard issues.
Thanks!

**Comment by xor-gate** [comment]
You mean I should fixup that I have more test coverage with improving tests?

**Comment by kirillDanshin** [comment]
@xor-gate I mean you should add more tests and check that all tests you have are working as expected.

**Comment by xor-gate** [comment]
Thats right, it seems the coverage doesn't pickup the wrapped function for some reason. And I agree with all points. I come back in (hopefully) upcoming week when things have been resolved. I will keep you posted here! Thanks for the feedback.

**Comment by kirillDanshin** [comment]
@xor-gate ok, I'll wait your ping here :)

**Comment by xor-gate** [comment]
I have already improved it by many, still it needs some work. Could you review already what currently is in master? I'm clueless why gocover gives the mainfile `secdl.go` as complete empty but reports 92% coverage. I use coveralls myself.

Thanks for the feedback so far to improve it!

**Comment by kirillDanshin** [comment]
@xor-gate gocover is not displays `secdl.go` as complete empty. for some reasons that I don't know it hides (sets `display: none;` to) block with the code.
looks pretty well. thanks for your contribution! you're awesome :wink:

**Pull request merged**
