### PR TITLE
add gopter

### PR DESCRIPTION
**Pull request by fkromer**
**Please provide package links to:**

- github.com repo: https://github.com/leanovate/gopter
- godoc.org: https://godoc.org/github.com/leanovate/gopter
- goreportcard.com: https://goreportcard.com/report/github.com/leanovate/gopter
- coverage service link ([cover.run](https://cover.run/), [gocover](http://gocover.io/), [coveralls](https://coveralls.io/) etc.), example: `[cover.run](https://cover.run/go?tag=golang-1.10&repo=github.com%2Fuser%2Frepository)`

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by fkromer** [comment]
@ceriath 

- [x] goreportcardlink

**Comment by ceriath** [comment]
@fkromer i added the PR template again to the initial PR. Please add all the links

**Comment by fkromer** [comment]
@ceriath I added the missing links.

**Comment by ceriath** [comment]
Please fix the issues with 
https://goreportcard.com/report/github.com/leanovate/gopter#golint
https://goreportcard.com/report/github.com/leanovate/gopter#ineffassign
https://goreportcard.com/report/github.com/leanovate/gopter#misspell

Besides those minor issues, LGTM

**Comment by avelino** [comment]
> The maintainers will review your PR and notify you and tag it in case any information is still missing. They will wait 30 days for your interaction, after that the PR will be closed.
https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers

**Pull request closed without merging**
