### PR TITLE
Add gcm to Third-party APIs

### PR DESCRIPTION
**Pull request by Aorioli**

### CODE REVIEW

**Comment by avelino** [comment]
We cannot accept with fork, you must return your code for the official repository.

**Comment by Aorioli** [comment]
The original repo has not been updated in over 2 years and the owner has not approved a pull request in over 6 months. This code is a huge change from his, and the only reason it is forked is to show that there is a newer version when people look at the old repo.

**Comment by avelino** [comment]
`Latest commit 2407bc7 on Sep 28 @alexjlockwood alexjlockwood Update broken link to Google's Java implementation`

**Comment by Aorioli** [comment]
It's a change to the README.md file...
https://github.com/alexjlockwood/gcm/commit/2407bc782264326a3d4c71dd1ebeb8ab75221923

**Pull request merged**
