### PR TITLE
add Mailx library

### PR DESCRIPTION
**Pull request by valord577**
> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link: https://github.com/valord577/mailx
- pkg.go.dev: [Go Reference](https://pkg.go.dev/github.com/valord577/mailx)
- goreportcard.com: [Go Report Card](https://goreportcard.com/report/github.com/valord577/mailx)
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.):

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below before you submit PR:**
_not every repository (project) will fit into every option, but most projects should_

- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added pkg.go.dev link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by phanirithvij — CHANGES_REQUESTED** [review]
Coverage link is required, please read the [quality standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).

**Comment by valord577** [comment]
Codecov: https://codecov.io/gh/valord577/mailx

**Comment by avelino** [comment]
> Codecov: https://codecov.io/gh/valord577/mailx

Coverage required >= 80%, today your package is 60%

Read more here https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards

**Comment by valord577** [comment]
@avelino 

Codecov and Gocover, have some differences.

> Codecov: [77.17%](https://app.codecov.io/gh/valord577/mailx)
> Gocover: [85.4%](https://gocover.io/github.com/valord577/mailx)

Screen Shot 2022-02-08 at 19 56 36

**Comment by avelino** [comment]
we can now see the test coverage of your project - whenever you contribute to awesome-go remember to put the links that are requested in the description of the pull request

I need you to resolve the conflict with branch `main`

**Comment by valord577** [comment]
> we can now see the test coverage of your project - whenever you contribute to awesome-go remember to put the links that are requested in the description of the pull request
> 
> I need you to resolve the conflict with branch `main`

I do resolve the conflict. I will remember to add unit tests for coverage. :P

**Review by avelino — APPROVED** [review]
LGTM

**Review by phanirithvij — APPROVED** [review]

**Pull request merged**
