### PR TITLE
adding the roaring library (compressed bitset format)

### PR DESCRIPTION
**Pull request by lemire**
- godoc.org:  https://godoc.org/github.com/RoaringBitmap/roaring
- goreportcard.com: https://goreportcard.com/report/github.com/RoaringBitmap/roaring
- gocover.io: https://gocover.io/github.com/RoaringBitmap/roaring
- travis : https://travis-ci.org/RoaringBitmap/roaring

Make shure that you've checked the boxes below before you submit PR:
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link
- [x] I have added gocover.io link
- [x] I have added goreportcard link
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome :+1:

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@lemire thanks for contribution!
please, add more tests and leave comment here. thanks!

**Comment by lemire** [comment]
Thanks. I commented out some currently unused code and I added a few tests for the few features that were not currently tested. There is one small file were the percentage of coverage remains at 66% (popcnt_asm.go) but if you look at it, the untested code is made of several independent functions that are tested elsewhere, and we can't easily fix it because the code paths depend on the system. Other than that, all our coverage is cleanly above 80%. Note that we do have extensive testing (hundreds of thousands of assertions).

**Comment by lemire** [comment]
Note that you need to allow several minutes for all the tests to run.

**Comment by kirillDanshin** [comment]
yep, it's ok. thanks!

**Pull request merged**
