### PR TITLE
Add lru

### PR DESCRIPTION
**Pull request by floatdrop**
> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc): https://github.com/floatdrop/lru
- pkg.go.dev: https://pkg.go.dev/github.com/floatdrop/lru
- goreportcard.com: https://goreportcard.com/report/github.com/floatdrop/lru
- coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), [gocover](http://gocover.io/) etc.): github actions

**Note**: _that new categories can be added only when there are 3 packages or more._

**Make sure that you've checked the boxes below that apply before you submit PR.**
_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines for detials._

- [x] The package has been added to the list in alphabetical order.
- [x] The package has an appropriate description with correct grammar.
- [x] As far as I know, the package has not been listed here before.
- [x] The repo documentation has a pkg.go.dev link.
- [x] The repo documentation has a coverage service link.
- [x] The repo documenation has a goreportcard link.
- [x] The repo has a version-numbered release and a go.mod file.
- [x] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines), [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers) and [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards).
- [x] The repo has a continuous integration process that automatically runs tests that must pass before new pull requests are merged.
- [x] The authors of the project do not commit directly to the repo, but rather use pull-requests that run the continuous-integration process.

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Review by avelino — CHANGES_REQUESTED** [review]
To ensure the minimum necessary quality of your package we ask that you have a system that monitors the coverage of your tests, in the pull request template we recommend 3

read the awesome-go contribution guide here
https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md

**Comment by floatdrop** [comment]
@avelino I have code coverage setup from [COVETAGE.md](https://github.com/avelino/awesome-go/blob/main/COVERAGE.md) instruction. Is it outdated?

**Comment by avelino** [comment]
> @avelino I have code coverage setup from [COVERAGE.md](https://github.com/avelino/awesome-go/blob/main/COVERAGE.md) instruction. Is it outdated?

I believe it is not outdated, have you tested it?

If it is outdated I would be grateful for your contribution to update it.

**Comment by floatdrop** [comment]
> I believe it is not outdated, have you tested it?

It is working, but it does not provide coverage report – only updates README with actual code coverage percentage as separate [commits](https://github.com/floatdrop/lru/commit/570ab540feb060d274b9ca764c6b424daa3e2500).

**Comment by spekary** [comment]
Please merge or resubmit as the organization around databases has changed. I suggest you put this in the new Caches section.

**Pull request closed without merging**
