### PR TITLE
add bigfile

### PR DESCRIPTION
**Pull request by gamelife1314**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/bigfile/bigfile
- godoc.org: https://godoc.org/github.com/bigfile/bigfile
- goreportcard.com: [go-report](https://goreportcard.com/report/github.com/bigfile/bigfile) [golangci](https://golangci.com/r/github.com/bigfile/bigfile)
- coverage service link: [codecov](https://codecov.io/gh/bigfile/bigfile)

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by gamelife1314** [comment]
Hi, I have submitted the repo translation. Actually, "逼格" is powerful in English, it's Chinese pronunciation is "big".

**Comment by kirillDanshin** [comment]
@gamelife1314 thanks! 

Also, I found some issues with naming. `RandomWithMd5` should be `RandomWithMD5`, cause in Golang we name all known abbreviations in the same case, like `NewID()`, `SHA256` or `sha256` etc.

**Comment by gamelife1314** [comment]
@kirillDanshin thanks, I'll fix it in a minute

**Comment by gamelife1314** [comment]
@kirillDanshin thank you for your seriousness, I have refixed it, https://github.com/bigfile/bigfile/commit/480adb2cb3c3360fbb8388618972fc353052cdff

**Comment by kirillDanshin** [comment]
@gamelife1314 thanks. can you please also take a look into your gocyclo reports on goreportcard? when they will be fixed, I think we can merge it

**Comment by gamelife1314** [comment]
ok, thank you,  I'll continue to fix my code

**Comment by gamelife1314** [comment]
@kirillDanshin I have fixed the problem on goreportcard. thanks again for your seriousness

**Pull request merged**
