### PR TITLE
Add RUFS

### PR DESCRIPTION
**Pull request by krotik**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/krotik/rufs
- godoc.org: https://godoc.org/devt.de/krotik/rufs
- goreportcard.com: https://goreportcard.com/report/devt.de/krotik/rufs
- coverage service link ([gocover](https://gocover.io/github.com/krotik/rufs), <a href="https://void.devt.de/pub/rufs/coverage.txt">Code coverage</a>

Note: The linked github repo in the README.md is a mirror of (devt.de/krotik/rufs) - I would like to use it to cope with traffic and receive stars.

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x ] I have added my package in alphabetical order.
- [x ] I have an appropriate description with correct grammar.
- [x ] I know that this package was not listed before.
- [x ] I have added godoc link to the repo and to my pull request.
- [x ] I have added coverage service link to the repo and to my pull request.
- [x ] I have added goreportcard link to the repo and to my pull request.
- [x ] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@krotik please check your gocyclo warnings

**Comment by krotik** [comment]
Thanks for the review @kirillDanshin . The majority of gocyclo warnings come from test files which can get quite long. Sometimes due to a special setup but often only because I write tests while I am developing the code and don't bother to create many different functions. The other cases are function which contain actual (sometimes complex) business logic which is fully tested (i.e. every branch, loop and condition has been tested).

**Comment by kirillDanshin** [comment]
@krotik I'd still suggest you to refactor your code

**Comment by krotik** [comment]
Ok nevermind then.

**Pull request closed without merging**
