### PR TITLE
add https://github.com/ybbus/httpretry

### PR DESCRIPTION
**Pull request by ybbus**
add httpretry to awesome go

- github.com repo: https://github.com/ybbus/httpretry
- godoc.org: https://godoc.org/github.com/ybbus/httpretry
- goreportcard.com: https://goreportcard.com/report/github.com/ybbus/httpretry
- coverage service link: http://gocover.io/github.com/ybbus/httpretry

- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body content check:
- godoc.org: True
- goreportcard.com: True
- coverage: False

**Comment by ybbus** [comment]
@panjf2000 This is no issue. This has documentary purposes, to see that the error is resetted at the beginning of the loop. Furthermore it does not do any harm or overhead.

**Comment by ybbus** [comment]
@panjf2000 issue should now be gone

**Comment by ybbus** [comment]
@panjf2000 
If there is still something missing, please let me know

**Pull request merged**
