### PR TITLE
Add cimgui-go

### PR DESCRIPTION
**Pull request by gucio321**
## We want to ensure high quality of the packages. Make sure that you've checked the boxes below before sending a pull request.

- [X] I have read the [Contribution Guidelines](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#contribution-guidelines)
- [X] I have read the [Maintainers Note](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#maintainers)
- [X] I have read the [Quality Standards](https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md#quality-standards)

_Not every repository (project) will require every option, but most projects should. Check the Contribution Guidelines for details._

- [X] The repo documentation has a pkg.go.dev link.
- [ ] The repo documentation has a coverage service link. (does not apply) - explained here https://github.com/AllenDang/cimgui-go/issues/329
- [X] The repo documentation has a goreportcard link.
- [X] The repo has a version-numbered release and a go.mod file.
- [X] The repo has a continuous integration process that automatically runs tests that must pass before new pull requests are merged.
- [X] Continuous integration is used to attempt to catch issues prior to releasing this package to end-users.

## Please provide some links to your package to ease the review

- [X] forge link (github.com, gitlab.com, etc): https://github.com/AllenDang/cimgui-go
- [X] pkg.go.dev: https://pkg.go.dev/github.com/AllenDang/cimgui-go
- [X] goreportcard.com: https://goreportcard.com/report/github.com/AllenDang/cimgui-go
- [ ] coverage service link ([codecov](https://codecov.io/), [coveralls](https://coveralls.io/), etc.): --does not apply--

## Pull Request content

- [X] The package has been added to the list in alphabetical order.
- [X] The package has an appropriate description with correct grammar.
- [X] As far as I know, the package has not been listed here before.

## Category quality

_Note that new categories can be added only when there are 3 packages or more._

Packages added a long time ago might not meet the current guidelines anymore. It would be very helpful if you could check 3-5 packages above and below your submission to ensure that they also still meet the Quality Standards.

Please delete one of the following lines:

- [X] The packages around my addition still meet the Quality Standards.
- [ ] I removed the following packages around my addition: (please give a short reason for each removal)

Thanks for your PR, you're awesome! :sunglasses:

### CODE REVIEW

**Review by yassinebenaid — COMMENTED** [review]
This is a C++ project. `awesome-go` is intended only for projects **BUILT with Go**.

**Comment by phanirithvij** [comment]
@yassinebenaid that's fine, go bindings are to be used by go developers.

**Comment by phanirithvij** [comment]
is it possible to run `gofmt -s`? If so I can approve.

**Comment by gucio321** [comment]
> @gucio321  is it possible to run `gofmt -s`? If so I can approve.

Its a bit more complex as these files are autogenerated too.

**Pull request merged**
