### PR TITLE
Add llgcode packages

### PR DESCRIPTION
**Pull request by llgcode**
I added 2 packages [draw2d](https://github.com/llgcode/draw2d) and [ps](https://github.com/llgcode/ps) to your awesome go list.

### CODE REVIEW

**Comment by 0xCMP** [comment]
Maybe the ps interpreter should stay under image manipulation with draw2d?

**Comment by llgcode** [comment]
postscript is a scripting language this is why i put it in this category.
Sure it is used to generate image and define 2d images.

-- Laurent.

**Comment by mholt** [comment]
Although draw2d has some samples, both packages are lacking in documentation (godoc).

**Comment by llgcode** [comment]
I'm working on documentation for draw2d I have a branch with a better
documentation.

-- Laurent.

**Comment by cassiobotaro** [comment]
@llgcode For  quality standards please follow:  https://github.com/avelino/awesome-go/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Pull request closed without merging**
