### PR TITLE
Add github.com/bobg/mid

### PR DESCRIPTION
**Pull request by bobg**
> Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!

**Please provide package links to:**

- repo link (github.com, gitlab.com, etc): https://github.com/bobg/mid
- pkg.go.dev: https://pkg.go.dev/github.com/bobg/mid
- goreportcard.com: https://goreportcard.com/report/github.com/bobg/mid
- coverage service link: https://gocover.io/github.com/bobg/mid

**Make sure that you've checked the boxes below before you submit PR:**
_not every repository (project) will fit into every option, but most projects should_

- [X] I have added my package in alphabetical order.
- [X] I have an appropriate description with correct grammar.
- [X] I know that this package was not listed before.
- [X] I have added pkg.go.dev link to the repo and to my pull request.
- [X] I have added coverage service link to the repo and to my pull request.
- [X] I have added goreportcard link to the repo and to my pull request.
- [X] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: True
- coverage: True

> your project is about to be approved, it's under revision, _it may take a few days_

**Review by avelino — CHANGES_REQUESTED** [review]
review:

- put usage example in the project readme (how to use)
- test coverage must be higher than 80%, today it is 70.5%
- https://goreportcard.com/report/github.com/bobg/mid#gocyclo today it is 88%

**Comment by bobg** [comment]
Feedback addressed, thanks!

**Comment by bobg** [comment]
Feedback has been addressed, please reopen.

**Pull request closed without merging**
