### PR TITLE
Added go-sundheit - a service health checks lib to distributed systems section

### PR DESCRIPTION
**Pull request by eranharel**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/AppsFlyer/go-sundheit
- godoc.org: https://godoc.org/github.com/AppsFlyer/go-sundheit
- goreportcard.com: https://goreportcard.com/report/github.com/AppsFlyer/go-sundheit
- coverage service link: https://coveralls.io/github/AppsFlyer/go-sundheit?branch=master

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by eranharel** [comment]
> https://goreportcard.com/report/github.com/AppsFlyer/go-sundheit#misspell

Fixed

**Comment by eranharel** [comment]
Do I need to fix anything else @appleboy  (except for that spelling mistake I fixed a while ago)?
Can you take a look?

**Comment by eranharel** [comment]
Do I need to fix anything else @appleboy  (except for that spelling mistake I fixed a while ago)?
Can you take a look?

**Comment by kirillDanshin** [comment]
Merging this, but I'm also waiting for https://github.com/AppsFlyer/go-sundheit/pull/11 to be merged

**Comment by eranharel** [comment]
Thanks for you PR @kirillDanshin - merged

**Pull request merged**
