### PR TITLE
add antch

### PR DESCRIPTION
**Pull request by zhengchun**
Please check if what you want to add to `awesome-go` list meets [quality standards](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**

- github.com repo: https://github.com/antchfx/antch
- godoc.org: https://godoc.org/github.com/antchfx/antch
- goreportcard.com: https://goreportcard.com/report/github.com/antchfx/antch
- coverage service link: https://coveralls.io/github/antchfx/antch?branch=master

Very good coverage

**Note**: that new categories can be added only when there are 3 packages or more.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [x] I have added godoc link to the repo and to my pull request.
- [x] I have added coverage service link to the repo and to my pull request.
- [x] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by zhengchun** [comment]
Hi, @avelino , The `examples/get_started/main.go`  is a main package that as example of `Antch` to running , it make cover from `82%` drop to `74%`.

**Comment by kamilsk** [comment]
@zhengchun you can convert it to example https://golang.org/pkg/testing/#hdr-Examples

**Comment by zhengchun** [comment]
OK,thanks, I got it.

**Comment by zhengchun** [comment]
Hello,@avelino, in the last, i'm decide example `get_started` move to new page as independent repository, because it's sample code for getting started articles. now cover up to `80%`.

**Pull request merged**
