### PR TITLE
add Hjson

### PR DESCRIPTION
**Pull request by laktak**
Please check if what you want to add to awesome-go list meets quality standards before sending pull request. Thanks!

Please provide package links to:

-     github.com repo: https://github.com/hjson/hjson-go
-     godoc.org: https://godoc.org/github.com/hjson/hjson-go
-     goreportcard.com: https://goreportcard.com/report/github.com/hjson/hjson-go
-     coverage service link (gocover, coveralls etc.): https://gocover.io/github.com/hjson/hjson-go/

Note: that new categories can be added only when there are 3 packages or more.

Make sure that you've checked the boxes below before you submit PR:

- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added godoc link to the repo and to my pull request
- [x] I have added coverage service link to the repo and to my pull request
- [x] I have added goreportcard link to the repo and to my pull request
- [x] I have read Contribution guidelines and Quality standard.

Thanks for your PR, you're awesome! 👍

### CODE REVIEW

**Comment by kirillDanshin** [comment]
@laktak please fill our pull request template.

**Comment by laktak** [comment]
@kirillDanshin Sorry, added. Tests are in a separate folder so I omitted the coverage service.

**Comment by kirillDanshin** [comment]
@laktak please setup coveralls or something like this. it's allows you to use separate testing package.

**Comment by laktak** [comment]
@kirillDanshin updated.

**Comment by laktak** [comment]
@kirillDanshin can you merge or do you need anything else?

**Comment by kirillDanshin** [comment]
@laktak thanks for your contribution!

**Pull request merged**
