### PR TITLE
Add BugSnag to Utilities

### PR DESCRIPTION
**Pull request by donpinkus**
Added an error tracking tool with good Go support & a free-tier.

Note that this is a helpful tool for Go projects, not a Go library - so thats why godoc is left blank.

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order.
- [x] I have an appropriate description with correct grammar.
- [x] I know that this package was not listed before.
- [ ] I have added godoc link to the repo and to my pull request.
- [ ] I have added coverage service link to the repo and to my pull request.
- [ ] I have added goreportcard link to the repo and to my pull request.
- [x] I have read [Contribution guidelines](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers note](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#maintainers) and [Quality standard](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standard).

Thanks for your PR, you're awesome! :+1:

### CODE REVIEW

**Comment by cassiobotaro** [comment]
@donpinkus  is free for 14 days?

**Comment by kirillDanshin** [comment]
no way. it's not a cool open-source project, even not a book nor meetup.

if you want, you can send us a PR with bugsnag go client lib link, but not this link.

**Comment by donpinkus** [comment]
Hey @kirillDanshin - sorry about that, when you say "go client lib", do you mean specifically the docs on installing the Bugsnag error notifier lib for go (https://docs.bugsnag.com/platforms/go/)?

Or would it be better to list Bugsnag's open source error notifier (https://github.com/bugsnag/bugsnag-go)?

**Comment by donpinkus** [comment]
@cassiobotaro - there's a free 14 day trial, but there's also just a general free tier (indefinite length) https://www.bugsnag.com/pricing/

**Comment by kirillDanshin** [comment]
@donpinkus sorry for the delay. I'm talking about https://github.com/bugsnag/bugsnag-go.

**Pull request closed without merging**
