### PR TITLE
adds `conform` to `Forms`

### PR DESCRIPTION
**Pull request by leebenson**
- adds [conform](https://github.com/leebenson/conform) to "Forms" section

### CODE REVIEW

**Comment by avelino** [comment]
review Gocyclo pls http://goreportcard.com/report/leebenson/conform

**Comment by joeybloggs** [comment]
IMHO I don't think Gocyclo should be a factor in adding anyones library, although it **can sometimes** show a real issue, but allot of times it gives false positives when no issue really exist.

on a side note I don't even know what the threshold is set to when goreportcard.com runs gocyclo 5, 10, 20? it just seems very subjective to me.

**Comment by avelino** [comment]
```
Gocyclo calculates cyclomatic complexities of functions in Go source code. The cyclomatic complexity of a function is calculated according to the following rules: 1 is the base complexity of a function +1 for each 'if', 'for', 'case', '&&' or '||'

/github.com/leebenson/conform/conform.go
Line 114: 19 conform Strings repos/src/github.com/leebenson/conform/conform.go:114:1
```

**Comment by leebenson** [comment]
@avelino the library is iterating through reflected structs and parsing tag syntax. If you have a suggestion for reigning in loops and switches, I'd be happy to adjust the code but otherwise, the goals of gocyclo and the purpose of my code seem diametrically opposed. Artificially refactoring away from a single function would be solely to appease a third-party linter.

**Comment by joeybloggs** [comment]
@avelino I understand the rules that count towards the complexity, but there is a threshold that the program has to hit before it starts thinking there are too many +1's denoted by the rules I think it's the over parameter here https://github.com/fzipp/gocyclo/blob/master/gocyclo.go#L40

but I don't see the number that is being used by goreportcard.com anywhere, besides I thinkit's up to a programmer to ultimately decide if the complexity is a problem or not.

**Comment by leebenson** [comment]
forgive my bias, but I agree with @joeybloggs 

gocyclo is, at best, a somewhat arbitrary preemptor of code traps, based on a subjective score. My library is single purpose, designed to iterate through embedded structs, find qualifying strings, and format based on 16 possible user-specified rules. If gocyclo is choking on 19 counts, then that one switch statement accords for 84% of them. In some circumstances this might hint at the need to reduce complexity, but in my case, I see no more performant way for my code to function.

Since I do not know the N value that goreportcard considers "over", refactoring my code to satisfy an unknown quantity would be an exercise of appeasement to a subjective (and unknown) standard. It would be the same code, with a few extra function calls, likely rendering it less performant and increasing the surface area of an otherwise single-purpose function.

I can't see that upping the gocyclo score would increase the library's attractiveness to your user base. I appreciate your consideration for my lib's inclusion all the same.

**Comment by leebenson** [comment]
I would also add that sqlx, one of the main SQL libraries in Go, only weighs in at a 60% gocycle score:
http://goreportcard.com/report/jmoiron/sqlx

Likely because of similar struct parsing.

**Comment by joeybloggs** [comment]
so @avelino have you thought about Gocyclo?

**Comment by avelino** [comment]
In this "PR" we're not talking about just Gocyclo
https://goreportcard.com/report/leebenson/conform

If you really want to get in that discucao should read more about "awesome-go"
https://github.com/avelino/awesome-go/issues/683

**Comment by joeybloggs** [comment]
@avelino I never said you weren't just talking about Gocyclo for this pull request, I just asked if you have thought about it based on all of the previous comments in this thread about it.

I already brought it up in #683 in the first comment...

**Comment by leebenson** [comment]
Actually when I first submitted, gocyclo was the only issue. The gofmt stuff is news to me and very trivial to fix- I probably had 'format on save' turned off in Atom on my last commit.

I'm not sure what you have against this package or why you care so much about what a mindless linter (that's not designed for the use case the package intends to solve) determines the code quality to be?

If you don't feel the package is useful to readers, that's a different story.

**Comment by avelino** [comment]
Gentlemen, we get a lot of PR, if you don't follow the minimum quality (now use goreportcard to help us) does make it hard to maintain this list.

You want to help me send the quality of list? We need many employees.

**Comment by leebenson** [comment]
I mean 'mindless' in the sense of 'not context aware', to be clear. It's a decent first pass, but when a package's entire purpose defeats the lining, lining is a secondary concern.

There are plenty of packa

**Comment by leebenson** [comment]
Thank you @avelino

**Comment by joeybloggs** [comment]
Sure thanks @avelino

**Pull request merged**
