### PR TITLE
"Awesome-go" should be awesome!

### PR DESCRIPTION
**Pull request by kazhuravlev**
These changes improve the code contained in awesome-go. There are many high-level changes that make it easy to write, modify, and test the codebase.

- All file names are converted to constants
- Template parsing moved to program start
- All output files are collected in a separate, git-ignored, directory
- Source (templates and static resources) and resulting (output) directories are separated
- Output directory is cleared before next site generation
- Remove all references to the "vendor" directory
- Handling all errors in all functions
- Minor HTML improvements (fixed sponsor block, added modern html markup)
- Parse URLs with a batch of URLs, not strings. Divide
- Improved security of html generation. use "goquery" to change the html, not "strings.Replace"
- Find some issues (described in "FIXME" in the code. Author's solution required)
- Rename "objects" to "categories" and "elements" to "links".
- Break code into functions. This is useful for writing tests or making changes easily.
- Test refactoring: adding test helpers and assertions
- Remove panics
- Close file descriptors
- Do not pass cards and slices by signs
- Add netlify.toml, remove _redirects

### CODE REVIEW

**Comment by avelino** [comment]
Thank you for contributing with [awesome-go](https://github.com/avelino/awesome-go), we will revise your contribution as soon as possible.

Automation body links content check:
- godoc.org or pkg.go.dev: True
- goreportcard.com: False
- coverage: False

> your project is about to be approved, it's under revision, _it may take a few days_

**Comment by kazhuravlev** [comment]
@avelino looks like this is automatic response from bot. Just to clarify: this pr is about .go code in awesome-go repo.

**Review by avelino — CHANGES_REQUESTED** [review]
the proposed change SGTM, but we need to look at the existing workflows and update them

https://github.com/avelino/awesome-go/tree/main/.github/workflows

there are these two files, why not move them to main (since that is the move we are making in this proposal)?
- `make_site.go`
- `scripts.go`

**Comment by kazhuravlev** [comment]
Contents of `scripts.go` and `make_site.go` moved to `main.go`. Also, fixed warnings from `Codacy Static Code Analysis` check.

**Comment by kazhuravlev** [comment]
If you have an additional comments - please write them. If you need an explanation or additional help with netlify - please also text me. I was test this configuration on my own netlify account. It was fine.

**Review by avelino — CHANGES_REQUESTED** [review]
running "go test" is only generating the index in the "out" folder, the subpages (categories) and style file are missing:

```
~/p/a/awesome-go ❯❯❯ ll out/                                         kazhuravlev-awesome-go-should-be-awesome
total 768
-rw-r--r--@ 1 avelino  staff   380K Mar 18 07:59 index.html
```

Screenshot 2023-03-18 at 08 00 25

**Comment by kazhuravlev** [comment]
I am in a vacation. I will check, fix and answer you on 27.03-28.03

**Comment by kazhuravlev** [comment]
@avelino, problem and WF deployment has been fixed. This was because the linter asked to rename `Url` -> `URL`, but I forgot about HTML templates.

**Review by avelino — CHANGES_REQUESTED** [review]
Sync man branch (upstream)

**Comment by kazhuravlev** [comment]
done

**Comment by avelino** [comment]
thanks for your contribution, I just did the merge (via local cli).

there was some conflict with the github interface, your commits are already in the [main branch](https://github.com/avelino/awesome-go/commits/main)

> sorry for the long revision time

**Pull request closed without merging**
